### ISSUE TITLE
DiscordApiClient#CreateGuildStickerAsync sends a malformed request

### ISSUE THREAD

**Issue by NCPlayz** [DSharpPlus/DSharpPlus#1003]
# Summary
Was glossing over D#+'s implementation of guild stickers to check over Rapptz/discord.py#7126 and noticed that [`DiscordApiClient#CreateGuildStickerAsync`](https://github.com/DSharpPlus/DSharpPlus/blob/df1ad05511d068da102e5801ca4a1a411c707997/DSharpPlus/Net/Rest/DiscordApiClient.cs#L858) sends a malformed request.

# Details
Rather than:
```cs
            var pld = new RestStickerCreatePayload()
            {
                Name = name,
                Description = description,
                Tags = tags
            };

            var values = new Dictionary<string, string>
            {
                ["payload_json"] = DiscordJson.SerializeObject(pld)
            };
```

It should be:
```cs
            var values = new Dictionary<string, string>
            {
                ["name"] = name,
                ["description"] = description,
                ["tags"] = tags,
            };
```

Each form data field is a value rather than sending a JSON payload as a value for one field, `payload_json` only applies to creating messages.

While I haven't tested how D#+ does the file uploading, it seems that Discord rejects the request if it provides `application/octet-stream` rather than a concrete MIME type. For guild stickers, I believe that only `image/png` and `application/json` (lottie) are accepted. The MIME type doesn't matter for creating messages and everything else however.

**Comment by Lulalaby** [comment]
I'll take a look into this.

<~< Velvet will blame me

**Comment by Lulalaby** [comment]
![image](https://user-images.githubusercontent.com/14029133/126661602-8c36e4bb-1e9f-45cf-afe7-4e54219882e4.png)
Can reproduce, will fix

**Comment by Lulalaby** [comment]
![2021-07-22_17h22_05](https://user-images.githubusercontent.com/14029133/126669632-68fd880e-f58c-4434-9693-a425fcc6f836.png)

**Comment by Lulalaby** [comment]
@VelvetThePanda can you fix this? I tried a few things but does not work.

Atm my code is
```csharp
        internal async Task<DiscordMessageSticker> CreateGuildStickerAsync(ulong guild_id, string name, Optional<string> description, string tags, DiscordMessageFile file, string reason)
        {
            var route = $"{Endpoints.GUILDS}/:guild_id{Endpoints.STICKERS}";
            var bucket = this.Rest.GetBucket(RestRequestMethod.POST, route, new {guild_id}, out var path);
            var url = Utilities.GetApiUriFor(path);
            var headers = Utilities.GetBaseHeaders();
            if (!string.IsNullOrWhiteSpace(reason))
                headers.Add(REASON_HEADER_NAME, reason);
            /*
            var pld = new RestStickerCreatePayload()
            {
                Name = name,
                Description = description,
                Tags = tags
            };
            */

            var values = new Dictionary<string, string>
            {
                { "name", name },
                { "description", description.HasValue ? description.Value : null },
                { "tags", tags }
            };

            var res = await this.DoMultipartAsync(this.Discord, bucket, url, RestRequestMethod.POST, route, headers, values, new[] {file});
            
            var ret = JObject.Parse(res.Response).ToDiscordObject<DiscordMessageSticker>();

            ret.Discord = this.Discord;

            return ret;
        }
```

**Comment by VelvetThePanda** [comment]
> I'll take a look into this.
> 
> <~< Velvet will blame me

I was already informed of this off-platform shortly after this issue was opened. I wasn't aware of the different format for uploading stickers compared to uploading...literally any other type of media.

**Comment by VelvetThePanda** [comment]
> @VelvetThePanda can you fix this? I tried a few things but does not work.

Do you have the response payload? Otherwise my answer is "not really, no".

**Comment by Lulalaby** [comment]
[2021-07-23 16:23:33 +02:00] [123 /REST ↓      ] [Trace] {"message": "Invalid Asset", "code": 50046}

**Comment by Lulalaby** [comment]
50046 is "Invalid file uploaded"

**Comment by Lulalaby** [comment]
Seems to be the media content type?

**Comment by feelingnothing** [comment]
So, I went into it with a debugger or noticed that name of the multipart form field for file given based on iteration count and in https://discord.com/developers/docs/resources/sticker#create-guild-sticker-form-params it says it should be just "file"? I tried to default name to "file" and got 500 error code, checked media types of all field and it is all correct, im missing something
https://github.com/DSharpPlus/DSharpPlus/blob/df1ad05511d068da102e5801ca4a1a411c707997/DSharpPlus/Net/Rest/RestClient.cs#L443-L448
