### ISSUE TITLE
RequireDirectMessageAttribute is not working

### ISSUE THREAD

**Issue by MazeXP** [DSharpPlus/DSharpPlus#1079]
# Summary
Commands registered with `[RequireDirectMessage]` are not working at all.

# Details
Registered a simple command using `[Command(...)]` and `[RequireDirectMessage]` attributes.
The command method is not getting invoked at all when sending the command in direct message.
`DiscordClient` is being used, not the sharded one.

**Versions used:**
DSharpPlus: 4.2.0-nightly-00990
DSharpPlus.CommandsNext: 4.2.0-nightly-00990
DSharpPlus.Interactivity: 4.2.0-nightly-00990

**Technology used:**  
.NET 5.0
Windows 10
Visual Studio 2019

# Sample for reproduction
```csharp
        [Command("sample")]
        [RequireDirectMessage]
        public async Task Sample(CommandContext context)
        {
            var channel = context.Channel;
            if (channel == null)
            {
                throw new Exception("Channel is null!");
            }
        }
```

# Notes
When commenting the `[RequireDirectMessage]` attribute out, then the command is invoked.
But when checking `context.Channel` it returns null.

The event `MessageCreated` is also returning for `e.Message.Channel` always null when receiving a direct message.
Receiving a message from a guild returns a valid `DiscordChannel` object.

**Comment by VelvetThePanda** [comment]
This is partially intentional behavior. 

1. As of v8, Discord does not send the channel object in DMs

2. DMs are always handled on shard 1

**Comment by MazeXP** [comment]
I propose that the functionality of the `[RequireDirectMessage]` is being restored.
It must be somehow possible to detect if a message is a private message or not.

I suppose the best option would be to check wether the channel is null.

**Comment by DWaffles** [comment]
I believe this might have something to do with threads and I can confirm it's not related to sharing. Looking into it atm.

**Comment by DWaffles** [comment]
Apparently whoever the hell implemented threads messed up the getter for DiscordMessage.Channel. Hopefully nobody can use git blame here.
