### ISSUE TITLE
Feature: Being able to dynamically define and add slash command at runtime

### ISSUE THREAD

**Issue by darkalfx** [DSharpPlus/DSharpPlus#1098]
# Summary
Just like regular commands, there should be a way to define new slash commands and add dynamically at runtime.

# Details
Right now the only way to add slash commands is by creating classes/methods and decorating them with attributes, this is fundamentally incompatible with being to add/create new commands dynamically at runtime since the attributes along with their values must be set before compilation even happens.

**Comment by IDoEverything** [comment]
It's specifically noted in the readme that the slash commands extension is not supposed to be utilized for dynamic command registration. That was never meant to be supported and would require a major rewrite at this stage. The methods to create commands are public and can be used for this purpose. You can reference the code for the slash command extension to understand how you should register and handle commands.

The way to register commands at runtime in CommandsNext is almost as complex as directly using the slash command methods (bar maybe group commands), so it doesn't make much sense to use something similar to that. I'll keep this open if you can suggest a more practical way to handle commands generated at runtime.

**Comment by darkalfx** [comment]
Correct me if I'm wrong, but from looking at the code in **SlashExtension**, especially the **RegisterCommands** method, I got the impression that all we would need to do is to be able to pass in something other than a type.

If we had some kind of data structure that contained the slash command information along with which method to call, wouldn't that work?

At first glance, that's how it seemed to me.

**Comment by IDoEverything** [comment]
Making a custom builder for this would be as complex as figuring out how to register and handle slash commands yourself without using the extension.

**Comment by darkalfx** [comment]
Ah....I get what you're saying now.

I will have to reflect on this.
