### ISSUE TITLE
ctx.TriggerTypingAsync() returns error code 1020

### ISSUE THREAD

**Issue by movildima** [DSharpPlus/DSharpPlus#1118]
# Summary
Trying to send a typing start event(for example via the aforementioned method) results in error code 1020: A specific account option must be enabled to make this API call.
It feels like discord changed their API rules again, but I'm not entirely sure.

# Details
No exception is sent, stack trace reports only the following line:

```
[123 /REST ↓      ] [Trace] error code: 1020
```

**Comment by movildima** [comment]
Actually, appears to be an API issue.
https://discordstatus.com/incidents/k8jpm6gqr9kx

**Comment by Lulalaby** [comment]
Yep, it was an api issue xD
