### ISSUE TITLE
Members don't update user cache

### ISSUE THREAD

**Issue by VelvetToroyashi** [DSharpPlus/DSharpPlus#1135]
# Summary
When it comes to dealing with users, it seems that invoking any command that takes `DiscordUser` as a parameter will fail, even if the user in question is on the guild the command is being executed on. This applies when typing out the individual's name (Which CNext supports, if they're in UserCache). 

# Details
The issue arises when the user is not present in the user cache, as it only gets updated when someone sends a message, invokes an interaction, or updates something about themselves. 

Furthermore, even invoking a command and using their ID does not appear to update user cache, despite the command forming a user object that could be later updated. 

I also find it rather perplexing that we do not use gateway payloads to update user cache, given that this would mitigate this problem entirely. 

# Steps to reproduce
- Create a command that takes DiscordUser as it's parameter
- Start the bot
- Pick someone on the server who hasn't sent a message since the bot started
- Invoke the command
- Observe an Argument exception because it couldn't find a "suitable overload"; it's not detecting a user.

**Comment by Tawmy** [comment]
@VelvetThePanda ^
