### ISSUE TITLE
DiscordMembers should have a method like GetAvatarUrl, possibly GetGuildAvatarUrl

### ISSUE THREAD

**Issue by FireController1847** [DSharpPlus/DSharpPlus#1146]
# Summary
I think the title's pretty self explanatory. I could probably implement this myself but if somebody gets to it before me I won't stop them, I wanted to create this issue before the PR so somebody can do that if I'm not able to make a PR in time (and for opinions, of course).

# Details
It would be nice to be able to have the same functionality as choosing the image format and/or changing the size of the returned URL just like how it's done with `GuildUser#GetAvatarUrl`.

**Comment by IDoEverything** [comment]
Feel free to create a PR for this.
