### ISSUE TITLE
GuildAvatarUrl/GuildAvatarHash should be null when a member does not have a guild avatar

### ISSUE THREAD

**Issue by FireController1847** [DSharpPlus/DSharpPlus#1147]
# Summary
Once again a pretty self-explanatory title, I would like to suggest for the GuildAvatarUrl to be null (or some form of alternative indicator) if the user does not have a guild-specific avatar. Will likely make a PR for this as well at some point, again making the issue in case somebody would like to get to it before me as well (and gather opinions on this idea).

# Details
I find it strange that GuildAvatarUrl falls back to the user's avatar URL which can be gotten at `member.AvatarUrl`. Similarly, I don't understand why the GuildAvatarHash falls back to the user's avatar hash when, once again, that can be gotten at `member.AvatarHash`.

I think, logically, the GuildAvatar and the Avatar should be two separate items and not dependent on each other. With current functionality, the only way to check if the user has a guild avatar or not is to compare the avatar hash against the user's avatar hash and see if they're not equal, which is fairly unintuitive to me. I like to compare this feature to a user's nickname - the user's nickname does not inherently fallback to the user's username. They're two separate things and should be kept as such.

If current functionality is kept, it may be worth adding a note onto the GuildAvatar's docs stating that it will fallback to the regular user's avatar if they do not have one.

**Comment by bakabun** [comment]
This is what most people expected since raw API will return `null` on `avatar` property if the user doesn't have avatar yet. I was planning to make PR about it but since the commit for it had been rolled to version 4.1.0 it would be breaking change since some people might already checking against hash equality instead of `null`. Idk if breaking change is acceptable for 4.2.0

**Comment by IDoEverything** [comment]
This unfortunately cannot be changed now as it would be a silent breaking change. If you feel like the documentation can be updated to be more descriptive of the current behaviour, please feel free to create a pull request.
