### ISSUE TITLE
NullReferenceException triggered when creatingDM after a reaction has been added.

### ISSUE THREAD

**Issue by BlackLotusLV** [DSharpPlus/DSharpPlus#1150]
# Summary
System.NullReferenceException triggers when trying to create a DM after the bot has added reactions to users messages in DMs and bot can't create any new DMs

# Details

Bot is running on .net 5, using nightly1038, but has been an issue on previous versions too. Issue happens both on live version of the bot on a linux server as well as reproduced on dev envi on my windows machine.

My bot receives a mod mail ticket creation, when a user that created the ticket direct messages the bot, the bot sends copy of the message to my server and adds a reaction to the users message. In this moment, if the bot tries to create a DM channel from server member, it will trigger a null exception.
```
  [2021-10-27 21:21:32 +00:00] [202 /CMDError    ] [Error] Black Lotus tried executing '@ testaltdm' but it errored
  System.NullReferenceException: Object reference not set to an instance of an object.
     at DSharpPlus.Entities.DiscordMember.<CreateDmChannelAsync>b__90_0(DiscordDmChannel x)
     at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
     at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
     at DSharpPlus.Entities.DiscordMember.CreateDmChannelAsync()
     at LiveBot.Commands.AdminCommands.TestAltDM(CommandContext ctx, DiscordMember member) in D:\Git\LiveBot\LiveBot\LiveBot3\Commands\AdminCommands.cs:line 29
    at DSharpPlus.CommandsNext.Command.ExecuteAsync(CommandContext ctx)
```

But if turning off the confirmation reaction, the issue does not occur
Here is a demonstration [Video](https://www.youtube.com/watch?v=H-pYb3rfZPY).

# Steps to reproduce
1. User sends message to bot DMs
2. Bot adds reaction to message
3. Bot uses DiscordMember.CreateDmChannelAsync();
4. Triggers NullReferenceException

# Notes
Issue does not occur when creating a response to the DM message (ctx.RespondAsync();)

**Comment by IDoEverything** [comment]
How are you getting the member object here? If you're just using `ctx.Member` on a command in dms, that'll return null because a member refers to a guild member which doesn't apply in a dm. You should use `ctx.Channel` instead of creating a new dm channel.

**Comment by VelvetThePanda** [comment]
@IDoEverything refer to the attached video


They acquire it from a guild object

**Comment by VelvetThePanda** [comment]
I have a suspicion as to why this is happening.

**Comment by VelvetThePanda** [comment]
Actually, looking back, this doesn't make much sense.

**Comment by IDoEverything** [comment]
I think I've got the issue. On the MessageReactionAdded event, a skeleton dm channel is created and added to dm channel cache if it's in a dm, which doesn't have the `Recipients` property set. The `CreateDmChannelAsync` method checks for the recipients property, which causes the nullref.

**Comment by VelvetThePanda** [comment]
Ah. Good catch. This does make sense, too. Iirc @Neuheit was the one that added that, because as of V8 DM channels aren't sent to bots.

**Comment by IDoEverything** [comment]
The library is way too dependent on skeleton entities for dm channels, which can cause issues like this. I think we should just remove the dm channel cache altogether.

**Comment by VelvetThePanda** [comment]
While I agree that skeleton entities are an issue (quite literally, see #977 ), I don't think removing it all together is exactly ideal, as it would require more effort than just fixing the places that cause this, as well as potentially causing other issues? Ripping out an entire cache just doesn't seem like the right solution.
