### ISSUE TITLE
How do I get someones roles without attributes?

### ISSUE THREAD

**Issue by drinkingcarrots** [DSharpPlus/DSharpPlus#1152]
I need to use ctx.Member.Roles, and I know its supposed to give a list. but I have no clue how to get that list and turn it into a workable string or something.

like if I do Convert.ToString(ctx.Member.Roles), it gives System.Linq.Enumerable+WhereEnumerableIterator`1[DSharpPlus.Entities.DiscordRole].

when I want it to give "role1", "role2" etc. or anything like that is fine too.

I cant do what I want with the role checking attribute.

example code would help, pretty much anything would help. thanks

note* I kinda suck at coding, so I'm sorry if this is the dumbest question of your life.

edit for anyone with this problem. (using System.Linq;) <-- add this.

**Comment by VelvetThePanda** [comment]
I'm three hours late to the party, but we have a support server on Discord, where this question would be more appropriate. https://discord.gg/dsharpplus

**Comment by MaesLotws** [comment]
Have you tried using attributes? I think this will solve your problem :)
