### ISSUE TITLE
Slash command groups don't allow both top level commands and sub groups

### ISSUE THREAD

**Issue by CabbageAdi** [DSharpPlus/DSharpPlus#1153]
# Summary
Discord messed up their documentation.

# Details
You could apparently always have both top level commands and sub groups inside them. This was not listed as a valid case in the documentation, and assuming it wasn't allowed it was not accounted for.

**Comment by SeraphimRP** [comment]
Has there been any progress on this? This would be very valuable to have before the Slash Commands migration.

**Comment by OoLunar** [comment]
I currently have a lot on my plate, however I'll do it once I've finished everything else I'm working on

**Comment by OneYellowLemon** [comment]
I was attempting to work on this, but I am new to attributes in C# and don't fully understand them yet. 

I think the only disallowed case we need to check for is a subcommand group inside a subcommand group (inside a normal command group):
```
command
|
|__ subcommand-group
    |
    |__ subcommand-group
|
|__ subcommand-group
    |
    |__ subcommand-group
```

I believe subcommand groups inside of subcommands are already not possible by nature of groups being classes and commands being methods.

**Comment by IDoEverything** [comment]
This is indeed the case. If you're working on this issue, it's probably a better idea to refactor the entire registration and handling system to not use the weird multiple-classes-for-every-nesting-type model. This could be done with something like a single builder class, which could even be used for registering commands without the whole attribute system like you can with CommandsNext. Though if your priority is just to get this working then that's not necessary for now.
