### ISSUE TITLE
Slash commands "add mentions" gives 400 Bad Request every time

### ISSUE THREAD

**Issue by FireController1847** [DSharpPlus/DSharpPlus#1158]
# Summary
Not to criticize your template, but isn't the point of the issue title supposed to be for summarizing the issue? I mean, every issue I've made the title is pretty self explanatory lol.

# Details
I only have one case in which this happens 100% of the time, however I'm sure there might be more, I just haven't had the time to investigate into it. It's very easy to reproduce, just respond to a slash command like so:
```csharp
await context.CreateResponseAsync(InteractionResponseType.ChannelMessageWithSource, new DiscordInteractionResponseBuilder() {
    Content = $"Alright, {user.Mention} now has permission to speak in this channel once more!"
}.AddMention(new UserMention(user)));
```

It does not matter if you use AddMention or AddMentions. I've only tested with UserMention.

The error is a Bad request: 400 with the following errors:
```json
{
  "data": {
    "allowed_mentions": {
      "_errors": [
        {
          "code": "MODEL_TYPE_CONVERT",
          "message": "Only dictionaries may be used in a ModelType"
        }
      ]
    }
  }
}
```

# Steps to reproduce
Steps to reproduce provided in details.

# Notes
Using DSharpPlus 4.2.0-nightly-01038

**Comment by IDoEverything** [comment]
Thanks for reporting this; apparently interaction responses didn't respect allowed mentions at all. I've fixed this in #1163
