### ISSUE TITLE
[Feature][SlashInteractions] Add support for Discord API's permissions

### ISSUE THREAD

**Issue by stepech** [DSharpPlus/DSharpPlus#1161]
Hey there,

with SlashCommands came also discord slash commands permission support - [link](https://discord.com/developers/docs/interactions/application-commands#permissions). As I was informed, this implementation will be quite hard, as it requires several calls to Discord API after registering all the commands, but it is a very important feature. Implementing permissions this way instead of planned Attributes will make it possible to hide commands from unauthorised users and make the whole setup look nicer and cleaner.

I ask if it's possible to make it in 4.2.0, or if it's at least possible to implement it later, as such feature would be really usefull.

**Comment by Lulalaby** [comment]
This is implemented as far as I know

**Comment by stepech** [comment]
Can you give me an example of how to use it in code/link to src where it's defined?

**Comment by Lulalaby** [comment]
nvm was wrong
I had it 😅

**Comment by VelvetThePanda** [comment]
The current state of the API and slash command permissions are rather primitive, and this is reflected in our implementation. Given that its planned to [completely restructure how slash command permissions will work](https://github.com/discord/discord-api-docs/discussions/3581), I see no reason for us to invest time to attempting to make a primitive API more end-user friendly this late. Furthermore, the method you're looking for is on the guild object itself, called [EditApplicationCommandAsync](https://dsharpplus.github.io/api/DSharpPlus.Entities.DiscordGuild.html?q=EditApplicationCommand#DSharpPlus_Entities_DiscordGuild_EditApplicationCommandAsync_System_UInt64_Action_ApplicationCommandEditModel__)

**Comment by stepech** [comment]
I agree it might be good to wait (As you've put some valid points), I disagree that `EditApplicationCommandAsync` is the method I was looking for. That method only allows modifications already supported by the library, as changing command's name or some basic options. Slash Command permissions are whole new feature not yet implemented by DSharpPlus.

**Comment by VelvetThePanda** [comment]
Meant to link [this one](https://dsharpplus.github.io/api/DSharpPlus.DiscordRestClient.html?q=EditApplicationComman#DSharpPlus_DiscordRestClient_EditApplicationCommandPermissionsAsync_System_UInt64_System_UInt64_IEnumerable_DiscordApplicationCommandPermission__), sorry. 

This method (which also exists on the guild, or at least should) appears to take DiscordApplicationCommandPermission, which looking at [our docs](https://dsharpplus.github.io/api/DSharpPlus.Entities.DiscordApplicationCommandPermission.html?q=ApplicationCommandPermission#DSharpPlus_Entities_DiscordApplicationCommandPermission_Type) appears to reflect the API as far as I'm aware. Correct me if I'm wrong.

**Comment by IDoEverything** [comment]
The current slash command permission system will not be implemented natively into the slash commands extension. The rest methods for it are available in the library to be used. There's no point in coming up with an overcomplicated solution to use the current system when there's a much better and easier to use system in the works.
