### ISSUE TITLE
Finish Application Command Option Structure

### ISSUE THREAD

**Issue by b-rad15** [DSharpPlus/DSharpPlus#1171]
Make sure you familiarize yourself with our contributing guidelines.

# Summary
Not all application command options are enabled, specifically required and channel_types

# Details
All command options should be enabled to provide full support for slash commands. Having optional parameters can be important and specifying channel types makes it so that an extra check doesn't need to be added to disable voice, channel group, and threads

**Comment by IDoEverything** [comment]
Both of these are already available. `required` is automatically set, and you can assign a default value to the parameter to make it optional. `channel_types` can be set using the `[ChannelTypes()]` attribute on the parameter.

**Comment by b-rad15** [comment]
thanks, I see now how I missed it. Missed that line and was searching for "required" instead of "optional". I also put in a PR to clarify that that attribute is also a way to modify choices
