### ISSUE TITLE
Alternative to RespondWithFileAsync

### ISSUE THREAD

**Issue by johnny32** [DSharpPlus/DSharpPlus#1174]
# Summary
I'm upgrading from version 4.0.0-rc1 to the current stable 4.1.0. Previously, I used the method ```RespondWithFileAsync``` from the class ```DiscordMessage``` to respond to a user message with an image or a file. I see that in the current version this method is no longer available. What would be its alternative?

# Details
What I previously did was:

```
await context.Message.RespondWithFileAsync(fileRoute);
```

where ```context``` was a ```CommandContext``` and ```fileRoute``` indicated the physical path to a file.

I'm using DSharpPlus version 4.1.0 and .NET 6.0.

Thank you.

**Comment by JulianusIV** [comment]
Use a `DiscordMessageBuilder` and call `.WithFile(path)` on it.
You can then just give that builder to `SendMessageAsync()`

**Comment by johnny32** [comment]
Thanks, it worked.
