### ISSUE TITLE
Create and Edit message dont have the same Mentions default values

### ISSUE THREAD

**Issue by MichaelPrust** [DSharpPlus/DSharpPlus#1177]
# Summary
Messages assumes different behaviour about "mentions" between create and edit routines.

# Details
Using a DiscordMessageBuilder:
When creating a message using DiscordChannel.CreateMessageAsync(), the message assumes Mentions.All by default on DiscordApiClient.CreateMessageAsync() (currently on line 1300). 
But when editing a message by DiscordMessage.ModifyAsync(), the message assumes Mentions.None on by default on DiscordApiClient.EditMessageAsync() (currently on line 1414).

**Comment by VelvetThePanda** [comment]
This is a mitigation for an issue that arises with mentions. The reason Mentions.None is used when editing is so you don’t pseudo-mention users and roles (editing messages does not ping users, but will highlight the message)

**Comment by MichaelPrust** [comment]
> This is a mitigation for an issue that arises with mentions. The reason Mentions.None is used when editing is so you don’t pseudo-mention users and roles (editing messages does not ping users, but will highlight the message)

but the "highlight" is gone after editing the message

**Comment by VelvetThePanda** [comment]
What version are you using, though? And how're you going about editing messages, because I did extensive testing before opening a PR that put the nail in the coffin for mention issues.

**Comment by VelvetThePanda** [comment]
#1054 for reference

**Comment by MichaelPrust** [comment]
> What version are you using, though? And how're you going about editing messages, because I did extensive testing before opening a PR that put the nail in the coffin for mention issues.

I update yesterday to 4.2.0-nightly-01054 after saw the messages lossing highlight on edited messages. But its keep occuring.

Before it, I was on 4.2.0-nightly-01045 when I saw it happening for the first time.

Previous this update to 4.2.0-nightly-01045, I was using the 04.01.00, where its dont happens.

**Comment by VelvetThePanda** [comment]
How are you going about editing these messages?

**Comment by MichaelPrust** [comment]
> How are you going about editing these messages?![image](https://user-images.githubusercontent.com/13747320

I did a simple command to reproduce this issue

![image](https://user-images.githubusercontent.com/13747320/147287342-a59f7df5-f274-4c92-86b5-49f2d142adfa.png)
![image](https://user-images.githubusercontent.com/13747320/147287352-c878cd6a-3f60-44d6-806d-3612b812b94d.png)

```csharp
        [Command("TestBuildMessage")]
        public async Task TestBuildMessage(CommandContext ctx, [RemainingText] string msg)
        {
            var b = new DiscordMessageBuilder();
            b.WithContent(msg);

            await ctx.Channel.SendMessageAsync(b);
        }

        [Command("TestEditBuildMessage")]
        public async Task TestBuildMessage(CommandContext ctx, ulong msgId, [RemainingText] string msg)
        {
            var b = new DiscordMessageBuilder();
            b.WithContent(msg);

            var dMsg = await ctx.Channel.GetMessageAsync(msgId);

            await dMsg.ModifyAsync(b);
        }```

**Comment by VelvetThePanda** [comment]
👋🏽 Just making sure this is a nonissue before I close this
