### ISSUE TITLE
Missing event: EMBEDDED_ACTIVITY_UPDATE

### ISSUE THREAD

**Issue by TheArcaneBrony** [DSharpPlus/DSharpPlus#1178]
Make sure you familiarize yourself with our contributing guidelines.

# Summary
DSharpPlus prints a message about an unimplemented event when getting gateway events for voice activities (such as Watch Together)

# Details
.net 6.0
Windows 11
DSharpPlus 4.2.0-nightly-01054

```
[2021-12-24 04:29:12 +01:00] [105 /WebSocketRec] [Warn ] Unknown event: EMBEDDED_ACTIVITY_UPDATE
payload: "users": [
  "84022289024159744"
], "guild_id": "806142446094385153", "embedded_activity": {
  "type": 3,
  "timestamps": null,
  "state": "20 of 595 videos",
  "secrets": {
    "join": "291de587-2ecf-477b-a097-765627551304"
  },
  "name": "Watch Together",
  "details": "In a watch party",
  "created_at": null,
  "assets": {
    "large_image": "881026601624694814"
  },
  "application_id": "880218394199220334"
}, "channel_id": "837777977819004973"
```

# Steps to reproduce
1. Invite bot to a server
2. Start playing an activity such as Watch Together (can be done with the Activities bot)
3. Every time the video changes this will be dumped to console

# Notes
Not applicable

**Comment by Neuheit** [comment]
It looks like this isn't supposed to be dispatched to bots, so I'll be closing this issue. If it ever becomes documented feel free to reopen this.
