### ISSUE TITLE
Trying to diagnose cause of an issue with game mod that uses DSharpPlus

### ISSUE THREAD

**Issue by kotoroshinoto** [DSharpPlus/DSharpPlus#1180]
I have followed the instructions provided by the mod authors, as well as looking into the documentation for discord's settings and i'm not sure where the disconnect is.

The mod's discord interface is mostly implemented here: https://github.com/Eco-DiscordLink/EcoDiscordPlugin/blob/develop/DiscordLink/Source/DLDiscordClient.cs

There is an existing issue in their tracker regarding this problem here: https://github.com/Eco-DiscordLink/EcoDiscordPlugin/issues/62

I suspect there is something missing either from how we were directed to generate the invite link for the bot (something that would properly enable the intent), or that they're somehow reading/accessing the intent incorrectly.

as shown in that issue, my settings for the bot should have enabled the relevant guild members intents: 
![image](https://user-images.githubusercontent.com/1337560/147718616-dbb8ca17-8e16-49ba-814d-9a02091aa0c1.png)

yet the mod/bot doesn't think it has that intent enabled.

Does the fault lie with DSharpPlus, Discord's API, the mod's code or some combination of more than one of these? 

Their instructions for setting up the bot/application side of things are here:

https://github.com/Eco-DiscordLink/EcoDiscordPlugin/blob/develop/Installation.md#13-set-the-server-you-want-to-invite-the-bot-to-then-click-continue

**Comment by VelvetThePanda** [comment]
1. Embedding a gateway client (DiscordClient/DiscordShardedClient) in any form of game or UI application is ill-advised.
2. Ensure you have the intent configured in your code as well; simply turning it on in the dev portal only tells Discord you may want to use this intent when connecting to the gateway.
3. As far as I'm aware, we don't currently support the message content intent, but `DiscordIntents.All` should serve as a feasible hot-fix, assuming they haven't introduced a major breaking change with intent values.

**Comment by kotoroshinoto** [comment]
according to their code, it looks like the bot attempts to create a connection using full intents first, and if that fails, it uses partial intents. (lines 62-70)

the impact of that boolean occurs on line 106, where the OR of the guildmembers and all unprivileged intents are supplied if the boolean is true and only all unprivileged intents are used otherwise.

they do indicate in their issue tracker that something might be going wrong during our creation of the application and bot, but I want to rule out whether their code is doing something incorrectly before I delve too deeply into that possibility.

Should the code on lines 100 to 107 work as intended  and properly request the GuildMembers intent?

What might cause such a request to fail when it worked previously? Did anything in discord's security rules prevent this from working without additional action on my part? Do I have to use a more complex set of oauth scopes beyond just bot?

**Comment by MonzUn** [comment]
> 1. Embedding a gateway client (DiscordClient/DiscordShardedClient) in any form of game or UI application is ill-advised.
> 2. Ensure you have the intent configured in your code as well; simply turning it on in the dev portal only tells Discord you may want to use this intent when connecting to the gateway.
> 3. As far as I'm aware, we don't currently support the message content intent, but `DiscordIntents.All` should serve as a feasible hot-fix, assuming they haven't introduced a major breaking change with intent values.

Hey, author of DiscordLink here. Thanks for responding :)

1. I unfortunately don't have much choice since my application is a mod to a game which server has a graphical component. Yes, this causes me quite some pain.

2. Fairly sure it's set up right. O test full intents first and of it fails I go with a curated list of the minimum I need.

3. I haven't done anything for message content intent yet either, but I'll make sure to handle it when there is support!

**Comment by MonzUn** [comment]
@kotoroshinoto Are you using bleeding edge or the latest release?

The latest stable release is quite of of date on the DSharp version and will get updated around the 9.5 update of the game server.

If you're experiencing this on bleeding edge, we could test your bot in my debug environment as my own bot works fine on bleeding edge.

**Comment by Giggitybyte** [comment]
Any updates on this issue?

**Comment by MonzUn** [comment]
No, @kotoroshinoto never got back to me and nobody has claimed it's an issue on bleeding edge so I still think this ticket can be closed.

**Comment by Giggitybyte** [comment]
👌
