### ISSUE TITLE
[Bug] Inconsistent information in new uncached DiscordMessage

### ISSUE THREAD

**Issue by stepech** [DSharpPlus/DSharpPlus#1192]
# Summary
There is an inconsistency between parameters in uncached message. Some parameters initialize themselves even when the library doesn't have enough information leading to misleading information in the message object.

# Details
Using .NET 6, DSharp version 4.1.0 - tested on 4.2 nightly 01060 with same results

### Facts:
When initializing uncached message - eg from Event handling of added reaction - the library doesn't initialize the Message object correctly. When accessing Embed list of such message, the list is returned and empty - making developer believe that there are no embeds attached to that message, even though the library doesn't have enough info to say so. Other parameters behave correctly - like message content, which is returned as null if not cached. If retreiving same message, but cached, the info is then different. Embed list is correctly occupied.
Expected behaviour: Parameters about which we don't have information should stay on `null`, like already happens with most of them.

### Assumptions
[Message constructor initializes all list parameters](https://github.com/DSharpPlus/DSharpPlus/blob/master/DSharpPlus/Entities/Channel/Message/DiscordMessage.cs#L65) - attachments, embeds, mentioned_users, reactions, stickers.... They all seem to initialize always at least with empty list. The bug might not be only with Embeds?

# Steps to reproduce
1. Create reactionAdd event handler
2. Send a message through other bot on discord, which has an embed attached
3. Launch the bot
4. React to the message
5. Embed list is empty (not null, but empty)
6. Repeat 2 and 4
7. Embed list is occupied

# Notes
We can always retreive correct message through await method, but it's always worth checking if we don't have enough cached information. This is inconsistency which seems like we do, even though the information is wrong

**Comment by Giggitybyte** [comment]
https://github.com/DSharpPlus/DSharpPlus/blob/master/DSharpPlus/Clients/DiscordClient.Dispatch.cs#L1650-L1710

Discord [only sends an ID](https://discord.com/developers/docs/topics/gateway#message-reaction-add) for the message with the event. If the message is not found in cache, a partial object will be created using the available data from that event. The only way to 'fix' this would be to make an API call and fetch the full message.

**Comment by stepech** [comment]
> Discord [only sends an ID](https://discord.com/developers/docs/topics/gateway#message-reaction-add) for the message with the event. If the message is not found in cache, a partial object will be created using the available data from that event. The only way to 'fix' this would be to make an API call and fetch the full message.

I definitely don't want that as fetching whole message while handling an event might become very slow very quickly on big servers with a lot of "partial messages" being created. All I'm asking for is to make all the objects/vars that we don't know anything about `null`. Right now this is how it looks uncached:
![image](https://user-images.githubusercontent.com/29132060/149802694-8dbf1b08-9742-44a9-b0cf-6c90b0b9fd65.png)

And same message cached:
![image](https://user-images.githubusercontent.com/29132060/149802742-f92dd844-23b9-44ac-95ca-4342dc708709.png)

There is difference between it being empty array of size 0 and `null`.

**Comment by stepech** [comment]
You actually already do that with Components of the message. Uncached message:
![image](https://user-images.githubusercontent.com/29132060/149803300-9866c811-c43e-4757-9219-e84f528b1d10.png)

And cached message with no components:
![image](https://user-images.githubusercontent.com/29132060/149803383-f103d537-fcda-43d5-92fd-5f4f61ee7781.png)

**Comment by DWaffles** [comment]
Looking into it, unless I'm mistaken. It appears to be the lazy loading from the constructor of the discord message.
https://github.com/DSharpPlus/DSharpPlus/blob/7e9de2f8e0b7059c7a69d47764c83fce40c8a08d/DSharpPlus/Entities/Channel/Message/DiscordMessage.cs#L42

Implicitly setting `_embeds` to null in the DiscordMessage constructor here returns null for the Embed property.
https://github.com/DSharpPlus/DSharpPlus/blob/7e9de2f8e0b7059c7a69d47764c83fce40c8a08d/DSharpPlus/Clients/DiscordClient.Dispatch.cs#L1677-L1682

@Giggitybyte Would you like to make a PR setting the attachments, embeds, mentioned channels/roles/members to explicitly to null if the message isn't cached?

**Comment by OoLunar** [comment]
What's the status on this issue? Is anyone willing to try to fix this?

**Comment by stepech** [comment]
Any updates? 😅

**Comment by akiraveliara** [comment]
this is 'fixed by library design' in v6, and unfortunately approximately impossible to do comprehensively in v5 (although some individual spots can absolutely be fixed, if someone needs those, please file a separate issue)
