### ISSUE TITLE
Feature: Guild specific member banner

### ISSUE THREAD

**Issue by Mantas-2155X** [DSharpPlus/DSharpPlus#1200]
# Summary
Ability to get a _guild specific_ member banner.

# Details
Currently with DSharpPlus you can get a member's banner but not their _guild specific_ banner (Nitro feature).
It would be nice if it was an option just like getting the guild avatar for a specific member.

# Notes
Example URL of a guild specific banner 
`https://cdn.discordapp.com/guilds/{guildid}/users/{userid}/banners/{bannerhash}.png`

Example URL of a global banner
`https://cdn.discordapp.com/banners/{userid}/{bannerhash}.png`

**Comment by OoLunar** [comment]
Thanks for the detailed issue, I'll see if I can get this implemented today

**Comment by OoLunar** [comment]
To clarify further on this: It 100% *is*  possible to do this (as the endpoints exist and bots can access it), however the issue here is obtaining the banner hash in the first place. Further testing will be done in order to look for the hash.

**Comment by VelvetThePanda** [comment]
Yes, but this is [not in the documentation](https://discord.com/developers/docs/resources/guild#guild-member-object) and unsupported as of right now. no bot-accessible endpoints return guild banners in the member object.
