### ISSUE TITLE
Add support for codeblocks ANSI coloring in the `Formatter` class

### ISSUE THREAD

**Issue by OoLunar** [DSharpPlus/DSharpPlus#1205]
# Summary
In the Discord canary client, there's support to use ANSI formatting codes in codeblocks to make colored text, just as you would in a terminal. We need to find an intuitive way to implement this.

# Details
First we're going to have to introduce an `AnsiColor` class, which consists of a bunch of constants. As far as I'm aware, Discord only supports 8 bit ANSI colors, not 256+ colors such as other terminals. This may change in the future.

A possible way to implement this is by adding an extension method to the `StringBuilder` class called `StringBuilder.AddColor(AnsiColor color)` and then introducing a `Formatter.Colorize(string colorizedString)` method. The downsides to this is that it's not immediately obvious that there's an extension method available on the `StringBuilder` class unless if they read the documentation on the `AnsiColor ` method.

Another way of implementing this is by adding an extension method to the `string` object, called `AddColoredString(this string, AnsiColor color, string appendedString)`. This would allow for easy chaining of methods. The issue with this is that it isn't on the `Formatter` class, like it should be.

I'm not content with either of these implementations due to how they are only extension methods and not a `Formatter` method, which could make these difficult to find or allow them to be used out of the method's scope (such as attempting to use a colored string in logging files).

# Notes
Discussion highly encouraged.

**Comment by VelvetThePanda** [comment]
ansi*

**Comment by VelvetThePanda** [comment]
Done @OoLunar 
![image](https://user-images.githubusercontent.com/42438262/153107786-a868cea8-a7de-4b8d-b8a7-0a52fcac0d2d.png)

**Comment by VelvetThePanda** [comment]
I went with a far simpler API of accepting the string and then the styles to apply. `Formatter.Colorize("some text", AnsiColor.Blue, AnsiColor.BackgroundWhite)`

**Comment by OoLunar** [comment]
>Discussion highly encouraged.
>along with ideas on how to implement this.
While your solution is without a doubt ideal, I do wish that you would propose it as an idea before putting work into it. By proposing it as an idea in the discussion, this could potentially save you X amount of time **if** your idea was rejected.

**Comment by VelvetThePanda** [comment]
My PR is just pitching an idea; by no means does it have to be merged.

I also had free time and wanted to do something other than working on god awful modals, so no loss from me really

**Comment by VelvetThePanda** [comment]
Took all of five minutes actually 

![](https://cdn.discordapp.com/emojis/913662303080181800.webp?size=256&quality=lossless)

**Comment by OoLunar** [comment]
I completely understand. Looking at the PR and comparing to other resources online (such as [this](https://gist.github.com/rene-d/9e584a7dd2935d0f461904b9f2950007)) I noticed that there are a few missing elements. Is this because Discord doesn't support them?

**Comment by VelvetThePanda** [comment]
Yep. Discord supports ~8 colors for bg and fg, and 2 stylings. The former of which is a bit scuffed in the client lately? I left a note in there I think.
