### ISSUE TITLE
Cached DiscordThreadChannels don't get updated

### ISSUE THREAD

**Issue by Kaoticz** [DSharpPlus/DSharpPlus#1234]
# Summary
`DiscordThreadChannel.DiscordThreadMetadata` doesn't seem to get updated appropriately.

# Details
`DiscordThreadChannel`s don't seem to be updated after they are cached.
Sample code:
```cs
[Command("archivethreads")]
public async Task ArchiveThreadsAsync(CommandContext context, DiscordChannel channel)
{
    if (channel is DiscordThreadChannel)
    {
        await context.Message.CreateReactionAsync(DiscordEmoji.FromUnicode("❌"));
        return;
    }

    var isEmpty = channel.Threads.All(x => x.ThreadMetadata.IsArchived);

    foreach (var thread in channel.Threads.Where(x => !x.ThreadMetadata.IsArchived))
        await thread.ModifyAsync(x => x.IsArchived = true);

    await context.Message.CreateReactionAsync((isEmpty) ? DiscordEmoji.FromUnicode("❌") : DiscordEmoji.FromUnicode("✅"));
}
```

# Steps to reproduce
1. Create a thread on some channel. D#+ caches it ok.
2. Now archive that thread, either manually on Discord or through `DiscordThreadChannel.ModifyAsync()`.
3. `DiscordThreadMetadata.IsArchived` should go from `false` to `true`, but it doesn't.

# Notes
I've also noticed that thread channels that already exist don't get cached when the bot goes online, but I'm not sure if that's intentional or not.

**Comment by OoLunar** [comment]
> I've also noticed that thread channels that already exist don't get cached when the bot goes online, but I'm not sure if that's intentional or not.

Objects should be cached on an as-is basis, when the DAPI sends them to us. 

>  Create a thread on some channel. D#+ caches it ok.
    Now archive that thread, either manually on Discord or through DiscordThreadChannel.ModifyAsync().
    DiscordThreadMetadata.IsArchived should go from false to true, but it doesn't.

Thanks for the instructions. I'll check to see if it's this specific method that isn't caching, or if the metadata in general isn't caching
