### ISSUE TITLE
Default CNext Command Handler not truly async

### ISSUE THREAD

**Issue by OoLunar** [DSharpPlus/DSharpPlus#1244]
# Summary
The number of commands that can be executed at once is limited to the amount of threads available. On my system specifically, once I execute 8 help commands, any commands after fail to execute until I manually close the interactivity help menus.

# Steps to reproduce
1. Find the number of threads your CPU supports
2. Execute an interactivity command per CPU thread (I.E, execute >>help 8 times if you have 8 CPU threads)
3. Execute *any*  command after, and notice how the commands fail to process.

# Notes
I don't believe events are impeded in anyway, however I don't have an easy way to test at the moment.

**Comment by VelvetThePanda** [comment]
As Discussed on Discord it is asynchronous, and simply ignorantly documented.
