### ISSUE TITLE
Error setting value to 'OAuthFlags' on 'DSharpPlus.Entities.DiscordMember'.

### ISSUE THREAD

**Issue by jackiesphan1996** [DSharpPlus/DSharpPlus#1253]
I got this issue this morning without any code changes. Are there any one of you have this issue ? Thanks in advance.
![image](https://user-images.githubusercontent.com/59761905/161375243-28a02d0a-83c3-4333-8517-1d708abdec2f.png)

**Comment by ExaInsanity** [comment]
update to the latest nightly, it's fixed there.

**Comment by MillyKookie** [comment]
Not for me, i have update to 4.2.0-nightly-01091, but error always occurs.

**Comment by ExaInsanity** [comment]
well, the latest nightly is 4.2.0-nightly.01105 - it was fixed in 01104 iirc

**Comment by MillyKookie** [comment]
I haven't this version on my nugets package manager https://nuget.emzi0767.com/api/v3/index.json
Last is 01091
![Capture](https://user-images.githubusercontent.com/67654898/161378014-aa04f6ca-7ece-4c32-bf14-d7ed65dbcc4c.PNG)

**Comment by ExaInsanity** [comment]
nightly versions were moved to nuget.org recently.

**Comment by MillyKookie** [comment]
Okay, i'll try it. Thanks.
