### ISSUE TITLE
MessageReactionAddEventArgs.User cannot be cast to DiscordMember

### ISSUE THREAD

**Issue by oliverbooth** [DSharpPlus/DSharpPlus#1263]
# Summary
`InvalidCastException` is thrown when attempting to cast the `User` property of `MessageReactionAddEventArgs`

# Details
The xmldoc written on the `User` property indicates that the value can be cast to `DiscordMember` if the reaction was added to a guild message:
![image](https://user-images.githubusercontent.com/1129769/162400857-0ee257ea-1aa2-4afb-b313-6548cb151bbc.png)
However, this throws `InvalidCastException`:
```
[2022-04-08 09:37:54 +01:00] [104 /EventHandler] [Error] Event handler exception for event MESSAGE_REACTION_ADDED thrown from System.Threading.Tasks.Task <<Main>$>b__0_0(DSharpPlus.DiscordClient, DSharpPlus.EventArgs.MessageReactionAddEventArgs) (defined in Program+<>c)
System.InvalidCastException: Unable to cast object of type 'DSharpPlus.Entities.DiscordUser' to type 'DSharpPlus.Entities.DiscordMember'.
```

# Steps to reproduce
1. Subscribe to `MessageReactionAdded` event
2. Check for non-null guild (to ensure the reaction was, in fact, added in a guild)
3. Cast `User` to `DiscordMember`

```cs
using DSharpPlus;
using DSharpPlus.Entities;

var client = new DiscordClient(new DiscordConfiguration {Token = Environment.GetEnvironmentVariable("DISCORD_TOKEN")});
client.MessageReactionAdded += async (_, args) =>
{
    if (args.Guild is null) return;

    var member = (DiscordMember) args.User;
    await args.Channel.SendMessageAsync($"Reaction added by {member.Mention}");
};

await client.ConnectAsync();
await Task.Delay(-1);
```

**Comment by oliverbooth** [comment]
My initial thoughts are this is due to b59751f4798d09e8064e4c173af196056aa48db5 which resorted to decorating properties in `DiscordMember` with `JsonIgnoreAttribute`, causing it to not be deserializable from the payload provided by `MESSAGE_REACTION_ADDED`.

That is merely an assumption though.

**Comment by DWaffles** [comment]
Am able to recreate this and make a hotfix for this. I'm not sure what other events has this issue, and I won't have the time to test a lot of other events. If someone else would like to get me a list of other events that have this error, I'll look into those. Otherwise, I'll be making a PR soon-ish:tm:.
