### ISSUE TITLE
Smart quotes handling.

### ISSUE THREAD

**Issue by Liviu50** [DSharpPlus/DSharpPlus#1268]
The issue is probably related to the CommandsNext library from what i have been told.
Basically commands ignore any argument which might need the double quotes if those quotes are smart quotes.

More specifically:
Any command that needs a string as an argument for example:  -test "name with spaces" , will not even proc the function test itself if instead of the double quotes we use smart quotes ( “ ” ).
I tried and found this on my own bot, using windows 10 and a .NET Framework 5.0.
The way to reproduce it is of course very simple. to any bot create a command that requires a string to be activated, use those smart quotes or anything other than the normal double ones.

Since this issue was presented to me by one of my users, i am guessing that this is somewhat a common occurrence for mobile users so perhaps adding these quotes might benefit a lot more people.

Have a nice day!

**Comment by OoLunar** [comment]
Thanks for the issue, will look into it

**Comment by Kaoticz** [comment]
An alternative solution would be to tell the users to disable Smart Punctuation on their devices. It's somewhere in the settings.
To my knowledge, iPhones and iPads have that setting enabled by default.

**Comment by OoLunar** [comment]
Sure, but this seems like something we can handle.
