### ISSUE TITLE
Mentioning my bot

### ISSUE THREAD

**Issue by LennonPereira** [DSharpPlus/DSharpPlus#1271]
How do I return a message mentioning my bot?

**Comment by OoLunar** [comment]
Well if this is a brand new bot and you're still learning, you could do this:
```cs
namespace Bot
{
    public class Program
    {
        public static void Main(string[] args)
        {
            DiscordClientConfiguration config = new()
            {
                Token = args[0] // We're going to assume that the first argument passed to the program is the token. Ideally you should read it from a file or environment variables.
            }
            DiscordClient client = new(config);
            client.MessageCreated += async e =>
            {
                if (e.Message.Content == "!mention_bot")
                {
                    await e.Message.RespondAsync(context.Client.CurrentUser.Mention);
                }
            };
        }
    }
}
```
However instead, you should use our commands framework: CommandsNext. With CNext, you can easily auto-register commands, run pre-execution checks, and use the advanced built-in help command. I seriously recommend it.

If you're already using the CommandsNext extension, you can do something like this:
```cs
namespace Bot.Commands
{
    public class MentionBot : BaseCommandApplication
    {
        [Command("mention_bot"), Description("Mention the bot.")]
        public async Task MentionBotAsync(CommandContext context)
        {
            await context.RespondAsync(context.Client.CurrentUser.Mention);
        }
    }
}
```

Here are some [examples](https://github.com/OoLunar/Tomoe/tree/rewrite/DSP_3.0/src/Commands/Common) from my bot. If you ever have any more questions, feel free to reach out to us over at our [Discord](https://discord.gg/dsharpplus)

**Comment by DWaffles** [comment]
> Here are some [examples](https://github.com/OoLunar/Tomoe/tree/rewrite/DSP_3.0/src/Commands/Common) from my bot. If you ever have any more questions, feel free to reach out to us over at our [Discord](https://discord.gg/dsharpplus)

I would like to take this time to peddle the work of @Giggitybyte in writing articles for CommandsNext if you need a general overview of how to get started. https://dsharpplus.github.io/articles/commands/intro.html
