### ISSUE TITLE
Socket Error & Weird Issue

### ISSUE THREAD

**Issue by Liviu50** [DSharpPlus/DSharpPlus#1277]
Good day,

So lately i've been having a bizarre error.
Basically when the bot is already started and i try to invite it on a new server no commands work on it.
On the other side if the bot was already present when i started the code then everything works.
The only solution i found was restarting the bot so everything starts working again.

Digging around with the debug i found the following:

```
[2022-04-14 02:33:55 +03:00] [108 /WebSocketRec] [Error] Socket handler suppressed an exception
System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at DSharpPlus.DiscordClient.UpdateUser(DiscordUser usr, Nullable`1 guildId, DiscordGuild guild, TransportMember mbr)
   at DSharpPlus.DiscordClient.UpdateMessage(DiscordMessage message, TransportUser author, DiscordGuild guild, TransportMember member)
   at DSharpPlus.DiscordClient.PopulateMessageReactionsAndCache(DiscordMessage message, TransportUser author, TransportMember member)
   at DSharpPlus.DiscordClient.OnMessageCreateEventAsync(DiscordMessage message, TransportUser author, TransportMember member, TransportUser referenceAuthor, TransportMember referenceMember)
   at DSharpPlus.DiscordClient.HandleDispatchAsync(GatewayPayload payload)
   at DSharpPlus.DiscordClient.HandleSocketMessageAsync(String data)
   at DSharpPlus.DiscordClient.<InternalConnectAsync>g__SocketOnMessage|391_1(IWebSocketClient sender, SocketMessageEventArgs e)
```

Since this is a very big issue i think its sort of urgent.
I use Windows 10, Visual Studio 2019 with .NET 5.0. My NUGET packages are all updated except for entity framework core and entity framework core design which give an error when updating (i guess because they need .NET 6.0).
Otherwise everything is updated. 
To be noted that this error is somewhat new, 3/4 weeks more or less, because before that it was working and no modifications were applied to the bot's settings or similar before and after it started to show these errors.
Any help is welcome thank you very much!

**Comment by OoLunar** [comment]
Which version of D#+ are you on? 4.1.0 or the latest nightly?

**Comment by Liviu50** [comment]
NUGET says that i am at the 4.1.0

**Comment by OoLunar** [comment]
Enable pre-releases and use the latest version

**Comment by Liviu50** [comment]
should i do that for every DSharpPlus related library like Interactivity and CommandsNext?

**Comment by OoLunar** [comment]
I don't *think*  it'd matter, but I usually do it anyways since pre-releases (also known as nightlies) usually contain bug fixes. I'd do it anyways

**Comment by Liviu50** [comment]
The error of the socket is gone, but the issue of the bot not working when you try to invite it to a new server while the code is running is still there...

**Comment by OoLunar** [comment]
Which command package are you using? CNext or Slashies?

**Comment by Liviu50** [comment]
I am unsure where should i check that.
I know i am using DSharpPlus.CommandsNext...but thats all i know.

**Comment by OoLunar** [comment]
CNext is CommandsNext, apologies for my nicknames. Could you list your intents? They should be set in your DiscordConfiguration object. If you haven't set any by hand, that means you're using `DiscordIntents.AllUnprivileged`

**Comment by Liviu50** [comment]
I tried to modify those as well to make sure that is not the issue but sure, intents were unchanged since the start of the bot (like i said the error is new) so unless an update screw them over...
But here they are:
DiscordIntents.GuildMessages | DiscordIntents.Guilds | DiscordIntents.DirectMessages | DiscordIntents.GuildEmojis | DiscordIntents.GuildMessageReactions | DiscordIntents.GuildWebhooks | DiscordIntents.GuildIntegrations,

**Comment by Liviu50** [comment]
to be more helpful here is the full config i use

```
                TokenType = TokenType.Bot,
                AutoReconnect = true,
                MinimumLogLevel = LogLevel.Debug,
                Intents = DiscordIntents.GuildMessages | DiscordIntents.Guilds | DiscordIntents.DirectMessages | DiscordIntents.GuildEmojis | DiscordIntents.GuildMessageReactions | DiscordIntents.GuildWebhooks | DiscordIntents.GuildIntegrations,
                AlwaysCacheMembers = false,
                MessageCacheSize = 0,
```
The loglevel is usually information but i needed it to check the issue.
Hope it helps!

**Comment by OoLunar** [comment]
Could you try the following, restarting your bot and re-executing the commands per step:
- Set your intents to `DiscordIntents.All`
- Subscribe to the `DiscordClient.GuildAvailable` event, printing text to console
- Subscribe to the `DiscordClient.MessageCreate` event, printing text to console

**Comment by Liviu50** [comment]
Ok i tried to wait for 10/15m and it started working.
Maybe the updates took a while to take effect? now it seems to be working.
If the error presents itself again ill make sure to reopen the issue.

**Comment by OoLunar** [comment]
Glad you got it working, just a few final questions:
- Did the bug occur across restarts?
- Did you change anything in your startup process?
- Are you using a custom command handler for the CNext extension?

**Comment by Liviu50** [comment]
Ok so:
1) No. Restarting the bot made it work on all servers that was already on (even the new ones) but if you tried to add it again on a new server after the restart it would keep having the same issue until the next restart.
2) No. 0 changes were made unless we count internal code for my functions but those are not related to the bot or its configs. In fact i tried to make changes to those only after it started getting those issues.
3) No i use the basic one i suppose:         
[Command("Test")]
        public async Task Test(CommandContext ctx)
        {}
Nothing special or custom there, that is how i saw it in the tutorial and followed it.
Hope it helps.

**Comment by OoLunar** [comment]
I'm quite stumped myself. I no longer work on the v4 branch as I mainly focus on the v5 branch (still in development), however, I see no reason why CNext would subscribe or be affected by the guild available event. If anyone finds a fix to this issue, I'll be sure to let you know. Thanks for opening up an issue!

**Comment by Liviu50** [comment]
Thank you for the extremely fast help and assistance!
I am just glad i fixed the problem and now i know to use the nightly ones, i did not know that i had to use those...so i kept to the stable ones.
Thank you once again for your help!

**Comment by OoLunar** [comment]
For future reference, you usually aren't forced to use nightlies. It's just been a bit since we've done a stable release and Discord has made a *lot*  of unannounced breaking changes recently. We've been trying to make a 4.2.0 release, however, we keep finding bug after bug.

**Comment by Liviu50** [comment]
Understandable, i will take note of that thank you. i heard discord was breaking stuff yeah but i did not expect it to go so much against a wall.
