### ISSUE TITLE
DiscordApplication.GenerateBotOAuth does not account for all OAuth scopes

### ISSUE THREAD

**Issue by SakuraIsayeki** [DSharpPlus/DSharpPlus#1292]
# Summary
Using the `DiscordApplication.GenerateBotOAuth()` method does not allow selecting all scopes to generate an OAuth URI.  
It currently only supports the `bot` scope, and doesn't support redirect URIs.

# Details
Starting from an ideal result of  
https://discord.com/api/oauth2/authorize?client_id=583412458560159776&permissions=8&scope=bot%20applications.commands  
This link has scopes `bot` and `applications.commands` and permission `0x8` (Administrator) specified.  

*(Generated from Discord's OAuth URL Generator tool, using the following settings)*
![image](https://user-images.githubusercontent.com/4705518/164889823-25939d7c-8473-46eb-969e-f4d3ba5e6e9d.png)

However, the current method only allows specifying a `DSharpPlus.Permissions` argument, inferring that the OAuth link will only use the `bot` scope.  

Ideally, we should be able to specify further parameters, like OAuth scopes, and a redirect link, used by other scopes (only `bot` and `applications.commands` don't make use of a redirect).

An ideal implementation would be an overload, or extending the current method, as such:
```cs
public string GenerateBotOAuth(
    Permissions permissions = Permissions.None, 
    OAuthScopes scopes = OAuthScopes.Bot, 
    string RedirectUri = null) 
{ /* Implementation */ }

// TODO: Add OAuthScopes enum.
```

Instead of the current method, found [here (source)](https://github.com/DSharpPlus/DSharpPlus/blob/master/DSharpPlus/Entities/DiscordApplication.cs#L159-L168) : 
```cs
public string GenerateBotOAuth(Permissions permissions = Permissions.None) { /* Implementation */ }
```
*Let it also be known that the current method spars absolutely no documentation whatsoever, so we might want to brush up on that too ^^*

# Steps to reproduce
### N/A

# Notes
If maintainers have their hands full, I'd be happy to Fork & PR relevant changes, as well as add documentation to the method, given my first-hand interest in this issue.

**Comment by VelvetThePanda** [comment]
It's worthwhile to note that 

1. This method greatly predates any practical OAuth2 scopes
2. This is *technically* correct in what it does, and has "no" reason to change given it's name

Renaming this method to be more generalized would be a breaking change, so perhaps creating a new method is due. 

Either way, this will be something to do in 4.3.

**Comment by SakuraIsayeki** [comment]
> It's worthwhile to note that
> 1. This method greatly predates any practical OAuth2 scopes
> 2. This is _technically_ correct in what it does, and has "no" reason to change given it's name

1. I don't think anteriority matters for extending any implementation. Times change, and people changes with the times.
2. Fantastic. Then I suppose you also accounted for the fact that no app commands provided by a bot will be made usable, given the `application.commands` is not included in the invite link? That in itself is a problem for any bot relying on slash commands and whatnot, and is in fact what brought me to opening this issue.  


> Renaming this method to be more generalized would be a breaking change, so perhaps creating a new method is due.  

Now I'm curious. Where did I mention renaming this method? My proposal was to create an overload. But, indeed, a whole other method is another viable solution.

<hr />

On another note, @VelvetThePanda, given our... Delicate and problematic history (to put it as such) and any bias that may arise from this, I'd rather appreciate further feedback from your maintainer peers. Also provided you actually did block me, I would also appreciate you further leave any issue created by me to your peers, unless absolutely necessary.  
Our bickering is not necessary, so let's leave it out of DSP and just ignore each other, okay?

**Comment by VelvetThePanda** [comment]
To the upper-half of that comment, I say it because it would not be apt to change its behavior given its very narrow name. `Generate`*`Bot`*`OAuth` doing more than a what it says on the tin not only subverts expectations, but would also be a violation of SRP, hence renaming the method to make it more apt. There's also the issue that the bot scope is independent of application.commands, so either renaming the current method to be broader and allowing for such change, or making a new, dedicated method as to not introduce breaking changes. 

---

As for the bottom half of your comment, this is not an appropriate place to bring up any personal matters, especially when they're irrelevant to the functioning of this repository. 

As a maintainer, I have the duty of keeping this library up to snuff, so your identity is rather moot to me. Please, do not drag drama into a GitHub issue, thanks.

**Comment by ExaInsanity** [comment]
I agree with Velvet on all counts here. 

Adding an overload, while a possibility, would be beyond counter-intuitive: a method that does something it is not named to do. Including `application.commands` would be acceptable to me, though not future-proof to whatever Discord may come up with. Any other scope, not being connected to the name, is out of the question to me. We can add a secondary method.

**Comment by SakuraIsayeki** [comment]
With given feedback, I'd personally advocate creating a new method, for the broader use case. Something like `GenerateOAuthUri()` ?

**Comment by OoLunar** [comment]
> On another note, @VelvetThePanda, given our... Delicate and problematic history (to put it as such) and any bias that may arise from this, I'd rather appreciate further feedback from your maintainer peers. Also provided you actually did block me, I would also appreciate you further leave any issue created by me to your peers, unless absolutely necessary.
Our bickering is not necessary, so let's leave it out of DSP and just ignore each other, okay?

As both a lib maintainer and a moderator, I'm going to ask you to quit the drama here. Velvet maintains v4 exceedingly well and belongs on this issue just as well as any other.

- Velvet already said you were right and that this will be fixed/added in 4.3.
- The conversation was going well until you brought up your past history.

If you're unable to cooperate with Velvet on something as simple as a Github Issue, I'm going to have to ask you to leave. Of course, I know that you're a responsible and respectable person, so I know you won't let it come to that. Thank you for understanding.

**Comment by SakuraIsayeki** [comment]
Just saw the follow-up this morning. I wanted to apologise for bringing this up in the first place, and apologise to you people, especially @VelvetThePanda, as a maintainer. Indeed, this should not've been brought up. Not wanting to reiterate such a mistake, I'm ready to renew my support by bringing solid contributions to DSharpPlus, wherever I can.

To conclude, thank you lads/lasses for such a quick conclusion to this issue :)

**Comment by OoLunar** [comment]
Thank you for your apology, I look forward to working with you in the future (if desired)
