### ISSUE TITLE
Request: Add an option to bypass cache in GetMemberAsync

### ISSUE THREAD

**Issue by Foxite** [DSharpPlus/DSharpPlus#1296]
## Request
Please add a parameter to GetMemberAsync, and other methods which can return cached objects, that can be used to bypass the cache entirely and request the object from Discord directly.

I will be back with a PR for this shortly, unless I forget :P

## Background
My bot lets users configure terms and when anyone says them, the bot will DM them in response. It is important that users who left guilds no longer receive DMs, so before sending them the DM I call guild.GetMemberAsync with the user ID (saved in database) to see if they are still present. However, due to caching in DSharpPlus, this method will return a DiscordMember object directly from the cache even if that user is no longer present in the guild, causing the bot to DM users who left the guild since the bot last restarted.

I could listen for GuildMemberAdded and GuildMemberRemoved events and store the full member list in memory for every guild, but I think this my request allows a less error-prone solution.

**Comment by VelvetThePanda** [comment]
I'll look into this tomorrow, or in eight months. Schrodinger's investigation.
