### ISSUE TITLE
DiscordUser.Username returns empty when saving to file because it doesn't get saved in v4.2.0

### ISSUE THREAD

**Issue by Oxyaine** [DSharpPlus/DSharpPlus#1304]
# Summary
With the newest version of D#+ (v4.2.0) saving type **DiscordUser** to a **.json** file doesn't save the username of the user, Meaning using **DiscordUser.Username** returns empty. This functioned in the previous version but not after updating. A workaround that still works is using **DiscordGuild.GetMemberAsync(DiscordUser.Id).Result.Username**

# Details
Note: All info like id, username & discriminator are blanked for privacy, By default these are filled (Obviously)

The code for saving the user to a file is as follows:
```
string path = Environment.GetFolderPath(Environment.SpecialFolder.Desktop) + "/user.json";
File.Create(path).Close();
File.WriteAllText(path, JsonConvert.SerializeObject(new TestClass() { User = ctx.User }));
```
The class TestClass is simply just a public DiscordUser, Nothing else

Here is the information found in the file before the update (v4.1.0) -
```
{
    "User": {"roles":[],"joined_at":"2022-01-30T03:04:00.914+10:30","is_deafened":false,"is_muted":false,"pending":false,"username":"*Username*","discriminator":"0000","bot":false,"public_flags":0,"id":000000000000000000}
}
```

Here is the information found in the file after the update (v4.2.0) -
```
{
    "User": {"roles":[],"accent_color":null,"communication_disabled_until":null,"joined_at":"2022-01-30T03:04:00.914+10:30","is_deafened":false,"is_muted":false,"pending":false,"id":000000000000000000}
}
```

With the following code...
```
DiscordUser user = ctx.User;
Console.WriteLine(user);
```
The result comes out as:
```
Member 000000000000000000; *Username*#0000 (*Username*)
```

That's everything I could find on the subject, Sorry if its not enough information or too much information, If more info is needed just ask and I will provide whatever is required.

Not sure if this is considered an actual issue or is just part of the update but here is the report just in case. This could also be an issue with NewtonSoft.JsonConvert, Sorry if that is the case.

**Comment by MindHardt** [comment]
The lib doesn't support, and, furthermore, deprecates serializing entities, since they have no sense if not created internally. You should not do this. Consider storing IDs and retrieving members/users during runtime.
