### ISSUE TITLE
Slash command groups can have both subcommands and subgroups

### ISSUE THREAD

**Issue by clienthax** [DSharpPlus/DSharpPlus#1305]
# Summary
Attempting to register a slash command group with both subcommands and subgroups fails.

# Details
```
2022-05-05 16:35:26.2098     27 FATAL There was an error registering application commands 
System.ArgumentException: Slash command groups cannot have both subcommands and subgroups!
   at DSharpPlus.SlashCommands.SlashCommandsExtension.<>c__DisplayClass39_0.<<RegisterCommands>b__0>d.MoveNext()
```

Nightly of https://github.com/DSharpPlus/DSharpPlus/commit/21ca805315f69b28bbaba4ce65e7601002a4281c

# Steps to reproduce
Attempt to register a slaash command with both subcommands and subgroups.

# Notes
https://discord.com/developers/docs/interactions/application-commands#subcommands-and-subcommand-groups

**Comment by VelvetThePanda** [comment]
Potentially related to #1153?

**Comment by OoLunar** [comment]
Confirmed duplicate
