### ISSUE TITLE
Retry on 5xx errors

### ISSUE THREAD

**Issue by Foxite** [DSharpPlus/DSharpPlus#1336]
I've been getting random 5xx (mostly 502) errors from Discord, which has made my bot fail to do its job at least twice. I suggest making DSharpPlus retry requests that fail to 5xx errors. It's probably a good idea to make this an optional thing that's enabled by default.

If this isn't done by the end of the week I'll probably™ do it myself on monday.

**Comment by OoLunar** [comment]
I'm personally not in favor of this. HTTP 5xx errors usually aren't one-off and can be reproduced multiple times with multiple arguments. Retrying the request multiple times likely won't solve the error and will instead only waste your ratelimits

**Comment by VelvetThePanda** [comment]
You're expected to handle server-side errors appropriately, see the [bottom of the docs](https://discord.dev/topics/rate-limits#invalid-request-limit-aka-cloudflare-bans)

**Comment by Foxite** [comment]
The errors I'm getting do seem to be one-off, http 502 is internal server error. My bot will be functioning normally and randomly get a http 502 error for no reason, like once every few days.

@VelvetThePanda the link you sent concerns dealing with 4xx errors.
