### ISSUE TITLE
Thread cache is not updated when creating a new thread

### ISSUE THREAD

**Issue by oliverbooth** [DSharpPlus/DSharpPlus#1360]
# Summary
When calling `DiscordChannel.CreateThreadAsync`, a `DiscordThreadChannel` is returned. However, this instance is not cached in `guild.Channels`, `guild.Threads`, or `channel.Threads`.

# Details
After creating a new thread, the following behaviour occurs:

* `guild.GetChannel(THREAD_ID)` returns null
* `guild.Threads.TryGetValue(THREAD_ID, out var thread)` returns false and thread is null
* `channel.Threads.FirstOrDefault(t => t.Id == THREAD_ID)` returns null

Even when the ID was fetched from the returned thread object from `CreateThreadAsync`.

# Steps to reproduce
```cs
using DSharpPlus;
using DSharpPlus.Entities;

var client = new DiscordClient(new DiscordConfiguration {Token = Environment.GetEnvironmentVariable("DISCORD_TOKEN")});
client.MessageCreated += async (_, e) =>
{
    if (e.Message.Content == "!thread")
    {
        DiscordThreadChannel? thread = await e.Channel.CreateThreadAsync(e.Message, "Test thread", AutoArchiveDuration.Day);
        await thread.SendMessageAsync("Message sent using returned thread");

        if (e.Guild.Threads.TryGetValue(thread.Id, out thread))
            await thread.SendMessageAsync("Message sent using fetched thread");
        else
            Console.WriteLine("Thread not found");
    }
};

await client.ConnectAsync();
await Task.Delay(-1);

```
The output of this program in the console:
![image](https://user-images.githubusercontent.com/1129769/181776636-373a4077-a68e-4714-a98c-d3bd020685e3.png)

And the output of this program in Discord:
![image](https://user-images.githubusercontent.com/1129769/181775822-f5803a79-c661-433e-80e0-8c7f38e1853f.png)

# Notes
Granted this specific example seems edge-case at first glance, as you already have the thread object as returned by `CreateThreadAsync`, but this becomes an issue in the service layer where a different service needs to fetch a thread by its ID rather than using - what appears to be - a temporary instance of `DiscordThreadChannel`.

**Comment by OoLunar** [comment]
Taking a look into it now, thanks for the report!

**Comment by OoLunar** [comment]
Looking at the following methods, it seems like @DWaffles forgot cache existed when implementing threads.
- [CreateThreadFromMessageAsync](https://github.com/DSharpPlus/DSharpPlus/blob/2bcabe3cb01a256c5e1d6bcccee75794d8af0352/DSharpPlus/Entities/Channel/DiscordChannel.cs#L1025)
- [CreateThreadAsync](https://github.com/DSharpPlus/DSharpPlus/blob/2bcabe3cb01a256c5e1d6bcccee75794d8af0352/DSharpPlus/Entities/Channel/DiscordChannel.cs#L1050)

**Comment by DWaffles** [comment]
> Looking at the following methods, it seems like @DWaffles forgot cache existed when implementing threads.
> 
>     * [CreateThreadFromMessageAsync](https://github.com/DSharpPlus/DSharpPlus/blob/2bcabe3cb01a256c5e1d6bcccee75794d8af0352/DSharpPlus/Entities/Channel/DiscordChannel.cs#L1025)
> 
>     * [CreateThreadAsync](https://github.com/DSharpPlus/DSharpPlus/blob/2bcabe3cb01a256c5e1d6bcccee75794d8af0352/DSharpPlus/Entities/Channel/DiscordChannel.cs#L1050)

You'll want to check with Maxine or Velvet as there was something something design philosophy about getting the updated entity from the gateway instead of the return from the API call.
