### ISSUE TITLE
InteractionContext.CommandName only displays group name 

### ISSUE THREAD

**Issue by Yeffian** [DSharpPlus/DSharpPlus#1367]
# Summary
Accessing `InteractionContext.CommandName` only shows the name of the group, instead of the name of the executed command.

# Details

**.NET Version**:  6.0.106
**D#+ Version**: 4.3.0-nightly-01152

# Steps to reproduce
1. Add a callback to the `SlashCommandExtension.SlashCommandExecuted` event
2. Log `SlashCommandExecutedEventArgs.CommandName`

Example Code:
```cs
private static SlashCommandsExtension? _slashExtension;

// setup the slash extension

_slashExtension!.SlashCommandExecuted += async (_, args) =>
{
            var ctx = args.Context;
            Log.Information($"/{ctx.CommandName} ran by {ctx.User.Username}#{ctx.User.Discriminator}");
            
            await Task.CompletedTask;
};
```

**Comment by OoLunar** [comment]
Will fix in the `fix/v4/slashies-cleanup` branch. Thanks for reporting!
