### ISSUE TITLE
CommandsNext checking if user is a bot isn't optional

### ISSUE THREAD

**Issue by Ecorous** [DSharpPlus/DSharpPlus#1369]
# Summary
When using CommandsNext, it defaults to checking if the user who ran the command is a bot/webhook, and it isn't optional

# Details
This is a big issue when using a [Revolt](https://revolt.chat) bridge with the bot, as I'd like to be able to use the bot from the Revolt side

And with design, this check shouldn't forced upon us. It would probably be a pretty simple fix as well

**Comment by VelvetThePanda** [comment]
This check exists for the very reason of, well, not responding to bots; while I can under and the use-case, we'd certainly be filling a very niche niche here.

**Comment by OoLunar** [comment]
I mean, I suppose we could do something like this:
```cs
[Flags]
public enum AcknowledgeAccountType
{
    Users,
    Bots,
    Webhooks
}
```
But as Velvet had mentioned, it *does*  seem rare that someone would have to do this. Then again... This is the 3rd time someone asked for this feature in a month

**Comment by VelvetThePanda** [comment]
Sure, and while it would be trivial to add (or rather remove), I'm not sure it's a great addition. 
V4 is already full of tech debt and our hands are either tied to other endeavors or focused on trying to keep this jenga-tower of a library from falling apart as Discord adds new features.

**Comment by DWaffles** [comment]
Mayhaps I might later in a week look into adding this as an opt in specific feature in a noncomplex manner.

**Comment by VelvetThePanda** [comment]
This issue has seemingly stalled, so I'll be closing it due to inactivity. Feel free to reopen if desired.

**Comment by e2489** [comment]
Any chance we can get this added? For my use case, I need commands to trigger when sent by webhooks, and currently that's not possible.

**Comment by akiraveliara** [comment]
While you're free to submit a pull request against CommandsNext yourself; our current plans for CNext do not involve adding new features. Progress towards the superseding technology is tracked in #1553 for the time being.
