### ISSUE TITLE
Add support for forums

### ISSUE THREAD

**Issue by oliverbooth** [DSharpPlus/DSharpPlus#1372]
# Summary
Exactly what it says on the tin.

# Details
The [`ChannelType`](https://github.com/DSharpPlus/DSharpPlus/blob/master/DSharpPlus/Enums/Channel/ChannelType.cs) enum does not currently list `GUILD_FORUM` (type 15) as a supported value (it also does not list `GUILD_DIRECTORY` - type 14 - but that is unrelated to the issue at hand here)

As per the [API reference](https://discord.com/developers/docs/resources/channel#channel-object-channel-types), Forums are a new feature that are still being rolled out and innovated, but this should still be on the roadmap for D#+ imo. It appears that they are just the same as any other channel object, the only difference being that you can only create threads in them (i.e. "posts") - not send messages directly to them.

# Notes
The endpoint for creating a thread inside a forum is the same as creating the thread anywhere else (see https://discord.com/developers/docs/resources/channel#start-thread-in-forum-channel), but it appears to accept different parameters in the body. Namely `invitable` and `type` are not accepted, but a `message` is required.

**Comment by oliverbooth** [comment]
I'm bumping this. I feel this issue was closed accidentally because there was only a single PR linked to it. Forums are by no means implemented yet.

**Comment by Naamloos** [comment]
Yeah that closing was accidental

**Comment by VelvetThePanda** [comment]
I'll hopefully get to this by the end of the week. Life has been rough recently, so no promises.
