### ISSUE TITLE
Discord Member IsPending not updating when passing membership screening

### ISSUE THREAD

**Issue by BlackLotusLV** [DSharpPlus/DSharpPlus#1373]
Make sure you familiarize yourself with our contributing guidelines.

# Summary
IsPending for DiscordMember does not update after agreeing to the rules via membership screening.

# Details
D#+ does not update IsPending status if user updates it while bot is active.
1. Start Bot.
2. Join the server and IsPending status will be true.
3. Agree to rules via membership screening, IsPending status is still true. (it should be false)

But if you join the server and agree to rules and only the start the bot, IsPending status is false. So it does get the initial info correctly, just fails to update it.

**Comment by VelvetThePanda** [comment]
Semi-intentional change; `DiscordMembers` are more so data objects with convenience methods than god objects because constantly checking for places that things are and aren't updated, as well as what exactly is and isn't updated was very inconsistent across the entire library. See [this PR](https://github.com/DSharpPlus/DSharpPlus/pull/1208)

**Comment by BlackLotusLV** [comment]
I find this to be quite a big issue in my use case. I use membership screening in my server and the welcome message is sent only after they have agreed. Previously it was simply done by checking past IsPending to current one in the member updated event. Now got to add other checks like adding a role to the user and checking for role count, to not spam whenever the change the nickname, until the bot has restarted.
And quite idiotic to need to restart the bot every time you want to check on a smaller server weather the person has accepted the rules or not.

I understand that in my use case the actual solution is for discord to finally release and documentate the membership screening  update thing in the API, but lets be honest, 5.0 is coming sooner than that.

**Comment by VelvetThePanda** [comment]
> Previously it was simply done by checking past IsPending to current one in the member updated event.

I'd like to mention that this *should* work as intended? Just that if you were to pull any given member from `DiscordGuild#Members`, that member object would not be updated, but instead replaced with the updated object; the events should still work fine, but if *that* is the issue, then I'll take a look into this.

**Comment by VelvetThePanda** [comment]
Also here's [the code I'm referring to.](https://github.com/DSharpPlus/DSharpPlus/blob/master/DSharpPlus/Clients/DiscordClient.Dispatch.cs#L1247-L1250)

**Comment by BlackLotusLV** [comment]
Lets say I have this code running
```
Client.GuildMemberAdded += Welcome_Member;

public static async Task AcceptRules(object Client, GuildMemberUpdateEventArgs e)
{
   if (e.PendingBefore == null) return;
   if (e.PendingBefore.Value && !e.PendingAfter.Value)
   {
             1. send welcome message,
             2. assign role to user
    }
}
```
Now theoretically it only should execute the most inner if only once, right after agreeing to rules because the user was pending before but after was not. 
But the code will execute again fully because the role was changed, so the event fires and code still thinks before pending was true and after pending was false. Meaning it doesn't change.

Solution was to check if the user has any roles, but lets say i remove the role, it will trigger and execute the full thing once more.


Sorry if im not explaining that well

**Comment by VelvetThePanda** [comment]
So this is in fact an issue with the event, which helps us triage this better.

**Comment by BlackLotusLV** [comment]
Yes the issue is with the event, but when i call for GetMemberAsync, it should provide correct information, which, relating to isPending, is not correct.
It just makes that field useless as you can never rly on it to be accurate.

So the issue is with the isPending field not updating correctly in both, DiscordMember and the event when member is updated.

**Comment by BlackLotusLV** [comment]
can't reproduce on latest nightly, probably fixed ages ago, never noticed due to using a workaround.
