### ISSUE TITLE
Slash Commands Cooldown

### ISSUE THREAD

**Issue by hopto-dot** [DSharpPlus/DSharpPlus#1374]
I've been wanting to implement a cool down for slash commands but from the [DSharp​Plus.​Slash​Commands.​Attributes](https://dsharpplus.github.io/api/DSharpPlus.SlashCommands.Attributes.html) page in the docs it doesn't seem like it exists - are cooldown attributes not able to be implemented for slash commands or is this just a missing feature?

What's the recommended way to implement per-user cooldowns without a slash command attribute?

**Comment by Poinet** [comment]
You may use `TimeSpan` Class to implement the per-user cooldowns.

**Comment by Poinet** [comment]
To be honest, the **DSharpPlus** does not need to implement per-user cooldown attribute for Slash Commands, you may create your own attribute instead.

**Comment by ExaInsanity** [comment]
while that is a good point, DSharpPlus does provide a cooldown attribute in CommandsNext, so a SlashCommands cooldown attribute isn't unjustified per se.

**Comment by hopto-dot** [comment]
> You may use `TimeSpan` Class to implement the per-user cooldowns.
> To be honest, the DSharpPlus does not need to implement per-user cooldown attribute for Slash Commands, you may create your own attribute instead.

@Poinet I'm still an unskilled programmer, would you mind elaborating?

I was thinking something like creating a `MemberUse` class which inherits from `DiscordMember` with a property that stores when the user last used a command. When a command is used they would be added to a list called usersUsingCommand and removed once the command has finished executing.
The problem I see with doing this is that an instance of MemberUse in the list won't be removed if code halts unexpectedly. This is why I'm really wanting a cooldown attribute because it makes it super easy and deals with this all for me.

**Comment by ExaInsanity** [comment]
If you need a reference for implementation, see https://github.com/DSharpPlus/DSharpPlus/blob/master/DSharpPlus.CommandsNext/Attributes/CooldownAttribute.cs.

**Comment by hopto-dot** [comment]
I'm going to have to do it another way because that is beyond my level.

**Comment by ExaInsanity** [comment]
fortunately for you, #1375 aims to port the feature to slash commands.

**Comment by hopto-dot** [comment]
Wow, that's great! Can I expect this to be out in a nightly release sometime soon?

**Comment by ExaInsanity** [comment]
Probably as soon as someone gets around to testing it.

**Comment by OoLunar** [comment]
Nightlies are created when a new commit to the master branch happens. They're done automatically by Github Actions and are usually downloadable from Nuget within 10 minutes

**Comment by hopto-dot** [comment]
Thank you guys, much appreciated 👍
