### ISSUE TITLE
Put image on embed on right

### ISSUE THREAD

**Issue by AndreZila01** [DSharpPlus/DSharpPlus#1380]
Hey everyone...

I have one question is possible put image on right? I try and search on internet but i dont found a solution?

At the moment i have this:
`
var Embed = new DiscordEmbedBuilder
				{
					Description = "POKÉMON TAL COM : EDUARDO CUNHA E GEKKOKAMI ! - !GIVEAWAY !RTP ! !SOCIAL",
					Color = DiscordColor.Purple,
					ImageUrl = "https://avatars.cloudflare.steamstatic.com/924fe822a0f69f135418bde03a4973b753432623_full.jpg"
				};
				Embed.AddField("Game", "Kirby's Dream Buffet").AddField("Stream", "https://twitch.tv/khaheri_");
`

The solution:
![image](https://user-images.githubusercontent.com/56931353/187089596-5b63ff25-863f-47b6-9c3f-140afcf81f02.png)

My objetive:
![image](https://user-images.githubusercontent.com/56931353/187089617-f9ca7818-47b5-4aa1-9604-e9c40482c951.png)

**Comment by VelvetThePanda** [comment]
Use `WithThumbnail` on the `DiscordEmbedBuilder`. For support, we implore you join the [D#+ Discord](https://discord.gg/dsharpplus)
