### ISSUE TITLE
create a command with /

### ISSUE THREAD

**Issue by AndreZila01** [DSharpPlus/DSharpPlus#1383]
Hey everyone.
i would like understand how i can create a command with "/" and receive all camps i need completed, like this image on bellow.

![image](https://user-images.githubusercontent.com/56931353/187557140-d22f8865-9abc-4ed6-9737-22b3ccfb25d1.png)

Thanks.

**Comment by VelvetThePanda** [comment]
See our [Slash Command Extension](https://github.com/DSharpPlus/DSharpPlus/tree/master/DSharpPlus.Slashcommands). As I stated in the prior issue, please forward all support requests to the [Official D#+ Discord](https://github.com/DSharpPlus)
