### ISSUE TITLE
Change parameter "delete_message_days to "delete_message_seconds"

### ISSUE THREAD

**Issue by bakirov-eldar** [DSharpPlus/DSharpPlus#1448]
I propose to replace
this

    DiscordGuild
    {
        ...
        public Task BanMemberAsync(ulong user_id, int delete_message_days = 0, string reason = null)
                => this.Discord.ApiClient.CreateGuildBanAsync(this.Id, user_id, delete_message_days, reason);
        ...

to this

    DiscordGuild
    {
        ...
        public Task BanMemberAsync(ulong user_id, int delete_message_seconds = 0, string reason = null)
                => this.Discord.ApiClient.CreateGuildBanAsync(this.Id, user_id, delete_message_seconds, reason);
        ...

and this

    DiscordApiClient
    {
        ...
        internal Task CreateGuildBanAsync(ulong guild_id, ulong user_id, int delete_message_days, string reason)
            {
                if (delete_message_days < 0 || delete_message_days > 7)
                    throw new ArgumentException("Delete message days must be a number between 0 and 7.", 
    nameof(delete_message_days));
                var urlparams = new Dictionary<string, string>
                {
                    ["delete_message_days"] = delete_message_days.ToString(CultureInfo.InvariantCulture)
                };
        ...

to this

    DiscordApiClient
    {
        ...
        internal Task CreateGuildBanAsync(ulong guild_id, ulong user_id, int delete_message_seconds, string reason)
            {
                if (delete_message_seconds < 0 || delete_message_seconds > 604800)
                    throw new ArgumentException("Delete message seconds must be a number between 0 and 604800.", 
    nameof(delete_message_seconds));
                var urlparams = new Dictionary<string, string>
                {
                    ["delete_message_seconds"] = delete_message_seconds.ToString(CultureInfo.InvariantCulture)
                };
       ...

since "delete_message seconds" is more accurate than "delete_message_days" with the same range.

**Comment by VelvetThePanda** [comment]
For reference the change comes from Discord's side.

**Comment by Giggitybyte** [comment]
You're welcome to [fork ](https://docs.github.com/en/get-started/quickstart/fork-a-repo)this repo and create a [pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests).

**Comment by Naamloos** [comment]
wait- Discord changed this? why lmao

**Comment by VelvetThePanda** [comment]
Precision
