### ISSUE TITLE
e.Message.Content == "" empty

### ISSUE THREAD

**Issue by aa255** [DSharpPlus/DSharpPlus#1469]
https://www.youtube.com/watch?v=sPMw32ZGqX8

why e.message.content == '' when i write 'asdmslkadjsdak' and etc
```cs
         var discord = new DiscordClient(new DiscordConfiguration()
            {
                Token = a_hui_na,
                TokenType = TokenType.Bot,
            });

            discord.MessageCreated += async (s, e) =>
            {
                Console.WriteLine(e.Message.Content);

                if (e.Message.Content.ToLower().StartsWith("ping"))
                    await e.Message.RespondAsync("pong!");
            };

            await discord.ConnectAsync();
            await Task.Delay(-1);
   ```

**Comment by InFTord** [comment]
you forgot to enable your intents

**Comment by aa255** [comment]
how

**Comment by InFTord** [comment]
https://dsharpplus.github.io/DSharpPlus/articles/beyond_basics/intents.html

**Comment by aa255** [comment]
undestandable have a great day

**Comment by aa255** [comment]
why. [2023-02-17 20:13:04 +03:00] [111 /ConnectionCl] [Info ] Connection terminated (4014, 'Disallowed intent(s).')

**Comment by InFTord** [comment]
![2023-02-17_22-13](https://user-images.githubusercontent.com/60395110/219719655-ae516eb1-daa3-4a79-bf08-3ab882524472.png)

**Comment by aa255** [comment]
many thanks

**Comment by aa255** [comment]
and question how to remove? [Warn ] Pre-emptive ratelimit triggered

**Comment by VelvetThePanda** [comment]
You're doing some action in rapid succession. It's just a warning and can be safely ignored, however you should rethink whatever it is you're doing.

**Comment by Naamloos** [comment]
> undestandable have a great day

![](https://media.tenor.com/Z6uHH2k0_vEAAAAd/understandable-have-nice-day.gif)

**Comment by aa255** [comment]
2023-02-17 23:07:33 +03:00] [116 /RatelimitPre] [Warn ] Pre-emptive ratelimit triggered - waiting until 2023-02-17 20:08:18 +00:00 (00:00:45.1950004).

why his blocked me i send 2 messages

**Comment by OoLunar** [comment]
Ratelimiting happens when you spam too many API requests at a time. Each API endpoint (route) has it's own limit that is only known to us through the HTTP headers. My guess is that you're sending too many messages at once, which is why the API is telling you to wait (to prevent Discord's systems from being overloaded).

https://discord.com/developers/docs/topics/rate-limits#rate-limits

**Comment by aa255** [comment]
I MAKE 1 REQUEST, I MAKE 1 MORE AND IT'S ALL IN THE Ratelimit hit BATH, I don't spam anything like that, but they give me warn and ban. why is that?

**Comment by aa255** [comment]
i have sent 4 commands  [Error] Ratelimit hit,

**Comment by aa255** [comment]
maybe because im russian

**Comment by OoLunar** [comment]
> maybe because im russian

Politics does not belong in this issue or this repository, please take this mindset somewhere else.
