### ISSUE TITLE
NRE in DiscordApiClient due to insufficient null handling

### ISSUE THREAD

**Issue by Izumemori** [DSharpPlus/DSharpPlus#1470]
# Summary
Clearing a DiscordMessageBuilder of Components without adding any stickers to it causes an NRE when trying to send it via a DiscordRestClient (probably also normally, have only tested with a rest client)

# Details
I have encountered it in every version since presumably the commit a1e5becd2dbd4bfdd37caa82116b1596b389a6e3. 
The issue is that invoking ClearComponents sets the Sticker to `default` here
https://github.com/DSharpPlus/DSharpPlus/blob/94717715ce97651187c32655ae70f298801c12c8/DSharpPlus/Entities/Channel/Message/DiscordMessageBuilder.cs#L229-L236
But then when trying to send the Message in DiscordApiClient it is not handled when the sticker itself should be `null`
https://github.com/DSharpPlus/DSharpPlus/blob/94717715ce97651187c32655ae70f298801c12c8/DSharpPlus/Net/Rest/DiscordApiClient.cs#L1358-L1367

Obviously this then also causes the message to fail to send.

This code snippet should be enough to reproduce the issue
```cs
var bot = new DiscordRestClient(...);
var messageBuilder = new DiscordMessageBuilder();
messageBuilder.WithContent("Test");
messageBuilder.ClearComponents();

await bot.CreateMessageAsync(<channel_id>, messageBuilder);
```

**Comment by VelvetThePanda** [comment]
The actual issue lies here:

https://github.com/DSharpPlus/DSharpPlus/blob/94717715ce97651187c32655ae70f298801c12c8/DSharpPlus/Entities/Channel/Message/DiscordMessageBuilder.cs#L52-L60

**Comment by VelvetThePanda** [comment]
We should pick whether we support multi sticker support or not (I think there's methods to add stickers?) but as it stands this code is evidently dangerous and prone to sneaky bugs.

**Comment by OoLunar** [comment]
I believe we should support multiple stickers since the API supports it (even if the client does not)

**Comment by Izumemori** [comment]
My proposed fix would be to either just clear the Sticker list in the ClearConponents method (why is that even there?) and slowly migrate to using NRTs to prevent unknown nullables in the future or to null check it when sending it.

**Comment by VelvetThePanda** [comment]
NRTs are great but supposedly broke CNext; they'll be enabled in V5 afaik

**Comment by akiraveliara** [comment]
yes, v5 will use nullability annotations

**Comment by Izumemori** [comment]
#1481 Has fixed this, thank you
