### ISSUE TITLE
The DSharpPlus API documentation is missing

### ISSUE THREAD

**Issue by garymon16** [DSharpPlus/DSharpPlus#1516]
# Summary
The link to the API docs returns a 404 and github docs/api is empty. 

# Details
The page at https://dsharpplus.github.io/DSharpPlus/ has a link to the API docs. 
The API Docs link is https://dsharpplus.github.io/api/ and returns a 404. 
Your docs/api index here on github has only a 8 lines and no content files.

# Steps to reproduce
1. Open browser
2. Go to https://dsharpplus.github.io/api/ 
3. No API

# Notes
I've used Discord.net and wanted to try DsharpPlus for a comparison. 
Tutorials has been enough to get me up and running in a bare bones bot.
But as I dig deeper it would be nice to have some documentation. 

Thank you.

**Comment by OoLunar** [comment]
The what is missing

**Comment by OoLunar** [comment]
No it very much still exists: https://dsharpplus.github.io/DSharpPlus/api/

Additionally I've started:tm: on updating the example bots repo: https://github.com/DSharpPlus/Example-Bots

**Comment by OoLunar** [comment]
>  Your docs/api index here on github has only a 8 lines and no content files.

Yeah that's because our documentation is generated from the `dll`'s by using `docfx`:  https://github.com/DSharpPlus/DSharpPlus/blob/master/.github/workflows/docs.yml

**Comment by garymon16** [comment]
Ah then it's just a broken link. 
Your page at:  https://dsharpplus.github.io/DSharpPlus/ 
Has a link to:           https://dsharpplus.github.io/api/
When it should be: https://dsharpplus.github.io/DSharpPlus/api/
Thank you for the good link, I will save it.

**Comment by InFTord** [comment]
FOOD?????
