### ISSUE TITLE
VoiceNextExtension.ConnectAsync() does not return

### ISSUE THREAD

**Issue by snerble** [DSharpPlus/DSharpPlus#1518]
# Summary
As of March 10 (yesterday), `VoiceNextExtension.ConnectAsync()` does not return.

# Details
Despite no changes being made to my program, the `VoiceNextExtension` is unable to create create a `VoiceNextConnection`. No deadlock occurs, as the bot is still able to process other events. No exception is thrown or logged. The bot does join the voice channel and is able to stay there indefinitely.

OS: Windows 11 and Ubuntu Server 22.04.2
.NET Version: .NET 7
Intents: AllUnprivileged, GuildMembers, MessageContents

# Steps to reproduce
1. await call to `VoiceNextExtension.ConnectAsync(DiscordChannel)`

# Notes
Edit: https://discord.com/developers/docs/topics/voice-connections#ip-discovery Likely relevant

I initially believed this issue to be a deadlock caused by awaiting the `ConnectAsync` call on the same async call stack as the `MessageCreated` event, however, executing the code on another thread did not solve this issue. Furthermore, the bot is able to process other events without issue, even while the command responsible for connecting to the voice channel is stuck awaiting the `ConnectAsync` call.

This issue seemed to appear overnight, while my production bot was still running on my Ubuntu Server, so I have a suspicion this issue is due to a change in the messages sent by Discord, however I cannot confirm this.

Checking the parallel stacks window, the second-last stack frame shows `VoiceNextConnection.ConnectAsync`. The last stack frame is an unnamed `[Async Code]`.

Checking the trace logs, the `VoiceDispatch` message with `OpCode = 4` is sent after attempting to connect to the voice channel. As far as I can see, this is never replied to with an Opcode 6 Heartbeat ACK, but I may be wrong.

As a last ditch effort I have tried adding the libopus.dll and libsodium.dll files next to the application EXE, but to no avail.

I have attached the Serilog CLEF logs which contain all trace logs from the last test run. On line 402, my `!test connect` command is received. This command never finishes executing.

[export-8db2a47b1519fcb.log](https://github.com/DSharpPlus/DSharpPlus/files/11033470/export-8db2a47b1519fcb.log)

The following code has demonstrated the issue on my machine (Note, the token and channel ID are replaced with ellipses)
```cs
using DSharpPlus;
using DSharpPlus.EventArgs;
using DSharpPlus.VoiceNext;

using System.Diagnostics;

var client = new DiscordClient(new()
{
	Intents = DiscordIntents.AllUnprivileged | DiscordIntents.GuildMembers | DiscordIntents.MessageContents,
	Token = ...
});

client.UseVoiceNext();

client.GuildDownloadCompleted += (s, e) => { Client_GuildDownloadCompleted(s, e); return Task.CompletedTask; };

// Return void to ensure async call is processed in the background
async void Client_GuildDownloadCompleted(DiscordClient sender, GuildDownloadCompletedEventArgs e)
{
	var vn = sender.GetVoiceNext();
	var voiceChannel = await sender.GetChannelAsync(...);

	Debug.Assert(vn != null);
	Debug.Assert(voiceChannel is { Type: ChannelType.Voice });

	var connection = await vn.ConnectAsync(voiceChannel);

	// Never gets sent
	await voiceChannel.SendMessageAsync("Connected!");
}

await client.InitializeAsync();
await client.ConnectAsync();
Console.ReadKey();
await client.DisconnectAsync();
```

**Comment by Sandbox5913** [comment]
Getting the same issue today after having no issues and not having touched my code in weeks.

**Comment by snerble** [comment]
Oh and it was addressed 3 weeks ago? https://github.com/DSharpPlus/DSharpPlus/pull/1485
Might need to find a nightly build somewhere.

**Comment by snerble** [comment]
Just updated the DSharpPlus packages to the 4.4.0-nightly-01436. Voice connections are working again.
![image](https://user-images.githubusercontent.com/45596162/226763910-56c8cb64-2717-47f1-ad60-a59c41b92a3f.png)

Remember to include prereleases.
![image](https://user-images.githubusercontent.com/45596162/226764048-ab95bddc-21df-4375-b11a-f690f2b14f3d.png)

**Comment by OoLunar** [comment]
I'm glad the latest nightly works well for y'all. We'll try to make a release soon
