### ISSUE TITLE
Every Slash Command throwing NRE

### ISSUE THREAD

**Issue by x3rt** [DSharpPlus/DSharpPlus#1531]
# Summary
Every once in a while, when the bot starts/restarts/boots none of the Slash Commands work, and just throw NREs from within the library.

# Details
`DSharpPlus - 4.4.0`
`DSharpPlus.SlashCommands - 4.4.0`
`NET 7.0`

This has been an issue since before the Thread update and seems to be occuring here (not 100% certain):
https://github.com/DSharpPlus/DSharpPlus/blob/dd429e9a371880e12fbc6d897ab3dc1e11c5a974/DSharpPlus.SlashCommands/SlashCommandsExtension.cs#L587

The error in question:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at DSharpPlus.SlashCommands.SlashCommandsExtension.<>c__DisplayClass47_0.<InteractionHandler>b__1(CommandMethod x)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at DSharpPlus.SlashCommands.SlashCommandsExtension.<>c__DisplayClass47_0.<<InteractionHandler>b__0>d.MoveNext()
```

# Steps to reproduce

It is difficult to reproduce, but this is how I register the commands

```cs
Slash = Client.UseSlashCommands();
Assembly assembly = Assembly.GetExecutingAssembly();
Slash.RegisterCommands(assembly, guildID);
```

# Notes

> It is very hard to reproduce, because it doesn't happen all the time.
> This is not a rate-limit issue, or an issue with Commands not getting registered
> CommandsNext commands still work
> `SlashCommandsExtension` itself is NOT null

**Comment by VelvetThePanda** [comment]
Upon further investigation, this appears to be UB within the handling of the interactions when handling both guild and global commands, or when handling multiple guild commands; I suspect the latter, but the extension has never officially supported this behavior, and is a side effect of a lack of validation in that regard. 

While we will attempt to fix this on our side, the current recommended course of action is to stick strictly to guild commands for one (1) server, OR only use global commands, as this use-case has been time-tested. We apologize for the inconvenience. cc @IDoEverything
