### ISSUE TITLE
Increase finetuning of the DiscordIntents enum (specifically around MessageContents now being privileged)

### ISSUE THREAD

**Issue by BlueDanube-Damascius** [DSharpPlus/DSharpPlus#1541]
# Summary
Increased finetuning of DiscordIntents Enum would be nice.

# Details
Currently the enum looks like this

```
    AllUnprivileged = ScheduledGuildEvents | DirectMessageTyping | DirectMessageReactions

    All = AllUnprivileged | MessageContents | GuildPresences | GuildMembers, // 0x0001FFFF
```

I think it would be nice to have it so there is some version which wraps AllUnprivileged with just MessageContents ? - The bot in my usecase doesn't need to know presences or who is in the server - just the content of the message.

# Notes

I would just write a custom use case but I think it might benefit a lot of people, since they relatively recently made the MessageContents intent private.

I am doing this in 4.4.0 stable - if it's already been fixed in 5.0.0 nightlys please disregard.

**Comment by Plerx2493** [comment]
The enum is a bitflag (not sure if it's the technical word). You can combine exactly those intents which you would like to use. Use some intent and combine it with the bitwise XOR operator `|`

**Comment by akiraveliara** [comment]
They seem aware of that - they are asking for a shorthand for that specific combination. I'll bring it up to discuss on Discord.

**Comment by BlueDanube-Damascius** [comment]
> The enum is a bitflag (not sure if it's the technical word). You can combine exactly those intents which you would like to use. Use some intent and combine it with the bitwise XOR operator `|` with another intent.

TIL - so I could instantiate a new client with the intents section being ```AllUnprivileged | MessageContents``` and that'd work...?

> They seem aware of that - they are asking for a shorthand for that specific combination. I'll bring it up to discuss on Discord.

I wasn't, and I wonder how many other people may have the same question / not want to activate all values for one specific privileged usecase :D 

anyway please feel free to close if you think it's not worth adding a specific shorthand in this case, maybe it'd be best resolved to just add some documentation about combining values via a pipe when setting the intents field in the client at instantiation?

**Comment by akiraveliara** [comment]
oh well then - yes, that'd work, and we do in fact show it in the docs: https://dsharpplus.github.io/DSharpPlus/articles/beyond_basics/intents.html

**Comment by BlueDanube-Damascius** [comment]
RTFM, me!
