### ISSUE TITLE
 bot.RunAsync().GetAwaiter().GetResult(); giving error csharp(CS1061)

### ISSUE THREAD

**Issue by justice5600000** [DSharpPlus/DSharpPlus#1543]
using DSharpPlus;
using DSharpPlus.CommandsNext;
using DSharpPlus.Interactivity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using System.IO;
using Newtonsoft.Json;
using DSharpPlus.Interactivity.Extensions;
using DSharpPlus.EventArgs;

namespace jrbcs 
{
    internal class Program
    {
        static void Main(string[] args)
        {
            var bot = new bot();
            bot.RunAsync().GetAwaiter().GetResult();
        }
    }
}

**Comment by justice5600000** [comment]
ive been following from a tutorial and it works fine with him lmk, if you need other parts of code

**Comment by akiraveliara** [comment]
you're trying to call something that doesn't exist. also, you can just use an async main method...

**Comment by justice5600000** [comment]
https://www.youtube.com/watch?v=YjqoAhtSZU0

**Comment by justice5600000** [comment]
22:25
