### ISSUE TITLE
Support `global_name` on user object

### ISSUE THREAD

**Issue by Khitiara** [DSharpPlus/DSharpPlus#1568]
# Summary
Should expose the `global_name` field on Users

# Details
Under the new username system users may pick a display name which is exposed as `global_name` on the user object. This value may be present on any user and may be null if the user has not picked a display name. This field should be incorporated into the `DisplayName` property of member objects - i propose the following API structure

```diff
public class DiscordUser {
+    public string? GlobalName { get; }
+    public virtual string DisplayName => GlobalName ?? UserName;
}

public class DiscordMember {
-    public string DisplayName => this.Nickname ?? this.Username;
+    public override string DisplayName => this.Nickname ?? base.DisplayName;
}

**Comment by Erisa** [comment]
There is a branch @VelvetToroyashi was working on https://github.com/DSharpPlus/DSharpPlus/tree/velvet/feat/pomelo
Though it currently has some issues, like not having populated GlobalName in members and events.

**Comment by VelvetToroyashi** [comment]
Few kinks to work out in that code, namely with inexplicable behavior in regards to how global name is handled. I'll look more into it later today.

**Comment by Erisa** [comment]
That branch should be a lot closer to being usable now that I've applied #1570
