### ISSUE TITLE
Global Name isn't visible in DSharpPlus

### ISSUE THREAD

**Issue by djidave** [DSharpPlus/DSharpPlus#1592]
# Summary
Since Discord have change the Username setting of the platform I have noticed that the package isn't passing through the "Global Name"

Discord seems to have the following names for a user
- Username (this changed recently to remove the # and number, it no longer allows spaces etc)
- Display Name (this is more open, looks like the Discord API calls this Global Name but that isn't made visible in DSharpPlus)
- Nickname (this is set at a Guild level)

# Details
When I call the DiscordUser object from DSharpPlus I am presented with 3 name options for the user
- Username
- DisplayName
- Nickname

If you set a user in a guild up to have a different username (user1) to global name (user1 test) and leave the nickname blank you get the following options back on the DiscordUser object

- Username - user1
- DisplayName - user1
- Nickname - null

The global name is lost

See example below
![image](https://github.com/DSharpPlus/DSharpPlus/assets/10652571/2ce9f3e3-4a8b-44fe-a046-ff66dcfdaf1b)

I can see in the codebase that Displayname is defined as 
```
        [JsonIgnore]
        public string DisplayName => this.Nickname ?? this.GlobalName ?? this.Username;
```

So would expect as Nickname is null this to default to GlobalName

I can also see in the codebase that GlobalName is a public property
```
        [JsonIgnore]
        public override string? GlobalName
        {
            get => this.User.GlobalName;
            internal set => this.User.GlobalName = value;
        }
```

But this isn't visible on the options in version 4.4.2

![image](https://github.com/DSharpPlus/DSharpPlus/assets/10652571/08f5e293-0d01-4ba9-a410-eda279b13359)

# Steps to reproduce
If you set a user in a guild up to have a different username (user1) to global name (user1 test) and leave the nickname blank you get the following options back on the DiscordUser object when queried from the guild

- Username - user1
- DisplayName - user1
- Nickname - null

# Notes
I haven't checked the Discord API responses to validate that they are returning GlobalName correctly since the mandated change

**Comment by djidave** [comment]
UPDATE: I have just tested this on the latest github code (v5.0) and the issue is fixed

**Comment by Plerx2493** [comment]
If you want to use the latest features its recommended to use the nightly prereleases.

**Comment by akiraveliara** [comment]
this will not be backported to v4, which will receive important bugfixes only. v5 will be released whenever it's ready; until then, you are implored to use nightly versions.
