### ISSUE TITLE
Thread creation message types aren't in MessageType enum

### ISSUE THREAD

**Issue by NortrixP** [DSharpPlus/DSharpPlus#1621]
MessageType enum does not contain types 18 (ThreadCreated) and 21 (ThreadStarterMessage), which makes it a bit harder to work with thread creation messages, since I have to compare type with int object: 
`(int)message.MessageType == 18`
These message types are written in https://discord.com/developers/docs/resources/channel#message-object-message-types

My suggestion is just to add these types to MessageType enum.

<sub>I could add these types myself, but I do not know what should also be done to make it work correctly</sub>

**Comment by NortrixP** [comment]
accidently hit the enter before writing

**Comment by fitzmill** [comment]
This was fixed in #1626 but then regressed in ["the great formatting of 2023"](https://github.com/DSharpPlus/DSharpPlus/commit/f1d26a7021f37405b9dfe28fe39f40a6051ebdd2#diff-d465c027d6c2082d1899cf0b54e92a3d03afe8bf944af3fe7409eaf1abebb6ea)

**Comment by Plerx2493** [comment]
Its fixed again
