### ISSUE TITLE
Changing the return type of predicate from bool to Task<bool> to enable asynchorous operations in the WaitForSelectAsync, and WaitForButtonAsync methods

### ISSUE THREAD

**Issue by izagawd** [DSharpPlus/DSharpPlus#1628]
In this part of the code below 

![Screenshot (103)](https://github.com/DSharpPlus/DSharpPlus/assets/30781523/58ccd07d-414b-4ef9-9ed4-c4fd3082461f)

changing  `Func<ComponentInteractionCreateEventArgs, bool> ` predicate to 
`Func<ComponentInteractionCreateEventArgs, Task<bool>>` predicate would allow for asynchronous operations, which I believe would be useful in cases like in the code below

assuming any user that clicks this button would have some column changed in a database,
```c#
     await message.WaitForButtonAsync(async i =>
        {
            var userId = i.User.Id;
            var entityFrameWorkDbContext = new PostgreSqlContext();
            await entityFrameWorkDbContext.UserData.Where(i => i.Id = userId).ForEachAsync(i => i.RandomProperty = "something");
            return false;
            //returns false always so the message can wait for a button until the timespan (which is 10 min) runs out
        }, new TimeSpan(0,10,0));
```

or say everytime the button is clicked some number is incremented in the message, and i want to asynchorously update the number in the message with **CreateResponseAsync**

**Comment by izagawd** [comment]
Is there another way to do something similar to the example I provided then?

**Comment by akiraveliara** [comment]
yes, appending what you have in the predicate after the call to `WaitFor*Async`, optionally using the result yielded by that method call.

**Comment by izagawd** [comment]
But if i do that, it will stop waiting for buttons once the button is
pressed once.

I want it to do something asynchronously when a button is pressed depending
on the user (in this case editing the users data in the database) no matter
how many times it is pressed, until the timespan runs out.

Kind of like how the collectors work in discord.js

**Comment by Plerx2493** [comment]
So you want a button which is only active for a given time? Something like this?:
https://github.com/DSharpPlus/Example-Bots/tree/4.3.0/src/Core/ComponentHandling
