### ISSUE TITLE
Rewrite incoming voice

### ISSUE THREAD

**Issue by Emzi0767** [DSharpPlus/DSharpPlus#164]
Incoming voice is currently a mess. There's a single misconfigured decoder that works on all incoming streams.

Post-rewrite, it should:

* Implement OP13 (user leave)
* Create and dispose Opus decoders per each audio stream
* Use appropriate configuration for thereof
* Fill blanks with silence
* Use less CPU

**Comment by NaamloosDT** [comment]
(just a comment to test a new webhook 👀 )

**Comment by Emzi0767** [comment]
🎉
