### ISSUE TITLE
"The request message was already sent. Cannot send the same request message multiple times" sporadic error

### ISSUE THREAD

**Issue by djidave** [DSharpPlus/DSharpPlus#1645]
**Describe the bug**
I have a bot that sends 40k messages per day and usually has a failure rate of 0-20 in any 24 hours (so less than 0.1%). 

After upgrading my code from 5.0.0-nightly-01633 to 5.0.0-nightly-01797 I started to see a lot of failed messages that are not sent. The failure count jumped to ~4000 per 24 hours (so around 10%)

The error was 
        The request message was already sent. Cannot send the same request message multiple times.

The messages the bot send are all in a very similar style, and each type had a mixture of success and failure, so this was very sporadic in nature.

I have since downgraded back to 5.0.0-nightly-01633 and the errors have vanished and all is working again.

**To Reproduce**
Steps to reproduce the behaviour:
1. Have a bot running with high message load on 5.0.0-nightly-01633
2. Upgrade to 5.0.0-nightly-01797
3. I think it is linked to rate limiting, so ensure a limit is hit
4. See error and the message doesn't seem to be posted to Discord

**Expected behavior**
I would expect the messages to be delivered successfully. I am not clear if this is successful in delivering the message and also creates an error, or if the error is produced as well as a successful post. I have checked several of the errors and I can't see a message posted, so I suspect it isn't but I haven't manually checked all errors.

**Screenshots**
No

**Additional context**
To send a message here is a snip of the code

```
            DiscordClient _discord;
            var guild = _discord.Guilds.Where(g => g.Value.Name == serverName).FirstOrDefault();
            var channel = guild.Value.Channels.Where(c => c.Value.Name == channelName).FirstOrDefault();
            var msg = new DiscordMessageBuilder()
                .WithContent(message)
                .WithAllowedMentions(mentions);

            var discordMessage = await msg.SendAsync(channel.Value);

```

The captured stack trace (with some standard error handling lines removed)

[{"id":"28343314","outerId":"0","type":"System.InvalidOperationException","message":"The request message was already sent. Cannot send the same request message multiple times.","parsedStack":[{"level":0,"method":"System.Net.Http.HttpClient.CheckRequestMessage","assembly":"System.Net.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","line":0},{"level":1,"method":"System.Net.Http.HttpClient.CheckRequestBeforeSend","assembly":"System.Net.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","line":0},{"level":2,"method":"System.Net.Http.HttpClient.SendAsync","assembly":"System.Net.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","line":0},{"level":3,"method":"DSharpPlus.Net.RestClient+<>c__DisplayClass22_0`1+<<ExecuteRequestAsync>b__0>d.MoveNext","assembly":"DSharpPlus, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":7,"method":"System.Runtime.CompilerServices.TaskAwaiter`1.GetResult","assembly":"System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":8,"method":"DSharpPlus.Net.RateLimitPolicy+<ImplementationAsync>d__6.MoveNext","assembly":"DSharpPlus, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":12,"method":"Polly.AsyncPolicy`1+<ExecuteAsync>d__13.MoveNext","assembly":"Polly, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":16,"method":"Polly.Wrap.AsyncPolicyWrapEngine+<>c__DisplayClass0_0`1+<<ImplementationAsync>b__0>d.MoveNext","assembly":"Polly, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":20,"method":"Polly.Retry.AsyncRetryEngine+<ImplementationAsync>d__0`1.MoveNext","assembly":"Polly, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":24,"method":"Polly.AsyncPolicy`1+<ExecuteAsync>d__13.MoveNext","assembly":"Polly, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":28,"method":"Polly.Wrap.AsyncPolicyWrapEngine+<ImplementationAsync>d__0`1.MoveNext","assembly":"Polly, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":32,"method":"Polly.AsyncPolicy`1+<ExecuteAsync>d__13.MoveNext","assembly":"Polly, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":36,"method":"System.Runtime.CompilerServices.TaskAwaiter`1.GetResult","assembly":"System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":37,"method":"DSharpPlus.Net.RestClient+<ExecuteRequestAsync>d__22`1.MoveNext","assembly":"DSharpPlus, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":41,"method":"System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult","assembly":"System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":42,"method":"DSharpPlus.Net.DiscordApiClient+<CreateMessageAsync>d__63.MoveNext","assembly":"DSharpPlus, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":46,"method":"System.Threading.Tasks.ValueTask`1.get_Result","assembly":"System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":47,"method":"DSharpPlus.Entities.DiscordChannel+<SendMessageAsync>d__88.MoveNext","assembly":"DSharpPlus, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":51,"method":"xxx.Command.DiscordHelperDSharp+<SendMessage>d__37.MoveNext","assembly":"xxx.Command, Version=1.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":55,"method":"xxx.Command.processAlertMessage+<SendMessage>d__13.MoveNext","assembly":"xxx.Command, Version=1.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":59,"method":"xxx.Command.processAlertMessage+<ProcessAlert>d__7.MoveNext","assembly":"xxx.Command, Version=1.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":63,"method":"xxx.Command.processAlertMessage+<ProcessAlert>d__5.MoveNext","assembly":"xxx.Command, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","line":104,"fileName":"processAlertMessage.cs"}]}]

**Comment by akiraveliara** [comment]
this issue was fixed in a subseqient nightly version.
