### ISSUE TITLE
REST API pass

### ISSUE THREAD

**Issue by Emzi0767** [DSharpPlus/DSharpPlus#165]
In several cases, internal REST API client doesn't return objects created by Discord API, or returns wrong objects. This should be corrected.

**Comment by Emzi0767** [comment]
To be considered as well: several endpoints take optional values, this is not always properly reflected in the lib.

**Comment by xt449** [comment]
I looked through the rest client and found only a few of these remaining. I'm still checking, but I can probably make the PR later.

**Comment by xt449** [comment]
Should I fix
Color being an int? here instead of DiscordColor?
https://github.com/DSharpPlus/DSharpPlus/blob/0783a25f7a12cbd0ee0799b1a8a1ff77258a45ca/DSharpPlus/Net/Abstractions/RestGuildPayloads.cs#L140-L141

This is really picky so just wondering if I should change that.

**Comment by Emzi0767** [comment]
If I am not mistaken, this is a raw payload, which means that the most primitive type possible should be utilized.

**Comment by xt449** [comment]
This is becoming a frustrating. I'm looking through DiscordRestClient right now and about 50% of the methods that have a `string reason` parameter that are defaulted to null, so I'm not sure which way it's supposed to be.

**Comment by uwx** [comment]
Reason is always optional

**Comment by Emzi0767** [comment]
Also I just realized that this issue is meant for tracking the *internal* REST client, not the `DiscordRestClient`.

That said, methods that are supposed to be "auditable" can optionally specify a reason. There's no point in having that for e.g. querying channel list.

**Comment by Emzi0767** [comment]
Seemingly resolved by #527, paging @Neuheit to confirm.

**Comment by Neuheit** [comment]
Which objects weren't being returned correctly?

**Comment by Naamloos** [comment]
I still have no idea.

**Comment by Emzi0767** [comment]
We've had no reports, and my recent cursory look didn't bring up anything. I'll close this as resolved.
