### ISSUE TITLE
ReplaceRolesAsync throws UnauthorizedException trying to remove managed role

### ISSUE THREAD

**Issue by sudokoko** [DSharpPlus/DSharpPlus#1651]
**Describe the bug**
The `ReplaceRolesAsync` method does not check to see if managed roles are being modified, thus causing an `UnauthorizedException`. I've confirmed that this is the issue by testing this on server boosters vs. non-server boosters, as well as manually adding the managed server booster role to the list of roles to add, which prevents the exception.

**To Reproduce**
1. Replace the roles of a server booster for example, but do not include the server booster managed role in the list of roles to replace.
2. See issue

**Expected behavior**
The method should not attempt to modify the managed role(s).

**Screenshots**
In these screenshots, we are modifying a user that is a server booster.

Not Working:
<img width="824" alt="Screenshot 2023-10-16 at 9 22 39 AM" src="https://github.com/DSharpPlus/DSharpPlus/assets/68549366/a3a0b4e9-5558-4461-9c23-de4539440e99">

Working (`boosterRoleTest` is the `DiscordRole` of the managed server booster role in my server.):
<img width="850" alt="Screenshot 2023-10-16 at 9 22 15 AM" src="https://github.com/DSharpPlus/DSharpPlus/assets/68549366/a517b309-1777-47e0-9639-8077c3a1caa0">

**Additional context**
Additionally, this is not documented in the causes of `UnauthorizedException` in the XMLdoc of the method which may cause confusion as to why this is occurring, as it's noted that this exception is caused by a lack of bot permissions.

**Comment by Plerx2493** [comment]
Can you test the pr artifacts from #1652?

**Comment by sudokoko** [comment]
> Can you test the pr artifacts from #1652?

Will test this once I get home.
