### ISSUE TITLE
DSharpPlus Seems to be causing a temporary bans for users

### ISSUE THREAD

**Issue by vekien** [DSharpPlus/DSharpPlus#1667]
**Describe the bug**
I have used DSharpPlus to call these methods:
- DiscordChannel channel = await discord.GetChannelAsync(DISCORD_CHANNEL);
- DiscordGuild guild = await discord.GetGuildAsync(DISCORD_SERVER);
- DiscordMember member = await guild.GetMemberAsync(message.Author.Id);

We've noticed that since the integration into the app, members are having issues with their own Discord clients and unable to retrieve messages from the server, it's like a temporary IP ban. The app isn't massively used and this is only called once every now and then.

We're using our own bot key.

Any ideas what could cause this?

**Comment by Plerx2493** [comment]
Is `discord` a `DiscordClient` or `DiscordRestClient`?

**Comment by akiraveliara** [comment]
we'd need a clearer link between "bot operates" and "member has issues" than this. if you have any logs to provide that look off, please post them, but this is impossible to accomplish using the supported API - if you are selfbotting or using undocumented routes, we cannot help you

**Comment by vekien** [comment]
So I have a program which has code like I posted. It uses our bot key for that coders when the program loads it runs that code.

After that, users are being temp suspended on discord and going to https://discord.com/api/gateway shows they we are temporarily suspended

there is no other code, I can print the whole code if it helps. It runs once every 5 minutes for those 3 calls. And after it has run a few times we’re being suspended by discord.

is this a discord issue? And how would this even happen? As it seems it would happen no matter what we do with discord sharp.

**Comment by Plerx2493** [comment]
It sounds like you use one application and uses it to open gateway clients on each member pc which uses your app. So you would be temp banned for to many connections

**Comment by vekien** [comment]
> Is `discord` a `DiscordClient` or `DiscordRestClient`?

Discord client.

Full Code:

```

DispatcherTimer timerAnnouncements = new();
timerAnnouncements.Tick += (sender, e) =>
{
   _ = RenderLatestDiscordAnnouncement();
};
timerAnnouncements.Interval = TimeSpan.FromMilliseconds(300 * 1000);
timerAnnouncements.Start();
			
			
public static async Task<string[]> GetLatestAnnouncementAsync()
        {
			var discord = new DiscordClient(new DiscordConfiguration()
			{
				Token = DISCORD_BOT_TOKEN,
				TokenType = TokenType.Bot,
				Intents = DiscordIntents.AllUnprivileged | DiscordIntents.MessageContents
			});

			DiscordChannel channel = await discord.GetChannelAsync(DISCORD_CHANNEL);
			DiscordGuild guild = await discord.GetGuildAsync(DISCORD_SERVER);

			IAsyncEnumerable<DiscordMessage> messages = channel.GetMessagesAsync(10);

			List<string> announcement = new();
			await foreach (DiscordMessage message in messages)
			{
				// Too short? continue
				if (message.Content.Length < 3)
				{
					continue;
				}

				DiscordMember member = await guild.GetMemberAsync(message.Author.Id);
				DateTime messageUtc = message.Timestamp.UtcDateTime;

				string content = message.Content;
				content = ReplaceUnixTimestampWithRelativeTime(content);

				announcement.Add(member.Nickname);
				announcement.Add(member.Color.ToString());
				announcement.Add(content);
				announcement.Add(messageUtc.ToLocalTime().ToString());
				break;
			}

			return announcement.ToArray();
		}
```

**Comment by vekien** [comment]
> It sounds like you use one application and uses it to open gateway clients on each member pc which uses your app. So you would be temp banned for to many connections

I see, why would it ban for single user?

**Comment by vekien** [comment]
I think for this the issue is we have one bot key being used by multiple clients and  then it’s just temp blocking IPs, like you said too many connections.

we are going to look at another approach and consider this an issue with my approach to implement discord and my fault.

thanks!
