### ISSUE TITLE
resetStreamPosition does not reset stream if the sending throws an exception

### ISSUE THREAD

**Issue by tynave** [DSharpPlus/DSharpPlus#1677]
Description of issue:
When an exception is raised while sending a message where the `AddFile` method has the `resetStreamPosition` parameter set to `true`, the stream is not reset.

I have been trying to write the following code for the `SlashCommandErrored` event:
```
slash.SlashCommandErrored += async (s, e) =>
{
    Stream stream = new MemoryStream(Encoding.UTF8.GetBytes(e.Exception.StackTrace));

    stream.Seek(0, SeekOrigin.Begin);

    var embed = new DiscordEmbedBuilder()
            .WithTitle("Error")
            .WithDescription("An exception has occured!")
            .AddField("Error Message", e.Exception.Message)
            .WithColor(new DiscordColor("FF0000"));

        try
        {
            await e.Context.Interaction.CreateResponseAsync(InteractionResponseType.ChannelMessageWithSource,
            new DiscordInteractionResponseBuilder().AddEmbed(embed).AsEphemeral().AddFile("StackTrace.txt", stream, true));
            return;
        }
        catch (BadRequestException)
        {
        }

        try
        {
            await e.Context.Interaction.EditOriginalResponseAsync(
            new DiscordWebhookBuilder(new DiscordInteractionResponseBuilder().AddEmbed(embed)
                    .AsEphemeral().AddFile("StackTrace.txt", stream, true)));
            return;
        }
        catch (BadRequestException)
        {
        }

};
```
When the exception is coming from a slash command that has already been responded to / deferred, the stream does not get reset due to the first try block throwing an exception.

**Comment by tynave** [comment]
My initial tests show that something's still not right. 
Tried the same code as in the initial report. Please let me know if you think I'm doing something wrong :3

![image](https://github.com/DSharpPlus/DSharpPlus/assets/34435573/8608af88-dabb-474b-a600-68fb8912867a)

**Comment by akiraveliara** [comment]
@tynave can you try again with the latest artifacts?

**Comment by Plerx2493** [comment]
Also i would appreciate if you could post your feedback on the pr (#1678) so its all in one place
