### ISSUE TITLE
Guild.CurrentMember is null

### ISSUE THREAD

**Issue by bakirov-eldar** [DSharpPlus/DSharpPlus#1684]
Guild.CurrentMember is null.
Exception: System.NullReferenceException. Object reference not set to an instance of an object

```
var guild = await client.GetGuildAsync(guildId, true);
var member = client.CurrentMember; \\Null
```

**Comment by Plerx2493** [comment]
What version do you use?

**Comment by OoLunar** [comment]
When are you calling the code? Is it after you've called `DiscordClient.ConnectAsync` and after `DiscordClient.GuildDownloadedComplete` has fired?
