### ISSUE TITLE
"Kicking" (removing) guild member does not include reason

### ISSUE THREAD

**Issue by extraes** [DSharpPlus/DSharpPlus#1696]
**Describe the bug**
[DSharpPlus tries setting a "reason" url parameter](https://github.com/DSharpPlus/DSharpPlus/blob/master/DSharpPlus/Net/Rest/DiscordApiClient.cs#L3418), but [Discord says to set the "X-Audit-Log-Reason"](https://discord.com/developers/docs/resources/guild#remove-guild-member) header.
This results in consistently reason-less kicks.

**To Reproduce**
1. Kick a member with the `reason` parameter set to any non-null and non-empty value.
2. Go to audit log
3. See no reason for the kick.

**Expected behavior**
The user is kicked with a reason.

**Screenshots**
(Audit log entry is missing reason foldout because it is missing a reason)
![image](https://github.com/DSharpPlus/DSharpPlus/assets/52384576/dc589bc8-6f15-4bd8-8d5c-1c676bbbd8bb)

**Additional context**
A kick by a user with a defined reason will have a foldout toggle (shown here)
![image](https://github.com/DSharpPlus/DSharpPlus/assets/52384576/605e1536-1b32-418f-8f75-0dcbf65ac3d3)

**Comment by OoLunar** [comment]
My fault! It seems I missed this in https://github.com/DSharpPlus/DSharpPlus/pull/1194
