### ISSUE TITLE
Lavalink V4 Support

### ISSUE THREAD

**Issue by steele123** [DSharpPlus/DSharpPlus#1721]
**Is your feature request related to a problem? Please describe.**
It appears lavalink v4 has breaking changes that are not compatible with v3

**Describe the solution you'd like**
Support for lavalink v4

![9pxZBt](https://github.com/DSharpPlus/DSharpPlus/assets/60533996/7d6ea2ef-d7dc-4a89-970e-2b0361532d12)

**Comment by OoLunar** [comment]
Lavalink hasn't been explicitly maintained by anyone for quite a bit of time now, however I'm open to rewriting the extension myself if I happen to obtain the proper motivation for it

**Comment by InFTord** [comment]
for now you can use lavalink4net

**Comment by steele123** [comment]
> for now you can use lavalink4net

This is probably the best option overall, as it appears [lavalink4net](https://github.com/angelobreuer/Lavalink4NET) has support for DSharpPlus, thanks! I feel like this issue could probably be closed unless you guys wanted to support lavalink as well (with maybe lavalink deprecated in the dsharpplus repo), but I'll leave that up to you guys :)

**Comment by OoLunar** [comment]
Yeah, we're just going to deprecate our Lavalink extension and instead point existing users to LL4Net. I recently went and took a quick review of how LL4Net hooks into D#+ and everything looks to be functional. As I'm not familiar with Lavalink, I hadn't explored the project any further. I can however confirm that the maintainer of LL4Net is a very pleasant person to work with. Head on over to LL4Net's Discord server if you ever need any support <3

**Comment by Naamloos** [comment]
Glad we do take into account the friendliness of external devs before pointing users towards them :^)

**Comment by Plerx2493** [comment]
official certified by D#+

**Comment by InFTord** [comment]
d#+ seal of approval

**Comment by Naamloos** [comment]
![your did it](https://github.com/DSharpPlus/DSharpPlus/assets/12187179/1ab36e6f-aadd-4419-9e3b-cec9a4c3d0b5)
