### ISSUE TITLE
[Commands] Register slashies to a specific guild

### ISSUE THREAD

**Issue by Lounek09** [DSharpPlus/DSharpPlus#1734]
I'm currently trying [DSharpPlus.Commands](https://github.com/DSharpPlus/DSharpPlus/tree/master/DSharpPlus.Commands) over [DSharpPlus.SlashCommands](https://github.com/DSharpPlus/DSharpPlus/tree/master/DSharpPlus.SlashCommands) but it lack a very important feature to me : The possibility to register commands to a specific guild. 

To be brief, my bot is an encyclopedia for the MMORPG [Dofus Retro](https://www.dofus.com/en/dofus-retro), I have sensitive commands principally used to parse game data and explore it more precisely. These commands should not be public but rather on a private admin guild (and potentially other specific guilds).

It's currently possible to do it with [DSharpPlus.SlashCommands](https://github.com/DSharpPlus/DSharpPlus/tree/master/DSharpPlus.SlashCommands) from [SlashCommandsExtension.RegisterCommands](https://github.com/DSharpPlus/DSharpPlus/blob/master/DSharpPlus.SlashCommands/SlashCommandsExtension.cs#L88), I think this is the most flexible approach to implement it.

**Comment by OoLunar** [comment]
This is absolutely something we can implement! Should be as simple as another if statement. I'll close this issue once it's implemented. Thank you for raising this to our attention!

**Comment by ecrocombe** [comment]
+1,

Currently doing the same thing, migrating from DSP.SlashCommands to DSP.Commands, and dearly missing this lovely feature.

**Comment by Plerx2493** [comment]
Currently the extension provides a config to register commands only to one specific guild as requested, but i will not close this issue and expand it to the scope of supporting multiple guild specific commands for different guilds
