### ISSUE TITLE
Silent embed messages

### ISSUE THREAD

**Issue by BloodyBaRGaIn** [DSharpPlus/DSharpPlus#1740]
### Discussed in https://github.com/DSharpPlus/DSharpPlus/discussions/1733

<div type='discussions-op-text'>

<sup>Originally posted by **BloodyBaRGaIn** February  1, 2024</sup>
Is there any way to send silent embed messages? I know that it is possible with discord.js, but I can't find a similar way to do the same thing with .NET library 😢
I can refer only to that info from stackoverflow
https://stackoverflow.com/questions/76517603/how-to-send-a-silent-message-with-discord-js</div>

Please add pld.Flags = builder.Flags in DiscordApiClient.CreateMessageAsync(ulong channelId, DiscordMessageBuilder builder)

**Comment by Plerx2493** [comment]
Can you test the pr artifacts from #1741

**Comment by BloodyBaRGaIn** [comment]
I hope that flags asignment will affect the resulting message in a propper way 😇

**Comment by BloodyBaRGaIn** [comment]
> Can you test the pr artifacts from #1741

Is there anything I can do about this now?

**Comment by Plerx2493** [comment]
You can test it when you use the pr artifacts:

To run the library off a pull request, you will need a GitHub account. Navigate to the pull request you want to use and click on the green check mark next to the latest commit: image.png

Then, go to "Details" and scroll all the way down to "Artifacts". Download the zip file and extract it into a folder of your choice.

Now, you need to add the packages to your project.

Using CLI:

Run dotnet add package <package-name> --source "path/to/your/package/folder"

Using Visual Studio:

Add your local folder as a package source in this dialog, reached through the little gear icon in your NuGet dialogue, see unknown.png and unknown.png. You'll want to click the plus icon to create a new package source, then enter your folder name at "Source".

Using your .csproj file:

(do not.)
Add <RestoreAdditionalPackageSources>path/to/your/package/folder</RestoreAdditionalPackageSources> to your head PropertyGroup. 

In the latter two cases, you should then be able to update D#+ to the pull request build through your NuGet dialogue.

**Comment by Plerx2493** [comment]
https://github.com/DSharpPlus/DSharpPlus/actions/runs/7769562271

**Comment by BloodyBaRGaIn** [comment]
It says I need to run it with .NET 8, but my project can use .NET 7

**Comment by BloodyBaRGaIn** [comment]
Sorry I've never done that things before

**Comment by akiraveliara** [comment]
nightly builds require .NET 8. you'll have to update.

**Comment by BloodyBaRGaIn** [comment]
Updating VS.. It will take a while

**Comment by BloodyBaRGaIn** [comment]
It's working!
