### ISSUE TITLE
Slash commands don't show up for accounts without Admin permissions

### ISSUE THREAD

**Issue by Invixvb** [DSharpPlus/DSharpPlus#1743]
**Describe the bug**
The slash commands aren't showing up in the discord menu for the person that doesn't have Admin permissions. If we go back to v4 of DSP it's fine and works as expected.

**To Reproduce**
1. Have 2 accounts. Both on a different client for convenience.
2. Give one a role with Admin permissions and one without.
3. Type "/" and see that on the one with permissions it does show up, and the on without it doesn't show up.

**Expected behavior**
It at least show up accurately. As currently if you give them permissions that should work or just have a command that doesn't need permissions it doesn't show up anyway.

**Screenshots**
Here's my Admin Account
![image](https://github.com/DSharpPlus/DSharpPlus/assets/74636900/9b40da75-7ad6-40d7-9b42-a8d222dc65f5)

Here's my normal Member Account
![image](https://github.com/DSharpPlus/DSharpPlus/assets/74636900/7bc3815f-9591-4469-bbfe-bfe130c288ba)

As you can see there's no bot with the L in the logo, that's the bot on the new v5 version.

**Comment by Invixvb** [comment]
[DSharpPlus_Console_Logs_Trace.txt](https://github.com/DSharpPlus/DSharpPlus/files/14156717/DSharpPlus_Console_Logs_Trace.txt)
This is the logging in the console on startup.

**Comment by akiraveliara** [comment]
[commands.json](https://github.com/DSharpPlus/DSharpPlus/files/14156731/commands.json)
i don't have time to look at this right now, but i've taken the liberty to format the commands uploaded to discord to be more readable for whoever wants to look at this

**Comment by Invixvb** [comment]
I believe these messages are quite important to a potential fix: https://discord.com/channels/379378609942560770/1202000142170062928/1203678516005314630
