### ISSUE TITLE
GetGuildWebhooksAsync(UInt64 guild_id) throws NRO

### ISSUE THREAD

**Issue by snnaakee** [DSharpPlus/DSharpPlus#1754]
**Describe the bug**
GetGuildWebhooksAsync(UInt64 guild_id) will throw NullReferenceException when the Discord Developer News channel is added to the guild.

**To Reproduce**
1. Add the Discord Developer News channel to the same guild you're querying the webhooks
2. Query webhooks for that same guild

**Code**
`var webhooks = await guild.GetWebhooksAsync();`

**Logs**
[logs.txt](https://github.com/DSharpPlus/DSharpPlus/files/14222031/logs.txt)

Deleting the webhook removes the exception:
![image](https://github.com/DSharpPlus/DSharpPlus/assets/62524548/50bb1214-5d04-4d26-b25a-879d03c9c618)

**Comment by Plerx2493** [comment]
What version do you use?

**Comment by snnaakee** [comment]
> What version do you use?

DSharpPlus, version 4.4.6+3a90ac8625573943ffe930a328de81180ad193dd

**Comment by Plerx2493** [comment]
I have in mind that i had a NRO earlier and i think its fixed in nightlies

**Comment by Plerx2493** [comment]
#1594

**Comment by Plerx2493** [comment]
I will close this as fixed. Feel free to reopen if you can reproduce it when using latest nightly
