### ISSUE TITLE
member.DisplayName returns username instead of displayname (v4.4.6)

### ISSUE THREAD

**Issue by Jdalt40** [DSharpPlus/DSharpPlus#1757]
**Describe the bug**
The Display Name of a member is only the username, not the actual display name.

**Expected behavior**
member.DisplayName should return in this order server display name=> global display name => username

**Comment by akiraveliara** [comment]
4.4.6 does not have the new username sysyem implemented, and it is exceedingly unlikely that we'll backport it from v5.x development
