### ISSUE TITLE
AllowNullAttribute for equality operators

### ISSUE THREAD

**Issue by BloodyBaRGaIn** [DSharpPlus/DSharpPlus#1758]
If we need to compare two instances of DiscordChannel, and if at least one of them has an AllowNullAttribute,
then the Equals(DiscordChannel e) method or operator ==(DiscordChannel e1, DiscordChannel e2) will generate
warning CS8604 when used in this way.
Therefore, we have to suppress this warning locally:
```
private async Task Client_VoiceStateUpdated(DiscordClient client, VoiceStateUpdateEventArgs e)
{
#pragma warning disable CS8604
    bool channel_changed = (e.After?.Channel) != (e.Before?.Channel);
#pragma warning restore CS8604
    /* other code */
}
```
The same situation applies to DiscordGuild instances. There may be other classes where the same thing happens.
Not critical.

**Comment by Plerx2493** [comment]
We are currently updating our nullability annotations and while doing so we update those methods

**Comment by BloodyBaRGaIn** [comment]
I saw that "epic-nullability" label and realized how many things should be done. Sorry for disturbing and have a great day!!!
