### ISSUE TITLE
Suggestion: Group commands without having to invoke with group name

### ISSUE THREAD

**Issue by moonPtr** [DSharpPlus/DSharpPlus#176]
Shortly put, allow something like command grouping in discord.py

For a group X with Commands Y and Z

help shows X
help X shows Y and Z

and Y and Z can be invoked prefix-Y / prefix-Z, instead of prefix-X Y and prefix-X Z

Hope it makes sense.
(Some people are challenged with with having every command in a group, but it's necessary to prevent the help list from becoming an utter mess, especially with "larger" bots.)

**Comment by Emzi0767** [comment]
That's completely missing the point of command groups though.

**Comment by moonPtr** [comment]
It could be optional as part of the Group attribute
~I  don't really want to do all the reflection stuff necessary to bodge it together myself~

**Comment by Emzi0767** [comment]
I'm not a fan of that idea. Right now you can create a command that uses sudo to achieve your goal, and that's the preferred way to be honest.

What I can offer is changes to sudo interface to enable doing that more easily.

**Comment by moonPtr** [comment]
I can vaguely (but not fully) imagine how that would work out, would appreciate it!

**Comment by uwx** [comment]
sudo implement this feature

**Comment by Emzi0767** [comment]
Note for future me: 

* Allow easier command invocation via sudo:
   * By qualified name
   * By command object
* Allow passing arguments to sudo as raw strings or converted objects.

**Comment by armaa** [comment]
Isnt it bit more logical to use commands in that way tho? As `prefix X-Y`, unless stated otherwise?

**Comment by uwx** [comment]
@armaa department of redundancy department

**Comment by Emzi0767** [comment]
@armaa not sure what you mean. Currently if you have a command group called `group` and command named `command`, you have to invoke it as `group command`. This is about allowing invoking it as `command` in addition to that.

I don't want to make the system work like this, however it can be achieved by using CNext's sudo functionality. The only problem is that at the moment it's crude.

The way this would work is you have a group called `group` and a command called `command`. On top of that you have an ungroupped command called `command`, which invokes `group command` via sudo.

**Comment by moonPtr** [comment]
@armaa yes it is more logical to do prefix-X Y
But did you even read the issue?

People may want to group commands to avoid cluttering, but find it a hassle to always have to type group names (even when you can alias them down to 1 or 2 letters)
I often forget to type group name altogether, and wonder why I'm getting a commandnotfoundexception

**Comment by armaa** [comment]
@Emzi0767 I meant exactly that as you said it, doing `group command`.

@moonPtr I did read it and i get what you mean, im just stating my view on it, i suppose

**Comment by moonPtr** [comment]
Another way to implement this would be to have

All commands ungrouped, and [Hidden]
Then the command groups, not hidden (so they show in help)
And then have group command call command

However that might lead to some spaghetti code due to how you would have to go about letting group command access command

**Comment by Emzi0767** [comment]
Which is why I'm suggesting the sudo solution, as it takes care of all the binding and conversions, and would also permit you to use dynamically-defined commands, should we ever implement that.

**Comment by Emzi0767** [comment]
This is now implemented as part of e8ac9eef00b451d0c485998073bb7601eda53753.

**Comment by GabrielTK** [comment]
Hey Guys, I know I'm kind of late to this thread, but I'm new to this project and just wanted to confirm: By using the master branch / nightly builds, would this work out-of-the-box or is changing a setting, writing a custom handler or anything similar needed?

**Comment by Emzi0767** [comment]
Sudo changes are. The original suggestion from this issue was rejected.
