### ISSUE TITLE
Rate Limits are being hit, Bot is being blocked, IP Banned

### ISSUE THREAD

**Issue by ecrocombe** [DSharpPlus/DSharpPlus#1763]
Thank you very much for your solid work on DSharpPlus, It has been magical for me to work with.

### Background: 
The bot acts as a Killfeed Bot for a video game, every action in the game posts a message to a designated discord channel for their players to see. The bot is public and is currently connected to approx ~400 gameservers. Some "battlefield" type gameservers have ~2-3 kills per second. The bot is self hosted at my home, with a static IP. As you can imagine, its in the nature of the beast to exceed rate limits by posting each kill event into a discord channel.

### Describe the bug
I was under the impression that this library would queue messages being posted until a future timeframe where the rate limit would not be exceeded, this does not seem to be the case. For the last two days running, the bot has caused my IP to be temporarily banned during peak times.

This is the code used to post messages to discord.

```cs
try
{
    if (await DiscordClient.GetShard(gs.GuildId).GetChannelAsync(gs.KillfeedPvEChannel.Value) is DiscordChannel chnl)
    {
        var eb = new DiscordEmbedBuilder(); // other logic to build the embed hidden

        await chnl.SendMessageAsync(x =>
        {
            x.AddEmbed(eb);
            x.WithAllowedMentions(Mentions.None);
        });
    }
}
catch (UnauthorizedException e)
{
    logger.LogWarning(e, $"Removing PvE Channel, Unauthorized, for GuildID: {gs.GuildId}, GameserverID: {gs.Id}, Channel: {gs.KillfeedPvEChannel.Value}");
    // remove the PvE Discord channel from the DB if we cannot send messages in there to stop future posts
    gs.KillfeedPvEChannel = null;
}
catch (NotFoundException e)
{
    logger.LogWarning(e, $"Removing PvE Channel, NotFound, for GuildID: {gs.GuildId}, GameserverID: {gs.Id}, Channel: {gs.KillfeedPvEChannel.Value}");
    // also remove the PvE Discord channel if it has been deleted
    gs.KillfeedPvEChannel = null;
}
catch
{
    // catch all other errors and continue
}

await db.PvEEvents.AddAsync(new Entities.PvEEvent()
{
    Entity = msg.PvEFeedType,
    GameserverId = gs.Id,
    PlayerId = player.Id,
    TimeStamp = DateTimeOffset.UtcNow.ToUnixTimeSeconds()
});

await db.SaveChangesAsync();
```
### To Reproduce**
Ummm.... be a super spammy bot¿? and post a tonne of messages to lot of different guilds and watch being temp IP banned.

I'm happy to screen share the code, but its not in a public repo.

### Expected behavior
That the library would "queue" messages and not send them if they were to hit the rate limit.

### Screenshots
```
[2024-02-13 17:28:13 +11:00] [114 /RatelimitHit] [Error] Ratelimit hit, requeueing request to https://discord.com/api/v10/channels/**************30558
[2024-02-13 17:28:13 +11:00] [114 /RatelimitHit] [Error] Ratelimit hit, requeueing request to https://discord.com/api/v10/channels/**************79742
[2024-02-13 17:28:14 +11:00] [114 /RatelimitHit] [Error] Ratelimit hit, requeueing request to https://discord.com/api/v10/channels/**************743946
[2024-02-13 17:28:14 +11:00] [114 /RatelimitHit] [Error] Ratelimit hit, requeueing request to https://discord.com/api/v10/channels/**************99807
[2024-02-13 17:28:14 +11:00] [114 /RatelimitHit] [Error] Ratelimit hit, requeueing request to https://discord.com/api/v10/channels/**************086726
[2024-02-13 17:28:14 +11:00] [114 /RatelimitHit] [Error] Ratelimit hit, requeueing request to https://discord.com/api/v10/channels/**************425396
[2024-02-13 17:28:14 +11:00] [114 /RatelimitHit] [Error] Ratelimit hit, requeueing request to https://discord.com/api/v10/channels/**************085466
[2024-02-13 17:28:16 +11:00] [114 /RatelimitHit] [Error] Ratelimit hit, requeueing request to https://discord.com/api/v10/channels/**************53536/messages
[2024-02-13 17:28:16 +11:00] [114 /RatelimitHit] [Error] Ratelimit hit, requeueing request to https://discord.com/api/v10/channels/**************53536/messages
[2024-02-13 17:28:16 +11:00] [114 /RatelimitHit] [Error] Ratelimit hit, requeueing request to https://discord.com/api/v10/channels/**************53536/messages
```
![image](https://github.com/DSharpPlus/DSharpPlus/assets/42088209/65b5f422-de5c-4769-8245-57319627d836)

**Comment by OoLunar** [comment]
> That the library would "queue" messages and not send them if they were to hit the rate limit.

This is what the library should be doing at the moment. In your testing, does it not?

**Comment by ecrocombe** [comment]
I was under the impression that "Error" type messages:
```
[2024-02-13 17:28:16 +11:00] [114 /RatelimitHit] [Error] Ratelimit hit, requeueing request to https://discord.com/api/v10/channels/**************53536/messages
```
Is actually hitting the limits, as apposed to the "Warning" messages that simply say they will be queuing future message? 
Please excuse my naiveness if this is not the case

**Comment by OoLunar** [comment]
The error message means your last request hit the ratelimit and the current request will be delayed until the ratelimit resets

**Comment by ecrocombe** [comment]
So once a message hits the limit and gets queued, what happens to the next message that gets sent on a different thread?
Does it:
1. wait before trying? honouring the previous messages "X-Retry-After"
2. Send a new message, and honour its own response "X-Retry-After"?

I'm setting up some logging as we speak to hopefully get some more insights into this.

**Comment by akiraveliara** [comment]
so... ratelimits are vastly different depending on which version you use, v4.x uses a different implementation to v5.x nightly, which uses a different implementation to v6.x not-even-alphas.

first off, since i can see a sharded client there, please make sure you're on the latest version of either stable or nightly builds - we caught a ratelimiting-related bug in the sharded client not too long ago, and i recently fixed another scenario where we would queue up too many requests in nightly.

the second important thing is that there are 429s we cannot prevent, since we can only act upon receiving ratelimit information from discord, and if a 429 happens before that, that is a problem we can't solve.

the third premise here is that ratelimiting absolutely does not support multiprocess sharding, if that's something you want to do - there is currently no way to transmit ratelimits between processes.

if you want to understand how it works, i would need to know what version you're using - if you want me to look into it deeper, i would need a trace log (redacting tokens of course, but all other information intact) and lastly i would recommend you batch multiple embeds into one message, which reduces ratelimit strain and would also deal with the possibility of discord considering this API abuse, at least to some extent.

**Comment by ecrocombe** [comment]
I would love any and all help on this, the bot has "premium" features which customers are paying for.

    <PackageReference Include="DSharpPlus" Version="4.4.6" />
    <PackageReference Include="DSharpPlus.Interactivity" Version="4.4.6" />
    <PackageReference Include="DSharpPlus.SlashCommands" Version="4.4.6" />

The bot is using in-process sharding, only 1 instance of the application is running at any given time. 
I am however using the 1x DiscordSharedClient (Singleton) across multiple threads in the same application. I hope this answers your multi-process question?

Trace?? I'll see what i can do, Much appreciated your input!

**Comment by ecrocombe** [comment]
How should i get this trace log to you @akiraveliara ? its not something I would want to post here, i hope you understand. my discord handle is "private_wire#9001" if you would prefer?

**Comment by akiraveliara** [comment]
my DMs on discord are open, handle is @akiraveliara

**Comment by ecrocombe** [comment]
Hi team, thanks for your quick response, time and effort in producing a fast update.

I have migrated from 4.4.6 to5.0.0-nightly-02069.
I have also disable one of the more spammy feeds. (hopefully temporarily)

The ban has been lifted in the last 30min, and with this most recent patch, slash commands are no longer working, although they did for a short while... maybe 5min¿

I have also noticed a pattern with the previous bans, they appear to be occurring after connected for pretty much spot on 1 hour, and the ban lasts for pretty much spot on 1 hour.

**Comment by OoLunar** [comment]
> The ban has been lifted in the last 30min, and with this most recent patch, slash commands are no longer working, although they did for a short while... maybe 5min¿

Which command framework are you using? `DSharpPlus.SlashCommands` or `DSharpPlus.Commands`?

**Comment by ecrocombe** [comment]
> Which command framework are you using? `DSharpPlus.SlashCommands` or `DSharpPlus.Commands`?

    <PackageReference Include="DSharpPlus" Version="5.0.0-nightly-02069" />
    <PackageReference Include="DSharpPlus.Interactivity" Version="5.0.0-nightly-02069" />
    <PackageReference Include="DSharpPlus.SlashCommands" Version="5.0.0-nightly-02069" />

![image](https://github.com/DSharpPlus/DSharpPlus/assets/42088209/c4943496-0780-4473-882c-97c3f11d475a)
![image](https://github.com/DSharpPlus/DSharpPlus/assets/42088209/e485f895-4af5-4d17-b3bb-7730c969ecd7)

This appears as a recurring log entry:
[WRN] Slash commands failed to register properly on startup. (1209a574)
System.InvalidOperationException: Slash commands failed to register properly on startup.
   at DSharpPlus.SlashCommands.SlashCommandsExtension.<>c__DisplayClass47_0.<<InteractionHandler>b__0>d.MoveNext()
   


   Startup/Program
   ```c#
HostApplicationBuilder builder = Host.CreateApplicationBuilder(args);
   builder.Services.AddHostedService<BotWorker>();
// Discord
var discordConfig = new DiscordConfiguration()
{
    Intents = DiscordIntents.AllUnprivileged | DiscordIntents.GuildMembers,
    Token = builder.Configuration.GetValue<string>("DISCORD_BOT_TOKEN") ?? throw new Exception("DISCORD_BOT_TOKEN"),
    TokenType = TokenType.Bot,
    AlwaysCacheMembers = true,
    AutoReconnect = true,
    GatewayCompressionLevel = GatewayCompressionLevel.Stream,
    LargeThreshold = 250,
    MinimumLogLevel = LogLevel.Trace,
    LogUnknownEvents = false       
};
builder.Services.AddSingleton(discordConfig);
var discordShardedClient = new DiscordShardedClient(discordConfig);
builder.Services.AddSingleton<DiscordShardedClient>(discordShardedClient);
using (IHost host = builder.Build())
{
    // Run Host Applications.
    await host.RunAsync();
}
   ```
   
   BotWorker Hosted Service
   ```c#   
       public class BotWorker : IHostedService
    {
        private readonly IServiceProvider _provider;
        private readonly DiscordShardedClient _discordClient;

        public BotWorker(IServiceProvider provider,
                       DiscordShardedClient discordClient
                       )
        {
            _provider = provider ?? throw new ArgumentNullException(nameof(provider));
            _discordClient = discordClient ?? throw new ArgumentNullException(nameof(discordClient));
            _discordClient.SessionCreated += _discordClient_SessionCreated;  //_discordClient_Ready;
        }

        private async Task _discordClient_SessionCreated(DiscordClient sender, SessionReadyEventArgs args)
        {
            if (sender.ShardId == 0)
                await sender.UpdateStatusAsync(new DSharpPlus.Entities.DiscordActivity(_stringLocalizer[Resources.BOT_ACTIVITY], DSharpPlus.Entities.ActivityType.Playing), DSharpPlus.Entities.UserStatus.Online);
        }
        public async Task StartAsync(CancellationToken cancellationToken)
        {
            var slash = await _discordClient.UseSlashCommandsAsync(new SlashCommandsConfiguration() { Services = _provider });
            var inter = await _discordClient.UseInteractivityAsync(new DSharpPlus.Interactivity.InteractivityConfiguration()
            {
                PollBehaviour = PollBehaviour.DeleteEmojis,
                Timeout = TimeSpan.FromSeconds(30)
            });
            slash.RegisterCommands<CategoriesModule>();
            slash.RegisterCommands<ChatModule>();
            slash.RegisterCommands<CommandsModule>();
            slash.RegisterCommands<EconomyModule>();
            slash.RegisterCommands<FeedsModule>();
            slash.RegisterCommands<GameserverModule>();
            slash.RegisterCommands<PlayersModule>();
            slash.RegisterCommands<PremiumModule>();
            slash.RegisterCommands<ProductsModule>();
            slash.RegisterCommands<TimedCommandsModule>();
            slash.RegisterCommands<ReportModule>();

            slash.RegisterCommands<Bal>();
            slash.RegisterCommands<Buy>();
            slash.RegisterCommands<Dep>();
            slash.RegisterCommands<InstallKit>();
            slash.RegisterCommands<Link>();
            slash.RegisterCommands<Mute>();
            slash.RegisterCommands<Pay>();
            slash.RegisterCommands<Run>();
            slash.RegisterCommands<Spin>();
            slash.RegisterCommands<Stats>();
            slash.RegisterCommands<With>();


            foreach (var shard in slash)
            {
                shard.Value.SlashCommandErrored += Slash_SlashCommandErrored;
                shard.Value.AutocompleteErrored += Value_AutocompleteErrored;
            }

            await _discordClient.StartAsync();

        }

   ```
