### ISSUE TITLE
API Ratelimit Event and Request Counter

### ISSUE THREAD

**Issue by Rabergsel** [DSharpPlus/DSharpPlus#1768]
Hello, dear D#+ team,

I would really like to see an event when the rate limit is hit, just as some stats about how close I am to the ratelimit.

Even though some may think that this is nonsense, it is a nice-to-have feature. It may also help with diagnosis.

In detail I request:

1. An Event in the DiscordClient class which is triggered when the Ratelimit is (almost) hit.
2. Some APIState Class that will return the current allowed ratelimit, and how close I am to it. (In %)

I hope this feature may be added.
Thanks.

**Comment by akiraveliara** [comment]
For a multitude of reasons, implementing any event or current state is not particularly feasible nor useful, and instead we will focus on improving the internal ratelimiter and its extensibility and configurability. However, I've now implemented request metrics, reviewing which may help in tuning your bot to run into less ratelimit issues - let me know if there's anything else you need or want to know!
