### ISSUE TITLE
Rest client ratelimit inconsistencies

### ISSUE THREAD

**Issue by VelvetToroyashi** [DSharpPlus/DSharpPlus#1909]
Initially to be a comment in #1908, I wanted to point out some issues with this:

https://github.com/DSharpPlus/DSharpPlus/blob/4f42a502059f6b1c5f155c8ef9622f422f9c2bcf/DSharpPlus/Net/Rest/RestClientOptions.cs

Namely in regards to the data passed to rest client; 

First, `Timeout` is a `TimeSpan`, which is good, and sensible.
https://github.com/DSharpPlus/DSharpPlus/blob/4f42a502059f6b1c5f155c8ef9622f422f9c2bcf/DSharpPlus/Net/Rest/RestClientOptions.cs#L14

However, the retry delay fallback is a `double`, and represents *seconds*. https://github.com/DSharpPlus/DSharpPlus/blob/4f42a502059f6b1c5f155c8ef9622f422f9c2bcf/DSharpPlus/Net/Rest/RestClientOptions.cs#L24-L27

This would be OK if the first were also a double, and/or measured in seconds, however this timeout is an `int`, and measured in milliseconds. https://github.com/DSharpPlus/DSharpPlus/blob/4f42a502059f6b1c5f155c8ef9622f422f9c2bcf/DSharpPlus/Net/Rest/RestClientOptions.cs#L29-L32

This is undoubtedly a confusing mess to deal with and relies on looking closely at documentation to not accidentally set nonsensical values in either direction for users that want to fine-tune the library.

Ideally, this would be consistent, and all three would be `TimeSpan`, which is an unambiguous datatype, 

---
https://github.com/DSharpPlus/DSharpPlus/blob/4f42a502059f6b1c5f155c8ef9622f422f9c2bcf/DSharpPlus/Net/Rest/RestClientOptions.cs#L22

I also had concerns about this; it's an `int`, so I'd expect that `-1` would be used as the sentinel value, however int.MaxValue is so absurdly huge that this doesn't really matter. That being said, perhaps this could be set to `uint` for that very reason.

**Comment by Plerx2493** [comment]
> I also had concerns about this; it's an int, so I'd expect that -1 would be used as the sentinel value, however int.MaxValue is so absurdly huge that this doesn't really matter. That being said, perhaps this could be set to uint for that very reason.

This value is choosen because its the way that Polly represents retries
