### ISSUE TITLE
Getting archived threads for forum?

### ISSUE THREAD

**Issue by TheVVaS** [DSharpPlus/DSharpPlus#1915]
### Summary

All functions to get archived threads performed on channel with type `DiscordChannelType.GuildForum` always leads to `InvalidOperationException`.

By all I mean:
- ListPublicArchivedThreadsAsync()
- ListPrivateArchivedThreadsAsync()
- ListJoinedPrivateArchivedThreadsAsync()

### What version of the library are you using?

v5.0.0-nightly (make sure you are using the latest nightly!)

### What .NET version are you using? Make sure to use the latest patch release for your major version.

.NET 8.0

### Operating System

windows 10

### Reproduction Steps

Everything is above

**Comment by Plerx2493** [comment]
Will open a pr later

**Comment by Plerx2493** [comment]
Can you test #1916 ?

**Comment by TheVVaS** [comment]
Works nice, but is it for nightly too?

**Comment by Plerx2493** [comment]
Will be merged to master and then publish to nightly a few minutes later
