### ISSUE TITLE
NRE on RequirePermissionCheck

### ISSUE THREAD

**Issue by ecrocombe** [DSharpPlus/DSharpPlus#1917]
### Summary

NRE Exception on RequirePermissionCheck

### What version of the library are you using?

v5.0.0-nightly (make sure you are using the latest nightly!)

### What .NET version are you using? Make sure to use the latest patch release for your major version.

.NET 8.0

### Operating System

Ubuntu

### Reproduction Steps

Decorate
```[RequirePermissions(botPermissions: DiscordPermissions.None, userPermissions: DiscordPermissions.ManageGuild)]```
on SlashCommand
Run in Discord Text Channel.

This happens for every user, for every command in 1 specific guild, but works in others.

This randomly occurs in guilds, not shard specific, fixes when bot restarts, but eventually makes its way to a different guild.

### Trace Logs

```log
Object reference not set to an instance of an object.   
at DSharpPlus.Commands.ContextChecks.RequirePermissionsCheck.ExecuteCheckAsync(RequirePermissionsAttribute attribute, CommandContext context)
   at DSharpPlus.Commands.DefaultCommandExecutor.ExecuteContextChecksAsync(CommandContext context)
DSharpPlus.Commands.Exceptions.ChecksFailedException: Checks for gs test failed.
```

**Comment by Plerx2493** [comment]
Does this happen in guilds where you have a bot account in? I know there is a bug with user installations or guild installations without bot account in the guild

**Comment by ecrocombe** [comment]
Yes, we do not use user installs yet.
