### ISSUE TITLE
Rework reconnection logic

### ISSUE THREAD

**Issue by Plerx2493** [DSharpPlus/DSharpPlus#1921]
# Summary
New fields in Config:
- uint MaximumReconnectionRetries
- `TimeSpan?` ReconnectionDelayDuration (Static delay)
- `Func<uint attempt, TimeSpan result>?` ReconnectionDelayGenerator (dynamic delay)

To be removed:
- bool ReconnectIndefinitely

Defaults should have a implementation with some kind of hardlimit (maybe 15-30 min?)

# Notes 
Currently blocked by #1908

**Comment by akiraveliara** [comment]
in the same spirit as #1909 , the duration should use a TimeSpan
and instead of the multiplier we might want to take a `Func<TimeSpan initial, uint attempt, TimeSpan result>`
