### ISSUE TITLE
cool repo

### ISSUE THREAD

**Issue by soijasioda1** [DSharpPlus/DSharpPlus#1948]
### Summary

cool repo

### What version of the library are you using?

v4.4.6 (Stable)

### What .NET version are you using? Make sure to use the latest patch release for your major version.

.NET 6.0

### Reproduction Steps

cool repo

### Trace Logs

```log
cool repo
```

### Exceptions or other error messages

```txt
cool repo
```

### Anything else you'd like to share

cool repo

**Comment by InFTord** [comment]
thank you for your feedback, we appreciate it
but don't use issues for stuff like this, please!
