### ISSUE TITLE
InteractionLocalizerAttribute does not snake-case slash command names and args

### ISSUE THREAD

**Issue by ecrocombe** [DSharpPlus/DSharpPlus#1950]
### Description

command names and arg names can't contain uppercase, so the extension snake-cases them automatically. you can manually specify a parameter name using this attribute, if you need to.

However, when using the `DSharpPlus.Commands.Processors.SlashCommands.Localization.InteractionLocalizerAttribute`, the above case does not apply. 

Consistency update?

### Specify the libraries you want this feature request to affect

DSharpPlus.Commands

### Other considerations

Adding to the difficulty of this request, using .ToLower() may have to be performed whilst the the thread is set to the culture of the language? idk tbh 🤷

**Comment by akiraveliara** [comment]
https://learn.microsoft.com/en-us/dotnet/api/system.char.tolower?view=net-8.0#system-char-tolower(system-char-system-globalization-cultureinfo) might be useful to implementers
