### ISSUE TITLE
Inconsistent CommandChecks

### ISSUE THREAD

**Issue by Plerx2493** [DSharpPlus/DSharpPlus#1958]
### Description

Some built in checks are inherited by sub commands and custom checks seem to not follow this

https://discord.com/channels/379378609942560770/1094835363475886163/1250952035105509416

### Specify the libraries you want this feature request to affect

DSharpPlus.Commands

**Comment by selfdocumentingcode** [comment]
I have a bunch of classes for my commands, which don't act as command groups, but are just a collections of independent commands which use the same checks. 

With CommandsNext, I was able to place the check attribute on the class itself and the check would be executed for every command method in the class. 

With Commands, the check attribute has to be placed on each and every command method. Applies to both built-in checks e.g. RequireGuild and custom checks. 

```cs
// The checks do not get executed when the attributes are placed here.
[RequireGuild]
[MyCustomCheck]
public class RandomModule
{
    // They only get executed when placed here
    [RequireGuild]
    [MyCustomCheck]
    [Command("oi")]
    [Description("Oi!")]
    public static ValueTask Oi(CommandContext ctx)
    {
        return ctx.RespondAsync("Oi!");
    }

    // And have to be copy-pasted for each and every command
    [RequireGuild]
    [MyCustomCheck]
    [Command("slap")]
    [Description("Slap someone with a large trout")]
    public static async ValueTask Slap(
        CommandContext ctx,
        [Parameter("slapee")] [Description("The receiver of the slap")]
        DiscordMember member)
    {
        string slapper = ctx.Member?.DisplayName ?? ctx.User.Username;
        string slapee = member.DisplayName;

        await ctx.Channel.SendMessageAsync($"_**{slapper}** slaps **{slapee}** around a bit with a large trout_");
    }
}
```
