### ISSUE TITLE
Add option to use no prefix

### ISSUE THREAD

**Issue by wthks** [DSharpPlus/DSharpPlus#1963]
### Description

I'm currently migrating to v5, it would be great to have an option inside TextCommandProcessor for EnablePrefix to enable or disable a prefix

### Specify the libraries you want this feature request to affect

DSharpPlus.Commands

**Comment by akiraveliara** [comment]
you can write your own prefix resolver to always resolve to `true`.

**Comment by Plerx2493** [comment]
The structure you have there, should resolve to the following:

play play
play game
play reset

**Comment by cydolo** [comment]
In v4 I used `[GroupCommand]` which allowed me to only use `play` and not `play play`
i tried to add `DefaultGroupCommand` but that not works

that was the working one in v4
```
[group("play")]
public class Play
{
    [GroupCommand]
    public async Task PlayAsync(CommandContext ctx)
    
    
    [Command("game")]
    public async Task GameAsync(CommandContext ctx)
    
    
    [Command("reset")]
    public async Task ResetAsync(CommandContext ctx)
}
````

**Comment by Plerx2493** [comment]
I'm not sure if we support that because it's a structure we can't represent with slash commands
