### ISSUE TITLE
Command regristration is bugged when using assembly to register all commands

### ISSUE THREAD

**Issue by Plerx2493** [DSharpPlus/DSharpPlus#1975]
### Summary

Currently we scan for all methods or classes that have the `Command` attribute which leads to multiple registrations of subcommands.

### What version of the library are you using?

v5.0.0-nightly (make sure you are using the latest nightly!)

### What .NET version are you using? Make sure to use the latest patch release for your major version.

.NET 6.0

### Reproduction Steps

```
[Command("root")] 
public static class RootCommand
{
    [Command("subcommandgroup")] 
    public static class SubCommandGroup
    {
         [Command("command")]
         public static async Task Command(SlashCommandContext ctx) { /* .. */ }
    }
}
```

Using this structure will produce the following commands:

```
root subcommandgroup command
subcommandgroup command
```

**Comment by Plerx2493** [comment]
Current workaround is using `CommandsExtension#AddCommands(IEnumerable<Type> types)` instead of `CommandsExtension#AddCommands(Assembly assembly)`

**Comment by OoLunar** [comment]
Unable to reproduce

**Comment by Plerx2493** [comment]
Afaik this area of code wasnt changed but i cant reproduce it also anymore.
