### ISSUE TITLE
General onboarding documentation 

### ISSUE THREAD

**Issue by eastwood** [DSharpPlus/DSharpPlus#1977]
### Description

Hello,

I've been working through the documentation on the website and noticed that there are issues in the examples which are invalid:

```cs
DiscordClientBuilder builder = DiscordClientBuilder.CreateDefault("My First Token", DiscordIntents.AllUnprivileged);  // Builder does not exist
DiscordClient client = builder.Build();
```

But this does not exist in the latest stable version of the Nuget package. I'm assuming these docs are targeted towards either a nightly build or an older version?

Secondly:

```cs
DiscordClient client = builder.Build();
await discord.ConnectAsync();
await Task.Delay(-1);
```

Should probably be:

```cs
client.ConnectAsync()
```

I'd be happy to uplift these docs as I go through them, but just want to make sure that this is the correct direction.

### Specify the libraries you want this feature request to affect

DSharpPlus, the core library

**Comment by akiraveliara** [comment]
our documentation vaguely targets nightly (although they're often a bit outdated), correct; since we do not encourage using the badly outdated stable builds and only service critical fixes. - we'd probably accept pull requests for adding stable documentation somewhere, though

this specific case is incorrect, and yes, it should be `await client.ConnectAsync()`. if you want to a pull request we'd be happy to merge it; if not i can do this shortly

**Comment by eastwood** [comment]
Oh gotchya - so perhaps I can update the dogs to target a nightly version instead of the older ones while I'm at it?

**Comment by Plerx2493** [comment]
1. The preamble of our docs clearly state that our docs target nightly
<img width="1021" alt="image" src="https://github.com/DSharpPlus/DSharpPlus/assets/50530305/495efd2e-42bc-4e2c-8a46-de9ad6ce5900">

2. The `Task.Delay` is intended because otherwise the programm would exit immediately

**Comment by Plerx2493** [comment]
> Can you let me know what version of the build you'd like to target in the docs? Both v4 and v5 major versions don't appear to have the DiscordClientBuilder for example. Is this something you want in the docs, or should I just keep the use of `DiscordClient`?

The current article works for any nightly version v5.0.0-nightly-02271+

**Comment by eastwood** [comment]
> 1. The preamble of our docs clearly state that our docs target nightly
No worries, thanks for this. Admittedly, I missed this and installed the latest stable release via `dotnet add package`. Coming in new to the documentation, I _assumed_ incorrectly that since my version was after that in the images, then I'd be good. 

> 2. The `Task.Delay` is intended because otherwise the programm would exit immediately
More specifically, the variable name is incorrect.

**Comment by Plerx2493** [comment]
oh yeah thats a small mistake

**Comment by eastwood** [comment]
> > Can you let me know what version of the build you'd like to target in the docs? Both v4 and v5 major versions don't appear to have the DiscordClientBuilder for example. Is this something you want in the docs, or should I just keep the use of `DiscordClient`?
> 
> The current article works for any nightly version v5.0.0-nightly-02271+

Thank you, clearly made some assumptions that although felt intuitive are clearly incorrect.
This answers everything I need for now, I'll close this for now and make a PR with any small things I notice as I'm working through my weekend project.
