### ISSUE TITLE
Request: Allow returning multiple messages by the custom help formatter

### ISSUE THREAD

**Issue by GHXX** [DSharpPlus/DSharpPlus#198]
# Summary
Currently it is only possible to return one message when the custom help formatter (IHelpFormatter) builds. 
My request is to allow returning multiple help messages when the Build method inside the custom help formatter is called.
This would allow for sending long help messages that are then sent after another (total length >2000).

# Changes proposed
+ Allow returning a List of messages (List\<CommandHelpMessage\>)
+ Add code to send help messages one after another here (foreach loop):
https://github.com/NaamloosDT/DSharpPlus/blob/1e51adecd929321999cb569bd4eb8ec37b5a4945/DSharpPlus.CommandsNext/CommandsNextExtension.cs#L689

# Notes
Changing the return type of the build method will break all projects, but I think changing it is better than creating an entirely new object. But thats up to you. Thanks!

**Comment by moonPtr** [comment]
Just write your own help command ya dingus

**Comment by uwx** [comment]
how do you do the thing with the code block like that

**Comment by moonPtr** [comment]
Actually that's kinda rude but I can't figure out how to delete my reply so sorry

**Comment by uwx** [comment]
there's an X button next to the smiley

**Comment by moonPtr** [comment]
mobile, got neither

**Comment by uwx** [comment]
welp

**Comment by Emzi0767** [comment]
@uwx he linked a part of the repo.
@GHXX this isn't currently possible, and I can't think of a clean way to do this. You probably want to make a help command that takes advantage of Interactivity. As I don't want interdependency between the modules, I need to first figure out a way to do this cleanly.

**Comment by GHXX** [comment]
Alright, thanks!

**Comment by Emzi0767** [comment]
As the help formatter is designed for the internal help only, facilitating interactivity usage, which is a standalone extension independent of CNext, doesn't make much sense. Rolling your own help typically also means rolling your own formatting system.
