### ISSUE TITLE
DiscordClientBuilder doesn't exist

### ISSUE THREAD

**Issue by brand421** [DSharpPlus/DSharpPlus#1988]
### Summary

Tried following the "Your First Bot" guide using DSharpPlus 4.4.9, and on .net6.0 and .net7.0, and in both instances when I tried to build the program the errors "The type or namespace name 'DiscordClientBuilder' could not be found" and "The name 'DiscordClientBuilder' does not exist in the current context".

### What version of the library are you using?

v4.4.9 (Stable)

### What .NET version are you using? Make sure to use the latest patch release for your major version.

.NET 6.0

### Operating System

Windows 11

### Reproduction Steps

Created a new console app and started a program from scratch (ensuring to install DSharpPlus v4.4.9)

### Exceptions or other error messages

"The type or namespace name 'DiscordClientBuilder' could not be found" and "The name 'DiscordClientBuilder' does not exist in the current context" when building app

**Comment by Plerx2493** [comment]
![image](https://github.com/DSharpPlus/DSharpPlus/assets/50530305/4a273015-a9d8-4b21-9f38-8fb397060407)

https://dsharpplus.github.io/DSharpPlus/articles/preamble.html

As stated in the documentation, it is not present because the documentation targets the prerelease version.

**Comment by Minabsapi** [comment]
That's nice and all, but where can the documentation for the latest **stable** release be found in that case? I hope there's one, because I've never been a fan of bleeding edge, and this isn't going to change now.
