### ISSUE TITLE
DiscordRestClient's HttpClient has no Authorization Header

### ISSUE THREAD

**Issue by Izumemori** [DSharpPlus/DSharpPlus#1992]
### Summary

DiscordRestClient's HttpClient is left blank and never has any token information provided to it.

### What version of the library are you using?

v5.0.0-nightly (make sure you are using the latest nightly!)

### What .NET version are you using? Make sure to use the latest patch release for your major version.

.NET 8.0

### Operating System

Arch Linux

### Reproduction Steps

```cs
var restClient = new DiscordRestClient(new DiscordConfiguration(), token, TokenType.Bot);
await restClient.CreateMessageAsync(...);
```

And you'll receive an `UnauthorizedException`.

### Exceptions or other error messages

```txt
DSharpPlus.Exceptions.UnauthorizedException: Unauthorized: Unauthorized
   at DSharpPlus.Net.RestClient.ExecuteRequestAsync[TRequest](TRequest request)
   at DSharpPlus.Net.DiscordApiClient.CreateMessageAsync(UInt64 channelId, DiscordMessageBuilder builder)
   at DSharpPlus.DiscordRestClient.CreateMessageAsync(UInt64 channelId, DiscordMessageBuilder builder)
```

### Anything else you'd like to share

The HttpClient is initialized here with no parameters, no token information is provided to the RestClient and no Authorization Headers are being set.
https://github.com/DSharpPlus/DSharpPlus/blob/3535be34601b30eddd0ad22f43fecdc1d6cb5c98/DSharpPlus.Rest/DiscordRestClient.cs#L31-L38

This results in only the `User-Agent` header being set in `RestClient.cs`:
https://github.com/DSharpPlus/DSharpPlus/blob/a056dc833a48c259f52cc90d32f73bfa550ac54a/DSharpPlus/Net/Rest/RestClient.cs#L60-L98

![image](https://github.com/DSharpPlus/DSharpPlus/assets/18233978/57a58784-40ab-4b14-a4d4-9352c7752f17)

**Comment by Plerx2493** [comment]
Could you be so kind and test #1993 for us?
