### ISSUE TITLE
Missing ShardClients

### ISSUE THREAD

**Issue by wthks** [DSharpPlus/DSharpPlus#2006]
### Description

The DiscordShardClient have been removed, I'm currently looking for the ShardClients property is it currently not available?

### Specify the libraries you want this feature request to affect

DSharpPlus, the core library

**Comment by Plerx2493** [comment]
https://dsharpplus.github.io/DSharpPlus/articles/beyond_basics/sharding.html?tabs=discordclientbuilder

**Comment by akiraveliara** [comment]
what are you trying to accomplish using the property

**Comment by akiraveliara** [comment]
since `DiscordClient.Guilds` contains all guilds now, this can already be accomplished.

**Comment by Plerx2493** [comment]
DiscordClient.Guilds contains all guilds from all shards
