### ISSUE TITLE
Sharded client does not load all guilds.

### ISSUE THREAD

**Issue by wthks** [DSharpPlus/DSharpPlus#2014]
### Summary

I'm encountering multiple issues with DSharpPlus v5 in a sharded bot setup:

Incomplete guild loading: Not all guilds are being loaded across shards, despite successful shard connections.

Event handling inconsistency: The HandleGuildDownloadCompleted event is only firing once, instead of for each shard as expected.

Slash command execution failure: Slash commands are reportedly registered successfully, but attempts to execute them result in an "interaction failed" message.

```cs
var discordClient = DiscordClientBuilder.CreateSharded(discordToken, DiscordIntents.AllUnprivileged)
    .ConfigureLogging(a => a
        .AddConsole()
        .SetMinimumLevel(LogLevel.Debug))
    .ConfigureEventHandlers(a =>
    {
        a.HandleGuildDownloadCompleted((sender, args) => 
        {
            Console.WriteLine($"Loaded: {args.Guilds.Count} Guilds.");
            return Task.CompletedTask;
        });

    })
    .Build();

var commands = discordClient.UseCommands(new()
{
    RegisterDefaultCommandProcessors = false
});

await commands.AddProcessorAsync(new SlashCommandProcessor());
commands.AddCommands(Assembly.GetExecutingAssembly());
```

### What version of the library are you using?

v5.0.0-nightly (make sure you are using the latest nightly!)

### What .NET version are you using? Make sure to use the latest patch release for your major version.

.NET 9.0 Previews

### Operating System

Windows 11

### Reproduction Steps

The migration to v5 has introduced these problems, as the previous DiscordShardedClient in v4 functioned correctly for all these aspects

**Comment by akiraveliara** [comment]
Please open separate issues for separate issues, for both clarity and resolution tracking purposes.

GuildDownloadComplete firing once per client rather than per shard is an intentional change, since it refers to all guilds having finished streaming to the relevant `DiscordClient` instance.

**Comment by akiraveliara** [comment]
I will need more and more specific information to try to solve any potential issues, ideally involving a clear reproduction setup and trace logs; best tracked in separate issues.
