### ISSUE TITLE
Addition of docs about allowed command arguments

### ISSUE THREAD

**Issue by Sella-GH** [DSharpPlus/DSharpPlus#2029]
### Description

The [Slash Commands article](https://dsharpplus.github.io/DSharpPlus/articles/slash_commands.html#arguments) got a pretty good short overview about every possible argument which is allowed inside a command method. My consideration is to add an article about the general allowed arguments of the DSharpPlus.Commands library too so users of the lib got a quick look at what they can use or not.

The error messages are good already (when you use an unallowed argument) but I'd prefer an overview like in the mentioned article above, just to prevent some errors in advance and to improve the completeness of docs.

### Specify the libraries you want this feature request to affect

DSharpPlus.Commands

**Comment by Plerx2493** [comment]
In addition to this, docs about context menues

**Comment by akiraveliara** [comment]
implemented in #1975
