### ISSUE TITLE
Better application commands registration 

### ISSUE THREAD

**Issue by Plerx2493** [DSharpPlus/DSharpPlus#2055]
### Description

Currently we always overwrite all application commands on startup, this issue proposes to first fetch current application commands and only use bulk overwrite when we detect changes.

### Specify the libraries you want this feature request to affect

DSharpPlus.Commands

**Comment by Naamloos** [comment]
Honestly in my opinion it would've been nice if Discord had a `Bulk Add` and `Bulk Delete` for app commands. That way, we could smartly detect changes and only add / remove those that need updating.

I think it's worth discussing whether we want to do this "smartly" (don't update commands that are still correct) or the easy way (overwrite everything as soon as ANYTHING differs)

**Comment by Naamloos** [comment]
With that I'd also like to add that a bulk overwrite renders application commands useless until e.g. the client is reloaded. We could lessen the impact of this by "smartly" updating commands. 

Though again, we can only bulk overwrite _everything_, which sucks.

**Comment by akiraveliara** [comment]
before we consider implementation strategies for anything like this, i would like to point out that this would cause a lot of extra API requests if we manage on a per-command basis, which would be problematic for rapid iteration (since application command limits are per day) and for large bots with many commands; and that therefore any such strategy should ideally be gated behind a configuration option

**Comment by Plerx2493** [comment]
I thought about adding it behind an option and only match and bulk overwrite, so its one api call more in cases where they changed but we safe the user from hitting the daily limit if they only change internals

**Comment by Naamloos** [comment]
> before we consider implementation strategies for anything like this, i would like to point out that this would cause a lot of extra API requests if we manage on a per-command basis, which would be problematic for rapid iteration (since application command limits are per day) and for large bots with many commands; and that therefore any such strategy should ideally be gated behind a configuration option

Agree with that, really this is Discord's design issue causing rapid exhaustion of snowflake IDs :^) /j
