### ISSUE TITLE
"Threads can only be created within text or news channels."

### ISSUE THREAD

**Issue by SuperPyroManiac** [DSharpPlus/DSharpPlus#2060]
### Summary

_This was brought up on Discord but I was told to post it here to get attention to it.
https://discord.com/channels/379378609942560770/1094835363475886163/1267444114123657236_

You cannot create thread in build 02332+ for some reason I thinks the parent channel is not a text or news channel. I tried creating new channels, different permissions, and even a new bot on a new guild. Same issue.

### What version of the library are you using?

v5.0.0-nightly (make sure you are using the latest nightly!)

### What .NET version are you using? Make sure to use the latest patch release for your major version.

.NET 8.0

### Operating System

Ubuntu (Error on Windows 11 as well)

### Reproduction Steps

Create a thread in any channel on the latest nightly.

### Trace Logs

```log
[2024-07-29 06:48:24 +00:00] [DSharpPlus.IClientErrorHandler] [Error] Event handler exception for event DSharpPlus.EventArgs.ComponentInteractionCreatedEventArgs thrown from System.Threading.Tasks.Task HandleInteraction(DSharpPlus.DiscordClient, DSharpPlus.EventArgs.ComponentInteractionCreatedEventArgs) (defined in LSPDFRHelper.EventManagers.CompInteraction).
System.InvalidOperationException: Threads can only be created within text or news channels.
   at DSharpPlus.Entities.DiscordChannel.CreateThreadAsync(String name, DiscordAutoArchiveDuration archiveAfter, DiscordChannelType threadType, String reason)
```

### Exceptions or other error messages

```txt
System.InvalidOperationException: Threads can only be created within text or news channels.
```

### Anything else you'd like to share

Breaks at version 02332 in nightly. I have to stick to 02317 though due to the command issues that were not fixed until after that.

**Comment by Plerx2493** [comment]
This is likely caused by not using all data coming from an interaction. I have rewriting/parsing this correctly on my todo but due to me starting a new job, I have no idea when I will have time to tackle it.

**Comment by Naamloos** [comment]
Why do we have this as a client-side check at all?

**Comment by Erisa** [comment]
From some context in https://discord.com/channels/379378609942560770/1094835363475886163/1275207054868348998 and my own testing, this is due to the channel being null in the data for the interaction, introduced by https://github.com/DSharpPlus/DSharpPlus/commit/1d54d42c55c6c3719928c5f3f153adf8c1b92da8
