### ISSUE TITLE
Locale property stays null when user executes a slash command

### ISSUE THREAD

**Issue by Sella-GH** [DSharpPlus/DSharpPlus#2063]
### Summary

When a user executes a slash command and starts an interaction the user (or guild member) does not have the "locale" property filled inside the SlashCommandContext - instead it's null.

### What version of the library are you using?

v5.0.0-nightly (make sure you are using the latest nightly!)

### What .NET version are you using? Make sure to use the latest patch release for your major version.

.NET 8.0

### Operating System

Windows 11 23H2 - Build 22635.4005

### Reproduction Steps

1. Create a slash command
2. Debug the slash command
3. Look inside the SlashCommandContext and review the "Member" and "User" properties

### Anything else you'd like to share

Tried different things now but still stays at null value:
* Enabling Server Member Intents
* Re-Inviting the bot with activated OAuth2 Permission for identity (like in discord [docs](https://discord.com/developers/docs/resources/user#user-object-user-structure) provided)
* Tried web and client to differ if it's there too

**Comment by akiraveliara** [comment]
the `locale` field is optional per API docs, which for DSharpPlus means null values should be expected
