### ISSUE TITLE
Add Default Slash Command Permissions that can be overridden in the client

### ISSUE THREAD

**Issue by ecrocombe** [DSharpPlus/DSharpPlus#2073]
### Description

I propose a new Command Attribute, one that registers slash commands with a "default_member_permissions" requiring the supplied `DSharpPlus.EntitiesDiscordPermissions` but can be overridden using Discords built-in "Integrations". 

Similar to how the old `DSharpPlus.SlashCommands.SlashCommandPermissionsAttribute` (I think it was this attribute from memory :think:) used to work.

### Specify the libraries you want this feature request to affect

DSharpPlus.Commands

**Comment by Plerx2493** [comment]
There is a RequirePermission attribute + check which should do exactly this

**Comment by ecrocombe** [comment]
> There is a RequirePermission attribute + check which should do exactly this

It cannot be overriden by client settings

**Comment by Plerx2493** [comment]
Oh yeah I see, so basically the same attribute but without the "hardcoded" client side check

**Comment by ecrocombe** [comment]
Yes please sir!

Reproduction step:
1. Make a slashy with RequirePermission attribute that requires "Manage Server" permission from the User
2. Use Discords "Integrations" to override the required permission to allow 'everyone'
3. Try and use the slashy by a User without the "Manage Server" permission.

Expect:
The slash command to run successfully.

Actual:
DSP blocks it.

**Comment by ecrocombe** [comment]
Although, I think there is still a use case for the current `RequirePermission`, which is why I propose a new attribute.

**Comment by akiraveliara** [comment]
that sounds more like a bug report in that DSharpPlus isn't supposed to block that command

**Comment by Plerx2493** [comment]
I think the best way would be to simply always skip the check when its a SlashCommandContext

**Comment by akiraveliara** [comment]
i already see this short-circuiting here, going to need an error message from @ecrocombe 

https://github.com/DSharpPlus/DSharpPlus/blob/master/DSharpPlus.Commands/ContextChecks/RequirePermissionsCheck.cs#L14-L22

**Comment by Plerx2493** [comment]
This shortcircuit is only to use the app permission data contained in the interaction

**Comment by ecrocombe** [comment]
I can no longer reproduce, and it works as expected :/ 

Sorry for wasting your time
