### ISSUE TITLE
DsharpPlus no working with latest Lavalink

### ISSUE THREAD

**Issue by tomdavies98** [DSharpPlus/DSharpPlus#2078]
### Summary

Getting the following error from lava link when using the latest DsharpPlus lavalink build with the latest lavalink jar file

`2024-08-22T21:10:07.720+01:00  WARN 26656 --- [  XNIO-1 task-2] lavalink.server.config.WebsocketConfig   : This is the old Lavalink websocket endpoint. Please use /v4/websocket instead. If you are using a client library, please update it to a Lavalink v4 compatible version or use Lavalink v3 instead.`

Does DsharpPlus support V4 websockets or am I missing something in my setup (I was previously running this setup a couple years ago without issue on older builds)

![image_2024-08-22_211547541](https://github.com/user-attachments/assets/d4414262-2467-4fdd-969b-42aa76cbc217)

### What version of the library are you using?

v4.4.9 (Stable)

### What .NET version are you using? Make sure to use the latest patch release for your major version.

.NET 6.0

### Operating System

Windows 11

### Reproduction Steps

Launching both applications gives this on startup

### Anything else you'd like to share

Tried running a version of lavalink before they implemented V4 Web sockets with a DsharpPlus build from the same time (June 2023) but Lavalink had no luck

**Comment by akiraveliara** [comment]
DSharpPlus.Lavalink is defunct, and it seems the problems have reached stable now. We recommend using Lavalink4NET instead, which supports Lavalink v4.
