### ISSUE TITLE
`RequirePermissionsCheck` does not use `attribute.UserPermissions` when the context is a `SlashCommandContext`

### ISSUE THREAD

**Issue by AALUND13** [DSharpPlus/DSharpPlus#2117]
### Summary

In the `RequirePermissionsCheck` class, when the context is a `SlashCommandContext`, it does not verify whether the user has the required permissions to execute the bot command.

```cs
        if (context is SlashCommandContext slashContext)
        {
            if (!slashContext.Interaction.AppPermissions.HasPermission(attribute.BotPermissions))
            {
                return ValueTask.FromResult<string?>("The bot did not have the needed permissions to execute this command.");
            } // No check to verify user permissions here

            return ValueTask.FromResult<string?>(null);
        }
```

### What version of the library are you using?

v5.0.0-nightly (make sure you are using the latest nightly!)

### What .NET version are you using? Make sure to use the latest patch release for your major version.

.NET 8.0

### Operating System

 windows 11

### Reproduction Steps

Set the `RequirePermissions` attribute `UserPermission` parameter to a permission like `DiscordPermissions.ManageGuild`, And run the slash command.
![Image](https://github.com/user-attachments/assets/097d6b6e-551b-4e60-8ec2-36f0568cec22)
![Image](https://github.com/user-attachments/assets/1fcbfb5a-2a76-444a-97b4-2f1949665bea)

**Comment by akiraveliara** [comment]
This is working as intended - we rely on Discord to check user permissions, since application commands can have permission overwrites the library cannot see or control.
