### ISSUE TITLE
MfaEnabled always returns null

### ISSUE THREAD

**Issue by Cyconi** [DSharpPlus/DSharpPlus#2121]
### Summary

No matter what I do MfaEnabled always seems to be null
```cs
[SlashCommand("command", "")]
[SlashCooldown(1, 5, SlashCooldownBucketType.User)]
public async Task Command(InteractionContext ctx)
{
    Console.WriteLine($"command was called by {ctx.User.Id}");
    if (ctx.User.MfaEnabled == null)
        Console.WriteLine("MfaEnabled is null");

    if (ctx.User.MfaEnabled != true)
    {
        Console.WriteLine($"{ctx.User.Id} tried calling a command without 2FA");
        await ctx.CreateResponseAsync(new DiscordInteractionResponseBuilder()
                .WithContent("You must have 2FA enabled to use this command.")
                .AsEphemeral(true));
        return;
    }
    else
        await ctx.CreateResponseAsync(new DiscordInteractionResponseBuilder()
                .WithContent("2FA is enabled")
                .AsEphemeral(true));
}
```
### What version of the library are you using?

v4.4.9 (Stable)

### What .NET version are you using? Make sure to use the latest patch release for your major version.

.NET 8.0

### Operating System

Windows 10

### Reproduction Steps

Running the example slash command

### Trace Logs

None

### Exceptions or other error messages

None

**Comment by VelvetToroyashi** [comment]
This is expected behavior; the user needs to authorize your bot, [and moreover you need to use their bearer token](https://discord.com/developers/docs/topics/oauth2) for this, as per the 'Required OAuth2 Scope' field [on the docs](https://discord.com/developers/docs/resources/user#user-object-user-structure).

**Comment by Cyconi** [comment]
does MfaEnabled check if the user has authenticated with the bot? or does it check if they have MFA with discord?

**Comment by VelvetToroyashi** [comment]
We only return what Discord tells us, so no we don't check if the user has authenticated - you need their bearer token anyway, as per the OAuth2 docs I linked prior. You can use the `DiscordRestClient` class to follow through with the OAuth2 flow and using the acquired bearer token.

**Comment by Cyconi** [comment]
okay thank you, will this require me to set up a oauth call back URI?
