### ISSUE TITLE
InvalidOperationException when not adding a processor and default processors set to true

### ISSUE THREAD

**Issue by BlackLotusLV** [DSharpPlus/DSharpPlus#2127]
### Summary

On nightly 2390 if you leave "RegisterDefaultCommandProcessors" to default (true) and not register text commands processor, it throws this exception.
```
System.InvalidOperationException: TextCommandProcessor has not been configured.
   at DSharpPlus.Commands.Processors.TextCommands.TextCommandProcessor.ExecuteTextCommandAsync(DiscordClient client, MessageCreatedEventArgs eventArgs)
   at DSharpPlus.Commands.ProcessorInvokingHandlers.HandleEventAsync(DiscordClient sender, MessageCreatedEventArgs eventArgs)
   at DSharpPlus.Clients.DefaultEventDispatcher.<>c__DisplayClass5_0`1.<<DispatchAsync>b__0>d.MoveNext()
```

As soon as you set `RegisterDefaultCommandProcessors = false` in the commands config, it does not throw.

### What version of the library are you using?

v5.0.0-nightly (make sure you are using the latest nightly!)

### What .NET version are you using? Make sure to use the latest patch release for your major version.

.NET 8.0

### Operating System

win11

### Reproduction Steps

```csharp
CommandsConfiguration commandsConfiguration = new()
        {
            DebugGuildId = guildId,
            RegisterDefaultCommandProcessors = true //<--- this is the issue spot
        };
        services.AddCommandsExtension((_, commands) =>
            {
                commands.CommandExecuted += SystemEvents.CommandExecuted;
                commands.CommandErrored += SystemEvents.CommandErrored;
                commands.AddProcessors(
                    new SlashCommandProcessor(),
                    new UserCommandProcessor(),
                    new MessageCommandProcessor()
                );
                commands.AddCommands(typeof(LiveBotService).Assembly);
            },
            commandsConfiguration);
```
Leave/Set `RegisterDefaultCommandProcessors` to true and do not register `new TextCommandProcessor()` this will throw on every message sent.

**Comment by akiraveliara** [comment]
i cannot reproduce this with your configuration on the latest nightly build - do you have any other information to share

**Comment by BlackLotusLV** [comment]
Can't reproduce in latest nightly. Seems to be fixed with Nightly 2393
