### ISSUE TITLE
DSharpPlus.Commands not detecting commands that already exist

### ISSUE THREAD

**Issue by Aaron2550** [DSharpPlus/DSharpPlus#2129]
### Summary

Starting the bot with a command like this:
```csharp
[Command("NameHere")]
[SlashCommandTypes(DiscordApplicationCommandType.MessageContextMenu)]
[InteractionInstallType(DiscordApplicationIntegrationType.UserInstall)]
[InteractionAllowedContexts(DiscordInteractionContextType.Guild, DiscordInteractionContextType.PrivateChannel, DiscordInteractionContextType.BotDM)]
public static async Task RunDaCommand(SlashCommandContext context, DiscordMessage message) {
```
works until i restart the bot: "Command `NameHere` was not found.".
Changing the name and reloading the client makes it work again until i restart the bot

### What version of the library are you using?

v5.0.0-nightly (make sure you are using the latest nightly!)

### What .NET version are you using? Make sure to use the latest patch release for your major version.

.NET 9.0.100-rc.1.24452.12

### Operating System

Windows 11 23H2 22631.4317

### Reproduction Steps

- Create command, run bot, CTRL+R client to see the command
- Use command, works
- Restart bot
- Try using the command, does not work
- Stop bot, change command name, start bot and CTRL+R client again
- Use new command, works again

### Trace Logs

Works: https://files.catbox.moe/jrjip7.txt
Doesnt Work: https://files.catbox.moe/9x65pe.txt

### Exceptions or other error messages

Command `<command name here>` was not found.

### Anything else you'd like to share

https://discord.com/channels/379378609942560770/1094835363475886163/1299291904286130238

**Comment by MattJeanes** [comment]
This still seems to be an issue in the latest previews as far as I can tell, 5.0.0-nightly-02426 the bot after some time just stops responding to commands and gives the 'Command `<command>` was not found' error. I can temporarily fix it by restarting the app but it always breaks after a while again.

**Comment by akiraveliara** [comment]
@MattJeanes could you open a new bug report with a trace log of it happening, including as much surrounding context as possible?

**Comment by MattJeanes** [comment]
New issue raised here: https://github.com/DSharpPlus/DSharpPlus/issues/2210
