### ISSUE TITLE
Cannot declare PreCheck for ExecuteGroupAsync

### ISSUE THREAD

**Issue by nick-strohm** [DSharpPlus/DSharpPlus#213]
# Summary
If you set a PreCheck like `Cooldown` for the ExecuteGroupAsync method, it will be completely ignored. If you add the PreCheck to the targeted method it will also be ignored. The only way to get a PreCheck then is to apply it on the class layer. But then you are not able to use other commands that are grouped in the class.

# Details
See Summary

# Steps to reproduce
1. Create a class with `GroupAttribute` that allows invocation without a subcommand.
2. Add a method without a `CommandAttribute` and give it a `CheckBaseAttribute` like `CooldownAttribute` and try to trigger it.
3. Move the `CheckBaseAttribute` to the ExecuteGroupAsync method and try to trigger it.
4. Move the `CheckBaseAttribute` to the class definition and try to trigger it.
5. Add other subcommands with `CommandAttribute` and repeat steps 2-4.

# Notes
//

**Comment by Emzi0767** [comment]
It's by design. That command uses the same checks as the entire group. I'm not sure what would the use for it having separate checks be.

**Comment by nick-strohm** [comment]
For example: I have this class:
https://github.com/Pet-Platoon/PetPlatoon.Godfrey/blob/master/src/Godfrey/Commands/QuoteCommand.cs#L20
I want that you can access any subcommands without any downtime, but the quote command itself should have a specified downtime. Currently im doing this by a pretty dirty way.

My idea would be that you first check on class layer if there are any PreChecks and then on the specific command. If you allow invocation without subcommand you check the ExecuteGroupAsync method for any PreChecks otherwise the specific command

**Comment by Emzi0767** [comment]
That would be a little difficult to do, since any group is treated the same as regular command, and executable group simply has an invokable method attached to it. Method itself is nothing more than a delegate, and thus has no way of attaching additional checks to it.

In theory what you're trying to do can be achieved by doing sudo (as primitive as it is right now, but we'll be updating that - see #176).

**Comment by moonPtr** [comment]
Just run the checks from ExecuteGroupAsync, and if any fail, return silently or throw a ChecksFailedException
A tiny bit dirty, but not a huge deal.

**Comment by nick-strohm** [comment]
I thought about that too. Guess i will do it like that. Thanks

**Comment by moonPtr** [comment]
No prob :p

**Comment by Emzi0767** [comment]
Closed because of inactivity.
