### ISSUE TITLE
Leaving require permissions to blank or .None sets it to require administrator permissions

### ISSUE THREAD

**Issue by BlackLotusLV** [DSharpPlus/DSharpPlus#2136]
### Summary

On latest nightly 2396
For slash commands if you leave required permissions unspecified or set them to `RequirePermissions(DiscordPermissions.None)` it sets it to require Administrator permission. 
![Image](https://github.com/user-attachments/assets/2dafd56d-2220-4f2f-9ceb-cba8e96c6c08)
![Image](https://github.com/user-attachments/assets/4c5a84e2-dadc-427d-9735-3a7c0483612e)

### What version of the library are you using?

v5.0.0-nightly (make sure you are using the latest nightly!)

### What .NET version are you using? Make sure to use the latest patch release for your major version.

.NET 8.0

### Operating System

Win11

### Reproduction Steps

- Use latest nightly
- Create a slash command
- Do not specify permissions
- When viewing integrations, shows the command requires Administrator permission

**Comment by VelvetToroyashi** [comment]
Setting to `.None` is unfortunately expected, [and documented](https://discord.com/developers/docs/interactions/application-commands#application-command-permissions-object-using-default-permissions) - leaving it blank however should probably have at the very least the permission to UseApplicationCommands much like your commit - this should be easy enough to fix if Aki agrees with the above as the default
