### ISSUE TITLE
Command name converts - to _ by default

### ISSUE THREAD

**Issue by BlackLotusLV** [DSharpPlus/DSharpPlus#2139]
### Summary

Creating a command with a name that contains a `-` will forcibly replace it with `_`.
![Image](https://github.com/user-attachments/assets/2ca72ad6-9bd8-4f91-a0d4-e239aa521f59)
![Image](https://github.com/user-attachments/assets/688fca9e-c4e9-4103-8880-79567928f3d4)

### What version of the library are you using?

v5.0.0-nightly (make sure you are using the latest nightly!)

### What .NET version are you using? Make sure to use the latest patch release for your major version.

.NET 8.0

### Reproduction Steps

Create a command that contains `-` in the name

**Comment by akiraveliara** [comment]
this seems like *intended*, albeit maybe not *ideal* behaviour, per https://github.com/DSharpPlus/DSharpPlus/blob/36becd1a8efae922e555f76d656a047a39f90605/DSharpPlus.Commands/Processors/SlashCommands/InteractionNamingPolicies/SnakeCaseNamingPolicy.cs?plain=1

**Comment by BlackLotusLV** [comment]
I would argue that if I explicitly write `-` in the command name, then I want it so and no code should replace it.
