### ISSUE TITLE
Curse of multiple tokens on one bot

### ISSUE THREAD

**Issue by BelgVolish** [DSharpPlus/DSharpPlus#2151]
### Summary

I have a bot using slash commands written in Disnake and a bot using slash commands written in DSharpPlus. When using commands on the bot written in DSharpPlus all commands become unavailable for use. However, they remain in SlashCommandsExtension.RegisteredCommands.

### What version of the library are you using?

v4.4.9 (Stable)

### What .NET version are you using? Make sure to use the latest patch release for your major version.

.NET 8.0

### Operating System

Windows 10 and Ubuntu 24.04.1 LTS x86_64 

### Reproduction Steps

Use slash command in DSharpPlus bot

**Comment by VelvetToroyashi** [comment]
So, generally speaking slash commands aren't *really* designed to be used like this, however the latest nightly builds (V5) do have support for this by virtue of fixing a different issue. Our recommendation would be to update to V5, though there is no support for merging subcommands at this time.
