### ISSUE TITLE
Action overloads for entity mutation methods are missing from RestClient

### ISSUE THREAD

**Issue by uwx** [DSharpPlus/DSharpPlus#228]
# Summary
The REST client has not been updated with Naam's Action stuff. This might be intentional, since that client does not have entities, but I'm not sure.

**Comment by NaamloosDT** [comment]
It's an oversight. Not really a bug. emzi pls

**Comment by Emzi0767** [comment]
Oversight is a bug 🤷‍♂️

**Comment by NaamloosDT** [comment]
Comin up
