### ISSUE TITLE
Events (such as MessageCreated) should propably not be awaited everywhere

### ISSUE THREAD

**Issue by RedworkDE** [DSharpPlus/DSharpPlus#246]
# Summary
If all tasks are are awaited directly after creation, the using async has no advantages over not using it.
Example: If a user writes a long-running message handler that is perfectly async it will still block the message dispatch.

# Steps to reproduce
Minimal Example:
```csharp
var client = new DiscordClient(new DiscordConfiguration()
{
	Token = "...",
	TokenType = TokenType.Bot,
	LogLevel = LogLevel.Debug
});
client.DebugLogger.LogMessageReceived += (object sender, DebugLogMessageEventArgs e) => { Console.WriteLine(e); };
await client.ConnectAsync();
client.MessageCreated += async args =>
{
	if (args.Message.Content == "some command that has some long processing")
	{
		DateTimeOffset start = DateTimeOffset.UtcNow;
		await args.Message.RespondAsync($"command started processing");
		await Task.Delay(TimeSpan.FromMinutes(1));
		var end = DateTimeOffset.UtcNow;
		await args.Message.RespondAsync($"command has been processed ({start:R} - {end:R}, {end-start})");
	}
};
await Task.Delay(Timeout.InfiniteTimeSpan);
```
Expected behavior: multiple commands can be processed concurrently
Actual behavior: multiple commands are processed sequentially 

# Notes
This can be avoided by the user by not awaiting something in the event handler, but i feel like that is something that the library should take care of
This does not affect CommandNext as it creates and discards a task for exactly this purpose (https://github.com/DSharpPlus/DSharpPlus/blob/master/DSharpPlus.CommandsNext/CommandsNextExtension.cs#L213)
I would have created a PR for this myself but i am not exactly sure where the best point to do this is:
1. `AsyncEvent.InvokeAsync` should probably use `Task.WhenAll` instead of awaiting the handlers sequentially but I don't think think the method should complete before the individual handlers
2. `DiscordClient.OnMessageCreateEventAsync` + other methods for the other events
3. `DiscordClient.HandleDispatchAsync`
4. `DiscordClient.HandleSocketMessageAsync`
5. `DiscordClient.SocketOnMessage` 
My personal favorite place to change this would be `DiscordClient.HandleSocketMessageAsync`, but i am not too sure about this (and about if this blocking might even be intentional) so i would like some advice about this before creating a PR for this.

**Comment by uwx** [comment]
This is intentional. _Do not provoke the Emzi._

**Comment by Quahu** [comment]
If you have code that takes a lot of time to complete wrap it in a Task.Run().

**Comment by uwx** [comment]
Yes. The lib could do that automatically, but that would result in non-deterministic behavior, which is why it's not done outside of command invocation.

**Comment by Quahu** [comment]
Yes. Excellent cooperation, as usual.

**Comment by RedworkDE** [comment]
currently my bot runs a manually ThreadPool for handling commands, but i wanted to clean that up a bit and changing this in the library would be a real niche one line change instead of having to having to take care of this everywhere. Also this is so pretty nondeterministic already so that change would not do too much but if that is the sentiment here, looks like i will have to continue using my own build of the library.

**Comment by Emzi0767** [comment]
1. Why aren't you using CNext?
2. Event handlers run sequentially by design. This is to ensure cache consistency and integrity.

**Comment by RedworkDE** [comment]
`Why aren't you using CNext?` I started without using it and now it has some features, mainly a dynamic permission system and an entirely different way of handling arguments so i am not going to switch either.

and if this is intentional i am just going to continue using my own version of this and close this.

**Comment by Tee7even** [comment]
>Event handlers run sequentially by design. This is to ensure cache consistency and integrity.

Excuse me for necroposting, but is this true for all events globally or two events related to different servers/channels can run concurrently?

**Comment by Emzi0767** [comment]
All means all. No exceptions.
________________________________

**Comment by uwx** [comment]
It's per shard.

**Comment by Tee7even** [comment]
>All means all. No exceptions.

Oh I see, thank you.
>It's per shard.

That's fairly obvious.
