### ISSUE TITLE
CooldownAttribute & Overloads

### ISSUE THREAD

**Issue by HurricanKai** [DSharpPlus/DSharpPlus#255]
# Summary
Cooldown Attribute isnt Working as expected together with Overloads

# Details
Based on #Support on Discord, Linux#0715 reported
that he had multiple overloads for a command, and the cooldown was done for all of the overloads together, instead of every single

# Notes
Untested, only based on the #Support Channel, if i have time, i will test this.

**Comment by Emzi0767** [comment]
That is very much the expected behaviour.
