### ISSUE TITLE
CHANNEL_PINS_ACK event is not handled

### ISSUE THREAD

**Issue by uwx** [DSharpPlus/DSharpPlus#256]
# Summary
The `CHANNEL_PINS_ACK` API event is not handled by the library, and will print an `Unknown event` message in the logs.

# Details
Environment:
* Like, any of them
* Yes, this shows up on bot accounts
* Notice my PR senpai

Example message:
```
[2018-03-26 00:29:43 -03:00] [Websocket] [Warning] Unknown event: CHANNEL_PINS_ACK
[2018-03-26 00:29:43 -03:00] [Websocket] [Warning] {
[2018-03-26 00:29:43 -03:00] [Websocket] [Warning]   "timestamp": "2018-03-26T00:29:43.534163-03:00",
[2018-03-26 00:29:43 -03:00] [Websocket] [Warning]   "channel_id": "444444444444444444"
[2018-03-26 00:29:43 -03:00] [Websocket] [Warning] }
```

# Steps to reproduce
1. Add pinned message to channel (outside of bot, preferably)
2. Query the channel's pins
3. You're winner!

Alternative steps:
1. Input the term `CHANNEL_PINS_ACK` into the GitHub search bar
2. Press the return key
3. Stand in awe as you notice the lack of any code mentioning it

**Comment by Emzi0767** [comment]
PRno or wait

**Comment by NaamloosDT** [comment]
You sure that's with bot tokens?

I thought that only happened for user tokens, which is the reason I think I didn't implement it..

**Comment by uwx** [comment]
Yep, bot tokens. Felt really odd to me too. Might be a bug on discord's end, who knows.

**Comment by Emzi0767** [comment]
@uwx was this ever implemented? I seem to vaguely remember something happening around this.

**Comment by uwx** [comment]
I remember getting a similar error recently (on the latest version) but I can't remember if it was `CHANNEL_PINS_ACK` or `PRESENCES_REPLACE`. Right now the code that used to reproduce it in the past is not causing anything to be logged, so either my code isn't valid anymore or it's no longer an issue.

I think we should close this issue and re-open if it pops up again some time in the future, since it's not a major problem.
