### ISSUE TITLE
Unable to load DLL 'libopus'

### ISSUE THREAD

**Issue by ThePieMonster** [DSharpPlus/DSharpPlus#259]
# Summary
Error in console showing libopus.dll is not found after issuing a ``` ;; join ```.

# Details
Using DSharpPlus v3.2.3

Once the bot joins the voice channel the error will be present in the console window. Also upon trying to issue a ``` ;; leave ``` the bot will say that it is not in a voice channel even though it still is.

```
[User tried executing 'join' but it errored: System.DllNotFoundException: Unable to load DLL 'libopus': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```

# Steps to reproduce
1. Download DSharpPlus-Example-04
2. Add the config.json
3. Run the bot
4. Enter ``` ;; join ``` so the bot joins the channel
5. Check the console output

**Comment by Emzi0767** [comment]
This is a failure to follow instructions. Please follow the instructions and try again.
