### ISSUE TITLE
Unable to load DLL 'libopus' Error VoiceNext

### ISSUE THREAD

**Issue by ThePieMonster** [DSharpPlus/DSharpPlus#260]
# Summary
Using the the DSharpPlus [DSPlus.Examples.CSharp.Ex04](https://github.com/DSharpPlus/Example-Bots/tree/master/DSPlus.Examples.CSharp.Ex04) example bot a error is received stating that libopus.dll is not found after bot joins a voice channel.

# Details
Using DSharpPlus v3.2.3
Using .NetCore 2.0.0

Have the bot join a voice channel. The error will be present in the console window. Also upon trying to issue a ``` ;; leave ``` the bot will say that it is not in a voice channel even though it still is.

Full error message:
```
User tried executing 'join' but it errored: System.DllNotFoundException: Unable to load DLL 'libopus': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```

# Steps to reproduce
1. You can use DSPlus.Examples.CSharp.Ex04 or test with your own bot
2. Run the bot
3. Enter ``` ;; join ``` so the bot joins the voice channel you are in
4. Check the console output (you will see the error here)
https://s9.postimg.org/3s3a0fqkf/capture.png
5. Also you issue a ``` ;; leave ``` and see that the bot responds with 

> Not connected in this guild

**Comment by uwx** [comment]
[RTFM](https://dsharpplus.emzi0767.com/articles/vnext_setup.html)

**Comment by ThePieMonster** [comment]
Most useful link I've seen all day. 👍

**Comment by Emzi0767** [comment]
Do not open new issues when previous one is closed. If you have further questions, use the previous issue.
