### ISSUE TITLE
Commands Next: More features.

### ISSUE THREAD

**Issue by nathan130200** [DSharpPlus/DSharpPlus#277]
Some features can be added in D#+ like:

MissingUserPermissionsException when use RequireUserPermissionsAttribute
MissingBotPermissionsException when use RequirePermissionsAttribute
FriendlyException when bot need warn that command aren't executed because some reason (without biggest stacktrace).

Can possible allow execute some command in DM but deny others?

**Comment by Emzi0767** [comment]
It's not really a good idea to create per-check exceptions just like that because it turns into a maintenance nightmare very quickly. As C# does not support generic attributes, it's not possible to do in any clean manner.

**Comment by SubstituteCS** [comment]
@Emzi0767 Could something like this be used then?

```cs
    public class GenericException : Exception
    { }

    public class SpecificException : GenericException
    { }

    public abstract class GenericAttribute
    {
        protected virtual bool Throws => false;
        protected virtual Type TypeToThrow => typeof(GenericException);
        internal void Throw()
        {
            if (Throws)
            {
                GenericException Exception = (GenericException)Activator.CreateInstance(TypeToThrow);
                throw Exception;
            }
        }
        public abstract bool Check();
    }


    class SpecificAttribute : GenericAttribute
    {
        protected override Type TypeToThrow => typeof(SpecificException);
        protected override bool Throws => true;
        public override bool Check()
        {
            int a = 1;
            int b = 0;
            return (a == b);
        }
    }

    public class ThisClassWouldBeTheClassWhereCNextChecksAttributes
    {
        //Filler Data
        GenericAttribute[] Attributes = new GenericAttribute[] { new SpecificAttribute { } };
        public void ThisMethodIsWhereCNextIsCheckingAttributes()
        {
            foreach (GenericAttribute Attrib in Attributes)
            {
                if (!Attrib.Check())
                {
                    Attrib.Throw();
                }
            }
        }
    }
```

Usage would be overriding ``TypeToThrow `` and ``Throws ``.  ``GenericException`` would be a DSP exception.
![example](https://user-images.githubusercontent.com/6234332/39090639-a1615afc-45b2-11e8-803e-4f31a5b77ef5.png)
I've attached an example where an Exception is raised, as you can see the real type of the Exception is the ``SpecificException``, while from a maintainer perspective, the only class that *really* matters is ``GenericException``.

**Comment by HurricanKai** [comment]
Instead of bothering with overwriting a class, we coud have a `CommandCheckAttribute`
it woud work like this:
`
[CommandCheck(lambda = (context => context.User.Role.Any(r => r.hasPermission(Permissions.Administator)))] //context coud be a Command Context, or simmilar
Your Command Here
`
else, if this check woud be used a lot, it coud even be registered:
`
_cnext.RegisterCheck("RequireAdmin", context => context.User.Role.Any(r => r.hasPermission(Permissions.Administator))]
`

and later be called:
`
[CommandCheck(Check = "RequireAdmin")]
Your Command Here
`

internally, it woud just check if lamda is not null, and either call that, or, lookup the Check.
for more Optimization, a registered lamda coud be, (by an optional bool in the function) baked.

**Comment by Emzi0767** [comment]
@SubstituteCS not really, this would still require validation logic at runtime etc.

@HurricanKai functions and lambdas (and delegates overall) are not compile-time constants.

**Comment by nathan130200** [comment]
I'm current using a custom permission attribute based on original D#+ attribute.

**Comment by nathan130200** [comment]
Only if uses a Predicate<T> inside a command?

`[CommandPredicate((ctx) => ctx.User.Id == 0)]`

**Comment by Emzi0767** [comment]
Predicate is a lambda, and lambda is a delegate, so this is still not possible.

**Comment by nathan130200** [comment]
Another thing, i have command_executed event that fire an exception, but D#+ debug logger don't show who exception, just "An <exception type> ocurred."

add in DiscordConfiguration:

bool ThrowExceptions, and where true, D#+ will throw any exception.

**Comment by HurricanKai** [comment]
but strings are, so my Baked version woud work... thats prob. why ASP.net solves this this way too
but possibly CNext coud have an option to have an "DoThings, or pass" function.
To explain:
before each command an function is called (overwritable from BaseCommandModule)
then, based on a string or something like that, the developer coud figure the Command out, (Cleaner Solution?)
and use this to then either:
`return Error("Some Error occured sorry")`, (Error  = Predefined in BaseCommandModule), which woud throw into the CommandException event, but not throw in generall.
`return Command()`, (=> Just have CNext pass the rest of shit)
`return Command("SomeOtherCommand")` (=> Have CNext figure out that command)
`return Command(/*Same for both before options*/, Type1, Object2, ......)` (=> same functionality as before, but also have CNext try mapping those to the Command Inputs, prefering those over the user inputs)

**Comment by NaamloosDT** [comment]
Why not just make your own attributes and register those? It's not as hard as it seems..

**Comment by nathan130200** [comment]
@NaamloosDT is good idea use commands translations per user, per guild or both?

**Comment by HurricanKai** [comment]
@NaamloosDT well, at least it shoud be allowed to throw an exception in the Before Command thingi, i know thats not what its ment to do, but creating 1000 Attributes is kinda, shitty (no offense too ;))

**Comment by nathan130200** [comment]
@NaamloosDT  Why AggregateException don't throw? Just appear in debug logger `An AggregateException ocurred in <event> ` and don't have details.

**Comment by Emzi0767** [comment]
Because this means an exception occurred within your event handler. Furthermore if this propagated to the top any exception would crash your bot.

**Comment by nathan130200** [comment]
Another thing for D#+ 4.0 allow interactivity use custom paginated emotes (and use default emojis where bot don't have permissions to use external emotes)

**Comment by Emzi0767** [comment]
Closed because of inactivity.
