### ISSUE TITLE
Do not defame me, part 2

### ISSUE THREAD

**Issue by TheLastTech** [DSharpPlus/DSharpPlus#283]
You guys should really review your own words before you accuse me of anything. I was nothing but nice and cordial before someone started his verbal abuse. I reached out to the other guy on the team and he continued the verbal abuse started by someone.

I did nothing but contribute a fix for a bug you probably wouldn't see otherwise. 

Then again, looking at the quality of your code I can see why you do not understand what happened and only see it in delusional ways.

**Comment by NaamloosDT** [comment]
I'm blocking you from the repo
