### ISSUE TITLE
Couldn't send embed with image

### ISSUE THREAD

**Issue by TheChilliPL** [DSharpPlus/DSharpPlus#284]
# Summary
When I try to send embed with image url, image's not visible (unline the same command with the same urls in Discord.js)

# Details
.NET 4.6.1
Windows 10
Custom message handler, but that's got nothing to do - I'm building embed and sending message using Message.RespondAsync() and DiscordEmbedBuilder

# Steps to reproduce
Execute following code on command/on message
```
cp.Message.RespondAsync(embed: new DiscordEmbedBuilder
{
    Title = "Some title",
    Description = "Some description",
    ImageUrl = "https://media2.giphy.com/media/RTvLtYTwR3w2c/giphy.gif" //or some other random image url
});
```

# Notes
I tried making embed without title and description (embed was empty) or with normal message content (still nothing)
I tested and URL is valid - also tried replacing https with http still with no success.
I searched through Google but there are no image sending tutorials that could help me diagnose the problem.

**Comment by Emzi0767** [comment]
Are you on 3.2 or 4.0 nightlies?

**Comment by TheChilliPL** [comment]
I have 3.2.3 stable

(How to install 4.0 through nuget?)

**Comment by Emzi0767** [comment]
4.0 is on myget. The instructions are in the channel and in the docs.

That said this shouldn't be a 3.2 issue.

**Comment by TheChilliPL** [comment]
Updated to 4.0 and still nothing...

**Comment by Emzi0767** [comment]
I'll investigate in a spare moment.

**Comment by Emzi0767** [comment]
I checked the link. It opens a website rather than displaying an image. This is most likely why it doesn't embed.

Actual image URL: https://i.giphy.com/media/RTvLtYTwR3w2c/giphy.gif

Your image URL: https://media2.giphy.com/media/RTvLtYTwR3w2c/giphy.gif

You should inspect the payload to see if there's something that resembles the first URL in it.

**Comment by TheChilliPL** [comment]
Strange - that worked on Discord.js, Giphy API doesn't send me that i.giphy.com address

**Comment by Emzi0767** [comment]
Interesting. Still, you should be able to replace the hostname manually using UriBuilder

**Comment by TheChilliPL** [comment]
That's 99% DSP's fault - I made a command so my bot responds with image from given URL

I passed `https://i.giphy.com/13gvXfEVlxQjDO.gif` and... It's not working...

**Comment by Emzi0767** [comment]
![Tested, works on 4.0](https://awau.moe/a00c95.png)

**Comment by TheChilliPL** [comment]
Is `.Build()` needed?

**Comment by Emzi0767** [comment]
In 3.2 no, in 4.0 yes.

**Comment by TheChilliPL** [comment]
Why though?

**Comment by TheChilliPL** [comment]
Compiler throws nothing.

**Comment by uwx** [comment]
Emzi works in mysterious ways

**Comment by TheChilliPL** [comment]
Is there a way to send an image as an attachment (but using URL, not file) and not embed?

**Comment by NaamloosDT** [comment]
no clue what you're going for rn

**Comment by TheChilliPL** [comment]
Well, it turned out that only I can't see it so this issue can be closed now (I'm using SendFileAsync with Stream for images now)
