### ISSUE TITLE
Issue with GuildRoleUpdated - (RoleBefore)

### ISSUE THREAD

**Issue by Kiritsu** [DSharpPlus/DSharpPlus#287]
# Summary
When you edit a role, the event `GuildRoleUpdated` will fire with its `GuildRoleUpdatedEventArgs` object which contains `RoleBefore` and `RoleAfter`. 

It looks like `RoleBefore` sometimes contains wrong informations. Admitting my role has `Mentionable` set to `false`, if I edit the role, `RoleBefore.Mentionable` will be `true` and `RoleAfter.Mentionable` will be `false`. 

Check the tree screenshots:
https://prnt.sc/jiomcc 
https://prnt.sc/jiomhn
https://prnt.sc/jiommx

1. Showing the role (not edited)
2. Showing changes (name property, from `Bot` to `Test2`)
3. Showing my bot telling me `Mentionable` property went from `true` to `false`

# Details
* .NET Core 2.0
* Windows 10
* DSharpPlus version: 4.0.0-beta-00450
* Visual Studio 2017

# Steps to reproduce
1. Subscribe to the GuildRoleUpdated event
2. Modify a role's name
3. Take a look at `GuildRoleUpdatedEventArgs.RoleBefore` and `GuildRoleUpdatedEventArgs.RoleAfter` and check the `Mentionable` boolean. You didn't made any change of this value but it's not the same in the two objects.

**Comment by uwx** [comment]
#288 should fix this.
