### ISSUE TITLE
DiscordChannelConverter throws NullReferenceException in DM on nightly build

### ISSUE THREAD

**Issue by 13xforever** [DSharpPlus/DSharpPlus#310]
# Summary
A `NullReferenceException` occurs when trying to resolve discord channel from a command invoked through DM when using DSharpPlus 4.0.0-beta-00467.

# Details
The issue is that `DiscordChannelConverter` ([EntityConverters.cs:129](https://github.com/DSharpPlus/DSharpPlus/blob/6c857eea53f6b08ad9aa340aca0879a67fae534c/DSharpPlus.CommandsNext/Converters/EntityConverters.cs#L129) and [138](https://github.com/DSharpPlus/DSharpPlus/blob/6c857eea53f6b08ad9aa340aca0879a67fae534c/DSharpPlus.CommandsNext/Converters/EntityConverters.cs#L138)) uses `ctx.Guild.Channels`, and `ctx.Guild` in DM context is `null`.
In this case `ctx.Client.Guilds` should be used, maybe?

# Steps to reproduce
1. create a command that tries to convert an argument to `DiscordChannel` using `DiscordChannelConverter`
2. invoke the command through dm

# Notes
This scenario worked in v3.2.3, but I haven't looked into the details of implementation differences.
Also as a result the command overload that is defined to receive `DiscordChannel` as an argument is not invoked.

**Comment by Emzi0767** [comment]
I'll flag this as a bug, but put it on hold for the time being. It's possible this was changed intentionally (lookups are much faster), however I can look into reverting it to become global behaviour.

**Comment by 13xforever** [comment]
What I meant is that you can lookup the guilds only if `ctx` doesn't have one already.
And aren't bot's guilds cached anyway?
I'll do a custom converter in the mean time, so no pressure.

**Comment by Emzi0767** [comment]
What I mean is that in 3.2.3 the converters were synchronous, and performing a global channel lookup is asynchronous. Mixing the two is a bad idea. So I decided to make it a guild-specific lookup for 2 reasons:
1. Querying a single (small) collection is fast.
2. We no longer have to mix async and non-async.

In 4.0 the converters became asynchronous to facilitate a number of new features we're planning on introducing, as well as to facilitate the requirement for async in certain built-in converters. Querying multiple collections is just much more expensive.

That said, I see where you're coming from, and this is certainly a valid use case. I'll consider it.
