### ISSUE TITLE
CheckBaseAttribute is not being checked on GroupCommand call

### ISSUE THREAD

**Issue by 13xforever** [DSharpPlus/DSharpPlus#311]
# Summary
If I add attribute to check permissions using any descendant of `CheckBaseAttribute` to a method that is marked as `GroupCommand`, it won't be checked.

# Details
I am using DSharpPlus 4.0.0-beta-00467, and just noticed that you can't use permission check attributes on a group command. The check is simply not being called: not during help, nor during actual invocation.
Adding the attribute to the group class or any subcommand method works as expected.

```csharp
    [Group("warn")]
    internal sealed class Warnings: BaseCommandModule
    {
        [GroupCommand, RequiresBotModRole] // doesn't work
        public async Task Warn(CommandContext ctx, DiscordUser user, [RemainingText] string reason) {}
    }
```

# Steps to reproduce
1. Create a group class
2. Create a method and mark it as a `GroupCommand`
3. Verify that the `ExecuteCheckAsync()` is not being called on command invocation

# Notes
This is a bummer, as I want to allow regular users to use only a subset of group subcommands, excluding the group-as-a-command invocation.

**Comment by uwx** [comment]
The current functionality is that the checks must be placed on the module type (Group) rather than the group command, however this doesn't seem like a bad feature request (although a little odd), cc @Emzi0767

**Comment by 13xforever** [comment]
If I place it on the group, this will prevent users to use any subcommand from it

**Comment by Emzi0767** [comment]
This is by design. Group commands are treated as overloads, but unlike regular overloads, every attribute applied to them is discarded. The reason is that in this case it's not the method that is the command, it's the group, so any attributes applied to the group command would be applied to the group anyway. There's no per-overload permission system.
