### ISSUE TITLE
Request: Ability to hide some command overloads from help

### ISSUE THREAD

**Issue by 13xforever** [DSharpPlus/DSharpPlus#312]
# Summary
It would be helpful to be able to hide all advanced overloads of a command, and only show the suggested forms of command invocation.

# Details
Currently in DSharpPlus 4.0.0-beta-00467 you can either hide the command altogether by placing `Hidden` attribute on first overload, or show all forms of invocation, no matter if they have this attribute.

It would be useful to check if command has overloads and only hide the marked ones from help, and hide the command completely if all of the forms are marked as `Hidden`.

# Steps to reproduce
1. Create a command overload
2. Mark second overload as `Hidden` 
3. Verify that it has no effect on help

# Notes
I can see how this complicates the code, but I think behavior should be consistent.

**Comment by uwx** [comment]
Attributes for command overloads are merged. This is intentional, not an oversight. If you really want to do whatever you're trying to do, it can be done with a custom help formatter.

**Comment by Emzi0767** [comment]
What @uwx said. Command overloads are treated as little more than delegates. Everything placed on overloads is pooled. A help formatter might be able to help here.
