### ISSUE TITLE
DiscordMessage.Timestamp throws NullReferenceException

### ISSUE THREAD

**Issue by 13xforever** [DSharpPlus/DSharpPlus#314]
# Summary
If you try to access `Timestamp` property of a message that is not in the client's cache, it will throw `NullReferenceException`.

# Details
I am using DSharpPlus 4.0.0-beta-00469, and noticed this in the handler that tries to moderate the reaction usage.
I think this property should be nullable and return `null` in case there's not data about the creation timestamp available, it will allow to handle this situation gracefully instead of wrapping everything in `try{} catch{}`.

`EditedTimestamp` and `MentionedUsers` have similar issues in that they throw if the message wasn't edited / doesn't contain mentions.

```
System.ArgumentNullException: Value cannot be null.
Parameter name: input
   at DSharpPlus.Entities.DiscordMessage.get_Timestamp()
   at CompatBot.EventHandlers.Starbucks.Handler(MessageReactionAddEventArgs args) in F:\Work\git\discord-bot-net\CompatBot\EventHandlers\Starbucks.cs:line 29
```

# Steps to reproduce
1. create a handler that can receive information about old messages
2. try to access `Timestamp` property of the message
3. cry, I guess

# Notes
As a workaround you can use `.CreationTimestamp` property or manually fetch the complete message information

**Comment by Emzi0767** [comment]
...wait why are there 2?

I'll look into it.

**Comment by 13xforever** [comment]
`Timestamp` in discord model is an ISO text date, and returns date in current time zone
`CreationTimestamp` retrieves data from the snowflake of an object and returns time in utc

**Comment by Emzi0767** [comment]
So just a question, how do you obtain a message that is *not* in the client's cache? The only ways of obtaining messages that bypass cache that come to mind fetch the full object.

**Comment by 13xforever** [comment]
The way I stumbeld upon it, is I have a handler for new reactions, and then someone reacted to something old.
