### ISSUE TITLE
guild.GetAuditLogsAsync(1) throws ArgumentException

### ISSUE THREAD

**Issue by Kriste00** [DSharpPlus/DSharpPlus#318]
# Summary
`ArgumentException` when using `guild.GetAuditLogsAsync(1)` in `client.MessageDeleted`.

# Details
This exception is thrown every time the bot deletes one of it's own messages. (Not tested with a user's message)

Exception:
`
Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll
An item with the same key has already been added. Key: 277498522285244427
`

The key is a User-Id so, I suspect the exception is thrown from:
https://github.com/DSharpPlus/DSharpPlus/blob/5bb49222193991b5f05e366ada929670df4da3e5/DSharpPlus/Entities/DiscordGuild.cs#L679

# Steps to reproduce
1. Hook `client.MessageDeleted`
2. have `e.guild.GetAuditLogsAsync(1)` in the event
3. Make the bot delete a message.
4. `ArgumentException` is thrown.

**Comment by Emzi0767** [comment]
Yeah Discord sends duplicate members sometimes, though I didn't think it'd manifest like this.

I want to forget that audit logs exist. I'll likely have it fixed later.
