### ISSUE TITLE
LavalinkNodeConnection is cached before a successful connection is made

### ISSUE THREAD

**Issue by Kriste00** [DSharpPlus/DSharpPlus#321]
# Summary
The `LavaLinkExtention` will cache a `LavalinkNodeConnection` even if the connection to the socket was not successful.

# Details
Example:
Line 53: The connection is not cached.
Line 59: The connection gets put into the cache.
Line 60: The connection fails (Network issue, ect)

Bug: The connection is still in the cache and will be returned on the next `ConnectAsync` call.

https://github.com/DSharpPlus/DSharpPlus/blob/f0737fa39aab6b99e5b94699a340dbbef8d262ea/DSharpPlus.Lavalink/LavalinkExtension.cs#L53-L62

**Comment by uwx** [comment]
wouldn't `Con_NodeDisconnected` be invoked in that case, removing it from the cache?

**Comment by Kriste00** [comment]
In my testing the connection is still there and returns it, event tho there is not lavalink socket running.

**Comment by uwx** [comment]
Do you get `Connection closed` or `Lavalink died` on your console when the connection fails? It should remove it from the cache right before `LavalinkNodeConnection.Disconnected` fires.

**Comment by Kriste00** [comment]
The way i got the bug was:
1. Connect to lavalink.
2. Kill lavalink
3. Try to connect 2 times in a row, after the first attempt throws WebSocketException
4. bug happens

**Comment by Kriste00** [comment]
`NodeDisconnected` will not be fired because the connection was never made. Cannot disconnect from something that was never connected.

**Comment by uwx** [comment]
Is the exception thrown by ConnectAsync, or in LavalinkSocketErrored? I think I know what's causing this issue.

**Comment by Kriste00** [comment]
By `ConnectAsync`
