### ISSUE TITLE
3.2.3 DiscordActivity not found in DSharpPlus.Entities

### ISSUE THREAD

**Issue by homebrewhops** [DSharpPlus/DSharpPlus#324]
In 3.2.3 DSharpPlus.dll my visual studio 2017 can't find the DiscordActivity class in DSharpPlus.Entities.

I'm expecting this:
https://dsharpplus.github.io/api/DSharpPlus.Entities.DiscordActivity.html

However this is what my IDE shows when using Intellisense:
https://imgur.com/a/644Zs19

I've saved and closed and re-opened my project. Am I missing something? I have using DSharpPlus.Entities; already and have worked with other classes in this namespace just fine.

Any help would be appreciated.

**Comment by Emzi0767** [comment]
Don't mind the above stuff I'm dumb 

Yes, as was pointed out, you should be using 3.2 docs with 3.2.

**Comment by homebrewhops** [comment]
Thank you. I found what I was looking for in the 3.2.3 documentation:

https://dsharpplus.emzi0767.com/api/DSharpPlus.Entities.Game.html

However, to bring to your attention that the documentation says the class is Game, but actually resolves to DiscordGame.
