### ISSUE TITLE
Lavalink gets muted

### ISSUE THREAD

**Issue by Kriste00** [DSharpPlus/DSharpPlus#330]
# Summary
Lavalink will not send any audio (still able to join/leave channels). Lavalink still spits out `[AudioLoader] Loaded playlist Search results for: song`, so the problem is not the connection. My guess is that the problem has something to do with `SessionID` or `VoiceToken`.

Btw this happens on every guild (LavalinkGuildConnection), so leave/rejoin or try on another server does not fix the issue.

# Steps to reproduce
Idk really, just use LavaLink and have a public bot running for 1-2 days. 
Then the issue will occur.

**Comment by Kriste00** [comment]
Or it could be an issue with LavaLink/Player, but i hope not.

**Comment by uwx** [comment]
Likely is the TrackStuck event which is an "intended" feature of Lavalink that I have no idea how to "implement" properly (presumably you should capture it then reconnect?)

**Comment by Kriste00** [comment]
But, the issue happens with the entire LavalinkNodeConnection. It would ne wired if one track gets stuck and then music does not work in any guilds at all.

**Comment by Kriste00** [comment]
I've looked at some LavaLink implementations and both Eris-Lavalink and Discord.js stops the player before invoking the event.
![image](https://user-images.githubusercontent.com/32580874/43557575-88899a32-9605-11e8-919c-f63fc38e5822.png)
https://github.com/briantanner/eris-lavalink/blob/89a15e5fcc9cce171bb47c9f1797f66b2071a2a6/src/Player.js#L274-L277

**Comment by Emzi0767** [comment]
I've experienced that as well, I was hoping someone would too.

I'll need to take a look when I've got 5 minutes.

**Comment by Kriste00** [comment]
Yea, i think its the websocket as well, since no JSON-Messages are displayed in the LavaLink command window.

**Comment by Emzi0767** [comment]
So ironically enough when I started trying to debug the issue, it stopped happening across all of my bots. I have no idea why.

Allan from D#+ guild pointed out that his lavalink instance showed an EOF from websocket, and he had issues with multiple guilds (although I am not completely sure why).

If anyone has any more information, such as Lavalink logs, D#+ log, bot uptimes, operating system, other environment information, please provide it.

Furthermore, if you hold your own Lavalink node connection objects and are able to reflect into it at runtime, please reflect into the internal WebSocket. You can do so using the following code:
```cs
using System.Collections.Concurrent;
using System.Net.WebSockets;
using System.Reflection;
using DSharpPlus.Net.Udp;
using DSharpPlus.Net.WebSocket;
using DSharpPlus.Lavalink;

var node = yourNodeConnectionObject;

var isConnected = node.IsConnected;
var socket = node.GetType().GetProperty("WebSocket", BindingFlags.NonPublic | BindingFlags.Instance).GetValue(node) as WebSocketClient;
var ws = socket.GetType().GetProperty("Socket", BindingFlags.NonPublic | BindingFlags.Instance).GetValue(socket) as ClientWebSocket;

return $"{isConnected} | {ws.State} | {ws.CloseStatus}";
```
`yourNodeConnectionObject` is the `LavalinkNodeConnection` instance

**Comment by Emzi0767** [comment]
As an addendum to the above, if you're using eu-central or us-east voice regions, try swapping to eu-west and us-central respectively to see if that helps anything.

**Comment by Emzi0767** [comment]
This issue is apparently caused by Discord's EU voice regions being broken. There's nothing I can do about this, much as I'd like to.
