### ISSUE TITLE
Suggestion/Commands Next: If no service provider create empty one.

### ISSUE THREAD

**Issue by nathan130200** [DSharpPlus/DSharpPlus#331]
When i created empty bot with commands next, i don't set ServiceProvider in CommandsNextConfiguration and i receive ArgumentNullException in CommandErrored:

![screenshot_2](https://user-images.githubusercontent.com/14365254/43642182-e96937e8-96fc-11e8-9b17-2423b8e58f29.png)

I recommend when if no set ServiceProvider, create a empty one in commands next configuration.

(Isn't a real problem, just a tip/suggestion for cnext)

NOTE: Sorry for bad english (i speak portuguese and say english without a translator)

**Comment by xSleepy** [comment]
Well you should use DI with CNext.

**Comment by nathan130200** [comment]
I know, is is just a suggestion to cnext internal create empty provider if no service provider has set.

**Comment by Emzi0767** [comment]
'll be fixed.

**Comment by Emzi0767** [comment]
Fixed by e0ced89.
