### ISSUE TITLE
Feature request - Add ability to connect to discord with a specified status

### ISSUE THREAD

**Issue by Kriste00** [DSharpPlus/DSharpPlus#332]
# Summary
Have an optional argument on `DiscordClient.ConnectAsync` of type `UserStatus`. Then that suatus will be used as the initial UserStatus.

**Comment by NaamloosDT** [comment]
Comin up

**Comment by NaamloosDT** [comment]
Added in 22c658f9e0440ab42638ed9d86621b8a37568f40
