### ISSUE TITLE
DiscordGuild.Channels is empty in DiscordClient.Ready

### ISSUE THREAD

**Issue by 13xforever** [DSharpPlus/DSharpPlus#343]
# Summary
If you try to check channel list in guilds inside `client.Ready()` event, you'll get an empty list. Even if you do manual guild resolution with `client.GetGuildAsync()`, you still get empty channel list (presumably because it returns the cached version, which has no channels).
Everything works fine if you check the list in one of the later event handlers (like `.MessageCreated`, etc).

# Details
Using the latest nightly build **4.0.0-beta-00508**

# Steps to reproduce
```csharp
using (var client = new DiscordClient(config))
{
  client.Ready += async r =>
  {
    Console.WriteLine(r.Client.Guilds.First().Value.Channels.Count);
  }
}
```

**Comment by Kiritsu** [comment]
Ready doesn't mean Guilds are downloaded yet, thats why Channels property is empty at this moment.

**Comment by 13xforever** [comment]
Hmm, this is not obvious, maybe you should throw some descriptive exception then?

**Comment by Kiritsu** [comment]
According to Discord's API documentation, https://discordapp.com/developers/docs/topics/gateway#ready

It says guilds are still unavailable at this moment. The lib is just following this. As my personal opinion, I hate handling things that can throws at any time.

**Comment by Emzi0767** [comment]
If you want to query channels on startup, use the `DiscordClient#GuildDownloadCompleted` event.

**Comment by 13xforever** [comment]
I am using `GuildAvailable` now to catch up on new messages.
You can close this issue if you think that no changes are necessary, but I'd still like some indication of improper client/api usage.

**Comment by Emzi0767** [comment]
It's hard to indicate improper when with this API it's sometimes hard to define proper. I'll close this for now, you can reopen or ask further questions in the D#+ guild.
