### ISSUE TITLE
Command with ulong[] argument is not being invoked

### ISSUE THREAD

**Issue by 13xforever** [DSharpPlus/DSharpPlus#344]
# Summary
If you try to create a command with `ulong[]` argument, it won't be called.
Commands with `ulong` argument work correctly.

# Details
Using DSharpPlus and CommandsNext **4.0.0-beta-00508**.
Trying to invoke the command simply ignores it. This is even more confusing if you have an overload, as it would never be called.

```csharp
[Command("test1")]
public async Task Test1(CommandContext ctx, ulong guildId)
{
  await ctx.RespondAsync("command with the single ulong argument: " + guildId).ConfigureAwait(false);
}

[Command("test2")]
public async Task Test2(CommandContext ctx, ulong[] guildIds)
{
  await ctx.RespondAsync("command with the ulong[] array argument: " + guildIds.Length).ConfigureAwait(false);
}
```

# Steps to reproduce
1. Have a command with `ulong[]` argument
2. Try to invoke it

**Comment by Kiritsu** [comment]
You must use `params ulong[] guildIds`

**Comment by 13xforever** [comment]
Sigh, I swear I can read documentation
