### ISSUE TITLE
Question: How to property use DI with CommandNext?

### ISSUE THREAD

**Issue by Tillman32** [DSharpPlus/DSharpPlus#348]
# Summary
Unable to get CommandsNext to inject my commands dependencies.

# Details
I'm trying to use dependency injection (specifically the built in .Net Core "Constructor Injection") within a command class. I don't see the provided examples using any injected dependencies. However I did find one in your .Test project on **line 73 and 90** that appears to be out of date: https://github.com/DSharpPlus/DSharpPlus/blob/master/DSharpPlus.Test/TestBot.cs

Looking at the line 73, a ServiceCollection() is created and passed into CommandsNextConfiguration on line 90. I cannot get this example to work in my code - it can't convert from 'ServiceProvider' to 'DependencyCollection' - Oh and 'Services' appears to be 'Dependencies' now.

Example snippet:
``` csharp
var deps = new ServiceCollection()
    .AddScoped<KarmaService>();

_botCommands = _discord.UseCommandsNext(new CommandsNextConfiguration
{
    StringPrefix = _botSettings.Prefix,
    Dependencies = deps.BuildServiceProvider(true)
});
```

I then tried using the provided 'DependencyCollectionBuilder()' and adding my service using its 'Add()' method. With the following error:

> System.InvalidOperationException: 'No dependencies matched the criteria.'

Example snippet:
``` csharp
var deps = new DependencyCollectionBuilder()
    .Add<KarmaService>();

_botCommands = _discord.UseCommandsNext(new CommandsNextConfiguration
{
    StringPrefix = _botSettings.Prefix,
    Dependencies = deps.Build()
});
```

Ideally, I'd like to be able to use the ServiceCollection already created within my Startup class. 

How is dependency injection supposed to work within CommandsNext 'RegisterCommands<T>()'?

# Notes
I'm using a .Net Core 2.1 console application.

**Comment by Kiritsu** [comment]
That's because the test bot is for nightly versions. Check the example bots and/or documentation to see how it works!

**Comment by Tillman32** [comment]
@Kiritsu Thank you! I've definitely checked out the docs, it just doesn't work on my version and that's the confusion. 

I typically use Nuget and just grabbed the latest. I'll poke around and see how to get the nightly into my project.

**Comment by Emzi0767** [comment]
You're using 4.x docs with 3.x.

**Comment by Tillman32** [comment]
@Kiritsu Thanks much! I appreciate it. 

@Emzi0767 It's not apparent which version the docs are for, on the documentation website or the docs in the repo. Am I missing something?

**Comment by Giggitybyte** [comment]
https://dsharpplus.emzi0767.com/ is for 3.x
https://dsharpplus.github.io/ is for 4.x

**Comment by Tillman32** [comment]
@Giggitybyte Thank you!
