### ISSUE TITLE
Ability to choose what pagnation buttons to display

### ISSUE THREAD

**Issue by Lachee** [DSharpPlus/DSharpPlus#364]
# Summary
Allow users to choose which sets of buttons to display when sending a paginated button (not the emojis as that is already possible). 

# Details
It would be nice to be able to optionally tell the interactivity to exclude some pagnation buttons to keep styling or simplicity. One may even want to ignore all the pagnation buttons all together and manually move through the pages. 

I first thought making the emojis nullable would be a decent idea without creating new parameters, but that is unclear and unobvious. So instead I propose adding a extra flag at the end. The flag could look like this:
```cs 
    [Flags]
    public enum PaginationControlStyle
    {
        None = 0,
        MoveToNext = 1,
        SkipToEnd = 2,
        Stop = 4
    }
```

It can be placed at the end of the SendPagnatedMessage as a optional field, with the default being `MoveToNext | SkipToEnd | Stop` which is how it currently behalves. Example usage may look like this:

`SendPaginatedMessage(ctx.User, pages, controlStyle = PaginationControlStyle.MoveToNext | PaginationControlStyle.Stop);`

`SendPaginatedMessage(ctx.User, pages, controlStyle = PaginationControlStyle.None);`

Obviously the later should return a PaginatedMessage object of sorts (potential improvement for rewrite?) so one could manually call `message.NextPage()` on a timer or something.

**Comment by uwx** [comment]
It would be cool (and quite simple) if setting the emotes to null would cause them to not be added. My interactivity fork (unreleased) can already do this :^)

**Comment by Lachee** [comment]
Setting the emojis to null is one way to do this, but I think its better to just add a completely separate flag. That way you do not have to null check everything while you are implementing this feature and it creates a distinct correlation between what the parameter does and what to expect when you change it. 

Having it as making the emojis being null trigger it may add some confusion and could be difficult to document.

**Comment by NaamloosDT** [comment]
I _think_ this one is ready to be closed. Tell me what you think @Lachee 
https://github.com/DSharpPlus/DSharpPlus/blob/master/DSharpPlus.Interactivity/EventHandling/Requests/PaginationRequest.cs#L193-L209

**Comment by NaamloosDT** [comment]
adding to that: These can be set to null to disable them.

**Comment by NaamloosDT** [comment]
+ the interactivity config contains defaults

**Comment by Lachee** [comment]
Excellent! Thank you very much.
