### ISSUE TITLE
 Despite being connected to the Guild and getting data from it, the bot doesn't respond anymore to CommandControllers and MessageCreated

### ISSUE THREAD

**Issue by LuckyScamper** [DSharpPlus/DSharpPlus#368]
# Summary
Bot purpose: work in a large gaming group to handle data about the group during gameplay. (the game in question encourages proper maintenance of data, which is done via SQLite.)

Note: my bot comes online and is able to get data from the Guild (e.g. GetAllMembersAsync) without any problems. The Token I'm using in Configuration is correct. The bot is listed as ''online'' in the server with the activity as set below.

# Details
targetframework .NET framework 4.7.1 (.NET Core 2.1 gives the same result)

install the latest 4.0.0 nightlybuild myget packages

# Steps to reproduce
1. Put it in a server and write a message.

```
    using (discord = new DiscordClient(new DiscordConfiguration
     {
         Token = Configuration.TOKEN,
         TokenType = TokenType.Bot
     }))
     {
         discord.MessageCreated += EasterEggsHelper.Discord_MessageCreated;
         commands = discord.UseCommandsNext(new CommandsNextConfiguration
         {
             StringPrefixes = Configuration.PREFIXES,
             EnableDms = false
         });

         // Start listening to commands from the controllers.
         commands.RegisterCommands<UserController>();
         commands.RegisterCommands<WikiController>();
         commands.RegisterCommands<MusicController>();

         interactivity = discord.UseInteractivity(new InteractivityConfiguration
         {
             Timeout = new TimeSpan(24, 0, 0),
             PaginationTimeout = new TimeSpan(24, 0, 0)
         });

         // Connect to the servers
         await discord.ConnectAsync(new DiscordActivity("You", ActivityType.Watching));

         // Start background Tasks in separate threads.
         BackgroundHelper.Client = discord;
         discord.Ready += BackgroundHelper.Discord_Ready;

         Console.WriteLine($"{Configuration.BOT_NAME} online. Listening to commands...");
         await Task.Delay(-1);
     }

     Console.WriteLine($"{Configuration.BOT_NAME} shutting down. Have a nice day.");
```

# Notes

No responses. I've put breakpoints on all controller classes functions and the event handler for general messages.

**Comment by Emzi0767** [comment]
What exactly are you doing? Using interactivity in event handlers directly? If that is the case, you're deadlocking the thread.

**Comment by LuckyScamper** [comment]
No. As per your suggestion, I've commented out all interactivity code, and that didn't alter results. I've also tried commenting out the registration of the controllercommands and messagecreated event respectively, also no result.

**Comment by Emzi0767** [comment]
Also why are you `using` your client instance, but then holding the block indefinitely? There's absolutely no point in this, and your client might get disposed.

**Comment by Emzi0767** [comment]
Since there's no more activity, I will close the issue. If you wish to ask further questions, feel free to reopen.
