### ISSUE TITLE
Make DiscordMember.RoleIDs public get instead of a private variable.

### ISSUE THREAD

**Issue by LuckyScamper** [DSharpPlus/DSharpPlus#369]
# Summary
If I load a list of users from a Guild (which i do with guild.GetAllMembersAsync), the users contain a DiscordRole IEnumerable, however, it only contains a list of empty DiscordRoles (amount of entities with value null in the IEnumerable is the amount of roles the user does actually have, say two or three). However, my Visual Studio inspector tells me that in the private RoleIds function a list (ulong's) representing the id's of the Roles is present.

What I want to do; capture these RoleId's and use guild.GetRole(id) to create a dictionary<ulong, DiscordRole> as a lookup table. (Either that or please ensure that Roles does actually contain data about the Roles in the server rather than null's)

**Comment by Emzi0767** [comment]
You are doing it wrong. Don't grab stuff right after you issue a connection request. Use `Ready` or `GuildDownloadCompleted` (4.x) events.

**Comment by LuckyScamper** [comment]
@Emzi0767 the function is called in the Ready event

**Comment by Emzi0767** [comment]
If your guild roles are not populated then it generally means you're grabbing them too early - that is likely before Ready, and most certainly before guild download is completed.
