### ISSUE TITLE
Replacement for IGuildUser

### ISSUE THREAD

**Issue by Braythor** [DSharpPlus/DSharpPlus#372]
Trying to port Discord.Net code to DSharpPlus code and I can't find a replacement for IGuildUser. Here's a before and after:
### Before
```
var user = Context.User;
var role = Context.Guild.Roles.FirstOrDefault(x => x.Name == "RoleName");
await (user as IGuildUser).AddRoleAsync(role);
````
### After
```
        [Command("i_accept"), Description("Accept the rules and gain full access to the server.")]
        [Hidden]
        public async Task accept(CommandContext ctx)
        {
            var user = ctx.User;
            var role = ctx.Guild.Roles.FirstOrDefault(x => x.Name == "Approved");
            await (user as IGuildUser).AddRoleAsync(role);
            await ctx.RespondAsync("You are now approved!");
        }
```
.NET Framework 4.7.2
Windows 10 Pro 64 bit

**Comment by Emzi0767** [comment]
The proper term is member.
________________________________

**Comment by Braythor** [comment]
DiscordMember or just Member?

**Comment by Quahu** [comment]
DiscordMember.

**Comment by NaamloosDT** [comment]
Thanks for trying DSharpPlus! You're indeed (like said three times before) looking for the DiscordMember object.

Take a look at our documentation:
- 3.2: https://dsharpplus.emzi0767.com/
- 4.0: https://dsharpplus.github.io/

**Comment by Giggitybyte** [comment]
Hello! I don't believe it's been said yet, but I'm pretty sure what you're looking for is the `DiscordMember` object.

**Comment by WamWooWam** [comment]
Good afternoon, I'm not sure anyone's pointed this out, but I could swear you're looking for `DiscordMember`

(On a serious note, `is` casts are usually a little safer than straight `as` :P)

**Comment by Emzi0767** [comment]
On a related subject, the `User` object on the context can be a `DiscordMember` (as it derives from `DiscordUser`, thus permitting casting). As an alternative, there's a `Member` property on the context which is guaranteed to be a member object which sent the message.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Emzi0767** [comment]
Since there's no more activity, I will close the issue. If you wish to ask more questions, feel free to reopen it.
