### ISSUE TITLE
Request: Queue-based cooldown

### ISSUE THREAD

**Issue by uwx** [DSharpPlus/DSharpPlus#373]
# Summary
* New check attribute
* Uses the same buckets as CooldownAttribute
* Sets a limit for concurrent command execution instances on that bucket (usually only 1)
* Configurable to cancel command execution, or delay execution until bucket is available

# Details
Sample:
```cs
[ConcurrentLimit(0, 5, CooldownBucketType.Guild)] // int initialCount, int maxCount
public async Task DoSomethingInteresting(CommandContext ctx)
{
    Thread.Sleep(AVeryLongTime);
}
```

# Notes
Cooldowns that expire at a certain date/time rather than an interval would also be pretty cool (e.g a command with 10000 API users per day, limits to 100 calls per guild, resets every day at midnight).

This will probably go into Extended if it's rejected, but it really seems like the kind of thing that should come in the standard library.

**Comment by Emzi0767** [comment]
To reiterate what was said in the guild, this is not a job for checks (it would be abuse thereof), however it could be implemented as a new component of CNext.

**Comment by Neuheit** [comment]
Closing this due to slash commands.
