### ISSUE TITLE
PresenceUpdateEventArgs Typo maybe? 

### ISSUE THREAD

**Issue by chriskolenko** [DSharpPlus/DSharpPlus#378]
https://github.com/DSharpPlus/DSharpPlus/blob/6d6a000c2640870447a79bfb7f9f7055607696db/DSharpPlus/DiscordClient.cs#L159

Is that a typo inside this repository? Or is this some sort of special Discord Event Type? 
"PRESENCE_UPDATEED" <- double "EE"

What's the impact if we fix it?

**Comment by NaamloosDT** [comment]
sounds like black friday to me
