### ISSUE TITLE
VoiceNext documentation ZIP files are missing.

### ISSUE THREAD

**Issue by Braythor** [DSharpPlus/DSharpPlus#379]
Parts of the VoiceNext documentation is missing: https://dsharpplus.github.io/natives/index.html has both the x64 and x86 installs missing.

**Comment by uwx** [comment]
This is a fuckup due to our current hosting solution, the natives on the [old documentation](https://dsharpplus.emzi0767.com/natives/index.html) still work the exact same.

**Comment by Braythor** [comment]
Ah, thanks!
