### ISSUE TITLE
[Discussion] Interactivity Rewrite

### ISSUE THREAD

**Issue by NaamloosDT** [DSharpPlus/DSharpPlus#382]
As I promised quite a while ago, I'm going to start my work on a rewrite of DSharpPlus.Interactivity. To help me do this, I would like some user input. To keep this organised, I'll be using this thread for suggestions or discussion.

I will also use this thread as a little TODO list. Approved requests will also be added to this checklist.
- [x] Rewrite interactivity
- [x] Wait for messages with predicate
- [x] Wait for reaction
- [x] Polls (ahem, *working* polls)
- [x] Collecting reactions within a specific timeframe
- [x] Waiting for typing indicators
- [x] Pagination
- [x] Ability to disable certain pagination emotes
- [x] Default timeouts

- [x] Event Watcher (collecting matching objects)

So far, these are mostly just things I need to rewrite from the old interactivity.
Like I said, suggestions and discussion are welcome.

**Comment by NaamloosDT** [comment]
🎉🎉

**Comment by GreemDev** [comment]
make it good lol

**Comment by uwx** [comment]
Fixes and improvements to your gaming experience

**Comment by NaamloosDT** [comment]
General system stability improvements to enhance the user's experience.

**Comment by NaamloosDT** [comment]
Now, keep it serious please

**Comment by KillyMXI** [comment]
Wait for reaction - add predicate for user or (user, emoji).
Use case: waiting for a certain emoji from any user or another emoji from given user.

**Comment by nathan130200** [comment]
oh jesus this is good!

**Comment by nathan130200** [comment]
Can fix memory leaks 🤔 for  #305 ? :V ( just a question 😅 )

**Comment by NaamloosDT** [comment]
@nathan130200 I'm completely redoing interactivity (see it as an InteractivityNext). So far, there are no memory leaks discovered. Events now don't get hooked over and over anymore, they just get hooked once and that event gets reused for all of interactivity.

**Comment by nathan130200** [comment]
lol nice :D

**Comment by KillyMXI** [comment]
Let's say I have a menu system under a message, with different reactions doing different stuff.
I figured I can do something like this:

```
...
await Task.WhenAny(
    interactivity.WaitForMessageReactionAsync(..., user: ctx.User).ContinueWith(...).Unwrap(),
    interactivity.WaitForMessageReactionAsync(..., user: ctx.User).ContinueWith(...).Unwrap(),
    interactivity.WaitForMessageReactionAsync(..., user: null    ).ContinueWith(...).Unwrap()
    );
...
```

1. When user is set to null (to accept certain reaction from anyone) - it also triggers on bot reactions. Not only I'm not interested in bot reactions - it also breaks the whole thing by triggering on own reactions.

    User predicate will solve this. It will also make other scenarios possible, like waiting for reactions from users with a certain role only.

2. When certain reaction handled, there might be no need to wait for other reactions - I would like to tidy up and cancel the rest of them. But there is no exposed cancellation token. I wonder if I should just cancel my continuations or something prettier can be done about WaitForMessageReactionAsync function.

**Comment by NaamloosDT** [comment]
I see there's only two things left on the checklist (which are both part of pagination).

once these are implemented I'll go through the original interactivity module to make sure the rewrite has all features the original had.

**Comment by nathan130200** [comment]
When react button in pagination how to make the bot remove user reaction and go to next to page?
