### ISSUE TITLE
DiscordApiClient current user guilds improperly queries individual guilds for non-DiscordClient implementations, leading to 401s

### ISSUE THREAD

**Issue by Emzi0767** [DSharpPlus/DSharpPlus#383]
# Summary
The `DiscordApiClient` improperly handles response from Discord's API when querying `/users/@me/guilds`.

# Details
Per [implementation of GetCurrentUserGuildsAsync](https://github.com/DSharpPlus/DSharpPlus/blob/master/DSharpPlus/Net/DiscordApiClient.cs#L1004-L1021), the DiscordApiClient attempts to query the API for each individual guild received (possibly to fill in the blanks). This breaks DiscordRestClient, as it will attempt to perform an operation which the client might not be authorized to do.

The clients who call the method are immediately greeted with a 401.

# Steps to reproduce
1. Create an instance of `DiscordRestClient` with valid token
2. Call `GetCurrentUserGuildsAsync()`
3. You will get a 401

# Notes
The implementation should probably be unified, or someone should figure out why it was implemented like this in the first place.

**Comment by Emzi0767** [comment]
It seems it's a regression introduced by #303, which itself is a fix for #275. If possible, it should be fixed in a manner which doesn't break anything else.

**Comment by NaamloosDT** [comment]
![](https://cdn.discordapp.com/emojis/363081401563873280.png)
