### ISSUE TITLE
DiscordClient throws when registering command with some overloads

### ISSUE THREAD

**Issue by 13xforever** [DSharpPlus/DSharpPlus#385]
# Summary
A `NullReferenceException` occurs when trying to register a command with some overloads with default values, but works fine if you make overloads explicit.

# Details
Using .net core 2.1 with DSharpPlus & CommandsNext nightly 4.0.0-nightly-00564.

Stacktrace:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at DSharpPlus.DiscordClient.Dispose()
   at CompatBot.Program.Main(String[] args) in C:\\Develop\\discord-bot\\CompatBot\\Program.cs:line 262
```
Line 262 is the end of the `using` scope, it throws on registering the command inside said scope.

Example of a command overload:
```
class BadOverload
{
    [Command("c")]
    public async Task Crash(CommandContext ctx, int? year = null) => ;

    [Command("c")]
    public async Task Crash(CommandContext ctx, string name = null, int? year = null) => ;
}
```

# Steps to reproduce
1. Have a command overload similar to example
2. Try to register it to the client
3. Observe exception

4. Change overloads to be explicit (4 instead of 2 with default value)
5. Observe no exceptions

# Notes
Exception that is being thrown, is useless as it points to trying to dispose a `null` client for some reason, instead of pointing to the issue with overload resolving.

**Comment by Emzi0767** [comment]
Could you provide stack traces, and, if applicable, inner exceptions?
________________________________

**Comment by 13xforever** [comment]
Updated, but as I said, it's useless

**Comment by WamWooWam** [comment]
Also are you `using` your discord client? Because you shouldn’t be doing that

**Comment by Emzi0767** [comment]
Are you `using` your instance?

**Comment by 13xforever** [comment]
Yes. Here's link to the code if that helps: https://github.com/RPCS3/discord-bot/blob/master/CompatBot/Program.cs#L262

**Comment by WamWooWam** [comment]
Don’t do that, dispose the client when you’re application exits, or alternatively don’t, in doing so you’re disconnecting the client, probably before it actually connects in the first  place

**Comment by Emzi0767** [comment]
Don't do that. You're trying to dispose something while or before it is initialized that way.
________________________________

**Comment by Neuheit** [comment]
I tried using the example code for this, but I cannot seem to recreate the issue, as the command overloading works properly.

My test command class:
```csharp
public class badoverloadclass : BaseCommandModule
{
    [Command("c")]
    public async Task Crash(CommandContext ctx, int? year = null)
        => await ctx.RespondAsync("test1");

    [Command("c")]
    public async Task Crash(CommandContext ctx, string name = null, int? year = null)
        => await ctx.RespondAsync("test2");
}
```

And the register: 

```csharp
this.CommandsNextService.RegisterCommands<badoverloadclass>();
```

So I think that the client was just disposed improperly.

**Comment by uwx** [comment]
> So I think that the client was just disposed improperly.

Yes, they already figured that out.

**Comment by Neuheit** [comment]
I saw that, so in that case is there another reason why this issue is still open?

**Comment by Emzi0767** [comment]
Closed due to inactivity.
