### ISSUE TITLE
Add user.locale support

### ISSUE THREAD

**Issue by 13xforever** [DSharpPlus/DSharpPlus#387]
Make sure you familiarize yourself with our contributing guidelines.

# Summary
Discord provides an optional string field `.locale` on a `user` object that is currently not exposed through DSharpPlus.

# Details
I'm using latest 4.0.0-nightly-00565 and looking at the master, there's no support for this field.
See `locale` field in docs: https://discordapp.com/developers/docs/resources/user#user-object

**Comment by WamWooWam** [comment]
Would a string do for this? Or would it be worth trying to convert this into a .NET object like CultureInfo?

**Comment by 13xforever** [comment]
IMO string would be fine, as CultureInfo can be spotty, especially with .net core on exotic platforms

**Comment by WamWooWam** [comment]
Okay so I'm pretty sure I've implemented this just fine, *but* I'm getting a null string every time, considering how little I've heard about it, is this feature properly implemented on Discord's side yet?

**Comment by Emzi0767** [comment]
I believe this property is only ever sent 2 cases: current bot and current oauth user.
________________________________

**Comment by NaamloosDT** [comment]
They should still be added imo, as oauth is still a WIP and it could be useful in some cases.

**Comment by NaamloosDT** [comment]
oopsie, didn't see the PR that got merged
