### ISSUE TITLE
MessageReactionAdded event will set message's Author property to null for messages sent before the current session

### ISSUE THREAD

**Issue by XanTheDragon** [DSharpPlus/DSharpPlus#389]
This is a rather interesting bug, I think. 

### Repro:
Start the bot, have a user send a message, and add a reaction to the message. Within the `MessageReactionAdded` event, print the message's author to the console. The author will be the user who made the message. Shut down the bot and restart it, and have any user add another reaction to the existing message. The Author property will be null.

### My temporary workaround:
I've been able to work around this issue with a really hacky try/catch case.
```cs
if (evt.Message.Author != null) {
	if (evt.Message.Author == XanBot.Discord.CurrentUser) {
		await evt.Message.DeleteAllReactionsAsync();
	}
} else {
	//Author is null? TO DO: Report this
	try {
		await evt.Message.ModifyAsync();
		//If this works, it's our message since we can edit it, and we should delete the reactions.
		await evt.Message.DeleteAllReactionsAsync();
	} catch (Exception) { }
}
```

### Extra info:
I'm using the `WebSocket4NetClient` web socket client in a .NET Framework 4.6.1 environment on Win7.

**Comment by WamWooWam** [comment]
This sounds like a simple cache miss, the user your after isn’t cached locally, and reactions only include user ids

**Comment by Emzi0767** [comment]
I'm not entirely sure this can be classified as a bug - as stated above this is a cache miss. Reaction events don't provide full user objects, only IDs. This can lead to nulls when retrieving objects that are not cached.

**Comment by XanTheDragon** [comment]
That makes sense, alright. I'll go ahead and close this one then.
