### ISSUE TITLE
NullReferenceException when removing reaction from Message in a DM

### ISSUE THREAD

**Issue by jeffreyladd** [DSharpPlus/DSharpPlus#415]
# Summary
When Removing a Reaction to a message that the message was sent via a DM throws an error.  This is happening on 4.x

# Detaills

```
[2019-03-29 10:52:25 -04:00] [Websocket] [Error] Socket swallowed an exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at DSharpPlus.DiscordClient.OnMessageReactionRemoveAsync(UInt64 userId, UInt64 messageId, DiscordChannel channel, DiscordEmoji emoji)
   at DSharpPlus.DiscordClient.HandleDispatchAsync(GatewayPayload payload)
   at DSharpPlus.DiscordClient.HandleSocketMessageAsync(String data)
   at DSharpPlus.DiscordClient.<InternalConnectAsync>g__SocketOnMessage|54_1(SocketMessageEventArgs e)
```

# Steps to reproduce
1. Have the Bot Send a DM to a User.
2. Add a Reaction to that message
3. Remove that same reaction, Error will be thrown in the console.

**Comment by uwx** [comment]
Cannot reproduce on my branch. Check if you are on the latest version. I used this code:
```cs
var message = await ctx.Author.SendMessageAsync("This is a test");
await message.CreateReactionAsync(DiscordEmoji.FromName(ctx.Client, ":thinking:"));
await Task.Delay(2000);
await message.DeleteOwnReactionAsync(DiscordEmoji.FromName(ctx.Client, ":thinking:"));
```
Post the code you are using.

**Comment by jeffreyladd** [comment]
I am not by my computer but i think you misinterpreted what i meant.  I meant you the user add a reaction then remove it, then the null ref exception will occur not the bot adding it then removing it.  I am not however on the latest nightly, i am like 2 weeks behind.

**Comment by uwx** [comment]
Did that, still nothing happened. What size is your message cache?

**Comment by jeffreyladd** [comment]
I dont have one specificed.  So whatever the default is

**Comment by jeffreyladd** [comment]
Closing this for now as its not happening for both @uwx  and myself atm.  Chalking it up to Discords API was puking over something that got swallowed.
