### ISSUE TITLE
Get Guilds, users and channels from ids

### ISSUE THREAD

**Issue by OmegaRogue** [DSharpPlus/DSharpPlus#423]
methods to get DIscordGuilds, Discord Users, and Discord Channels from their ulong Id without the need of another object would be very useful. Like this:
```cs
DiscordGuild GetGuild(ulong id)
DiscordUser GetUser(ulong id)
DiscordChannel GetChannel(ulong id)
```

**Comment by Emzi0767** [comment]
Have you bothered reading the documentation? Because these exist already.
________________________________

**Comment by OmegaRogue** [comment]
In what namespace are they?

**Comment by Emzi0767** [comment]
They all exist on instances of appropriate types.
________________________________

**Comment by OmegaRogue** [comment]
i havent found them anywhere

**Comment by Kiritsu** [comment]
# Make a request to the API
```cs
DiscordChannel DiscordClient#GetChannelAsync(ulong id)
DiscordGuild DiscordClient#GetGuildAsync(ulong id)
DiscordUser DiscordClient#GetUserAsync(ulong id)
```

```cs
DiscordChannel DiscordGuild#GetChannelAsync(ulong id)
DiscordMember DiscordGuild#GetMemberAsync(ulong id)
```

# Pull from cache
```cs
DiscordGuild DiscordClient#Guilds.Values.FirstOrDefault(x => x.Id == id)
DiscordChannel DiscordClient#Guilds.Values.SelectMany(x => x.Channel).FirstOrDefault(x => x.Id == id)
DiscordMember DiscordClient#Guilds.Values.SelectMany(x => x.Members).FirstOrDefault(x => x.Id == id)
```

```cs
DiscordChannel DiscordGuild#GetChannel(ulong id)
DiscordMember DiscordGuild#Members.FirstOrDefault(x => x.Id == id)
```

DiscordMember objects can be casted into DiscordUser objects.

So yes. As Emzi just said, everything is in the doc, and you even have a fancy great search bar. https://dsharpplus.github.io/

**Comment by Emzi0767** [comment]
Members don't require casting to users per type inheritance rules.
________________________________

**Comment by TheRave05** [comment]
So how can I ban a user with this now?

**Comment by Neuheit** [comment]
[Get the member from the guild](https://dsharpplus.github.io/api/DSharpPlus.Entities.DiscordGuild.html?q=GetMember#DSharpPlus_Entities_DiscordGuild_GetMemberAsync_System_UInt64_) and [ban them](https://dsharpplus.github.io/api/DSharpPlus.Entities.DiscordMember.html?q=BanAsync#DSharpPlus_Entities_DiscordMember_BanAsync_System_Int32_System_String_).

In the future please ask these kinds of questions in our [Discord](https://discord.gg/KeAS3pU).

**Comment by sohdahh** [comment]
404 not found @Neuheit

**Comment by OoLunar** [comment]
Neu hasn't contributed to the repo in a long time @sohdahh. Additionally, please join our Discord for further support: https://discord.gg/dsharpplus
