### ISSUE TITLE
Broken message in cache after ModifyAsync with added embed

### ISSUE THREAD

**Issue by KillyMXI** [DSharpPlus/DSharpPlus#428]
# Summary

`GetMessageAsync` returns a message with no Content, if it was previously edited with `ModifyAsync` to add an embed. (it doesn't reproduce if no embed added on edit)

# Details

D#+ 3.2.3 (no custom sockets) (got couple of confirmations it also happens on 4.0 nightly)
.Net Core 2.2

# Steps to reproduce

First, add the following commands:

```csharp
private ulong testMsgId = 0;

[Command("test1")]
public async Task Test1Async(CommandContext ctx)
{
    var  msg1 = await ctx.RespondAsync("test message");
    testMsgId = msg1.Id;

    msg1 = await ctx.Channel.GetMessageAsync(testMsgId);
    await ctx.RespondAsync($"A: {msg1.Author.Username} at {msg1.Timestamp}: \"{msg1.Content}\"");
}

[Command("test2")]
public async Task Test2Async(CommandContext ctx)
{
    if (testMsgId == 0) { return; }

    var msg1 = await ctx.Channel.GetMessageAsync(testMsgId);
    await ctx.RespondAsync($"A: {msg1.Author.Username} at {msg1.Timestamp}: \"{msg1.Content}\"");

    if (msg1.Content != null)
    {
        await msg1.ModifyAsync(
            msg1.Content,
            new DiscordEmbedBuilder { Description = "test", Timestamp = DateTimeOffset.Now }
            );
    }

    msg1 = await ctx.Channel.GetMessageAsync(testMsgId);
    await ctx.RespondAsync($"B: {msg1.Author.Username} at {msg1.Timestamp}: \"{msg1.Content}\"");
}
```

Then, run them in the following order:
```
!test1
!test2
!test2
```

Every command should output "test message" in place of `{msg1.Content}`. But after first run of `.test2` has modified it, on the second run it is empty.

# Notes
I hope to have a fix or workaround for 3.2.x, unless you releasing 4.0 like tomorrow.

**Comment by KillyMXI** [comment]
I tried to set `MessageCacheSize = 0` and it makes the issue go away.
But I can't call it a workaround, as other things are getting quite a bit slower without cache.

**Comment by NaamloosDT** [comment]
I think this means cached messages don't get updated properly with the data returned by API, or the API is returning incomplete data. Most likely the former

**Comment by NaamloosDT** [comment]
Quoted from [Discord's API documentation](https://discordapp.com/developers/docs/topics/gateway#message-update):
```
Unlike creates, message updates may contain only a subset of the full message object payload (but will always contain an id and channel_id).
```

**Comment by NaamloosDT** [comment]
Fix coming up, will backport to 3.x as well
![](https://i.imgur.com/JkFdxhH.png)

**Comment by Emzi0767** [comment]
It's a classic Apple `goto fail;` bug.
