### ISSUE TITLE
Missing DiscordGuild properties/endpoints

### ISSUE THREAD

**Issue by uwx** [DSharpPlus/DSharpPlus#432]
# Summary

* The following Guild properties are not exposed by the library:

![image](https://user-images.githubusercontent.com/13633343/59287234-a4628f00-8c47-11e9-9aef-927b8f59e5f0.png)

* Tthese were added as part of the Nitro boosting thing:

![image](https://user-images.githubusercontent.com/13633343/59286535-4c775880-8c46-11e9-8976-88a175db2701.png)

This is a bitwise flags property called `system_channel_flags` and the only values appear to be:

```
Send a random welcome message when someone joins this server. - 0x1
Send a message when someone boosts this server. - 0x2
```

Note that the flags are _inverted_, that is, having the message type enabled means its bit will **not** be set. (Having both enabled means a value of zero, whereas having neither enabled means a value of 3.) This should be clearly documented. (Also, don't forget to add them to the edit model.)

* Banner image URL should be exposed somewhere (only the hash is ATM)
* `/guilds/{guild.id}/widget.png` URL should be exposed as a property
* `GET /guilds/{guild.id}/vanity-url` needs to be added
* `PATCH /guilds/{guild.id}/embed` should possibly be added
* IsOwner is wrong (there is no `is_owner` property, it's called `owner`, and that property is computed anyway, so it doesn't do anything)
* `widget_enabled`, `widget_channel_id` properties

**Comment by uwx** [comment]
I've updated this issue with missing endpoints in addition to the missing properties.

**Comment by uwx** [comment]
I've updated the OP with a detail about IsOwner that I've just stumbled upon.

**Comment by Neuheit** [comment]
What would be the best way to implement the `GET /guilds/{guild.id}/widget.png` endpoint? We could try returning a MemoryStream, or just a pure array of bytes. I tried getting the Base64 string using the ImageTool class and passing the memory stream, however it threw `"The data within the stream was not valid image data"`.

**Comment by WamWooWam** [comment]
> What would be the best way to implement the GET /guilds/{guild.id}/widget.png endpoint?

As a URL, like every other guild image property.

**Comment by Emzi0767** [comment]
There's 4 kinds of widget though
________________________________

**Comment by WamWooWam** [comment]
> There's 4 kinds of widget though

Then like `AvatarUrl`? With a default one and the ability to select one via a method call? My point was more so that they seemed to be trying to decode the base64 identifier string as an image...

**Comment by Neuheit** [comment]
Yes, I am mainly trying to see how we can interpret this endpoint, since it sends raw image data. We should expose it as a URL, however we would not be taking advantage of the image data sent from the endpoint. Also, when I tried getting the base64 string using the `ImageTool`, I got ` System.IO.InvalidDataException: The data within the stream was not valid image data.`
