### ISSUE TITLE
Missing News and Store channel types

### ISSUE THREAD

**Issue by uwx** [DSharpPlus/DSharpPlus#433]
# Summary
As per discordapp/discord-api-docs/issues/881, there are two new types of channels for verified servers: News and Store.

# Details
These are called GUILD_NEWS and GUILD_STORE in the docs, good luck figuring it out from there bucko

# Notes
Thank you to @WamWooWamWooWamWooWamWooWamWooWamWooWamWooWam for pointing this issue out.

**Comment by NaamloosDT** [comment]
![Sad Programmer Noices](blob:https://imgur.com/65ed1075-9acf-4bce-9ecb-8a32d5f64382)

**Comment by NaamloosDT** [comment]
oops what the fuck lemme fix that

**Comment by uwx** [comment]
Type 7 is now used for "LFG Listing Channel". I haven't been able to create channels of this type so I don't know exactly how they work. You can find some details in https://github.com/DJScias/Discord-Datamining/commit/80f018ba3c909ec25fee4a25e6f074f68e8656da#commitcomment-34038656.
