### ISSUE TITLE
Missing 'Suppress Embeds' endpoint

### ISSUE THREAD

**Issue by uwx** [DSharpPlus/DSharpPlus#434]
# Summary
As part of the hack week (?), a new endpoint was added to delete existing embeds.

# Details
The path to the endpoint is `POST /channels/::channel_id/messages/::message_id/suppress-embeds`. The parameters are `{suppress: true}` or `{suppress: false}`. This functionality may break the message edit handler, which might only expect embeds to be _added_ and not removed. Remember that previously, an embed could never be removed from a message after sending it.

# Notes
Thank you to @WamWooWamWooWamWooWamWooWamWooWamWooWamWooWam for pointing this issue out.

**Comment by Emzi0767** [comment]
Resolved by #468
