### ISSUE TITLE
Missing message types & DiscordMessage properties

### ISSUE THREAD

**Issue by uwx** [DSharpPlus/DSharpPlus#436]
# Summary
There are several recently-added Message fields that the lib does not yet expose.

# Details
As per the [API documentation](https://discordapp.com/developers/docs/resources/channel#message-object-message-types), the following message types are missing: `USER_PREMIUM_GUILD_SUBSCRIPTION`, `USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_1`, `USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_2` and `USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_3`. They should be added here:

https://github.com/DSharpPlus/DSharpPlus/blob/af01488ce518b06f2d638fad26567b08f733ebad/DSharpPlus/Entities/DiscordMessage.cs#L473-L517

The `activity` and `application` message properties are also not exposed, as per [API](https://discordapp.com/developers/docs/resources/channel#message-object-message-structure).

In addition, Author is seemingly not correctly handled for webhooks (the API specifically notes that it might not be a valid user object, and I'm not sure what the lib does in this case)

**Comment by Emzi0767** [comment]
Resolved by #472
