### ISSUE TITLE
Missing DiscordUser.Flags

### ISSUE THREAD

**Issue by uwx** [DSharpPlus/DSharpPlus#437]
# Summary
User flags should be exposed. These are colloquially known as badges, but presumably could be used for different purposes.

# Details
The current available flags are detailed here: https://discordapp.com/developers/docs/resources/user#user-object-user-flags

**Comment by Emzi0767** [comment]
Should be noted, this is only available for `@me`, and only for OAuth.

**Comment by uwx** [comment]
Thanks for clearing that up, I wasn't sure about that.
