### ISSUE TITLE
On Reconnect, The bots activity isnt reapplied

### ISSUE THREAD

**Issue by jeffreyladd** [DSharpPlus/DSharpPlus#445]
# Summary
When the bot comes back online due to Cloudflare puking or the bots internet connection taking a dump, the Bots activity is not reapplied.  

#Reproduction Steps
1. Setup the Bots activity right before the Connect Async.  
``` var act = new DiscordActivity("Waiting For my internet to puke", ActivityType.Watching);```
2. call ConnectAsync with the activity passed in. ``` await _client.ConnectAsync(act, UserStatus.Online);```
3. Start up your bot.
4. Go Disable the network adapter.
5. Go outside for a smoke, make a sandwich, or something else for 5 minutes. 
6.  Re-enable your network adapter.
7. Notice the Bots Activity is not shown in Discord any more

**Comment by jeffreyladd** [comment]
Forgot to mention this is happening with current source.

**Comment by F1restar4** [comment]
ConnectAsync (or just the identify payload) taking an activity is only an initial state, you're meant to subscribe to the ready/resumed event(s) and set the activity there to maintain it if it's static.

**Comment by jeffreyladd** [comment]
That is kinda silly.  Resume should resume the state the bot was originally in, this should also be the activity.  Some real life examples are
1. When a car stalls, and u turn it back on, does it turn ur ac off and turn on the heat?
2. When ur phone loses service and comes back in service, does all ur applications turn off?
3. When the bot goes offline and comes back, do you have to resetup all the commands again?
The answer to all these questions are no cause the state is maintained.  Same should go for activity.

**Comment by Emzi0767** [comment]
> Allow me to address the anxieties underlying your concerns, rather than try to answer every possible question you might have left unvoiced.

Activity is not part of the state. Indeed, even Discord does not consider this to be the case, and it does not allow you to track your own activity through the API (any self-update of the activity is never dispatched to you, only others). 

In D#+, activity tracking for oneself is really nothing more than a hack. We simply take whatever you give us at face value. You will be able to query your own status, but it will only affect your perception of reality, since Discord might drop it any point and will never tell you. It is therefore impossible to properly track, and therefore restore, your own activity.

If you are confused about the definition of state in Discord, it consists primarily of entites, for example (this is a non-exhaustive list):
- Messages
- Channels
- Guilds
- Roles
- Members

**Comment by uwx** [comment]
> ConnectAsync (or just the identify payload) taking an activity is only an initial state, you're meant to subscribe to the ready/resumed event(s) and set the activity there to maintain it if it's static.

No, status is supposed to persist between sessions. Yes, passing activities to ConnectAsync is an API formality.

> any self-update of the activity is never dispatched to you, only others

Yes, Discord doesn't send status updates for the connected client. However:

https://github.com/DSharpPlus/DSharpPlus/blob/8ad5b404dbd2e9433e14e7f3a4574c7711220186/DSharpPlus/DiscordClient.cs#L2210-L2219

Status _is_ maintained by the current client. And it should persist across an invalidated session:

https://github.com/DSharpPlus/DSharpPlus/blob/8ad5b404dbd2e9433e14e7f3a4574c7711220186/DSharpPlus/DiscordClient.cs#L2115-L2136

Unless the activity is updated from outside (e.g a different client on the same token and shard), it should be maintained across connections.

Very clearly this seems to be a bug, and if I'm not missing anything here, I'm disappointed that you have dismissed it so readily. cc @Emzi0767

**Comment by Emzi0767** [comment]
I have not dismissed it, merely provided an explanation for why it is the way it is.
________________________________

**Comment by uwx** [comment]
The code as it is is supposed to do what the OP wants (keep the last set status on reconnect). Unless the OP fucked something else up, this is a bug.

**Comment by uwx** [comment]
By the way, it was Naam who added that feature, which is probably why you don't remember it.

**Comment by Emzi0767** [comment]
I'm aware of that fact.
________________________________

**Comment by Emzi0767** [comment]
Closed by #485
