### ISSUE TITLE
Missing Guild properties for many events

### ISSUE THREAD

**Issue by uwx** [DSharpPlus/DSharpPlus#448]
# Summary
Many gateway events, despite not necessarily being tied to a guild, have `guild_id` properties, and these are usually discarded by the lib. They should be exposed in order to match the API. In addition, some of these events may also contain skeleton objects created in their handler, which should have their guilds filled in too.

# Details
I'm not going to write a conclusive list of every single event that is missing this property, but if you go on the [Gateway](https://discordapp.com/developers/docs/topics/gateway) docs page and search `guild_id?`, most of those are not mapped.

**Comment by Emzi0767** [comment]
This is a recent addition to the API, hence why it's missing. If anyone wants to implement them, feel free.

**Comment by Emzi0767** [comment]
Resolved by #497
