### ISSUE TITLE
Custom statuses (Activity type 4)

### ISSUE THREAD

**Issue by uwx** [DSharpPlus/DSharpPlus#451]
# Summary
This new undocumented/experimental activity type lets users apply a status without any prefix. During the experiment, it will only display in the percentile of guilds which are in the experiment. The remaining guilds will show no status at all.

# Details
This was added at about the same time as Nitro Server Boosting (around May), so all the info on it got completely swallowed. I got bored of sifting through comments on [Discord-Datamining](https://github.com/DJScias/Discord-Datamining) so I don't have much information.

# Notes
Be careful not to get yourself banned if you decide to implement sending this type of activity.

**Comment by jkrejcha** [comment]
It does seem that this data is still sent to other clients, regardless of if they are in the experiment or not. On some API clients (specifically an older version of the mobile application), the custom status is still visible.

On these clients, it will show up as "**Playing** Custom Status" and then if you select it you can view the status. There's some identifier (a `SnowflakeObject` of some sort perhaps?) and the status is displayed as other text.
