### ISSUE TITLE
X-RateLimit-Bucket header

### ISSUE THREAD

**Issue by Emzi0767** [DSharpPlus/DSharpPlus#456]
# Summary
This issue is for tracking developments related to `X-RateLimit-Bucket` header.

# Details
For bucketed requests, Discord now returns a header called `X-RateLimit-Bucket`, which appears to identify the request bucket. How reliable this is is unknown (see notes). Such header looks as follows: `80c17d2f203122d936070c88c8d10f33`.

We should reach a decision on whether we want to switch to this new bucketing system, or do we want to stick to our existing code.

# Notes
According to Danny, this is poorly implemented (major params are not resolved). ![Danny's comment](https://totally-not.a-sketchy.site/522cmRC.png).

**Comment by WamWooWam** [comment]
While we're at it, it would probably be beneficial to implement support for `X-RateLimit-Precision` (discordapp/discord-api-docs#1064)
