### ISSUE TITLE
Lavalink TrackExceptionEvent is not fired

### ISSUE THREAD

**Issue by Kriste00** [DSharpPlus/DSharpPlus#457]
# Summary
As the title states, the `TrackExceptionEvent` will not be fired when recieving the event from lavalink.

Here is an example of the payload sent, that is supposed to trigger the `TrackExceptionEvent`

```
{
"op":"event",
"type":"TrackExceptionEvent",
"track":"QAAAjgIAJ05pZ2h0Y29yZSAtIFRoZSBkZXZpbCB3aXRoaW4gLSAoTHlyaWNzKQANTmlnaHRjb3JlIE10YgAAAAAAAyDIAAtaOVcyWGUxWHU4YwABACtodHRwczovL3d3dy55b3V0dWJlLmNvbS93YXRjaD92PVo5VzJYZTFYdThjAAd5b3V0dWJlAAAAAAAAAAA=",
"error":"Something broke when playing the track.",
"guildId":"340113591950770177"
}
```

# Steps to reproduce
Play a track that raises an exception
Watch it never be raised from https://github.com/DSharpPlus/DSharpPlus/blob/bab7b64e33ffaf73c27a11ba1900f66e659b965d/DSharpPlus.Lavalink/LavalinkNodeConnection.cs#L401

**Comment by Emzi0767** [comment]
Update your Lavalink
________________________________

**Comment by Kriste00** [comment]
I thought i had the latest version, but maybei dont. I will try

**Comment by Kriste00** [comment]
I have version 3.2.1 build 799 and that is the latest version as far as i can see

**Comment by Emzi0767** [comment]
Then you should take this up with Lavalink and/or lavaplayer developers
________________________________

**Comment by Kriste00** [comment]
Lavalink sends the event, but this library does not raise the TrackException event.
