### ISSUE TITLE
A mentioned user object in a message is null if not a server member

### ISSUE THREAD

**Issue by KarlOfDuty** [DSharpPlus/DSharpPlus#467]
Trying to get a user which has been mentioned in a message will just return null if that user is not part of the guild. As it returns DiscordUsers and not DiscordMembers I assume I am supposed to be able to use pings for any users on discord.

Here is some code to reproduce the issue:

```cs
IReadOnlyList<DiscordUser> mentionedUsers = command.Message.MentionedUsers;

foreach (DiscordUser mentionedUser in mentionedUsers)
{
	if (mentionedUser == null)
	{
		// User is not a member of the server
	}
	else
	{
		// User is a member of the server
	}
}
```

**Comment by Emzi0767** [comment]
AFAIK users not in the server are not returned from the API anyways.
________________________________

**Comment by KarlOfDuty** [comment]
Ah rip, why doesn't it return DiscordMembers in that case? I mean the pings work in discord so I don't see why they wouldn't return them in the first place anyway.

**Comment by uwx** [comment]
In the real client, user pings only work if the user is either in the server or in the client's cache (e.g left the server recently). If the user left and you refresh the client, you will notice the ping probably will look like `<@id>` and will not be clickable. However, the library should return at least a skeleton object in this case, so this looks like a bug. The following lines would need to be changed:

https://github.com/DSharpPlus/DSharpPlus/blob/d028566bb06d3312aa488bb9c07740ad8771b07e/DSharpPlus/DiscordClient.cs#L1703

https://github.com/DSharpPlus/DSharpPlus/blob/d028566bb06d3312aa488bb9c07740ad8771b07e/DSharpPlus.CommandsNext/CommandsNextExtension.cs#L759

**Comment by uwx** [comment]
Correcting the last statement I made - the library parses the message for mentioned entities as a workaround to a previous inconsistency in Discord's API. The strange behaviour is to match what the API was to give if it returned correct results. As such this is working as intended, although the inconsistency in the API seems to no longer be a problem, so the mentioned entity parsing should be revisited, and changed to simply take in the relevant API fields.
