### ISSUE TITLE
guild_subscriptions support.

### ISSUE THREAD

**Issue by MatthieuCoder** [DSharpPlus/DSharpPlus#487]
According to the Discord documentation, the gateway have a feature called `guild_subscriptions` that can avoid the dispatch of events like Presence update and Typing events. As they said this can avoid unusual cpu / memory usage. Can it be implemented in D#+ Please ^^
https://discordapp.com/developers/docs/topics/gateway#guild-subscriptions

**Comment by Emzi0767** [comment]
I'm pretty certain that we already deemed it useless internally since it doesn't actually alleviate anything other than maybe bandwidth usage.

**Comment by Neuheit** [comment]
I just did some testing on this with a bot on over 38,000 servers, and setting this property to false actually has a significant impact on memory usage. Setting this to false only used around 1.9 GB, whereas by default/setting it to true used around 7.6 GB. In my opinion this should definitely be implemented, and I would be happy to submit a PR for it.

**Comment by Emzi0767** [comment]
If you do, I want you to put a big fat warning to the default logger that warns about potential cache incoherence problems when using the opt-out.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Neuheit** [comment]
For sure.

**Comment by uwx** [comment]
> Setting this to false only used around 1.9 GB, whereas by default/setting it to true used around 7.6 GB.

Although I appreciate this feature being supported, and disabling subscriptions is basically a free bandwidth bonus, this is a very optimizable region and should be explored further; individual event dispatches should not be causing this much horrendous GC pressure.

**Comment by Neuheit** [comment]
I used the `DSharpPlus.Test` bot code, if there's anything odd in there.

**Comment by Neuheit** [comment]
@Emzi0767 I believe this issue should be closed as well then.
