### ISSUE TITLE
DiscordChannel.ConnectAsync() doesn't establish a connection.

### ISSUE THREAD

**Issue by maxymoo22** [DSharpPlus/DSharpPlus#488]
# Summary
The `ConnectAsync()` method for the `DiscordChannel` class doesn't seem to fully work. It makes the bot join the channel, but afterwards if you try to get the connection with `VoiceNextExtension.GetConnection()`, it returns null.

# Details
The code I have tested this with:
```
discord.MessageCreated += async message =>
{
    var member = await message.Guild.GetMemberAsync(message.Author.Id);
    DSharpPlus.Entities.DiscordChannel memberChannel = member.VoiceState.Channel;
    await memberChannel.ConnectAsync();
    //line above doesn't ever finish executing
    await message.Message.RespondAsync("Connected");
}
```

`RespondAsync` never gets called, so I'm assuming that `ConnectAsync` is still being awaited. This, along with the fact that you can't get a connection with`VoiceNextExtension.GetConnection()`,  makes me think that maybe a connection is never being created.

# Notes
I'm using windows 10 by the way, with visual studio 2019 and the .net core version of the project is `3.0.100`

I've tried this code on the latest stable as well as the build I'm using now, latest nightly 4.0.0-nightly-00635, and it doesn't work on either of them.

**Comment by Emzi0767** [comment]
Everything is working just fine; you're deadlocking the thread.

**Comment by SeriousVitamin** [comment]
Same problem.
I tryied to copy source from https://github.com/DSharpPlus/Example-Bots/tree/master/DSPlus.Examples.CSharp.Ex04, and this solution can't get connection on ExampleVoiceCommands.cs, lines 49, 88 and 114. Everytime returns null.

**Comment by Emzi0767** [comment]
That is because you didn't follow the setup guide correctly.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by maxymoo22** [comment]
Hi thanks for your response @Emzi0767. I'm relatively new to c#, so I'm not too good with it but doesn't deadlocking mean that 2 tasks are waiting on eacthother? Also, could you be so kind as to tell me how I'm deadlocking it? Cant seem to figure it out for myself.
Thanks.

**Comment by SeriousVitamin** [comment]
@Emzi0767 which step into Setup guide need to deep exploration?
I do all steps into https://dsharpplus.emzi0767.com/articles/vnext_setup.html and cannot get VoiceNextClient.GetConnection() not null result.

**Comment by Emzi0767** [comment]
VNext and Lavalink wait for events. You're doing this on the thread which dispatches them, so you're causing it to wait for event dispatch to finish in order to dispatch more events.

As for setup, hook the appropriate exception events and inspect the exceptions you are getting. My suspicion is that you installed libraries incorrectly or installed the incorrect ones.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by maxymoo22** [comment]
Ok I see now. After doing come research on asynchronous programming in c#, I learned how to fix my code. Thanks so much for pointing out the deadlock to me Emzi0767!

Btw, @SeriousVitamin, if you can't solve your problem just mention me in discord (maxymoo22#6750) and I'll be happy to share my method of fixing it with you.
