### ISSUE TITLE
Feature: Make the fields property in DiscordEmbedBuilder settable.

### ISSUE THREAD

**Issue by Neuheit** [DSharpPlus/DSharpPlus#492]
# Details
When trying to add fields to the DiscordEmbedBuilder, it seems that the only way to do so is through the `.AddField()` method, whereas all of the other properties are settable through object initializer syntax.

Current way of adding embed fields: 
```csharp
var builder = new DiscordEmbedBuilder
{
     Color = DiscordColor.Red,
     Description = "This is an embed"
};

builder.AddField("field1", "I am a field", true);
builder.AddField("field2", "I am also a field", false);
```

While this certainly works, in my opinion it would look much cleaner to add them through object initializer syntax:

```csharp
var embed = new DiscordEmbedBuilder
{
     Color = DiscordColor.Red,
     Description = "This is an embed",
     Fields =
     {
          new DiscordEmbedField
          {
               Name = "field1",
               Value = "I am a field",
               Inline = true
          },

          new DiscordEmbedField
          {
               Name = "field2",
               Value = "I am also a field",
               Inline = false
          }
     }
};
```
This would of course involve making the EmbedField constructor public, as well as changing how the builder internally checks the fields to ensure there are no API errors.

**Comment by Emzi0767** [comment]
This is by design; we do this to enforce limits.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Naamloos** [comment]
This message was not sponsored by Outlook for Android

**Comment by uwx** [comment]
Why exactly this issue isn't closed is a mystery to all.

**Comment by Neuheit** [comment]
I'm looking in to something on it now, if it doesn't work out then I'll close it

**Comment by Naamloos** [comment]
I mean I suppose you _could_ override the setter with a limit check but I don't think that's really a good solution

**Comment by Neuheit** [comment]
Doesn't look like it would be possible to have the checks in the class itself, so if this were to get implemented, the checks would have to be moved in the `CreateMessageAsync()` method in the ApiClient: https://github.com/DSharpPlus/DSharpPlus/blob/6a89e0f60a0aed0e3bd792aeb980ba40b26ac5f5/DSharpPlus/Net/DiscordApiClient.cs#L518.

**Comment by uwx** [comment]
It's not that implementing this is impossible, it's that it's completely pointless. If you're desperate, my extension library supports it. (Whether or not it still works 2 years later is also a mystery to all.)

**Comment by Neuheit** [comment]
Yeah, just figured it would be nice since a few other libraries had it like that. In that case I'll close this then.
