### ISSUE TITLE
Exception occurred when decoding incoming audio data

### ISSUE THREAD

**Issue by maxymoo22** [DSharpPlus/DSharpPlus#493]
# Summary
An exception occurs when DSharpPlus runs my `VoiceReceived` event handler. The error is along the lines of:

`The given keys cannot be found in the dictionary at DSharpPlus.VoiceNext.VoiceNextConnection.ProcessVoicePacket(Byte[] data)`

# Details
I'm using the latest nightly build of DSharpPlus

Console output:
```
[2019-11-30 11:31:37 +13:00] [VNext RX] [Error] Exception occured when decoding incoming audio data
System.Collections.Generic.KeyNotFoundException: The given key '1' was not present in the dictionary.
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException(Object key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at DSharpPlus.VoiceNext.VoiceNextConnection.ProcessPacket(ReadOnlySpan`1 data, Memory`1& opus, Memory`1& pcm, IList`1 pcmPackets, AudioSender& voiceSender, AudioFormat& outputFormat)
   at DSharpPlus.VoiceNext.VoiceNextConnection.ProcessVoicePacket(Byte[] data)

Event fired.

[2019-11-30 11:31:37 +13:00] [DSharpPlus] [Error] An System.AggregateException occurred in VNEXT_VOICE_RECEIVED.
System.AggregateException: Exceptions occured within one or more event handlers. Check InnerExceptions for details. (The given key '402299820825509899' was not present in the dictionary.)
 ---> System.Collections.Generic.KeyNotFoundException: The given key '402299820825509899' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at maxymooapp_DSharp.Program.HandleVoiceData(VoiceReceiveEventArgs voiceData) in C:\Users\Max\Documents\stuff of max\node.js stuff\maxymooapp-DSharp\Program.cs:line 232
   at DSharpPlus.AsyncEvent`1.InvokeAsync(T e)
   --- End of inner exception stack trace ---
```

The code I am using for the event handler:
```
static async Task HandleVoiceData(DSharpPlus.VoiceNext.EventArgs.VoiceReceiveEventArgs voiceData)
{
    if (voiceData.User.IsBot) return;
    Console.WriteLine("Event fired.");
    
    var stereoBufferArray = voiceData.PcmData.ToArray();
    foreach(byte b in stereoBufferArray)
    {
        bufs.Add(b);
    }
}
```
Where bufs is a: `List<byte>`

There is no other code in the event handler so far as I cannot get this part to work.

# Notes
Every once in a while, no exception will be thrown. This usually happens when I don't have `var stereoBufferArray = voiceData.PcmData.ToArray();`  or the `foreach` loop in the code.

Also, in the second part of the error it cant find the key `402299820825509899` in a dictionary. I then realized that `402299820825509899` is my discord user id`

**Comment by Emzi0767** [comment]
> `The given key '1' was not present in the dictionary.`

Discord did not send the SSRC map.

> `System.Collections.Generic.KeyNotFoundException: The given key '402299820825509899' was not present in the dictionary.`

User cache is incoherent. We've encountered this, though unsure why it's happening.

**Comment by maxymoo22** [comment]
OK, thanks for the explanation. Is there any workaround I can implement or will I just have to wait until you guys figure out how to fix it?

**Comment by maxymoo22** [comment]
A few months ago discord made a change where they now only send the speaking event once per websocket connection. Apparently their clients only associate the ssrc with the user once, and then they no longer need it (see [this](https://github.com/discordjs/discord.js/issues/3524#issuecomment-540373200) comment in another library I used to use). Does DSharpPlus have to associate the ssrc with the user every time it joins a voice channel or receives voice packets? I'm not too good at c# so your library is kinda complicated for me, but if that is what's happening then that seems to me like it could be the cause of the first error, possibly the second one too as I never got the second error as long as I wasn't using VoiceNext (well actually outgoing audio was fine, only incoming audio from VoiceNext caused the error).

**Comment by Emzi0767** [comment]
We can work with associating once. Any subsequent association is just an update to existing state, should we ever receive one.

**Comment by maxymoo22** [comment]
K. well RIP then. Maybe I should just use discord.js cause like it works

**Comment by maxymoo22** [comment]
Huh for some reason my SSRC is always just 1. Even when I try the example code in the articles, it just outputs a file named 1.wav. Am I correct in thinking that the ssrc should actually be a longer string of numbers?

**Comment by Emzi0767** [comment]
No, SSRC is a number describing audio source. It can be anything so long as it fits within 32 bits.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
