### ISSUE TITLE
Suggestion: merge VoiceNextConnection and LavalinkGuildConnection into one thing.

### ISSUE THREAD

**Issue by maxymoo22** [DSharpPlus/DSharpPlus#494]
I've noticed that when you make the client join a voice channel voice VoiceNext, and then try to play a song using the Lavalink part of the library, nothing will happen. This will be happening because VoiceNextConnection and LavalinkGuildConnection aren't the same thing and the client can't have both of them on the same channel wont it? If so, I really think you should somehow merge the two. I have a bot made with the discord.js library which can play music and receive users voice commands at the same time because discord.js is actually good (not saying that DSharpPlus isn't 😊). I can't do this using your library because of what I said before and it's kind of annoying. Or, at least, I don't think I can. (If it is actually possible then just ignore my little rant and ban me from the server on account of my ignorance) Is it possible for this to be implemented because I think it would be much better then having 2 different types of connections which seems rather silly to me. Thanks.

Oh BTW, if this isn't the place for suggestions just tell me and ill move it to wherever. I just wasn't really sure where to ask about this.

**Comment by Emzi0767** [comment]
They're independent modules, and, as such, will not be merged.

Aside from this, VNext and Lavalink each have their specific functionality for their connections.

**Comment by maxymoo22** [comment]
So basically there is no way I can send and receive audio at the same time?

**Comment by maxymoo22** [comment]
Not gonna lie, that's pretty aids tbh. I thought D#+ was like this flashy new library but nah. cebs.

**Comment by Emzi0767** [comment]
No other library will allow you to mix Lavalink and non-Lavalink voice connections over the same sockets, because that's just not how any of it works. Furthermore, VoiceNext can do bidirectional transmission. You should also stop calling things you don't understand AIDS.

**Comment by maxymoo22** [comment]
Ikr?! Its habit of mine, I'm kinda addicted
