### ISSUE TITLE
Stable Release on the horizon?

### ISSUE THREAD

**Issue by braunsonm** [DSharpPlus/DSharpPlus#504]
Is there any timeline for the next release? Excited to use some of the nightly features but a new release has not been out in over two years.

**Comment by Kiritsu** [comment]
Just use the nightly feed like everyone else. It's more stable than latest release.

**Comment by braunsonm** [comment]
I have a constraint where we only use NuGet for our packages. Having them on a third party makes it difficult to use.

**Comment by uwx** [comment]
We will push out a new stable release when all 4.0-blocking features are complete and bugs are fixed. We can't release any sooner when the API is still slated to change. People also have other things to do and the blocking features aren't all easy to implement. I highly recommend using the nightly feed instead.

**Comment by Naamloos** [comment]
Nightly should indeed be good for use, but it's not release ready yet. Though in general you won't find a lot of issues with it.

You _could_ download the dlls and keep them in your repository to get around that constraint but I understand if you'd prefer not to do so

**Comment by braunsonm** [comment]
Understandable. At least you are still thinking about a release eventually.
