### ISSUE TITLE
GIFT_CODE_UPDATE event not handled

### ISSUE THREAD

**Issue by Neuheit** [DSharpPlus/DSharpPlus#506]
# Summary
I recently came across an unknown event from my bot logs: 
```
Unknown event: GIFT_CODE_UPDATE
{
  "uses": 1,
  "sku_id": "521846918637420545",
  "code": "Mk5sW59364S6TqDr",
  "channel_id": "661971994480476160",
  "guild_id": "661971766125527070"
}
```

Doing some research, I found that it is intentionally not documented in discord docs, according to Jake, so we should decide whether to emit it or ignore it internally.

**Comment by uwx** [comment]
It's free real estate

**Comment by Emzi0767** [comment]
I'm told it's one of 3 events that are not supposed to be dispatched to bots, that bots still get as a result of a bug or something else. We should ignore or suppress it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Neuheit** [comment]
Sounds good, I'll work on a PR for it
