### ISSUE TITLE
Client.GetVoiceNextClient().GetConnection() always returns null.

### ISSUE THREAD

**Issue by RubbyGT** [DSharpPlus/DSharpPlus#509]
# Summary
GetVoiceNextClient().GetConnection() keeps returning null for no reason, even on the Bot Examples [right here](https://github.com/DSharpPlus/Example-Bots/blob/decf67775fc711e2cf76f8d0a88b4136e037a718/DSPlus.Examples.CSharp.Ex04/ExampleVoiceCommands.cs#L88).

My computer is running Windows 10 x64 and i have tried both the x64 and x86 libs (opus, sodium). I have also tried to run the compiled program on 2 other computers (Win 7 and Windows Server 2012). Changing the discord server/bot doesn't seem to fix it either.

**Comment by Neuheit** [comment]
Did you rename your opus and sodium binaries?

**Comment by RubbyGT** [comment]
> Did you rename your opus and sodium binaries?

I did. Followed the instructions on the docs website.

**Comment by Kiritsu** [comment]
what version of the lib do you use? if you use nighlies you must remove lib from dll names

**Comment by Usertothename** [comment]
i am having the same problem both dlls are in folder with program name libopus.dll & libsodium.dll from did i install them wrong they are both 32 bit and i have prefer 32 bit

**Comment by Neuheit** [comment]
They need to be named `opus` and `sodium` respectively.

**Comment by ntamas9503** [comment]
I renamed the two dlls to opus and sodium, but GetConnection() still returns null. Also, I'm joining like this: https://github.com/DSharpPlus/Example-Bots/blob/decf67775fc711e2cf76f8d0a88b4136e037a718/DSPlus.Examples.CSharp.Ex04/ExampleVoiceCommands.cs#L71 , but the call never returns back. Am I missing something?

**Comment by Emzi0767** [comment]
An exception

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ntamas9503** [comment]
That's true, here's the exceptions:
Exception thrown: 'System.DllNotFoundException' in DSharpPlus.VoiceNext.dll
Exception thrown: 'System.DllNotFoundException' in System.Private.CoreLib.dll
Exception thrown: 'System.DllNotFoundException' in System.Private.CoreLib.dll

**Comment by Emzi0767** [comment]
And what does exception type say?

**Comment by ntamas9503** [comment]
It couldn't find libopus.dll, because I renamed it to opus.dll. Nevermind. I fixed this, but that again, when I call .ConnectAsync(), it doesn't return. The bot seems to be joined to the channel, because I see it, but I can't disconnect it.

**Comment by WamWooWam** [comment]
Alexa, remind me to research native nuget packages.

**Comment by MisterAlexD** [comment]
> It couldn't find libopus.dll, because I renamed it to opus.dll. Nevermind. I fixed this, but that again, when I call .ConnectAsync(), it doesn't return. The bot seems to be joined to the channel, because I see it, but I can't disconnect it.

Same issue for me
Using 3.2.3. My system is all x64

**Comment by Emzi0767** [comment]
Install [this package](https://www.nuget.org/packages/DSharpPlus.VoiceNext.Natives/).

**Comment by ntamas9503** [comment]
Installed VoiceNext.Natives nuget, but this call (vnc = await vnext.ConnectAsync(chn);) still doesn't not return.

**Comment by WamWooWam** [comment]
did you also update D#+ itself?

**Comment by ntamas9503** [comment]
No, the lastest on nuget is 3.2.3., which I have too.

**Comment by Neuheit** [comment]
You need to update to the nightlies then.

**Comment by ntamas9503** [comment]
Yeah, changing to nightly fixed all the issues. Thanks for your help, appreciate it!

**Comment by ZecosMAX** [comment]
at `https://www.myget.org/F/dsharpplus-nightly/api/v3/index.json` it says `Feed does not exist.` and so VS's packet manager can't get anything from there.

Even now problem is still there and we can't get latest nightly version.

It seems problems lies somewhere in the end of `VoiceNextClient.ConnectAsync()` because there is no returning value and 
`VoiceNextConnection.ActiveConnections` is still with `count = 0` after bot connected to channel.

**Comment by Neuheit** [comment]
The nightly package was changed. You should use `https://nuget.emzi0767.com/api/v3/index.json` instead.

**Comment by ZecosMAX** [comment]
> The nightly package reference was changed. You should use `https://nuget.emzi0767.com/api/v3/index.json` instead.

maybe update nightly link here then? `https://dsharpplus.emzi0767.com/articles/nightly.html`

**Comment by Neuheit** [comment]
Indeed, thanks for pointing that out.

**Comment by LGFlyper** [comment]
Hello,
I have downloaded DSharpPlus.VoiceNext with the function of Visual Studio "Manage Nuget Packages..." (4.0.0-nightly-00771).
The bot connects to the Channel. On the console the error message: "System.DllNotFoundException: Die DLL "libopus": Das angegebene Modul wurde nicht gefunden. (Ausnahme von HRESULT: 0x8007007E) kann nicht geladen werden." shows up. I have already tryed to manualy install the packages / renamed them and also tryed out the version 4.0.0-nightly-00743. And now i dont know what i should try next.
Hope you can help me and sry for the bad english.
