### ISSUE TITLE
Support for alternatives WebSockets

### ISSUE THREAD

**Issue by LuizFernandoNB** [DSharpPlus/DSharpPlus#519]
# Summary and Details
I am trying to make an alternative to the standard DSharpPlus WebSocket by making a WebSocket that also works on Windows 7, but what keeps me from continuing to work are the classes `SocketCloseEventArgs`, `SocketMessageEventArgs` and `SocketErrorEventArgs`. These classes contains properties with the internal set that do not let me instantiate the method in the right way.

SocketMessageEventArgs class:
https://github.com/DSharpPlus/DSharpPlus/blob/119ec85a377a31a8a114a60ca68063386bed4339/DSharpPlus/EventArgs/WebSocketMessageEventArgs.cs#L11

SocketCloseEventArgs class:
https://github.com/DSharpPlus/DSharpPlus/blob/119ec85a377a31a8a114a60ca68063386bed4339/DSharpPlus/EventArgs/SocketDisconnectEventArgs.cs#L13

https://github.com/DSharpPlus/DSharpPlus/blob/119ec85a377a31a8a114a60ca68063386bed4339/DSharpPlus/EventArgs/SocketDisconnectEventArgs.cs#L18

SocketErrorEventArgs class:
https://github.com/DSharpPlus/DSharpPlus/blob/119ec85a377a31a8a114a60ca68063386bed4339/DSharpPlus/EventArgs/SocketDisconnectEventArgs.cs#L31

# Solution
Remove the internal properties of the classes mentioned above

**Comment by MichalPetryka** [comment]
Alternate WebSocket support was removed few days ago

**Comment by Emzi0767** [comment]
Support itself was not removed, we just no longer ship or provide support for using them, but you can very much create and use your own providers.

**Comment by Emzi0767** [comment]
I should also point out that this issue is a result of an unfortunate oversight, but ultimately we will have to rework the interface to offload the work that should've been done in-library to the library itself. The end result will be much simplified interface for custom providers, as all you will need to do is handle socket events, without decoding or decompressing payloads, as it is right now.

**Comment by LuizFernandoNB** [comment]
I understand and look forward to the optimizations, but is there a problem with removing the internal properties mentioned?

**Comment by LuizFernandoNB** [comment]
I can't use the native DSharpPlus classes to recognize requests and messages, and it would be great to use that, it would help a lot

**Comment by LuizFernandoNB** [comment]
The pull request for this issue has been sent ;)

**Comment by Emzi0767** [comment]
This issue is now resolved as of build 658.
