### ISSUE TITLE
DiscordMessage.GetReactionsAsync() returns duplicate users

### ISSUE THREAD

**Issue by 13xforever** [DSharpPlus/DSharpPlus#524]
# Summary
D#+ Nightlies starting with build 641 include PR #514 which causes a regression with fetching reactions, which may result with duplicate users being returned.

# Details
`DiscordMessage.GetReactionsInternalAsync()` when called with default arguments will pass `limit`=`25, `before`=`null`, `after`=`null`.
Due to the logic of paging, this will result in `before` and `after` always being `null`, which result in identical fetches of reactions until `limit` runs out.
So if there's only 1 reaction on the message, you'll get 25 duplicate users as a result.

# Steps to reproduce
1. call `message.GetReactionsAsync(emoji)` on a message with only 1 reaction
2. observe that you always get list of 25 items with the same user

# Notes
Even though side effect can be mitigated by filtering the results on the client, you're still making excessive number of calls to the api.

**Comment by Emzi0767** [comment]
Confirmed regression, tagging @Kiritsu (author of aforementioned PR)

**Comment by Kiritsu** [comment]
Oops, I suppose that's indeed a case I forgot to test - I'll fix that asap

**Comment by Kiritsu** [comment]
Fixed in #525
