### ISSUE TITLE
Support for upcoming gateway intents

### ISSUE THREAD

**Issue by Neuheit** [DSharpPlus/DSharpPlus#526]
# Summary
As per https://github.com/discordapp/discord-api-docs/pull/1307, Discord will be completely changing how bots can interact with the API. 

# Details
Rather than receiving all WebSocket events by default, bots will soon be required to specify which events to receive via bitwise flags. These will be sent in the identify payload.

**Comment by Emzi0767** [comment]
night'd once again

**Comment by Neuheit** [comment]
I'm currently working on this so I should have something in for it soon.
