### ISSUE TITLE
Allow canceling voice transmissions

### ISSUE THREAD

**Issue by Mmedic23** [DSharpPlus/DSharpPlus#537]
# Summary
Outgoing VoiceNext transmissions should be cancellable.

# Details
I tried killing the ffmpeg process, flushing and disposing the transmission stream but the only half-working solution I could find was disconnecting and reconnecting the bot from the voice channel; but we need a better way to interrupt the playback and clear the stream.

# Notes
Not sure if these are related but I've noticed, as the audio files get bigger, more and more memory is used and not freed by the GC even after playback is complete and the bot is disconnected from the voice channel. I played around with dotMemory a bit and noticed after disconnecting (disposing the connection) and reconnecting a few times, multiple instances of VoiceNextConnection show up in the memory snapshot, not even sure if this is unintended behaviour..

**Comment by Emzi0767** [comment]
If you have multiple instances, that would generally indicate multiple active connections. Library is designed to keep one active instance per guild, a quasi-singleton pattern.

Packets would only linger until next GC cycle.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Mmedic23** [comment]
My bot is in 3 private guilds and only connected to a single voice channel in a single guild, and I see "10 instances" in dotMemory, after calling (;;join / ;;leave) 10 times, that's what concerns me.

![dotmemory-leak](https://user-images.githubusercontent.com/22303140/76063328-cd6e4100-5f87-11ea-90ef-0f6dbbca2bfe.png)

Should calling GC.Collect() get rid of lingering packets? Because it doesn't..

![vs-memory](https://user-images.githubusercontent.com/22303140/76063331-ce06d780-5f87-11ea-9d18-82647070d259.png)

Sorry if I'm misinterpreting these or doing something stupid with my code and wasting your time. Still, my main issue is, a more elegant way to stop voice transmission would be nice.

**Comment by Emzi0767** [comment]
Are you holding a reference to the connection or the transmit stream anywhere? As far as I can tell, we release all references on our end.

**Comment by Mmedic23** [comment]
I've been looking through my code all morning and I'm pretty sure I'm not holding anything. Everything stays in the scope of two methods.

The fact that someone else hasn't reported anything similar leads me to believe it's something on my end but I can't figure it out and it's driving me crazy.

I'll add the two methods I'm talking about, one for connecting to a voice channel, one for disconnecting, if you want to check it out.. The full source is on my repo as [Medic-Bot_CORE](https://github.com/Mmedic23/Medic-Bot_CORE)

```
public async Task Join(CommandContext ctx, ulong channelID = 0)
{
    var voiceNext = ctx.Client.GetVoiceNext();
    var voiceNextConnection = voiceNext.GetConnection(ctx.Guild);
    if (voiceNextConnection != null)
    {
        await ctx.RespondAsync(IsSafeServer(ctx.Guild.Id) ? "Bot zaten ses kanalına bağlı" : "Buradayız işte lan ne join atıyon");
        throw new InvalidOperationException("Already connected, no need to reconnect.");
    }
    if (channelID == 0 && ctx.Member.VoiceState == null)
        voiceNextConnection = await voiceNext.ConnectAsync(ctx.Guild.Channels.Where(ch => ch.Value.Type == DSharpPlus.ChannelType.Voice && ch.Value != ctx.Guild.AfkChannel).OrderBy(ch => ch.Value.Name).FirstOrDefault().Value);
    else if (channelID == 0)
        voiceNextConnection = await voiceNext.ConnectAsync(ctx.Member.VoiceState.Channel);
    else
        voiceNextConnection = await voiceNext.ConnectAsync(ctx.Guild.GetChannel(channelID));
}

public async Task Leave(CommandContext ctx)
{
    var voiceNext = ctx.Client.GetVoiceNext();
    var voiceNextConnection = voiceNext.GetConnection(ctx.Guild);
    if (voiceNextConnection == null)
    {
        await ctx.RespondAsync("Daha gelmedik ki kovuyorsun");
        throw new InvalidOperationException("Not connected, can't leave.");
    }
    await voiceNextConnection.SendSpeakingAsync(false);
    nowPlaying = false;
    queuedSongs.Clear();
    voiceNextConnection.Disconnect();
}
```

**Comment by GSHimself** [comment]
@Mmedic23 I've just notice the same fault. Did you resolve it in any way?

**Comment by Mmedic23** [comment]
I couldn't find a way to "elegantly" stop audio playback. I make the bot disconnect from voice and immediately rejoin. But, I think the memory issues may not be a problem. Maybe GC works differently than the way I guessed, and is slower than I had anticipated. I honestly have no idea.

**Comment by nicknick923** [comment]
using a cancellation token on your FlushAsync should help 

```
Process ffmpegPlayer = Process.Start(psi);
var ffout = ffmpegPlayer.StandardOutput.BaseStream;
VoiceTransmitStream transmitStream = voiceNextConnection.GetTransmitStream();
await ffout.CopyToAsync(transmitStream);
await transmitStream.FlushAsync(*CancelationTokenHere*);
await voiceNextConnection.WaitForPlaybackFinishAsync();
await voiceNextConnection.SendSpeakingAsync(false);
nowPlaying = false;
```

**Comment by Mmedic23** [comment]
The solution above didn't seem to work either.

I pass a token from a CancelationTokenSource to the FlushAsync method, then after starting an audio playback, I cancel the token from a command; but playback does not stop, or pause.
