### ISSUE TITLE
DiscordMessage.CreateReactionAsync always throws error

### ISSUE THREAD

**Issue by Sampleeeee** [DSharpPlus/DSharpPlus#543]
# Summary
CreateReactionAsync always throws an error, at least when I use it in a very basic command
```
[Command("react")]
public async Task React(CommandContext ctx, DiscordEmoji emoji)
{
    await ctx.Message.CreateReactionAsync(emoji);
}
```

# Details
IDE: Visual Studio 2017
Stack Trace: Box is always clear, even with break points
OS: Windows 10 Home Version 1909 Build 18363.720

# Error
```
[2020-03-22 16:55:39 -04:00] [MarvosaBot] [Error] Sample tried executing 'react' but it errored: System.ArgumentException: Could not convert specified value to given type.
Parameter name: value
```

# Notes
I am fairly new to C# and DSharpPlus, I could just be overseeing something

**Comment by Kiritsu** [comment]
What emoji or emote did you tried with and what lib version?

**Comment by SamBehner** [comment]
I use the nuget on latest stable, I used the `:rofl:` emoji

**Comment by Kiritsu** [comment]
Try to update to 4.0 (use slimget feed : ​https://nuget.emzi0767.com/api/v3/index.json)

If you don't know how, follow this: https://dsharpplus.github.io/articles/advanced/nightly_builds.html

**Comment by KillyMXI** [comment]
3.2.3 (not so "stable" anymore) has it's list of emojis way out of date. This makes it fail on many emojis.

4.0 has it's emojis more or less up to date (updated relatively recently).

**Comment by Emzi0767** [comment]
🤣 is indeed missing from the 3.2 emoji mapping, as are all the new twemoji, as well as some old. The mapping we used for 3.2 emojis was flawed, and was not a discord map in the first place. For 4.0 we use the desktop client's internal emoji map to generate the D#+ map. Unless that's not an option, try upgrading to 4.0 nightlies as @Kiritsu suggested.

**Comment by SamBehner** [comment]
I added the slimget feed but I'm still getting the error. I bet I did something wrong when adding it though, do I need to do anything else besides adding that to my project settings?

**Comment by Lachee** [comment]
@SamBehner yes, you need to actually install the version 4 package using your nuget package manager. It will likely tell you there is an update if you go to the option.

**Comment by SamBehner** [comment]
Ah ok, i found it, thanks guys!

**Comment by Emzi0767** [comment]
I should note, and throw this up for consideration: the underlying issue here is outdated/incorrect internal emoji mapping within D#+ prior to 4.x.

Whether this is worth updating and making a 3.2.4 release, is an entire issue. *If* someone was to fix this, we'd need to roll several other fixes into that release as well.

**Comment by Emzi0767** [comment]
As we're nearing a 4.0 RC release, we're officially freezing 3.x.
