### ISSUE TITLE
Websocket is throwing an error when attempting to reconnect

### ISSUE THREAD

**Issue by Skelyos** [DSharpPlus/DSharpPlus#547]
Had a conversation in the D#+ support channel.

This is the error message that my bot is getting. It doesn't really have a specific replication condition it will just happen when the socket disconnects and then attempts to reconnect when `AutoReconnect == true`
 
![](https://cdn.discordapp.com/attachments/379378610412191753/692667273625993316/unknown.png)

This is the line of code that Maxine pointed at when helping me with the issue, looking at the stack trace in the above image it seems like the error originates there.

https://github.com/DSharpPlus/DSharpPlus/blob/90de76fa4e5fa81d8ef21554e65746bfd7988dfe/DSharpPlus/DiscordClient.cs#L438

Wanted some information on how to proceed on this issue and stop this from happening

**Comment by Emzi0767** [comment]
`Utilities.GetDateTimeOffset(this._status.IdleSince.Value)` is what throws.

**Comment by Neuheit** [comment]
So when looking into this I found another issue with the client reconnecting. If you call `DiscordClient.ReconnectAsync()` again after reconnecting the client, it will throw another socket exception: 

```
System.Net.WebSockets.WebSocketException: 'The WebSocket is in an invalid state ('CloseSent') for this operation. Valid states are: 'Open, CloseReceived''
```

At this stack trace:

```
System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState(System.Net.WebSockets.WebSocketState, bool, System.Net.WebSockets.WebSocketState[])	System.Net.WebSockets.WinHttpWebSocketState.InterlockedCheckValidStates(System.Net.WebSockets.WebSocketState[])
	System.Net.WebSockets.WinHttpWebSocket.SendAsync(System.ArraySegment<byte>, System.Net.WebSockets.WebSocketMessageType, bool, System.Threading.CancellationToken)
	System.Net.WebSockets.WebSocketHandle.SendAsync(System.ArraySegment<byte>, System.Net.WebSockets.WebSocketMessageType, bool, System.Threading.CancellationToken)
	System.Net.WebSockets.ClientWebSocket.SendAsync(System.ArraySegment<byte>, System.Net.WebSockets.WebSocketMessageType, bool, System.Threading.CancellationToken)
    DSharpPlus.Net.WebSocket.WebSocketClient.SendMessageAsync(string) in WebSocketClient.cs
	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    DSharpPlus.DiscordClient.SendHeartbeatAsync(long) in DiscordClient.cs
	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
``` 

At this [line](https://github.com/DSharpPlus/DSharpPlus/blob/e95e810f05792faa2f284d4b4568a891900ec871/DSharpPlus/DiscordClient.cs#L2327).

Not sure what could be causing this.

**Comment by Neuheit** [comment]
Nevermind, my issue above was resolved with nightly 679.
