### ISSUE TITLE
Deleting messages with Non-ASCII characters in reason

### ISSUE THREAD

**Issue by usagirei** [DSharpPlus/DSharpPlus#555]
# Summary
When deleting a message, and reason contains non-ascii characters, you'll get an `HttpException`

# Details
As stated above.
Discord's API design choices aside, the reason is sent on an HTTP header instead of message body.

https://github.com/DSharpPlus/DSharpPlus/blob/c6828d38edffe8258db8f0fd4a12fd5f8d865e9c/DSharpPlus/Net/DiscordApiClient.cs#L740-L742
Gets eventually fed into
https://github.com/DSharpPlus/DSharpPlus/blob/c6828d38edffe8258db8f0fd4a12fd5f8d865e9c/DSharpPlus/Net/BaseRestRequest.cs#L60-L65
That gets eventually fed into
https://github.com/DSharpPlus/DSharpPlus/blob/c6828d38edffe8258db8f0fd4a12fd5f8d865e9c/DSharpPlus/Net/RestClient.cs#L286-L289

If the reason contains non-ASCII characters, it gets fed into the header, and the underlying net core http code will throw, as it's not a valid HTTP Header anymore

# Steps to reproduce
1. Try to delete a message, with a reason that contains non-ascii characters, like "Deleted message from <username/display name with eastern characters>"
2. Http Exception, and message is never deleted

# Notes
Did not test, but if they chose to read the reason from a header, Base64 encoding the reason message before putting it in might work, like basic http authorization headers are used.

Alternatively, maybe the endpoint supports sending the reason in the message body, that would avoid an invalid HTTP header too

**Comment by Emzi0767** [comment]
Base64 is not valid for purposes of specifying a reason. The header code behaves correctly as far as I know, in both 3.2 and 4.0, and quick testing confirms this theory:

![ban eval with non-ASCII reason](https://totally-not.a-sketchy.site/AdwZhGj.png)
![ban result](https://totally-not.a-sketchy.site/8g8F5DS.png)

What was the exact string passed to reason? What was the full exception text?

**Comment by usagirei** [comment]
I'm using v3.2.3

Code is part of a role self-assign command
Reason is something along the lines of  `Timeout for 'Usagirei 【ウサギ霊】' role request`

Relevant part of error logs
```
[INFO][gibe] Starting Timeout
[INFO][gibe] Timeout Started
[INFO][gibe] Deleting Message...
[INFO][gibe] Delete Reason: Gibe timeout for 'Usagirei 【ウサギ霊】' role request
[ERROR][gibe] Error Deleting Message: Request headers must contain only ASCII characters.
[ERROR][gibe] Stack Trace:
   at System.Net.Http.HttpConnection.WriteStringAsync(String s)
   at System.Net.Http.HttpConnection.WriteHeadersAsync(HttpHeaders headers, String cookiesFromContainer)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at DSharpPlus.Net.RestClient.ExecuteRequestAsync(BaseRestRequest request)
   at core_bot.Modules.Gibe.GibeCommand.<>c__DisplayClass15_2.<<Execute>b__2>d.MoveNext() in D:\<redacted>\core-bot\Modules\Gibe\GibeCommand.cs:line 152
```

and related code
```csharp
...
// Sends a message and waits 
sent = await ReplyRoleCaptcha(e, gibeable, timeout);
...
// And delete it timeout seconds later
Task.Factory.StartNew(async () =>
{
	try
	{
		shared_log.Info("gibe", "Timeout Started");
		await Task.Delay(timeout * 1000);
		shared_log.Info("gibe", "Deleting Message...");
		shared_log.Info("gibe", "Delete Reason: {0}", $"Gibe timeout for '{member.DisplayName}' role request");
		await sent.DeleteAsync($"Gibe timeout for '{member.DisplayName}' role request");
		shared_log.Info("gibe", "Message Deleted");
	}catch(Exception e)
	{
		shared_log.Error("gibe", "Error Deleting Message: {0}", e.Message);
		shared_log.Error("gibe", "Stack Trace:\n{0}", e.StackTrace);
	}
}, TaskCreationOptions.LongRunning).ConfigureAwait(false);
```

After the fact, after seeing reason doesn't even show in discord audit logs for deleting own messages, i just removed the reason from it.

But the error doesn't happen if set the reason as something else that has no non-ascii characters, like someone else with a nick that is ascii only

**Comment by Emzi0767** [comment]
You're looking at 4.x source, which is not what you're using. I suggest upgrading to nightly.

**Comment by Emzi0767** [comment]
As we're nearing a 4.0 RC release, we're officially freezing 3.x.
