### ISSUE TITLE
Suggestion: Implement Lavalink Load/Region Balancing

### ISSUE THREAD

**Issue by Neuheit** [DSharpPlus/DSharpPlus#557]
# Summary
There are other Lavalink clients (such as eris-lavalink) that try to filter a node based on the closest region to the guild's region or the node with the least amount of usage. An example is [here](https://github.com/briantanner/eris-lavalink/blob/cd4654f90b66ed94d8202e8d3ecd8e4d842e6210/src/PlayerManager.js#L319), and I think it would be useful to see this integrated into the extension.

**Comment by Emzi0767** [comment]
It assumes you have a way of labelling each node's location.

**Comment by Neuheit** [comment]
I was thinking it could be specified in each node's LavalinkConfiguration.
