### ISSUE TITLE
Different data types (question)

### ISSUE THREAD

**Issue by Ludwintor** [DSharpPlus/DSharpPlus#564]
How can I make the variable `member` have data type `DiscordMember` or `DiscordRole` depending on what you mentioned

```c#        [Command("call")]
        public async Task Call(CommandContext ctx, DiscordMember member, int t)

**Comment by Emzi0767** [comment]
4.x supports command overloading

**Comment by Ludwintor** [comment]
Where can I download 4.x ?

**Comment by Emzi0767** [comment]
[RTFM](https://dsharpplus.github.io/articles/advanced/nightly_builds.html)
