### ISSUE TITLE
Login concurrency

### ISSUE THREAD

**Issue by Emzi0767** [DSharpPlus/DSharpPlus#569]
# Summary
For larger bots, Discord supports login concurrency, which allows for logging in multiple shards at once. This is not crucially important, but is worth implementing for completeness' sake at this point.

# Details
Payload field looks like this `"max_concurrency": 1`. It's received from `GET /gateway/bot`.

**Comment by Emzi0767** [comment]
This is related to #546, paging @Neuheit

**Comment by Neuheit** [comment]
Oh interesting, surprised this isn't documented for dapi
