### ISSUE TITLE
Interactivity not working with GuildMemberAdded event?

### ISSUE THREAD

**Issue by sumartk** [DSharpPlus/DSharpPlus#591]
Not sure if I've misread the documentation, but for some reason, interactivity does not seem to work with the GuildMemberAdded event. It does work with normal commands...

`        private async Task OnNewJoinedMember(GuildMemberAddEventArgs eventData)
        {
            var interactivity = client.GetInteractivityModule();

            await eventData.Member.SendMessageAsync("Welkom! Choose one of the roles");

            var msg = await interactivity.WaitForMessageAsync(messagectx => messagectx.Author.Id == eventData.Member.Id);

            if(msg != null)
            {
                switch(msg.Message.Content)
                {
                    case "Lid":
                        await eventData.Guild.GrantRoleAsync(eventData.Member, eventData.Guild.Roles.FirstOrDefault(x => x.Name == "Lid"));
                        break;
                    case "DVP":
                        await eventData.Guild.GrantRoleAsync(eventData.Member, eventData.Guild.Roles.FirstOrDefault(x => x.Name == "DVP"));
                        break;
                    case "Nieuw":
                        await eventData.Guild.GrantRoleAsync(eventData.Member, eventData.Guild.Roles.FirstOrDefault(x => x.Name == "Nieuw"));
                        break;
                    default:
                        await eventData.Member.SendMessageAsync("Die rol bestaat niet...");
                        break;
                }
            }
        }`

**Comment by Emzi0767** [comment]
You're deadlocking the gateway thread. Force your handler off of it.

**Comment by sumartk** [comment]
What do you mean by force? Remove the handler from the event itself completely, or from the thread? If latter, how would I do that?

**Comment by Emzi0767** [comment]
[Like this](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.run?view=netcore-3.1)

**Comment by s-kartej** [comment]
Aha, I see. Still running into it sadly... not sure what I'm doing wrong... my notion of threading in C# isn't too great...

`            client.GuildMemberAdded += (eventData) =>
            {
                return Task.Run(async () =>
                {
                    var interactivity = client.GetInteractivityModule();

                    await eventData.Member.SendMessageAsync("Welkom!");

                    var msg = await interactivity.WaitForMessageAsync(messagectx => messagectx.Content.Equals("continue"));

                    if (msg != null)
                    {
                        switch (msg.Message.Content)
                        {
                            case "Lid":
                                await eventData.Guild.GrantRoleAsync(eventData.Member, eventData.Guild.Roles.FirstOrDefault(x => x.Name == "Lid"));
                                break;
                            case "DVP":
                                await eventData.Guild.GrantRoleAsync(eventData.Member, eventData.Guild.Roles.FirstOrDefault(x => x.Name == "DVP"));
                                break;
                            case "Nieuw":
                                await eventData.Guild.GrantRoleAsync(eventData.Member, eventData.Guild.Roles.FirstOrDefault(x => x.Name == "Nieuw"));
                                break;
                            default:
                                await eventData.Member.SendMessageAsync("Die rol bestaat niet...");
                                break;
                        }
                    }
                });
            };`

**Comment by Emzi0767** [comment]
> my notion of threading in C# isn't too great...

Then your skill level is insufficient to make a Discord bot.
