### ISSUE TITLE
Direct (PM) Message

### ISSUE THREAD

**Issue by mtugnoli** [DSharpPlus/DSharpPlus#601]
Is it possible to send a direct message to user ?

**Comment by Speyd3r** [comment]
https://dsharpplus.github.io/api/DSharpPlus.Entities.DiscordMember.html?q=sendmes#DSharpPlus_Entities_DiscordMember_SendMessageAsync_System_String_System_Boolean_DSharpPlus_Entities_DiscordEmbed_

**Comment by mtugnoli** [comment]
I just studing with https://github.com/DSharpPlus/Example-Bots samples,
Is there an example inherent in private messages?

**Comment by Speyd3r** [comment]
A DM channel is just another channel, like a channel in a guild. That method is basically just an extension. It creates a DM Channel, thats a method on DiscordMember and then sends the message to that channel.
I dont think there are any examples that specifically show how DMs work, as its just another channeltype

**Comment by mtugnoli** [comment]
Thank You, is right !
