### ISSUE TITLE
Add Discord Role, HELP

### ISSUE THREAD

**Issue by mehmetarslann** [DSharpPlus/DSharpPlus#607]
Hello, I need help with something.
"SELECT * from launcher_users with logintate = 1"
There is such a query. Can I give the user a role based on the value of 1 or 0 returned from here?

**Comment by Emzi0767** [comment]
That is not a D#+ problem. Can you? Probably. It's up to you to solve it.

**Comment by mehmetarslann** [comment]
How to give role, is there any source you can send.  Thanks for everything
