### ISSUE TITLE
Is there a method for mass deleting messages from a text channel?

### ISSUE THREAD

**Issue by YanGusik** [DSharpPlus/DSharpPlus#609]
# Summary
Hello, is there bulk delete in this library? Quickly clear messages on the channel.
[Discord Api Bulk](https://discord.com/developers/docs/resources/channel#bulk-delete-messages)

**Comment by Kiritsu** [comment]
https://dsharpplus.github.io/api/DSharpPlus.Entities.DiscordChannel.html?q=deletemessage#DSharpPlus_Entities_DiscordChannel_DeleteMessagesAsync_System_Collections_Generic_IEnumerable_DSharpPlus_Entities_DiscordMessage__System_String_

**Comment by Emzi0767** [comment]
Man, reading is very hard.

**Comment by YanGusik** [comment]
> Man, reading is very hard.

Sorry, I already read this and there was a misunderstanding, I just thought that DeleteMessagesAsync just calls DeleteMessageAsync and deletes each message one by one.

Then I looked closely that this.Discord.ApiClient.DeleteMessagesAsync () was called and that executes bulk delete
```
this.DoRequestAsync(this.Discord, this.Rest.GetBucket(RestRequestMethod.POST, "/channels" + "/:channel_id" + "/messages" + "/bulk-delete", ...
```
