### ISSUE TITLE
Discussing about discordapp.com and discord.com domain

### ISSUE THREAD

**Issue by Creta5164** [DSharpPlus/DSharpPlus#614]
# Summary
Discord developer team noticed to me for future of Discord's bot and developer applications news.

> It's your friendly neighborhood Bots & API Team checking in. If you're reading this message, it's because you created an application in our Developer Portal: https://discord.com/developers.
> 
> We come bearing news, updates, and a one-time "Get Out of Rate Limits Free" card! Okay well, not the last one, but it caught your attention. We've got a few things to share with you, so let's get on with it.
> ...
> ...
> ...
> Discord API Domain Migration
> 
> Last month, we excitedly announced our official move to discord.com. It was a long time in the making, and the work isn't done yet! For now, our API will continue to handle requests made to discordapp.com. On **November 7, 2020** we will be dropping support for the discordapp.com domain **in favor of discord.com**. Please ensure that your libraries, bots, and applications are updated accordingly.
> 
> Due to technical constraints, our CDN domain will not be migrated and **will remain cdn.discordapp.com** for the foreseeable future.
> ...
> ...
> ...
> For those of you excited for the fancy new features shown in our blog post...keep being patient! We're putting some finishing touches on new API tools that will enable features like the ones you saw, and we can't wait to show them to you. Be prepared SLASH excited for the next coming couple months. If you haven't seen our blog post, go read it now: 
> https://blog.discord.com/the-future-of-bots-on-discord-4e6e050ab52e
> 
> Happy coding!

# Details
Importantly part is **Discord API Domain Migration**.

> Last month, we excitedly announced our official move to discord.com. It was a long time in the making, and the work isn't done yet! For now, our API will continue to handle requests made to discordapp.com. On **November 7, 2020** we will be dropping support for the discordapp.com domain **in favor of discord.com**. Please ensure that your libraries, bots, and applications are updated accordingly.

I checked DSharpPlus uses `cdn.discordapp.com` domain in this repository.  
https://github.com/DSharpPlus/DSharpPlus/search?q=cdn.discordapp.com

So I think may this should be fix to `*.discord.com` in later future. (not now)

> Due to technical constraints, our CDN domain will not be migrated and **will remain cdn.discordapp.com** for the foreseeable future.

**Comment by Speyd3r** [comment]
What? Why should it be changed at all? The cdn isn't changing, so i see no need on already changing it in the lab as it would just break things

**Comment by Creta5164** [comment]
I see, because I was wondering if there was something to do! 👀

**Comment by Emzi0767** [comment]
This was implemented months ago
