### ISSUE TITLE
Question about bot making

### ISSUE THREAD

**Issue by PLesiu6** [DSharpPlus/DSharpPlus#617]
Few Questions:

1.Can you make command that waits for another command ?
for example:
-User: !command
-User: _command_
-Bot: "_command_"
-User: **command2**
-Bot: "**command2**"

2. Can you make music bot with d#plus ?

**Comment by Speyd3r** [comment]
1. Kinda? You can just call another commands method from within the first command and wait for that

2. Yes, use the nightly builds for that as v3 is broken in that regard, also v4 nightly has Lavalink support for music features
