### ISSUE TITLE
Editing Bot messages

### ISSUE THREAD

**Issue by goldminer127** [DSharpPlus/DSharpPlus#620]
I want to try and edit the bot's response message to a command. I tried to use the following line to edit an embed the bot sent.
```
await ctx.Message.ModifyAsync(null, dembed);
```
ctx is CommandContext.  ctx.Message only gets the message that initiated the command, is there any way to get the response message the bot sends after a command is initiated and edit it?

**Comment by Kiritsu** [comment]
You already got told in the guild that SendMessageAsync returns the sent message, so you wanna assign it a variable and then call ModifyAsync on it.

**Comment by goldminer127** [comment]
Oh I completely forgot that I can assign the message to a variable. Thanks so much!
