### ISSUE TITLE
Missing Guild Widget Methods

### ISSUE THREAD

**Issue by Neuheit** [DSharpPlus/DSharpPlus#650]
# Summary
There are new widget endpoints that should be implemented as methods in the `DiscordGuild`

The methods include: 

[Get Guild Widget Settings](https://discord.com/developers/docs/resources/guild#get-guild-widget-settings)
[Modify Guild Widget](https://discord.com/developers/docs/resources/guild#modify-guild-widget)
[Get Guild Widget](https://discord.com/developers/docs/resources/guild#get-guild-widget)

**Comment by Neuheit** [comment]
Edit: These should also be added to the `DiscordRestClient`

**Comment by spydacarnage** [comment]
I'm taking a look at whether this is something I can contribute, but I'm looking for a little advice, please.

Looking at the API, the channels and (especially) members returned by Get Guild Widget aren't "real" objects.

The channels could be extrapolated into full DiscordChannel objects through the Guild, but the members only have a sequential Id, not a Snowflake, and no discriminator, so I don't think these can be made into DiscordMember (or DiscordUser) objects.  Would you suggest a new DiscordWidgetMember object, or do you have a standard other method for this sort of situation?

**Comment by Neuheit** [comment]
> Looking at the API, the channels and (especially) members returned by Get Guild Widget aren't "real" objects.

That's correct, we retrieve the partial objects from rest, and on the `DiscordGuild` you would check if those channels/members exist in cache with those IDs, and if so update the object with the respective cached entities. For REST it would just return those partial objects.

**Comment by Neuheit** [comment]
Those would become properties for a new `DiscordWidget` class.

**Comment by spydacarnage** [comment]
Sorry, I think I didn't make my question clear enough.  For the members, as shown in the example below, they will never be in the cache, because the Id isn't a real Snowflake (I've tested the API in Postman and that isn't just bad example data)

```js
    "members": [
        {
            "id": "0",
            "username": "1234",
            "discriminator": "0000",
            "avatar": null,
            "status": "online",
            "avatar_url": "..."
        }
    ]
```

**Comment by Neuheit** [comment]
Looks like you're right, so then I suppose 2 new classes: `DiscordWidget` to encapsulate everything, and something like `DiscordIntegration` that represents each of those integration "members".

**Comment by spydacarnage** [comment]
Currently going with DiscordWidgetMember to get it working (nothing like being descriptive, eh?)
Name can be modified later...
