### ISSUE TITLE
Discords New Private Channel system breaks PermissiosnFor

### ISSUE THREAD

**Issue by Soyvolon** [DSharpPlus/DSharpPlus#656]
# Summary
When channels are considered "Private" with Discords new private channel system, the checks run in PermissionsFor will return false even when the bot has the correct permissions.

# Details
.NET Core 3.1 D#+ Nightly-00743 (Latest from master branch as of 10/19/2020 22:00 EST)

When checking permission for the Connect to voice permission, which is a permission that is not able to be modified on a per-channel basis, DSharpPlus wrongly identifies a bot as not having the permission when it does if a command is run from a Private Channel using Discord's new private channel system. Running the same command in a normal channel will cause the command to run properly, even if the same channel and bot permissions are set.

```
public Permissions PermissionsFor(DiscordMember mbr)
        {
            // . . .
            // assign permissions from member's roles (in order) - UseVoice is allowed here
            perms |= mbRoles.Aggregate(Permissions.None, (c, role) => c | role.Permissions);

            // Adminstrator grants all permissions and cannot be overridden
            if ((perms & Permissions.Administrator) == Permissions.Administrator)
                return PermissionMethods.FULL_PERMS;

            // channel overrides for roles that member is in
            var mbRoleOverrides = mbRoles
                .Select(xr => this._permissionOverwrites.FirstOrDefault(xo => xo.Id == xr.Id))
                .Where(xo => xo != null)
                .ToList();
            
            // assign channel permission overwrites for @everyone pseudo-role
            var everyoneOverwrites = this._permissionOverwrites.FirstOrDefault(xo => xo.Id == everyoneRole.Id);
            if (everyoneOverwrites != null)
            {
                perms &= ~everyoneOverwrites.Denied;
                perms |= everyoneOverwrites.Allowed;
            } // UseVoice is no longer allowed, but Speak still is.

            // assign channel permission overwrites for member's roles (explicit deny)
            perms &= ~mbRoleOverrides.Aggregate(Permissions.None, (c, overs) => c | overs.Denied);
            // assign channel permission overwrites for member's roles (explicit allow)
            perms |= mbRoleOverrides.Aggregate(Permissions.None, (c, overs) => c | overs.Allowed);
            // UseVoice still not allowed, but Speak is.
            // . . . 
        }
```
When the permissions are first received, the bot has `UseVoice` in its permissions list, however, it later loses that permission when assigning channel perm overwrites for the everyone pseudo-role.

# Steps to reproduce
1. Create a private channel with Discords new private channel system. (I'll send an invite to a server with this enabled if someone needs it for further testing)
2. Make sure the bot has the Connect to voice permission globally.
3. Use a command with the `[RequireBotPermission(Permissions.UseVoice)]` attribute in the private channel.
4. The command will fail.

# Notes
This was only tested with the `UseVoice` permission, but there may be others that have this same problem.

**Comment by Emzi0767** [comment]
Are you using an official build from SlimGet?

**Comment by Soyvolon** [comment]
Yes, I updated from the visual studio package manager to the latest and tested the issue on the latest version before posting this issue.

**Comment by Soyvolon** [comment]
Permission setup on discord was invalid.
