### ISSUE TITLE
DiscordMessage.ModifyAsync Cannot Convert From DSharpPlus.Entities.DiscordEmbedBuilder to DSharpPlus.Entities.Optional<DSharpPlus.Entities.DiscordEmbed>

### ISSUE THREAD

**Issue by cdegeorge** [DSharpPlus/DSharpPlus#657]
# Summary
When I attempted to edit an embed message I get the error "Cannot Convert From DSharpPlus.Entities.DiscordEmbedBuilder to DSharpPlus.Entities.Optional<DSharpPlus.Entities.DiscordEmbed>"

# Details

- DSharpPlus Nightly Build 00743
- .NET Core 3.1
- Windows 10

Partial Code:
```
DiscordEmbedBuilder embed = new DiscordEmbedBuilder
{
    Title = "High-low",
    Color = DiscordColor.DarkBlue
};

DiscordMessage message = await ctx.RespondAsync(embed: embed).ConfigureAwait(false);

await message.ModifyAsync(embed: embed).ConfigureAwait(false);
```

# Steps to reproduce
1. Send a message with RespondAsync()
2. Attempt to modify it with ModifyAsync()

**Comment by Kiritsu** [comment]
You have to build your embed with method `Build`.

**Comment by cdegeorge** [comment]
@Kiritsu Thanks! Did I miss this in the documentation somewhere?

**Comment by spydacarnage** [comment]
It's because RespondAsync and SendMessageAsync have a parameter of `DiscordEmbed`, for which there is an implicit operator in the DiscordEmbedBuilder for, whereas in ModifyAsync, the parameter is for an `Optional<DiscordEmbed>`, even though it is optional in both.
