### ISSUE TITLE
Roles of the member is not updated

### ISSUE THREAD

**Issue by NeuroWhAI** [DSharpPlus/DSharpPlus#660]
Since some functions of 3.x do not work at some point,
I am migrating my project to version 4.
But I still have problems.
When I use `GrantRoleAsync` or `RevokeRoleAsync` of `DiscordMember`, It is not reflected to `Roles`.

I use .Net Core 2.1 and D#+ 4.0.0-nightly-00745.

Here is the code.

```cs
(First step):

var guild = discord.GetGuildAsync(DiscordConstants.GuildId).Result;
var member = guild.GetMemberAsync(id).Result;
var fooRole = guild.GetRole(DiscordConstants.FooRoleId);
var barRole = guild.GetRole(DiscordConstants.BarRoleId);

// In this example, it is assumed that the user has the Foo role.
if (member.Roles.Count() > 0 && member.Roles.Any(role => role.Name == "Foo"))
{
    // Grant Bar, Revoke Foo.
    member.GrantRoleAsync(barRole, reason).Wait();
    member.RevokeRoleAsync(fooRole, reason).Wait();
}

(In other method that called in few seconds later):

var guild = discord.GetGuildAsync(DiscordConstants.GuildId).Result;
var member = guild.GetMemberAsync(id).Result;
var fooRole = guild.GetRole(DiscordConstants.FooRoleId);
var barRole = guild.GetRole(DiscordConstants.BarRoleId);

// This condition is not satisfied.
// `Roles` still has "Foo" and doesn't have "Bar".
if (member.Roles.Count() > 0 && member.Roles.Any(role => role.Name == "Bar"))
{
    // Grant Foo, Revoke Bar. (Never executed.)
    member.GrantRoleAsync(fooRole, reason).Wait();
    member.RevokeRoleAsync(barRole, reason).Wait();
}
```

Need help.

**Comment by Neuheit** [comment]
You are forcing all of your async methods to be synchronous with `.Result` and `.Wait()`. Don't do that, `await` them instead.

**Comment by Emzi0767** [comment]
I suggest you learn C# and TAP.

Regarding this particular breakage, I recommend you visit [Discord Developers](https://discord.gg/discord-developers) and ask them. They're responsible.

**Comment by NeuroWhAI** [comment]
I know this is not good code. But is that related to my situation?

**Comment by Speyd3r** [comment]
Perhaps its because of intents?

**Comment by Neuheit** [comment]
> I know this is not good code. But is that related to my problem?
> I just make it works.

I would fix what I mentioned above first. If you're still having issues with that it is likely due to intents.

**Comment by NeuroWhAI** [comment]
Solved by turning on the bot's intent setting which is `SERVER MEMBERS INTENT` in the developer portal.
Thank you all.
