### ISSUE TITLE
Lavalink Reconnection Problem

### ISSUE THREAD

**Issue by cking** [DSharpPlus/DSharpPlus#661]
# Summary
It would be awesome if you can either:
- Easily and manually íssue a reconnect for a Lavalink Node Connection (for the Disconnect event) [and thus disabling the internal reconnect event]
- Or create  custom reconnect logic as a callback/lambda function

Right now there is an undocumented reconnect programmed in, that only fires once, and immediatly after a reconnect.
If you are restarting the LL process (or "worse", the server), its highly unlikely that this will connect to the node.

# Details
Details for this are pretty much irrelevant, but:
- .NET core 3.1
- Windows 10 Ultimate, but applies to Linux too
- IDE Rider

# Steps to reproduce
1. Create a Discord Connection
2. Add LavalinkEx
3. Connect to a Lavalink Node
4. Kill the Lavalink Node

# Notes
Discord Convo: https://discord.com/channels/379378609942560770/379378610412191753/772786931602948116

**Comment by Emzi0767** [comment]
16b33e1359fb7fe76ce734c6c9001ea7e23fc507 contains a quick and dirty implementation that resolves this. See if it works for you.

**Comment by cking** [comment]
It works, though I am a bit annoyed by the logging of the error in D#+
I don't wanna set the logging of D#+ to ignore, but it is pretty... well... fatal that it spams my console once a node disappears.
But thats less of a problem. Like I said, I can tell Serilog to ignore D#+'s logging messages, I'D prefer to not do that though :)

V = Verbose, F = Fatal, I = Information
```
[V 15:00:48] Maria.Naruse.Application: trying to reconnect to node localhost...{}
[F 15:00:52] DSharpPlus.BaseDiscordClient: Failed to connect to Lavalink{"EventId": {"Id": 401, "Name": "LavalinkConnectionError"}, 
[F 15:00:52] DSharpPlus.BaseDiscordClient: Failed to connect to Lavalink{"EventId": {"Id": 401, "Name": "LavalinkConnectionError"}, 
[I 15:01:00] Maria.Naruse.Application: reconnected to localhost: True{}
```
(I snipped the whole stack traces for both messages)


PS: For those who want to do something similar, this is what I am using (basically increase the number of reconnection tries up to 10s, and then loop.):
```cs
        private readonly AsyncPolicy lavaLinkRetryPolicy = Policy.Handle<WebSocketException>()
            .WaitAndRetryForeverAsync(retryNo => TimeSpan.FromMilliseconds(100 * Math.Min(retryNo, 100)));
```

**Comment by Emzi0767** [comment]
The logging interface should allow you to filter based on EventId.

**Comment by Neuheit** [comment]
Closing because the reconnection issue is resolved.
