### ISSUE TITLE
Guild.GetAllMembersAsync() 403 Unauthorized

### ISSUE THREAD

**Issue by cdegeorge** [DSharpPlus/DSharpPlus#663]
# Summary
When I call Guild.GetAllMembersAsync() I receive the "DSharpPlus.Exceptions.UnauthorizedException: Unauthorized: 403" in the console.

# Details
- .NET Core 3.1
- DSharpPlus 4.0.0-nightly-00748

Inside a command method I have:
```
IReadOnlyCollection<DiscordMember> members = await ctx.Guild.GetAllMembersAsync();
```

**Comment by Speyd3r** [comment]
You're missing the intents

**Comment by cdegeorge** [comment]
Thanks @Speyd3r! Do you know if there is a way to get multiple intents without using All?

**Comment by Speyd3r** [comment]
Just add the enums together
``EnumType.Value1 | EnumType.Value2 | ... and so on``

**Comment by cdegeorge** [comment]
Thanks again!
