### ISSUE TITLE
Request: disable UNKNOWN_EVENT warning if there is handler

### ISSUE THREAD

**Issue by RedApelsin** [DSharpPlus/DSharpPlus#664]
### Summary
I already added a handler for UNKNOWN_EVENT, but it still gives me a warning

### Details
There is added event handler for Unknow_event:
```cs
        public static Task UnknownEvent(UnknownEventArgs e)
        {
            Program.discord.DebugLogger.LogMessage(LogLevel.Info, "SelfBot", $"Account Event: {e.EventName}", DateTime.Now);
            return Task.CompletedTask;
        }
```
```cs
            discord.UnknownEvent += Events.UnknownEvent;
```

### Screenshots
![image](https://user-images.githubusercontent.com/59859860/98466395-4fca9700-21e0-11eb-8920-e3c69afb5fb0.png)

**Comment by Emzi0767** [comment]
Userbots are not supported.
