### ISSUE TITLE
Visual Studio says "The name 'LogLevel' does not exist in the current context"

### ISSUE THREAD

**Issue by fazelukario** [DSharpPlus/DSharpPlus#667]
So VS says that 'LogLevel' does not exist, librarys are conected and another parts of D#+ work propertly.
![image](https://user-images.githubusercontent.com/46999684/99134953-b7417600-2628-11eb-818d-43c5b77e98f8.png)
```
Token = BotSettings.Token,
LogLevel = LogLevel.Info
```
![image](https://user-images.githubusercontent.com/46999684/99134985-d5a77180-2628-11eb-9444-fd6811412889.png)
`Error	CS0103	The name 'LogLevel' does not exist in the current context`

**Comment by Neuheit** [comment]
Please see https://dsharpplus.github.io/articles/beyond_basics/logging/default.html for the new logging implementation.

**Comment by fazelukario** [comment]
So, i'll fix one error, but whats wrong now?
![image](https://user-images.githubusercontent.com/46999684/99139089-7b191000-263e-11eb-9bd2-fc90480dbb16.png)
```
var cfg = new DiscordConfiguration
            {
                Token = BotSettings.Token,
                MinimumLogLevel = LogLevel.Information,
                AutoReconnect = true,
                TokenType = TokenType.Bot,
                UseInternalLogHandler = true
            };
```

**Comment by Neuheit** [comment]
`UseInternalLogHandler ` is obsolete, so you can remove it. 

Also please join our Discord server to ask these kinds of support questions: https://discord.gg/nTk7HgF

**Comment by fazelukario** [comment]
About `UseInternalLogHandler` i understand, but about `LogLevel` i dont have any ideas.
![image](https://user-images.githubusercontent.com/46999684/99139421-08f5fa80-2641-11eb-97c0-96d7f3962f30.png)

**Comment by Neuheit** [comment]
You need to import `Microsoft.Extensions.Logging`.

**Comment by Neuheit** [comment]
The library should have it imported by default. You should use intellisense to resolve those kinds of syntax errors.

**Comment by fazelukario** [comment]
Whats about this
![image](https://user-images.githubusercontent.com/46999684/99140345-d13f8080-2649-11eb-96dd-243d9bba3252.png)
`Client.DebugLogger.LogMessageReceived += Listeners.LoggerListener.LogOnLogMessageReceived;`

**Comment by Neuheit** [comment]
Like I mentioned before, please continue this discussion in our support server.
