### ISSUE TITLE
DebugLoger doesn't exist.

### ISSUE THREAD

**Issue by fazelukario** [DSharpPlus/DSharpPlus#670]
![99140345-d13f8080-2649-11eb-96dd-243d9bba3252](https://user-images.githubusercontent.com/46999684/99160867-a9592700-26f4-11eb-99f2-15a86a9290f7.png)

`Client.DebugLogger.LogMessageReceived += Listeners.LoggerListener.LogOnLogMessageReceived;`

I will be very grateful for your help.

**Comment by Emzi0767** [comment]
Read the docs
