### ISSUE TITLE
Inline Replies

### ISSUE THREAD

**Issue by Neuheit** [DSharpPlus/DSharpPlus#676]
# Summary
This issue is for tracking developments related to [inline replies](https://github.com/discord/discord-api-docs/pull/2118). Right now it looks like it will be using message references as well as adding new data to message and activity types.

**Comment by Neuheit** [comment]
Currently waiting on https://github.com/discord/discord-api-docs/pull/2118 to be merged.

**Comment by fireflamemm** [comment]
[discord/discord-api-docs#2118](https://github.com/discord/discord-api-docs/pull/2118) was merged.

**Comment by VelvetThePanda** [comment]
How hard could it be :^)

**Comment by fireflamemm** [comment]
Famous last words. 

Anyway, so to start a conversation about the expected changes. 

1. Add the ReferencedMessage Property to the DiscordMessage. Should have type DiscordMessage
2. Update the XML for the MessageReference to reflect the changes in the way that it has been used
3. Add the new message type to the Enum MessageType
4. Add a ReplyAsync method to the DiscordMessage class (I'm going based on the fact that message_id is the only requirement to reply to a message according [to the comment thread](https://github.com/discord/discord-api-docs/pull/2118#issuecomment-718304550) and [this portion of the docs](https://github.com/discord/discord-api-docs/blob/master/docs/resources/Channel.md#create-message--post-channelschanneliddocs_resources_channelchannel-objectmessages) ).
5. Add a ReplyAsync method to the CommandContext class.
6. Since we don't have an AllowedMentions class as seen [here](https://github.com/discord/discord-api-docs/blob/master/docs/resources/Channel.md#allowed-mentions-object), we should make a boolean on our ReplyAsync methods to specify whether to ping the user or not. Should we default to false on pinging on our side? Or should we leave the default behavior up to Discord? 

This is all I can think of right now, and I might have missed some things.  Let me know what y'all think.

**Comment by VelvetThePanda** [comment]
Well at least on the client side, it defaults to mentioning. 

I'd be more than happy to help when it comes to adding the DiscordMessage#ReplyAsync and CommandContext#ReplyAsync.

**Comment by VelvetThePanda** [comment]
Also just gonna go on a hunch, given that the message reference only has a few Ids instead of a proper message object, I take it that property would only be a partial-object, and it's up to the end user to actually retrieve the message from REST if they want to get the full object? I don't know the deep inner-workings of the API, so that's my best guess :p

**Comment by fireflamemm** [comment]
From my (admittedly very basic) understanding `referenced_messaged` is a full message object. At least in V8. Not in V6. It doesn't even exist in V6.

**Comment by VelvetThePanda** [comment]
Last I checked in the docs, it just sends the id of the message and author, but not full object. I'll take a glance again.

**Comment by fireflamemm** [comment]
There are two fields, `message_reference` (that one is what you are talking about) and `referenced_message` and that is the one I'm talking about.

**Comment by VelvetThePanda** [comment]
Ohh yeah, that makes sense then. My bad.

**Comment by VelvetThePanda** [comment]
https://discord.com/developers/docs/resources/channel#message-object-message-structure I see it here.

Also good grief those asterisks lmao

**Comment by Emzi0767** [comment]
Implementing this will require us to bump GW/API to v8.

**Comment by Neuheit** [comment]
> 
> 
> Implementing this will require us to bump GW/API to v8.

Mason stated that this is still available for v6, but we'll just have to use an existing type rather than a new one.

**Comment by Neuheit** [comment]
> Famous last words.
> 
> Anyway, so to start a conversation about the expected changes.
> 
> 1. Add the ReferencedMessage Property to the DiscordMessage. Should have type DiscordMessage
> 2. Update the XML for the MessageReference to reflect the changes in the way that it has been used
> 3. Add the new message type to the Enum MessageType
> 4. Add a ReplyAsync method to the DiscordMessage class (I'm going based on the fact that message_id is the only requirement to reply to a message according [to the comment thread](https://github.com/discord/discord-api-docs/pull/2118#issuecomment-718304550) and [this portion of the docs](https://github.com/discord/discord-api-docs/blob/master/docs/resources/Channel.md#create-message--post-channelschanneliddocs_resources_channelchannel-objectmessages) ).
> 5. Add a ReplyAsync method to the CommandContext class.
> 
> Since we don't have an AllowedMentions class as seen [here](https://github.com/discord/discord-api-docs/blob/master/docs/resources/Channel.md#allowed-mentions-object), we should make a boolean on our ReplyAsync methods to specify whether to ping the user or not. Should we default to false on pinging on our side? Or should we leave the default behavior up to Discord?
> 
> This is all I can think of right now, and I might have missed some things. Let me know what y'all think.

1. Yes
2. Yes
3. Yes (make sure it's type 0)
4. This can probably be added as an optional parameter to `SendMessageAsync()` instead. Aside from the view message history permission checking, make sure to follow the prerequisites at the bottom of [create message](https://discord.com/developers/docs/resources/channel#create-message). Make sure this is also added to the DiscordRestClient.
5. Similarly to above, it should be made an optional parameter in `RespondAsync()` 

ChannelId for `DiscordMessageReference` will also need to be made nullable.
There will also need to be a `RepliedUser` property added to mentionables as per the comment you linked..

**Comment by Emzi0767** [comment]
Since this is an entirely new feature, adding new type vs reusing existing has little meaning here. We have to migrate to v8 anyways, so better start now than later.

**Comment by Emzi0767** [comment]
Should also point out that the only real point of staying on v6 - optional intents - is entirely moot now.

**Comment by VelvetThePanda** [comment]
Furthermore, I feel like adding more parameters to `CommandContext#RespondAsync` and `DiscordChannel#SendMessageAsync` is less than ideal, thought the latter would have to have an extra parameter since you need to pass the user. Meh. I digress.

**Comment by Neuheit** [comment]
> Furthermore, I feel like adding more parameters to `CommandContext#RespondAsync` and `DiscordChannel#SendMessageAsync` is less than ideal, thought the latter would have to have an extra parameter since you need to pass the user. Meh. I digress.
> 
> Though I guess this is less important given that parameters can be made optional, but ¯\_(ツ)_/¯

Optional parameters are ideal since `SendMessageAsync` is meant to mirror Discord's `Create Message` on the API docs.

**Comment by VelvetThePanda** [comment]
Fair enough. Not like I've actually really done anything on the lib yet, so it's not exactly detrimental to just add it to the method instead of creating a whole new one.

**Comment by fireflamemm** [comment]
So, while I was attempting to understand the codebase well enough to actually start on adding the properties I noticed that we don't keep track of MessageReference when using the internal copy constructor. Do we need to add this at this time?

https://github.com/DSharpPlus/DSharpPlus/blob/0c04045a2a12fd4f092e35cfc602dd1ad2136ea8/DSharpPlus/Entities/DiscordMessage.cs#L45-L71

**Comment by VelvetThePanda** [comment]
> > Famous last words.
> > Anyway, so to start a conversation about the expected changes.
> > 
> > 1. Add the ReferencedMessage Property to the DiscordMessage. Should have type DiscordMessage
> > 2. Update the XML for the MessageReference to reflect the changes in the way that it has been used
> > 3. Add the new message type to the Enum MessageType
> > 4. Add a ReplyAsync method to the DiscordMessage class (I'm going based on the fact that message_id is the only requirement to reply to a message according [to the comment thread](https://github.com/discord/discord-api-docs/pull/2118#issuecomment-718304550) and [this portion of the docs](https://github.com/discord/discord-api-docs/blob/master/docs/resources/Channel.md#create-message--post-channelschanneliddocs_resources_channelchannel-objectmessages) ).
> > 5. Add a ReplyAsync method to the CommandContext class.
> > 
> > Since we don't have an AllowedMentions class as seen [here](https://github.com/discord/discord-api-docs/blob/master/docs/resources/Channel.md#allowed-mentions-object), we should make a boolean on our ReplyAsync methods to specify whether to ping the user or not. Should we default to false on pinging on our side? Or should we leave the default behavior up to Discord?
> > This is all I can think of right now, and I might have missed some things. Let me know what y'all think.
> 
> 1. Yes
> 2. Yes
> 3. Yes (make sure it's type 0)
> 4. This can probably be added as an optional parameter to `SendMessageAsync()` instead. Aside from the view message history permission checking, make sure to follow the prerequisites at the bottom of [create message](https://discord.com/developers/docs/resources/channel#create-message). Make sure this is also added to the DiscordRestClient.
> 5. Similarly to above, it should be made an optional parameter in `RespondAsync()`
> 
> ChannelId for `DiscordMessageReference` will also need to be made nullable.
> There will also need to be a `RepliedUser` property added to mentionables as per the comment you linked. The default behavior should be up to Discord for mentioning.

@fireflamemm brought up an interesting point. "Should the user pass the message Id, or should they pass the message object, and expect the library to handle it". Both make sense, since we can always grab the message Id from that message object, and then go about the normal reply flow.

**Comment by fireflamemm** [comment]
https://github.com/VelvetThePanda/DSharpPlus/blob/d1a49c77ac2f03efcda8ea2d2bb2469fe8736534/DSharpPlus/Clients/DiscordClient.Dispatch.cs#L1179-L1190

Ok, here's my current rough way of getting around propagating the update to the message that had been replied to by some user. However, I already see a problem and need other people with more experience to point me in the direction of a better solution. This solution will pass around a reference to a DiscordMessage that has content in it even if said DiscordMessage has been removed from the cache. This is going to prevent the GC from garbage collecting this message. This means that when someone has a DiscordMessage with a non-null ReferencedMessage they will always believe that this ReferencedMessage is non-null even if they delete the message that was referenced. This smells funny to me and I'd prefer a cleaner solution. However, the only other solution I can see right off the top of my head is to go through the cache looking for all messages that reference a message and forcibly updating their message.

**Comment by VelvetThePanda** [comment]
Furthmore if anyone wants to take a glance at these files and give some feedback on overall quality of things. I was quite tired when I wrote this code, and it was cobbled together in <24Hr, so, not my proudest. Thanks to Wam for helping out on it, too.

[ApiClient.cs](https://github.com/VelvetThePanda/DSharpPlus/blob/master/DSharpPlus/Net/DiscordApiClient.cs#L612-L657)
[RestChannelPayloads.cs](https://github.com/VelvetThePanda/DSharpPlus/blob/master/DSharpPlus/Net/DiscordApiClient.cs#L612-L657)

[DiscordRestClient.cs](https://github.com/VelvetThePanda/DSharpPlus/blob/667f42d67f62b6f3e6da3a853967ead2789ecdce/DSharpPlus.Rest/DiscordRestClient.cs#L388-L401)

[CommandContext.cs](https://github.com/VelvetThePanda/DSharpPlus/blob/master/DSharpPlus.CommandsNext/EventArgs/CommandContext.cs#L104-L108)

Looking at that last one reminded me I have to add replies to uploading files, but I'll get to that within the next day or two, if nobody else wants to :p
