### ISSUE TITLE
[bug] AutoReconnect keeps retrying with disallowed intents

### ISSUE THREAD

**Issue by Naamloos** [DSharpPlus/DSharpPlus#682]
# Summary
The AutoReconnect will keep trying to connect when the bot is being disconnected by Discord because of disallowed intents. The bot shouldn't try to reconnect but instead tell the user (via the logger?) that they are trying to connect with intents they are not whitelisted to use.

# Details
Summary should explain it all. Here a screenshot of what happens:
![big oof bub](https://imgur.com/kiDtzae.png)

# Steps to reproduce
1. Disable all intents on bot page on Discord Developers.
2. Connect with `DiscordIntents.All` and `AutoReconnect = true`
3. Loop

# Notes
nah fam issa bug

**Comment by Emzi0767** [comment]
This definitely has to be fixed before 4.0 release.
