### ISSUE TITLE
WaitForMessageAsync throws a NullRefrenceException

### ISSUE THREAD

**Issue by llamanade1127** [DSharpPlus/DSharpPlus#686]
Make sure you familiarize yourself with our contributing guidelines.

# Summary
A NullRefrenceException Occurs when trying to use the WaitForMessageAsync function 

I used this for code:
 var messageResult = await interactivity.WaitForMessageAsync(x => x.Id == user.Id && x.Channel == channel).ConfigureAwait(false);

**Comment by jeffreyladd** [comment]
What was the full stacktrace

**Comment by llamanade1127** [comment]
Exception thrown: 'System.NullReferenceException' in DiscordBotEx.dll
Object reference not set to an instance of an object.

**Comment by Neuheit** [comment]
This doesn’t look like it’s throwing in D#+. First, what version are you on? Second, please provide a full sample to reproduce.

**Comment by llamanade1127** [comment]
Im using DSharp verson 3.4.3 and the latest version of visual studio. The error gets thrown evertime i call that function. 

Code that throws it:


            // first retrieve the interactivity module from the client
            var interactivity = ctx.Client.GetInteractivityModule();

            // generate a code
            var codebytes = new byte[8];
            using (var rng = RandomNumberGenerator.Create())
                rng.GetBytes(codebytes);

            var code = BitConverter.ToString(codebytes).ToLower().Replace("-", "");

            // announce the code
            await ctx.RespondAsync($"The first one to type the following code gets a reward: `{code}`");

            // wait for anyone who types it
            var msg = await interactivity.WaitForMessageAsync(xm => xm.Content.Contains(code), TimeSpan.FromSeconds(60)); 

As to reproduce i dont know what to tell you because it always happens.

**Comment by Emzi0767** [comment]
v3.4.3 does not exist

**Comment by llamanade1127** [comment]
Sorry i put the wrong one.
im using 3.2.3

**Comment by Neuheit** [comment]
Update to either 4.0.0 RC or nightly.

**Comment by llamanade1127** [comment]
So I updated to 4.0.0 and it still throws a error. I don't think its a problem with DSharp i think its something else but idk what it is.

**Comment by Kiritsu** [comment]
Have you properly registered interactivity in the setup of the bot? See: https://dsharpplus.github.io/articles/interactivity.html

**Comment by llamanade1127** [comment]
Yep that fixed it. I must of forgot to include that. Thanks for your help guys!
