### ISSUE TITLE
Missing Properties on Discord Activity

### ISSUE THREAD

**Issue by jeffreyladd** [DSharpPlus/DSharpPlus#692]
# Summary
When trolling through Discord Documentation PR's I came across this PR: https://github.com/discord/discord-api-docs/pull/2219

I have verified that these properties do occur within the json sent by the API and I kinda got lost on the best approach to add these properties.  Opening this issue up to start the discussion on how best to apply them

**Comment by Neuheit** [comment]
This was merged so this can now be worked on.

**Comment by Lulalaby** [comment]
See #889

**Comment by IDoEverything** [comment]
Added in #1015
