### ISSUE TITLE
DSharpPlus GrantRoleAsync removed in new update and don't know how to give a role now 

### ISSUE THREAD

**Issue by marcus12000** [DSharpPlus/DSharpPlus#694]
Make sure you familiarize yourself with our contributing guidelines.

# Summary
so at the moment I'm trying to give someone else a role through a command. it's supposed to be a modtool.
sadly they removed the GrandRoleAsync from the DiscordGuild methods and now I don't know what to do anymore.
any suggestions?

# Details
I already have a DiscordMember and a DiscordRole stored in a variable. So now all I need is a method to give it to that member.
```
await ctx.Guild.GrantRoleAsync(discordMember, muteRole, reason);
```

**Comment by Speyd3r** [comment]
Then use the GrandRoleAsync method on the DiscordMember?

**Comment by marcus12000** [comment]
doesn't that only give it to the person that executes the command?
I'm trying to give it to a different person that didn't execute the command

**Comment by marcus12000** [comment]
as far as I know I couldn't do something like
`muteRole.GrantRoleAsync();`
that doesn't exist right?

**Comment by Speyd3r** [comment]
Where are you getting that discordMember from in your initial response?

**Comment by marcus12000** [comment]
omg, I'm dumb as fuck. I made the member actually a DiscordUser instead of a DiscordMember hahaha

thanks for the help anyway :D
