### ISSUE TITLE
GetAllMembersAsync() UnauthorizedException

### ISSUE THREAD

**Issue by TruSoggy** [DSharpPlus/DSharpPlus#699]
Make sure you familiarize yourself with our contributing guidelines.

# Summary
So I need to get the Members of another Guild and in 4.0.0-nightly-00686 it worked fine but then the library autoupdated and i get this error. Since I cant find a way to revert to this old version im searching help here

# Details
Here is the code i used
```
var cloutserver = await ctx.Client.GetGuildAsync(727581802880958516);
                var allMembers = await cloutserver.GetAllMembersAsync();
                var slottedRole = cloutserver.GetRole(717839297083998278).Name;
                
                var count = 0;

                foreach (var member in allMembers)
                {
                    var result = member.Roles.Select(x => x.Name);
                    if (string.Join("\n", result).Contains(slottedRole))
                    {
                        count += 1;
                    }
                }
                await ctx.Channel.SendMessageAsync($"Slots: {count}/10").ConfigureAwait(false);
``` 

```
DSharpPlus.Exceptions.UnauthorizedException: Unauthorized: 403
   at DSharpPlus.Net.DiscordApiClient.ListGuildMembersAsync(UInt64 guild_id, Nullable1 limit, Nullable1 after)
   at DSharpPlus.Entities.DiscordGuild.GetAllMembersAsync()
   at DiscordBot.Commands.TestCommands.getSlots(CommandContext ctx) in C:\Users\minik\Desktop\cloutdiscordbot-master\DiscordBot\Commands\TestCommands.cs:line 76
```

**Comment by Neuheit** [comment]
Do you have the proper gateway intents enabled?

**Comment by TruSoggy** [comment]
i hav not altered my code since nightly-00686

**Comment by Neuheit** [comment]
> i hav not altered my code since nightly-00686

You have to enable them on your bot dashboard. Please read the below message: 

```
Intents are here... which means you probably need to enable the privileged ones from the application panel on Discord's website (https://discord.com/developers/applications). 

For more information about intents and why your bot is broken, go there: discord.gg/discord-developers. Don't forget to enable them on your DiscordConfiguration!

For more information on intents with D#+, see: https://dsharpplus.github.io/articles/beyond_basics/intents.html
```

**Comment by TruSoggy** [comment]
> > i hav not altered my code since nightly-00686
> 
> You have to enable them on your bot dashboard. Please read the below message:
> 
> Intents are here... which means you probably need to enable the privileged ones from the application panel on Discord's website (https://discord.com/developers/applications).
> 
> For more information about intents and why your bot is broken, go there: https://discord.gg/discord-developers. Don't forget to enable them on your DiscordConfiguration!
> 
> For more information on intents with D#+, see: https://dsharpplus.github.io/articles/beyond_basics/intents.html


Thanks that worked thanks but now GetRole returns null
