### ISSUE TITLE
CommandsNext: Attributes on subcommands aren't executing when no Command attribute is specified.

### ISSUE THREAD

**Issue by OoLunar** [DSharpPlus/DSharpPlus#708]
# Summary
All attributes, except for `Command`, `Description`, `GroupCommand` and `Aliases`, are not checked when a subcommand is being executed.

# Details
Environment:
```
OS: Ubuntu 20.10
.NET Version: 5.0, Microsoft Snap Package, https://snapcraft.io/dotnet-sdk
Editor: Gnome Terminal, VSC + Omnisharp extension
Exceptions: None
```

CSProj file:
```csproj
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net5.0</TargetFramework>
        <RuntimeIdentifier>ubuntu.20.04-x64</RuntimeIdentifier>
        <RootNamespace>Tomoe</RootNamespace>
        <PublishTrimmed>true</PublishTrimmed>
        <PublishSingleFile>true</PublishSingleFile>
        <IncludeNativeLibrariesInSingleFile>true</IncludeNativeLibrariesInSingleFile>
        <IncludeSymbolsInSingleFile>true</IncludeSymbolsInSingleFile>
        <IncludeAllContentInSingleFile>true</IncludeAllContentInSingleFile>
        <NoWarn>CS8632;CS4014;CS1998</NoWarn>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="DSharpPlus" Version="4.0.0-nightly-00766" />
        <PackageReference Include="DSharpPlus.CommandsNext" Version="4.0.0-nightly-00766" />
        <PackageReference Include="DSharpPlus.Interactivity" Version="4.0.0-nightly-00766" />
        <PackageReference Include="Microsoft.Data.Sqlite" Version="3.1.9" />
        <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
        <PackageReference Include="Npgsql" Version="4.1.4" />
    </ItemGroup>
</Project>
```

Code:
```csharp
namespace Tomoe.Commands.Public {
    [Group("tag")]
    public class Tags : BaseCommandModule {
        [RequireGuild]
        [Description("Gets a tag's content.")]
        [GroupCommand]
        [Command("get")]
        [Aliases("retrieve")]
        public async Task Get(CommandContext context, [RemainingText] string tagTitle) => context.RespondAsync("Hello world!");
    }
}
```

# Steps to reproduce
1. Open up a DM.
2. Execute `>>tag <string of choice>`
3. Notice that Hello World sent fine instead of throwing a NotAGuild error
4. Execute `>>tag get <string of choice>`
5. Notice how the NotAGuild error was thrown this time.
6. Execute `>>tag retrieve <string of choice>`
7. Notice how the NotAGuild error was thrown this time.

# Workaround
Remove `GroupCommand` and use `Command` instead.

# Notes
Issue of discovery was found on the DSharpPlus Discord: <https://discord.com/channels/379378609942560770/379378610412191753/786982611946831902>

**Comment by Emzi0767** [comment]
This is an invalid use of CNext. Refer to our documentation:
- https://dsharpplus.github.io/api/DSharpPlus.CommandsNext.Attributes.CommandAttribute.html
- https://dsharpplus.github.io/api/DSharpPlus.CommandsNext.Attributes.GroupCommandAttribute.html
- https://dsharpplus.github.io/api/DSharpPlus.CommandsNext.Attributes.GroupAttribute.html

**Comment by OoLunar** [comment]
The documentation you linked gave me no help on what I'm doing wrong, I've looked at those several times, while also searching your articles/FAQ of how it should be done. Additionally, all attributes are ignored except for the few listed previously. Custom attributes are also ignored. If this is still "an invalid use", it'd be wonderful if I could get an idea of how to correctly implement what I'm looking to do.

**Comment by Emzi0767** [comment]
`GroupCommand` and `Command` are mutually exclusive, for starters. `Aliases` is only valid with `Command` or `Group`. `Description` is only valid with `Command` or `Group`.

**Comment by OoLunar** [comment]
For the sake of the example, `Command` was included. If you remove the `Command` attribute, while still retaining the `Aliases` attribute, the behavior should still be the same.

**Comment by OoLunar** [comment]
Pardon me, I just realized you meant the `Group` attribute for the class, not the `GroupCommand` attribute

**Comment by Emzi0767** [comment]
No, it should not. GroupCommand marks an overload for a group. Any other attribute on it is invalid.

**Comment by OoLunar** [comment]
How should I add custom attributes for methods with the `GroupCommand` attribute then?

**Comment by Emzi0767** [comment]
You add them to the group

**Comment by OoLunar** [comment]
I'll try it out! Thank you for the support!

**Comment by OoLunar** [comment]
You were correct. Again, I thank you for the support. I'll see if I can write up an article later to clarify this. Have a wonderful day!
