### ISSUE TITLE
INTEGRATION_UPDATE event not handled

### ISSUE THREAD

**Issue by DubyaDude** [DSharpPlus/DSharpPlus#709]
# Summary
Event `INTEGRATION_UPDATE` is not handled on DSharpPlus v4.0.0-rc1. 
This event is listed [here](https://discord.com/developers/docs/resources/audit-log#audit-log-entry-object-audit-log-events) with more dumps on the event on a related DAPI issue [here](https://github.com/discord/discord-api-docs/issues/2121)
Seems like `INTEGRATION_CREATE` and `INTEGRATION_DELETE` also exist, however, I haven't run into these.

# Details

RAW Paste
```
[2020-12-14 09:09:59 -06:00] [105 /WebSocketRec] [Warn ] Unknown event: INTEGRATION_UPDATE
payload: "user": {
  "username": "foo",
  "public_flags": 768,
  "id": "98455211680490000",
  "discriminator": "0001",
  "avatar": "a_c8cc171659deb9611627b000aa000aa0"
}, "type": "twitch", "syncing": false, "synced_at": "2020-12-14T09:09:59.490606-06:00", "subscriber_count": 4, "role_id": "709699113373000000", "revoked": false, "name": "foobar", "id": "709699111967900000", "expire_grace_period": 1, "expire_behavior": 0, "enabled": true, "enable_emoticons": true, "account": {
  "name": "foobar",
  "id": "123680000"
}, "guild_id": "98455504340000000"
```

Formatted for your eyes
```
[2020-12-14 09:09:59 -06:00] [105 /WebSocketRec] [Warn ] Unknown event: INTEGRATION_UPDATE
payload:
"user":{
   "username":"foo",
   "public_flags":768,
   "id":"98455211680490000",
   "discriminator":"0001",
   "avatar":"a_c8cc171659deb9611627b000aa000aa0"
},
"type":"twitch",
"syncing":false,
"synced_at":"2020-12-14T09:09:59.490606-06:00",
"subscriber_count":4,
"role_id":"709699113373000000",
"revoked":false,
"name":"foobar",
"id":"709699111967900000",
"expire_grace_period":1,
"expire_behavior":0,
"enabled":true,
"enable_emoticons":true,
"account":{
   "name":"foobar",
   "id":"123680000"
},
"guild_id":"98455504340000000"
```

# Steps to reproduce
Unfortunately due to limited time with exams, I haven't been able to pinpoint what exactly causes the event to trigger, however, I included other mentions of it in Summary

**Comment by Neuheit** [comment]
The part of the docs you linked was for the audit log entries rather than the gateway events. This is a planned addition once https://github.com/discord/discord-api-docs/pull/2295 is merged.

**Comment by DubyaDude** [comment]
> The part of the docs you linked was for the audit log entries rather than the gateway events. This is a planned addition once [discord/discord-api-docs#2295](https://github.com/discord/discord-api-docs/pull/2295) is merged.

My apologies, updated the wording + link as `INTEGRATION_UPDATE` was listed under `Audit Log Events`.
Thank you for letting me know that it's planned!

**Comment by Neuheit** [comment]
I suspect supporting this would also require us to support several aspects of #712, which I'm not sure how we should go about at the moment.

**Comment by Emzi0767** [comment]
Realistically, I am not sure we need to handle this event at all. As far as I know it is not intended for bots, so we should probably just blackhole it to avoid warnings.

**Comment by Neuheit** [comment]
> Realistically, I am not sure we need to handle this event at all. As far as I know it is not intended for bots, so we should probably just blackhole it to avoid warnings.

Do you know if that's also the case with `INTEGRATION_DELETE`?

**Comment by Emzi0767** [comment]
Logically, yes. That said if I can get an official statement contradicting my original comment, I'd be more than happy to leave this up for grabs.

**Comment by Soyvolon** [comment]
It seems that handling these events could be used for any Bot that wants to locally track changes to the interactions and store the data so you don't have to make a request to Discord to get the most up to date information. Something along the lines of listing current interactions for the guild without grabbing it all at once.

Food for thought on keeping these events. The data *could* be used, even if it seems there isnt a big use for it. Granted, the page on Discord Docs is entirely unhelpful, so who knows.

**Comment by Emzi0767** [comment]
There's no way for bots to query integrations.

**Comment by Neuheit** [comment]
Whoops, was thinking of the `INTEGRATION_CREATE` event. I'm not sure when the update and delete versions will be documented, so we may have to end up ignoring them for the time being. Feel free to ask Discord if they have plans on documenting those.

**Comment by Neuheit** [comment]
This event will be temporarily ignored along with its create and delete versions. Discord still plans to document this so this issue will still be on hold for the time being.
