### ISSUE TITLE
Proper way of preventing Emzi0767.Utilities.AsyncEventTimeoutException exceptions

### ISSUE THREAD

**Issue by ploring04** [DSharpPlus/DSharpPlus#710]
# Summary
I am making a new voice channel when someone joins an existing voice channel (Similar to Party Bot where you join a channel and it creates a new one and then when everyone leaves the new channel it auto deletes the new voice channel).  Sometimes creating the new channel can take longer than 1 second.  Using the 4.0 RC1 build I am getting the AsyncEventTimeoutException because of this delay.

Is there something that I am missing to prevent this exception?

# Details
Using DSharpPlus 4.0 RC1 you can cause this exception to get logged with just a simple Task.Delay(1000) 

```
        private async Task Client_VoiceStateUpdated(DiscordClient client, VoiceStateUpdateEventArgs e)
        { 
            await Task.Delay(1000);
        }
```
```
[2020-12-14 14:36:50 -05:00] [104 /EventHandler] [Error] Event handler exception for event VOICE_STATE_UPDATED thrown from System.Threading.Tasks.Task Client_VoiceStateUpdated(DSharpPlus.DiscordClient, DSharpPlus.EventArgs.VoiceStateUpdateEventArgs) (defined in Bot.Program)
Emzi0767.Utilities.AsyncEventTimeoutException`2[DSharpPlus.DiscordClient,DSharpPlus.EventArgs.VoiceStateUpdateEventArgs]: An event handler caused the invocation of an asynchronous event to time out.
```

**Comment by Speyd3r** [comment]
If it takes too long put it in a background Task
`_ = Task.Run...`

**Comment by ploring04** [comment]
That makes sense.  Thanks for the quick response!
