### ISSUE TITLE
Implement Slash commands

### ISSUE THREAD

**Issue by Soyvolon** [DSharpPlus/DSharpPlus#712]
# Summary
Implement slash commands as per [Discord docs](https://discord.com/developers/docs/interactions/slash-commands).

# Details
- Implement registering a command
- Implement updating and deleting a command
  - A Cache for used commands? Code migrations? From what it seems, old commands would need to be manually removed from Discord, so if slash commands are used similarly to `CommandsNext` the library should handle when a change in code is made.
  - Updating a command can be done with the same `POST` request that a create uses, as Discord treats it as an upsert.
- Receive information from the Gateway
- Respond to Interactions (slash commands)
  - This needs to be over HTTP, it is not a command over the gateway (see [here](https://discord.com/developers/docs/interactions/slash-commands#responding-to-an-interaction)) 
  - Handle followup messages and/or editing the original response.
- Further [endpoints](https://discord.com/developers/docs/interactions/slash-commands#endpoints) would need to be added.
  
I haven't worked much on editing DSharpPlus, so correct me if I am wrong, but from Discord's Docs it seems a lot is different to handle slash commands than it is for regular bot commands. Would this be best as a new project, something like `DSharpPlus.SlashCommands`?

## Edit 2020-12-17
Example Interaction from Discord when an interaction command is run:
*This command takes no additional attributes and is not a subcommand.*
```json
{
   "channel_id":"750486424901386330",
   "data":{
      "id":"789290437416189955",
      "name":"hello"
   },
   "guild_id":"750486424469372970",
   "id":"789298197872377876",
   "member":{
      "deaf":false,
      "is_pending":false,
      "joined_at":"2020-09-01T22:45:07.036000+00:00",
      "mute":false,
      "nick":null,
      "pending":false,
      "permissions":"2147483647",
      "premium_since":null,
      "roles":[
         
      ],
      "user":{
         "avatar":"27690e2da064e8bdb9c0cef91b2d3a46",
         "discriminator":"8016",
         "id":"133735496479145984",
         "public_flags":131200,
         "username":"Soyvolon"
      }
   },
   "token":"aW50ZXJhY3Rpb246Nzg5Mjk4MTk3ODcyMzc3ODc2OjdEWVNvQkI1OXExb21vYjRXRUc2SERtdjc0Nk1aZzBxa2d0dm9tTnpXb1ptUnZ4a2s0a20xVkhzVjdZUW13N1kyR2xBVzlYRmwzcDZ4MWc4eW81QmY2bm55ZTJOUmZIb1djSUw3MzFrZklZOE8wdjJwVzNreDNvS2RqTTlZSW9U",
   "type":2,
   "version":1
}
```
## Edit 2020-12-24
- Removed mention of bad `DiscordMember` values as @Neuheit latest branch [Interaction Events](https://github.com/DSharpPlus/DSharpPlus/tree/feature/interaction-events) does properly parse these values.

**Comment by Neuheit** [comment]
This would be a major change for the lib so it will be on hold for the time being.

**Comment by Soyvolon** [comment]
For those interested, I have a very early implementation of the slash commands for use with webhooks [here](https://github.com/Soyvolon/DSharpPlus.SlashCommands).

It's not an upstream branch of DSharpPlus or anything seeing as I knew I wouldn't be following the Libs conventions when building it, but that also means its more flexible in what version of DSharpPlus you use with it. It just needs CommandsNext for some of the attributes that it uses detail the commands.

With that said, I most likely will move this to an upstream branch at some point once I can clean up the command operations (and learn more about how the heck the gateway works), but feel free to use any of this code for implementing an actual DSharpPlus version of Slash Interactions.

**Comment by Emzi0767** [comment]
Addendum to what @Neuheit said: the API, while finalized, is extremely primitive at this stage, and some feedback pertaining to it is still being processed.

**Comment by DrewDaPilot** [comment]
I am happy to look into working on this, I just need to be enlightened on the design philosophy (whether we plan on overhauling commands next to add slash commands as possible triggers, etc). It seems relatively straightforward but for now I think it makes the most sense to keep it as its own module perhaps?

**Comment by Soyvolon** [comment]
I would think this would work best as an extension, but still be dependent upon Commands Next. You also need to consider how the commands are going to be read, as you are supposed to update/post them to Discord once (or if the parameters/name has changed). Also, if a command gets removed that needs a separate request to Discord to remove that command. I implemented it by storing the commands in a JSON file which works pretty well. But still, as Emzi said, the API is still primitive and feedback is being processed. It would not be a good idea to do too much work at this stage as we don't know what will be changed.

On a slightly different note, It could be a good idea to allow the usage of the `DescriptionAttribute` (and maybe a Name attribute) on `enum` values if you parse `enums` to fit Discords `choices` attribute for their commands.

**Comment by DrewDaPilot** [comment]
Ill look into the feasibility of the suggested features. Thanks for the advice.

**Comment by Soyvolon** [comment]
> 
> 
> Ill look into the feasibility of the suggested features. Thanks for the advice.

As I mentioned above I have an implementation of slash commands that uses DSharpPlus already [here](https://github.com/Soyvolon/DSharpPlus.SlashCommands)

I used Enums and parsed the values pretty easily with this;
```csharp
private static object? ParseEnum(object arg, ParameterInfo info)
        {
            try
            {
                var e = Enum.ToObject(info.ParameterType, arg);
                return e;
            }
            catch
            {
                return null;
            }
        }```
Seeing as you control how it gets sent to discord so you always will know the `choice` type will be a number (if you set it up that way at least).

I'm also willing to work on this for the official lib once the API is a bit more stabilized on Discords end.

**Comment by Lulalaby** [comment]
@Soyvolon some news on this <3

**Comment by Soyvolon** [comment]
To start with: Slash commands are still in development and are constantly changing at this point. It would be quite a bit of work to properly maintain. Furthermore, I don't have much experience with the internals of this Lib, and am not going to work on it while the Lib itself is undergoing a lot of changes. I will be glad to start working on this once 4.0.0 is out.

That all said, I do have my own implementation (that I have linked here multiple times by now), and its given me a bit of insight on how the Slash Commands could be implemented.

## Command Building
Unlike `CommandsNext`, commands need to be registered on Discord's side of things as well as on the client. If you are going a route that is similar to `CommandsNext`, then reflection must be used for the following:
1. Command names must be validated as per [command name limits](https://discord.com/developers/docs/interactions/slash-commands#registering-a-command)
2. Command limits must be followed as per [command limits](https://discord.com/developers/docs/interactions/slash-commands#a-quick-note-on-limits)
3. Command parameters must be valid parameters, and no types listed as a [command option type](https://discord.com/developers/docs/interactions/slash-commands#applicationcommandoptiontype) are allowed.
4. Enums should be parsed and validated into `CHOICE` option types, as detailed [here](https://discord.com/developers/docs/interactions/slash-commands#applicationcommandoptionchoice), to allow users to use enums properly in their command
  i. Enum names and values must also be verified for limits
  ii. Option limits must be verified, an enum can have no more than 25 different values as per [discord limits](https://discord.com/developers/docs/interactions/slash-commands#a-quick-note-on-limits)
  iii. Description attribute should be expanded to be placed on enums, or a new name based attribute should be included, to describe the different options in a choice selection.

The library would then build a list of [`ApplicationCommand`](https://discord.com/developers/docs/interactions/slash-commands#a-quick-note-on-limits) objects and proceed to check for and see if they are new commands or need to be updated.

## Command Persistence and Registration
As Discord stores any commands server side, new commands must be added to Discord and old commands removed by way of sending messages to github. Therefore, a system to recognize when commands are added, updated, and removed is critical to removing old commands and ensuring the update requests are not spammed. As Discord is smart enough to do so, the `UPDATE` method will `POST` a new command if you try and update something that does not exists.

The library can only recognize commands when the software is running. Which means some form of data needs to be saved in a way the library can read it at the start of a new session, and update it after it has initialized. My proposal for this is a simple `JSON` file, prefixed (or suffixed) with the Client ID of the current bot and contains command information from the previous session. For example, saving the `json` content as `<guild_id>_interaction_config.json`, where the `json` content is the json representation of all built [`ApplicationCommand`](https://discord.com/developers/docs/interactions/slash-commands#applicationcommand) objects.

Once the previous sessions data has been loaded, the library needs to compare the current commands with the previous commands, and sort them:
- Commands that are in the current commands list, but not in the previous session data need to be placed in an update list
- Commands that are in the current and previous lists, but are not the save (ie parameters have changed) need to be placed in an update list
- Commands that are in the previous list, but not in the current list, need to be placed in a `to remove` list
- Commands that are in both lists and are identical between the lists have not been updated and can be placed in the final list of active commands

After the update and remove lists are built (or during the sort process, instead of saving them in lists), the proper requests need to be made to Discord to update and/or add commands, along with deleting removed commands.

## Executing Commands
To actually execute the commands, a system that functions almost exactly the same as `CommandsNext` would be the easiest to use. The command building portion needs Reflection to get the method details anyways, so using those method references in building the library command reference should be easier to do. Having a separate context for slash commands is what I would recommend, so methods and properties that are not applicable to slash commands from the existing command context are not in the way.

Support for both gateway and HTTP requests should be included, but the user needs to handle HTTP verification themselves. Discord requires an initial response, essentially saying "Command Received, processioning", so customization of that initial response should be allowed and left to the user.

## Notes
This is roughly the way I went about implementing it on my own. My current codes does not do all that I have described here (some it can't, others I haven't gotten around to it yet), but I quickly realized the most difficult task would be recognizing and properly registering (and removing) commands.

These are just my ideas on a possible implementation, feel free to ask questions or suggest your own way of implementing interaction support.

**Comment by Emzi0767** [comment]
we can just reuse CNext APIs to build a CNext-style API which allows for registering commands with Discord based on metadata alone.

**Comment by IDoEverything** [comment]
There actually doesn't need to be that rigorous of a check to update/create/delete commands. Discord provides a `PUT` endpoint not completely documented yet, but there's a pr for it [here](https://github.com/discord/discord-api-docs/pull/2713) that handles all of that for you. We only need to provide the list of commands and it deletes, updates and adds commands automatically.

*~~Also I have an implementation too~~* https://github.com/IDoEverything/DSharpPlusSlashCommands

**Comment by Lulalaby** [comment]
Just wanted to say. great work so far @Soyvolon

**Comment by Lulalaby** [comment]
> 
> 
> There actually doesn't need to be that rigorous of a check to update/create/delete commands. Discord provides a `PUT` endpoint not completely documented yet, but there's a pr for it [here](https://github.com/discord/discord-api-docs/pull/2713) that handles all of that for you. We only need to provide the list of commands and it deletes, updates and adds commands automatically.
> 
> _~Also I have an implementation too~_ https://github.com/IDoEverything/DSharpPlusSlashCommands

You updated the repo right? So the new link is https://github.com/IDoEverything/DSharpPlus.SlashCommands

And I love how you did it, I'm using it right now and it's really good.
Wish to see it like this in future in the core.

**Comment by VladPutinEu** [comment]
What is the progress on this? Has it completed yet?

**Comment by VelvetThePanda** [comment]
@VladPutinEu see the above comment, there's community implementations you can use, but SlashCommands has not been fully implemented into the library as of the time of writing

**Comment by VelvetThePanda** [comment]
As of #1094 we officially support slash commands now via @IDoEverything's implementation.
