### ISSUE TITLE
DiscordMember lacks of user properties when the cache is empty on Guild Member Removed event

### ISSUE THREAD

**Issue by FenikkusuKoneko** [DSharpPlus/DSharpPlus#713]
# Summary
The `DiscordMember` entity doesn't use the `DiscordUser`'s properties, instead it searches this in the user cache.

# Details
I found that the `DiscordMember` entity doesn't have the username, discriminator, avatar, basically all the general fields from the `DiscordUser` entity when this is not in the cache.
I was searching the cause of this and I found that `DiscordMember` searches the user in the user cache then it uses its properties.
I found this problem in the Guild Member Removed event when I started my bot with the cache empty. I believe Discord sends the full data of the user that left the server.

# Steps to reproduce
1. Start the bot with the cache empty (i.e. have only the member intent enabled or not)
2. Try to access member's username in the guild member removed event
3. You will get a `KeyNotFoundException`

**Comment by Giggitybyte** [comment]
Relevant URLs:
https://discord.com/developers/docs/topics/gateway#guild-member-remove
https://github.com/DSharpPlus/DSharpPlus/blob/master/DSharpPlus/Clients/DiscordClient.Dispatch.cs#L929-L941

**Comment by Soyvolon** [comment]
Would this have to do with the fact that the `User` property is only pulled from the cache?
As seen here:
```csharp
[JsonIgnore]
internal DiscordUser User 
      => this.Discord.UserCache[this.Id];
```
And the constructor that is used in the code snippet from the second link by @Giggitybyte is this one:
```csharp
internal DiscordMember(DiscordUser user)
{
    this.Discord = user.Discord;

    this.Id = user.Id;

    this._role_ids = new List<ulong>();
    this._role_ids_lazy = new Lazy<IReadOnlyList<ulong>>(() => new ReadOnlyCollection<ulong>(this._role_ids));
}
```
Which does not set the User, only the User ID and then relies on the cache to get the user information.

**Comment by Neuheit** [comment]
I believe this can be fixed by temporarily adding the sent user to the usercache, then removing it once the method is invoked.

**Comment by Neuheit** [comment]
@FenikkusuKoneko Which intents specifically did you have enabled? The user properties are in cache for me when only using the members intent.

**Comment by FenikkusuKoneko** [comment]
I have only the member intent enabled.
I found this in my bot dev and also in the logs of my public bot.
I have the logs for it. I retarted my bot 2 days ago and this is one of the logs while trying to get the username of a member that left a guild and it wasn't in the cache because the bot just started. The bot was supposed to send a leaving message.
Maybe in your case the member was updated and added in the member cache, I don't know.

```
2020-12-24 17:56:20.612 +01:00 [ERR] System.Collections.Generic.KeyNotFoundException: The given key '513749051393441794' was not present in the dictionary.
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException(TKey key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at DSharpPlus.Entities.DiscordMember.get_Username()
```

**Comment by Neuheit** [comment]
Okay sorry for the long wait, I tested this and was able to reproduce. I will get this issue fixed soon.
