### ISSUE TITLE
[Suggestion] Bad Request upon modifying an embed message with a null value in a field

### ISSUE THREAD

**Issue by Pentagrade** [DSharpPlus/DSharpPlus#715]
Make sure you familiarize yourself with our contributing guidelines.

# Summary
I have been setting up a wizard command that involved posting a complex embed containing fields and then Modifying it and updating the fields with new info as the wizard progresses. However, I ran across an issue when running ModifyAsync() with the new Embed, the method would create a BadRequest400 exception. 

# Details
Upon investigating this was due to one of the fields of the embed having a value that was "null". I understand why this would return a Bad Request from Discord. but perhaps it may be worth documenting these reasons either in the wiki or the exception itself to ease debugging?

**Comment by Giggitybyte** [comment]
Relevant links:
https://discord.com/developers/docs/resources/channel#embed-object-embed-field-structure
https://github.com/DSharpPlus/DSharpPlus/blob/master/DSharpPlus/Net/DiscordApiClient.cs#L612-L650

**Comment by Emzi0767** [comment]
This is documented in discord docs.
