### ISSUE TITLE
Replied user mention is not included in Message.MentionedUsers

### ISSUE THREAD

**Issue by dev-kittens** [DSharpPlus/DSharpPlus#717]
# Summary
When a message_reference is received with the original user being mentioned, the mention does not appear in `Message.MentionedUsers`.

# Details
.NET version: `net5.0`
DSharpPlus version: `4.0.0-rc1`

# Steps to reproduce
1. Send a message that includes a reply, with the "ping the original author" button enabled.
2. Observe the `Message.MentionedUsers` list being empty.

**Comment by Kiritsu** [comment]
Hello, this is not implemented yet, but there's a PR for it! See: https://github.com/DSharpPlus/DSharpPlus/pull/704

**Comment by dev-kittens** [comment]
Ah, thank you
