### ISSUE TITLE
SlimGet doesn't work

### ISSUE THREAD

**Issue by Shadowblitz16** [DSharpPlus/DSharpPlus#723]
# Summary
I tried getting the latest package from SlimGet using https://nuget.emzi0767.com/api/v3/index.json in my nuget package manger
however its doesn't show any packages

# Details
I am using windows 10 ltsc 64 bit and .net core 3.1

![image](https://user-images.githubusercontent.com/2453707/103307093-16cec780-49c4-11eb-9f7b-8dd054023b8f.png)

# Steps to reproduce
1. Goto nuget package manager 
2. Click the gear on the top right side of the package manager
3. Make a new package source and paste in `https://nuget.emzi0767.com/api/v3/index.json`
4. Click Update and OK
5. Switch to the package source you just created
6. See that nothing appears

# Notes
I tried just using the one on nuget but its api is different then the one used [here](https://www.youtube.com/watch?v=7-tyLCAO4mY&list=PLS6sInD7ThM0Zb8F_KBl4T_jGF1e3apsc)

**Comment by Kiritsu** [comment]
You must tick "include prerelease"
