### ISSUE TITLE
The first time a third-party bot joins a voice channel it has default values for many properties in the User object

### ISSUE THREAD

**Issue by JackSteel97** [DSharpPlus/DSharpPlus#728]
# Summary
In my case I am trying to ignore any voice state updates for Bots, the `VoiceStateUpdated` event handler in my code contains a simple `if(!args.User.IsBot /*[...]*/)` to try and achieve this. However, I have noticed the music bot in my test server is still getting through this check occasionally. After further investigation, I am able to reproduce the issue as laid out below.

# Details
I am running V4-Rc1 on a Windows 10 host, for the purposes of the reproduction listed below I am just running my bot in debug from Visual Studio 2019.

# Steps to reproduce
## Prerequisites
1. Set up a basic bot and add a basic handler for the `Client.VoiceStateUpdated` that logs out (or in my case has a breakpoint to inspect) the values of the `VoiceStateUpdateEventArgs` parameter passed to it.
2. Have a third-party bot in the discord server you are testing in that can join and leave voice channels on command. For my testing, I used the [Groovy Music Bot](https://groovy.bot/), simply because it is the bot I noticed the behaviour with originally.

## Steps to Reproduce
1. Join a voice channel as your own user.
2. Starting with your bot offline, start up your bot and wait for it to login and start the heartbeat task.
3. Get the third-party bot to join the voice channel (-join for Groovy)
4. Observe the content of the `VoiceStateUpdateEventArgs.User` - it looks something like this: ![image](https://user-images.githubusercontent.com/13905557/104095981-c1cb6500-5291-11eb-8551-8b8c641bc78a.png)
5. Get the third-party bot to leave the voice channel (-leave for Groovy)
6. Without restarting your bot, get the third-party bot to join the voice channel again.
7. Observe the content of this `VoiceStateUpdateEventArgs.User` - it now looks something like this upon the second join: 
![image](https://user-images.githubusercontent.com/13905557/104096044-1a026700-5292-11eb-8f05-cfc7025c16d2.png)

Note that crucially the `IsBot` flag is set to false is defaulting to false at step 4 here, allowing the update to continue on incorrectly for this user.

# Notes
I assume this is some sort of caching issue and not an issue on the Discord's end given that everything is set correctly after the first update is fired. 
I am not sure if this is a bug or because I am missing some extra setup that is required - though I do have intents enabled for my bot so I'm fairly sure it's not that.

**Comment by Kiritsu** [comment]
This is probably due to caching, when the user is not in cache, it creates a skeleton then which only has the id of the user... 

Have you the member intents enabled?

**Comment by JackSteel97** [comment]
My bad, seems the member intents were in fact not enabled for my dev bot - was sure I had turned them on
