### ISSUE TITLE
DiscordRoles on DiscordMember does not update

### ISSUE THREAD

**Issue by JBraunsmaJr** [DSharpPlus/DSharpPlus#729]
# Summary
I discovered DiscordRoles cache for a member does not update. My bot lists the roles you currently have, and this list does not update with any changes applied during runtime.

# Details
Lets say we have a user with roles A, B and C.

User uses command !join D
If you manually check discord, role D is properly applied. HOWEVER, the cache does not update.

If user uses !leave it will list ALL roles for the current user, allowing user to respond with the one they want to remove. Only roles A, B, and C appear. Restart bot, roles A through D appear. Same thing happens when you leave a role. List remains unchanged until restart. This makes me believe it's a caching issue.

Using:
Windows 10
NET5
Nightly build v4.0.0-nightly-00774 for DSharpPlus, DSharpPlus.CommandsNext, and DSharpPlus.Interactivity
I understand these aren't necessarily "stable" but I noticed the documentation pointed towards these builds.

Worth noting: I tried the previous 2 nightly builds.

# Steps to reproduce
1. Bot adds role to member
2. Have bot list member's roles. You'll see the added role does not appear in list
3. Remove role from member. You'll see the removed role remains in list

# Notes
I have tried the following (thinking perhaps it grabs things from discord instead of the cache)

```
var member = context.Guild.GetMemberAsync(context.Member.Id);
member.Roles
```

Also tried
```
context.Member.Roles
```

**Comment by jeffreyladd** [comment]
Please verify intents are enabled

**Comment by JBraunsmaJr** [comment]
Wow... good call. I never configured the DiscordIntents prior to these nightly builds and it worked beforehand. That did the trick! I had a feeling it would be something super obvious lol. Thanks ya'll
