### ISSUE TITLE
Users in channels is always empty

### ISSUE THREAD

**Issue by larsbloch** [DSharpPlus/DSharpPlus#739]
Hi

I am trying to find channels which have users in them. But unfortunately Channel.Users are allways empty. Is this a bug or do i miss a setting somewhere ?

Is there a workaround to this issue ?

Quick code sample:

			foreach (var channelDict in _discord.GetGuildAsync(id).Channels)
			{
				var channel = channelDict.Value;
				if (channel.Type != ChannelType.Voice || channel.Users.Count() == 0)
					continue;
				var connection = channel.ConnectAsync();
			}

**Comment by Kiritsu** [comment]
Do you have intents enabled ? Idk if your code is handwritten but please await your asynchronous methods.

**Comment by larsbloch** [comment]
Hi thanks for the reply.

Im using the latest 4.0.0-rc1

I am not using any intents. Or the intents are set at default. Could this be making an issue ? As ive read this shouldnt have an effect.

I am awaiting the guild. The the above example whas just a simplification of my real code.
I could write the testcode more simple for better understanding

			var guild = await discord.GetGuildAsync(id);
			var channel = guild.Channels.Values.SingleOrDefault(x => x.Name == "Test");
			var users = channel.Users;

The guild and the Channel has all values populated but users are still empty
It doesnt matter if it is a voice or text channel.

**Comment by JGray0705** [comment]
Yes, you need to enable intents [here](https://discord.com/developers/applications) to fix your issue.

**Comment by Kiritsu** [comment]
Indeed, and then you have to specify the MEMBER_INTENT and/or PRESENCE_INTENT in your DiscordConfiguration. Without intents, caching is kinda broken since it relies on gateway events (which are not being triggered because of these intents disabled!)

**Comment by larsbloch** [comment]
Here we go. I missed the Privileged Gateway Intents located as radio buttons in the bot Menu. and i have also added the correct intents in configuration.
			var discord = new DiscordClient(new DiscordConfiguration()
			{
				Token = "xx",
				TokenType = TokenType.Bot,
				Intents = DiscordIntents.All, //Testing intents
			});
Thanks for the quick help and feedback ! : )

**Comment by Kiritsu** [comment]
Nice!
