### ISSUE TITLE
Don't updating GuildMember Roles

### ISSUE THREAD

**Issue by MichaelPrust** [DSharpPlus/DSharpPlus#740]
When change the roles of a member, they are not updated on the GuildMember instance of the CommandContext.

Its happens using the Require​RolesAttribute to.

# Steps to reproduce
1. Create a command that requires a role and add the Require​RolesAttribute;
2. Run the bot, and run the command with a user without the role
3. Add the role to the user;
4. Run the command again.

**Comment by Kiritsu** [comment]
Hello,

You *probably* need the MEMBER_INTENT which you can enable in your Discord Bot Application and then in your DiscordConfiguration to have a reliable caching of roles/members, etc.

**Comment by MichaelPrust** [comment]
Its ok now! Thanks!
