### ISSUE TITLE
Use TweetNacl-cs instead of libsodium, removing a native dependency.

### ISSUE THREAD

**Issue by thunderstorm010** [DSharpPlus/DSharpPlus#741]
# Summary
We can remove native libsodium dependency by using [this library.](https://github.com/drr00t/tweetnacl-cs)
# Notes
This should be optional. There may be security issues as this library is not audited.

**Comment by uwx** [comment]
Latest release of the library is 2017. Abandoned. Plus it's not much use to replace libsodium if libopus is still necessary.

**Comment by Emzi0767** [comment]
Entirely pointless. The natives are installed automatically on Windows, and for Linux we have the setup guide.

As mentioned, this library is unaudited, abandoned, and not confirmed to be actually working. And there's probably a performance penalty associated with running the encryption in managed code. In other words, not a single reason to replace what works.
