### ISSUE TITLE
Internal Unicode Emoji Store is Out of Date

### ISSUE THREAD

**Issue by murl-digital** [DSharpPlus/DSharpPlus#751]
# Summary
Recently Unicode updated to version 13 (see [here](https://unicode.org/emoji/charts-13.0/emoji-released.html)), which includes new emojis which have already been added to Discord. These changes have not been reflected in DSharpPlus

# Details
Looking at the [file in question](https://github.com/DSharpPlus/DSharpPlus/blob/62e4bcf4081a48d547db96f9e2214d52efd74d2b/DSharpPlus/Entities/DiscordEmoji.EmojiUtils.cs#L15), the new emojis are missing (e.g :blueberries: or :smiling_face_with_tear:). This is an issue if you're working with emoji with commands, as argument conversion will fail and the command won't execute.

# Steps to reproduce
1. Set up a basic bot with a test command like so:
```
public class TestCommand : BaseCommandModule
    {
        [Command("test")]
        public Task Test(CommandContext ctx, DiscordEmoji emoji)
        {
            Console.WriteLine(emoji.Name);
            return Task.CompletedTask;
        }
    }
```
2. Run the bot and use a new emoji (e.g :blueberries:)
3. The command shouldn't execute

# Notes
I was having this issue with the latest nightly build

**Comment by RedApelsin** [comment]
This also affects DiscordClient.MessageReactionAdded/Removed events. There all emoji shown up as `??`
```cs
internal static async Task MessageReactionAdded(DiscordClient sender, MessageReactionAddEventArgs e)
{
     Console.WriteLine(e.Emoji.Name);
}
```
![image](https://user-images.githubusercontent.com/59859860/107128966-d459ae00-68d2-11eb-96e5-408aa303e840.png)

**Comment by Emzi0767** [comment]
> This also affects DiscordClient.MessageReactionAdded/Removed events. There all emoji shown up as `??`

That has nothing to do with this.

**Comment by SorenNeedsCoffee** [comment]
i wonder if there's a better way to handle unicode emojis besides just a 5000 odd line dictionary? nothing really comes to mind as an alternative after thinking about it for a bit but i feel like there's a way.

**Comment by uwx** [comment]
> i wonder if there's a better way to handle unicode emojis besides just a 5000 odd line dictionary? nothing really comes to mind as an alternative after thinking about it for a bit but i feel like there's a way.

The Discord client has an equally big JSON table, so there isn't really another option until Discord decides to release public emoji maps themselves.
