### ISSUE TITLE
Nightly 790/791 breaks EventArgs and/or intents

### ISSUE THREAD

**Issue by VelvetThePanda** [DSharpPlus/DSharpPlus#754]
Make sure you familiarize yourself with our contributing guidelines.

# Summary
When using the latest nightlies (This bug persists in 790 and 791, which changed intents, afaik), trying to access properties that are known to be null (e.g. `XEventArgs.Guild` in DMs), the property throws a `NullReferenceException`.

# Details
Using .NET 5, DSharpPlus version 4.0.0-nightly-00791.

Even if you provide the null propagation operator (`?.`), and not accessing any of the null's properties, a NRE is still thrown, as seen below. The EventArgs object is not null, yet trying access the `Guild` property at all throws an exception. Interestingly, in DMs, accessing the channel is fine, yet null(?). Not sure if that's intentional behavior?

# Steps to reproduce
- Update to 790/791
- Hook into `MessageX'd` and access `XEventArgs.Guild`, but not any of it's properties
- Trigger said event on a guild
- Notice normal flow
- Trigger event in DMs
- Observe NRE, even if you don't access `XEventArgs.Guild.Whatever`

# Notes
I also tested with `DiscordIntents.All`, to the same effect. This only applies to DMs, and trying to access the `Guild` property of any Event Args. 
## Expected behavior / pre-790
![](http://i.velvetthepanda.dev/u/rider64_veJ1QLIBRh.png)
## Behavior expressed in 790/791
![](http://i.velvetthepanda.dev/u/rider64_OJzQ2DHEvX.png)

**Comment by VelvetThePanda** [comment]
So as it would turn out, that suspicious `eventArgs.Channel is null` returning true is the cuplrit, as `EventArgs.Guild` returns the result of `Channel.Guild`,

**Comment by Emzi0767** [comment]
And so the tradition of first build being broken is upheld. Smh @Neuheit 

This could be related to some experiments removing the DM channel stuff?

**Comment by VelvetThePanda** [comment]
> This could be related to some experiments removing the DM channel stuff?
Was there? I don't remember hearing anything about removing DM stuff, and even then, just omitting the channel entirely both breaks the Guild property and DM channel checks most people may do, such as `EventArgs#Channel.IsPrivate`. I'd assume this is purely unintended behavior.

**Comment by Neuheit** [comment]
> This could be related to some experiments removing the DM channel stuff?

**Comment by Neuheit** [comment]
Updated ^
