### ISSUE TITLE
Don't log handeled unknown events 

### ISSUE THREAD

**Issue by dpeter99** [DSharpPlus/DSharpPlus#755]
# Summary
Unknown Events still get logged even if they are marked as ``Handled``. 

# Details
I'm on:
``4.0.0-nightly-00773``

I have the following set up:
```
Client.UnknownEvent += (sender, args) =>
{
    args.Handled = true;

    return Task.CompletedTask; 
};
```

**Comment by Emzi0767** [comment]
That is not how any of it works

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Emzi0767** [comment]
Logging and event system are separate. Handled property simply prevents other event handlers for the event from running. Has nothing to do with logging.

If you want to prevent log messages from popping up, look at the documentation of whatever logging facilities you use to set up log message filters.

**Comment by Neuheit** [comment]
As discussed in the guild, while I was originally open to the idea Emzi makes a good point about deciding what should be filtered. If you want to ignore these events you can do so with your own logger implementation. This is also only a temporary issue and will be resolved once Discord documents these events and they are implemented on our end. I Apologize for the confusion I may have created about that.
