### ISSUE TITLE
Poor audio receive quality

### ISSUE THREAD

**Issue by micya** [DSharpPlus/DSharpPlus#770]
# Summary
Audio receive quality is poor. I'd like to create a bot that can transcribe a voice channel, but I noticed on configuring a bot to simply echo audio, spoken text sounds garbled (like a chipmunk).

# Details
Simple audio resend setup as direct extension from tutorial:

```csharp
    [Command("start")]
    public async Task StartCommand(CommandContext ctx, DiscordChannel channel = null)
    {
        channel ??= ctx.Member.VoiceState?.Channel;
        var connection = await channel.ConnectAsync();

        Directory.CreateDirectory("Output");
        connection.VoiceReceived += VoiceReceiveHandler;
    }

    [Command("stop")]
    public async Task StopCommand(CommandContext ctx)
    {
        var vnext = ctx.Client.GetVoiceNext();

        var connection = vnext.GetConnection(ctx.Guild);
        connection.VoiceReceived -= VoiceReceiveHandler;
        connection.Dispose();

        return Task.CompletedTask;
    }

    private async Task VoiceReceiveHandler(VoiceNextConnection connection, VoiceReceiveEventArgs args)
    {
        var transmit = connection.GetTransmitSink();
        await transmit.WriteAsync(args.PcmData);
    }
```

# Steps to reproduce
- Env: .NET 5.0 on Ubuntu 18.04
- Version: DSharpPlus (and other related package) on version 4.0.0-rc1
- Dependencies are installed as outlined in prerequisites

```bash
sudo apt-get install libopus0 libopus-dev
sudo apt-get install libsodium23 libsodium-dev
```

# Notes
Running the actual example [here](https://dsharpplus.github.io/articles/audio/voicenext/receive.html), I've combined the wav files generated and can confirm it is the receive that is producing chipmunk noises.

Are there any settings I can tweak to improve the audio quality?

**Comment by thunderstorm010** [comment]
What program did you use to combine them? If FFmpeg, you should use -ac 1 when converting instead of -ac 2.

**Comment by micya** [comment]
> What program did you use to combine them? If FFmpeg, you should use -ac 1 when converting instead of -ac 2.

Referring to when saving the clips on VoiceReceived event as mentioned in the example or when combining? (I am not an ffmpeg expert, as you can probably tell 😅)

For reference, this is what was in the example

```csharp
private async Task VoiceReceiveHandler(VoiceNextConnection connection, VoiceReceiveEventArgs args)
{
    var fileName = DateTimeOffset.Now.ToUnixTimeMilliseconds();
    var ffmpeg = Process.Start(new ProcessStartInfo
    {
        FileName = "ffmpeg",
        Arguments = $@"-ac 2 -f s16le -ar 48000 -i pipe:0 -ac 2 -ar 44100 Output/{fileName}.wav", // <-- referring to this?
        RedirectStandardInput = true
    });

    await ffmpeg.StandardInput.BaseStream.WriteAsync(args.PcmData);
    ffmpeg.Dispose();
}
```

To combine, I ran the below (files.txt is a list of clip filenames):

```bash
ffmpeg -f concat -i files.txt -c copy output.wav
```

**Comment by Neuheit** [comment]
Since Discord does not provide documentation on how to properly receive audio, I will be closing this as voice receive is considered an unstable feature. If you know how to enhance the quality that you described in this issue then feel free to submit a PR.

**Comment by FlorentDChamps** [comment]
I also had some trouble receiving audio and that's what I found out:
* received audio pcm format is "-ac 2 -f s16le -ar 48000" (Signed 16-bit PCM as the encoding, a Little-endian byte order, 1 Channel (Mono) and a sample rate of 48000Hz)
* you can concatenate the pcm data bytes directly to create a unique file
* the AudioFormat given in VoiceNextConfiguration is used for output format (when playing in a vocal channel), so if you want to send directly some bytes received you need to set it to 1 channel (instead of 2 by default)

**Comment by Emzi0767** [comment]
> the AudioFormat given in VoiceNextConfiguration is used for output format (when playing in a vocal channel), so if you want to send directly some bytes received you need to set it to 1 channel (instead of 2 by default)

This is actually incorrect - the audio format from users can change over the course of transmission. A lot of clients begin with 2 channels, but then switch to 1, then briefly back to 2, and then back to 1 again. 48kHz is also not guaranteed. With every data burst you get an `AudioFormat` instance, which lets you know the exact decoded parameters of the received packet.

**Comment by FlorentDChamps** [comment]
Thanks for your answer! I didn't think to use the `AudioFormat` from the `VoiceReceiveEventArgs` 🤦
This VoiceNext functionality is becoming clearer 🙂
