### ISSUE TITLE
Add CancellationToken Parameter to Interactivity Methods

### ISSUE THREAD

**Issue by ProfDoof** [DSharpPlus/DSharpPlus#776]
# Summary
Interactivity waits and send paginated message do not have the ability to be canceled using a CancellationToken. I need this for one of the features I'm working on so even if nobody else wants to work on this I will... eventually™️. 

# Details
We should add a parameter to the Wait functionalities, as well as the SendPaginatedMessage, that allows you to pass in a CancellationToken. We then need to ensure that canceling said token will deregister any event handlers and all that jazz.

**Comment by Naamloos** [comment]
To be fair, this shouldn't be a big hassle to set up as CancellationToken(Source) is being used internally already anyway.

**Comment by ProfDoof** [comment]
@VelvetThePanda, is this already finished?

**Comment by VelvetThePanda** [comment]
@ProfDoof I didn't actually know this was an issue, but #1040 should be the final nail in the coffin for my changes to interactivity

**Comment by ProfDoof** [comment]
Want to verify that this is completed so that we can close it.
