### ISSUE TITLE
ConnectAsync never returns

### ISSUE THREAD

**Issue by Vrpndt** [DSharpPlus/DSharpPlus#801]
# Summary
This issue has been reported, but is still present on `4.0.0-rc2`. Trying to connect to a Voice Channel works fine, however the method never returns, preventing subsequent code from executing. This is also presumably the reason that `GetVoiceNext().GetConnection()` returns null. There's no exception and changing the log level to `Error`, `Warning` or `Fatal` showed nothing wrong.

# Details
.NET Framework Version 4.8
Visual Studio 2017
Windows 10 x64

# Steps to reproduce
1. Install DSharpPlus 4.0.0-rc2 (including CommandsNext and VoiceNext) on a new project.
2. Copy and Paste the code from the example bot.
3. Change the namespaces and classes to match that of the project.
4. Run the bot.

**Comment by Emzi0767** [comment]
.NETFX is not a supported target
