### ISSUE TITLE
BaseCommandModule not found

### ISSUE THREAD

**Issue by MakufonSkifto** [DSharpPlus/DSharpPlus#811]
When I try to use BaseCommandModule, it says `Cannot resolve symbol 'BaseCommandModule'`. I have everything installed (including using DSharpPlus.CommandsNext) and imported. I don't know what is causing this to happen. Can you guys help?

![image](https://user-images.githubusercontent.com/63517174/113133278-24485780-9228-11eb-8659-21de5b391bb2.png)

**Comment by Emzi0767** [comment]
Issue tracker is not for support. We have a discord for that.
