### ISSUE TITLE
GetAuditLogsAsync() throws InvalidCastException on role permission change

### ISSUE THREAD

**Issue by Aerochrome** [DSharpPlus/DSharpPlus#818]
# Summary
A `InvalidCastException` occurs when `GetAuditLogsAsync()` encounters a role permission change entry, such as granting or denying the `Manage Channels` permission to a role.

# Details

## Environment:
- Windows 10
- .NET Core 3.1
- Visual Studio 2019
- NuGET Packages
    - DSharpPlus 4.0.0-rc2
    - DSharpPlus.CommandsNext 4.0.0-rc2

## Code example:
```csharp
public class MainCommandModule : BaseCommandModule
{
    [Command("auditlog")]
    public async Task Auditlog(CommandContext ctx)
    {
        DiscordGuild guild = ctx.Guild;
        IReadOnlyList<DiscordAuditLogEntry> auditLog;

        try
        {
            auditLog = await guild.GetAuditLogsAsync(1);
        } catch(Exception e)
        {
            Console.WriteLine("Error: " + e.ToString());
            throw e;
        };
    }
}
```
## Error on role permission change entry
```
Error: System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Int64'.
   at DSharpPlus.Entities.DiscordGuild.GetAuditLogsAsync(Nullable`1 limit, DiscordMember by_member, Nullable`1 action_type)
   at UnPurgeBot.Commands.MainCommandModule.Auditlog(CommandContext ctx) in C:\Users\Philipp\source\repos\UnPurgeBot\UnPurgeBot\Commands\MainCommandModule.cs:line 24
```

# Steps to reproduce
1. Create a new CommandModule with the provided Command Method like outlined in the documentation here:
    https://dsharpplus.github.io/articles/commands/intro.html
2. Make a permission role change in the discord server (such as giving `@everyone` `Create Invite` permission)
3. Execute the command `auditlog`

# Notes
I also checked other AuditLog Events such as:
- Changing role name
- Changing role color
- Giving/Taking roles to/from users

All worked fine without errors.

Also, the error is not bound to a specific role, but occurs on every role when trying to change permissions of that given role.

**Comment by IDoEverything** [comment]
This has been fixed in the latest nightly version.

**Comment by Aerochrome** [comment]
Confirmed, the error no longer occurs in the latest nightly version `version 4.0.0-nightly-00826`

Closing bug therefore.
