### ISSUE TITLE
DiscordMessage.MentionedUsers NullReference

### ISSUE THREAD

**Issue by TheBarret** [DSharpPlus/DSharpPlus#824]
Was trying out the DSharpPlus library to see how it performs vs the other libraries,
Everything works as intended except when the mentioning list is iterated in the message instance.

![](https://i.imgur.com/ITph3Rw.png?1)

This was tested with on dotnet core 3.1, windows 10 64 bit, in the VS2019.

The Message instance is passed down to a filter that checks for mentioned users as follows:
```
Public Overrides Sub Analyze(p As Profile, sm As DiscordMessage)

            For Each user As DiscordUser In sm.MentionedUsers
            '//...code...
            Next
End Sub

**Comment by ProfDoof** [comment]
Which version of DSharpPlus are you on?

**Comment by Neuheit** [comment]
> > Which version of DSharpPlus are you on?
> 
> I installed the latest version 3.2.3 from nuget.

3.2.3 is out of support, update to the latest RC or nightly prerelease. See https://dsharpplus.github.io/articles/migration/3x_to_4x.html for support in migrating from 3.2.3.
