### ISSUE TITLE
Implement missing features

### ISSUE THREAD

**Issue by CabbageAdi** [DSharpPlus/DSharpPlus#825]
# Summary
A list of features that have yet to be implemented into the library. I'll keep updating it as more things come out.

I've split the commits by how important I feel they are to add, depending on how much difference they'll actually make to the library.

- [ ] [Get Thread Member](https://github.com/discord/discord-api-docs/commit/457926101da0dc8e5e872ad3b87a1d443d15be75)
- [ ] [More Thread Id on Webhooks](https://github.com/discord/discord-api-docs/commit/528975f5c2519c8548eccfe5ee288938382f2141)
- [ ] [More Activity Flags](https://github.com/discord/discord-api-docs/commit/9114a1bcb882619f1c42dd1c577f22a80e82b125)
- [ ] [Suppress Member Join Sticker Flag](https://github.com/discord/discord-api-docs/commit/4e8ec13a593445c1e529de86499cf07a79806d68)
- [ ] [Thread Slowmode](https://github.com/discord/discord-api-docs/commit/d56be860c5dd4c04e80337556d82eb3a04f971a2)
- [x] [Guild Events](https://github.com/discord/discord-api-docs/commit/1298152172d3359abf069d1b24d4bbc85532b735)
- [ ] [Boost Progress Bar](https://github.com/discord/discord-api-docs/commit/54e92a5432ea24ba5e09854fc73479fff54d2a3d)
 
### Completed
- [x] [Stage channels](https://github.com/discord/discord-api-docs/commit/71cc444a908401a194e8848bf184a6deab6e4fc8)
- [x] [Slash command permissions](https://github.com/discord/discord-api-docs/commit/47eab31c044cb2dec9ab36fcf9583cacc4701df5)
- [x] Api v9 and threads (refer to website)
- [x] [Files on patch](https://github.com/discord/discord-api-docs/commit/0afdd8143e05b0c7699ddf25adb331846eb8fe4a)
- [x] [Stage instances](https://github.com/discord/discord-api-docs/commit/f019fc358047050513c623f3639b6e96809f9280) and [events](https://github.com/discord/discord-api-docs/commit/2eabdfd4d3bde8e666821eaf90335905d0cb7970)
- [x] [Rtc region](https://github.com/discord/discord-api-docs/commit/fd7c6e44a6fdf8c1b0ca88de1faffb2b2b91bb53)
- [x] [Use slash commands permission](https://github.com/discord/discord-api-docs/commit/c7d25885c5cd80a49b31609a40b70603b35f9dec)
- [x] [Modify channel position](https://github.com/discord/discord-api-docs/commit/afc04f26fefb07d70166ec1e2f46eac02ef5aace)
- [x] [Webhooks source guild and channel](https://github.com/discord/discord-api-docs/commit/a96ea527dc8db7726637a1ec2ee6c8063a01bff6)
- [x] [Activity buttons](https://github.com/discord/discord-api-docs/commit/5d1f03c1ad8c0a83f50e6693aeb8416aa9707a55) (should also close #692)
- [x] [Video quality mode](https://github.com/discord/discord-api-docs/commit/3ae41f2a5b6ba1c9356919e16a41e91db04713ca)
- [x] [Attachment content type](https://github.com/discord/discord-api-docs/commit/ab7a51ffea418a354562404da51ee609f8bca539)
- [x] [Get webhook message/interaction response](https://github.com/discord/discord-api-docs/commit/94d57ea3ed3b2c42cbbb488c9f93d2bc81706cff)
- [x] [Mentionable slash command option type](https://github.com/discord/discord-api-docs/commit/91379ed78710d3020dcb46521485abecdf31e1d0)
- [x] [Invite expiration](https://github.com/discord/discord-api-docs/commit/2c9f17887a8e5c95d48b93901f4543beda4c09be)
- [x] [Webhook attachment patch](https://github.com/discord/discord-api-docs/commit/5afbad75892a907726ab47eea4d9bcbeabcdaa18) and [Channel attachment patch](https://github.com/discord/discord-api-docs/commit/0b2b84d94b9abd4688158edf0534dfdd062591b4)
- [x] [Webhooks on threads](https://github.com/discord/discord-api-docs/commit/cd0cae871e593876098ac8baf85d5f6403cd3d2c)
- [x] [Integration events](https://github.com/discord/discord-api-docs/commit/b761ed03c07e7fce80175947ec01732099b2b5cd)
- [x] [Message application id](https://github.com/discord/discord-api-docs/commit/415c423b5b0e1ec89b2cfbf35d2a9332a2579823)
- [x] [Guild Stickers](https://github.com/discord/discord-api-docs/commit/9c3577f6ca35904462adf8d57c4346afd2a6bcf0) and [Sticker Items](https://github.com/discord/discord-api-docs/commit/101c24dc80460e2e168ffd66551ea22eab72e796)
- [x] [Slash command channel types](https://github.com/discord/discord-api-docs/commit/72bf5acb5de5d804efb70039df7db1daf0c4b33b)
- [x] [Ephemeral attachments](https://github.com/discord/discord-api-docs/commit/d61166446ec954d2b8f561db0d87701df5de69d9)
- [x] [Role icons](https://github.com/discord/discord-api-docs/commit/0f09124859874a48a44dadfea8197bfc7ff8b2fe)
- [x] [Guild create and modify fields](https://github.com/discord/discord-api-docs/commit/5b63daebe35a8c0e9d313186f0de5fcf30304057)
- [x] [Webhook url](https://github.com/discord/discord-api-docs/commit/9f9c28313455ac4578a487a72aa97b2fea4a832f)
- [x] [Application flags](https://github.com/discord/discord-api-docs/commit/13000cd517b6ec802fc0986ed806ec6e5bea01ba)
- [x] [Application invites](https://github.com/discord/discord-api-docs/commit/1b4e363e324eb1f49a47e32cb0108fbe276c8e0e)
- [x] [Application privacy policy/tos](https://github.com/discord/discord-api-docs/commit/39b254bed1cc396c475e508a3f2bf328815605c9)
- [x] [Invite reminder](https://github.com/discord/discord-api-docs/commit/6b816cb6f542ea813c8f4dab797fc0e7ce203305)
- [x] [nsfw guilds](https://github.com/discord/discord-api-docs/commit/5e63e309bbc7e93b683b47bc8401d2d079580251)

**Comment by Lulalaby** [comment]
V9 Release of Discord API mentioned [here](https://github.com/discord/discord-api-docs/pull/2855)

- [ ] [Threads](https://github.com/discord/discord-api-docs/pull/2855/files/4f22153fb8650ef1467a42274ac3d6f2f0a11a29#diff-e28250ee18796453c6332a572fb2fe1f25be18b46bbb56934789cfaef57edec2)
- [ ] [Permissions](https://github.com/discord/discord-api-docs/pull/2855/files/4f22153fb8650ef1467a42274ac3d6f2f0a11a29#diff-83c324034ba0b1753dde3487f095f5307f7036c3e53a25bacba1879733a6ce23)
- [ ] [Opcodes / Statuscodes](https://github.com/discord/discord-api-docs/pull/2855/files/4f22153fb8650ef1467a42274ac3d6f2f0a11a29#diff-2adb841744dbfb715ce95d82e0c7bad2a498da041ee52c1282e2336286b8361a)
- [ ] [Gateway Events](https://github.com/discord/discord-api-docs/pull/2855/files/4f22153fb8650ef1467a42274ac3d6f2f0a11a29#diff-c24665b017972d8f7c266214d30655ea5e105826ef212048f9460632dd61e3df)
- [ ] [Guild Structure](https://github.com/discord/discord-api-docs/pull/2855/files/4f22153fb8650ef1467a42274ac3d6f2f0a11a29#diff-6a43fc10e10de61f31b90ab22421ef0612d0ea75e3cd53891c6393a6fb84872d)
- [ ] [Channels / Messages](https://github.com/discord/discord-api-docs/pull/2855/files/4f22153fb8650ef1467a42274ac3d6f2f0a11a29#diff-160acb4654c611c67c4ee46b2ce5dda2be82212af8d1d00cd0256ef6edda1e95)

**Comment by Lulalaby** [comment]
Stage Channel

- [ ] [Stage Instance](https://discord.com/developers/docs/resources/stage-instance)

**Comment by Lulalaby** [comment]
I'll do the following:
- [ ] Activity buttons (should also close #692)
- [ ] Guild member mute and deafen
- [ ] Application flags
- [ ] Application invites
- [ ] Application privacy policy/tos

**Comment by Lulalaby** [comment]
> 
> 
> V9 Release of Discord API mentioned [here](https://github.com/discord/discord-api-docs/pull/2855)
> 
>     * [ ]  [Threads](https://github.com/discord/discord-api-docs/pull/2855/files/4f22153fb8650ef1467a42274ac3d6f2f0a11a29#diff-e28250ee18796453c6332a572fb2fe1f25be18b46bbb56934789cfaef57edec2)
> 
>     * [ ]  [Gateway Events](https://github.com/discord/discord-api-docs/pull/2855/files/4f22153fb8650ef1467a42274ac3d6f2f0a11a29#diff-c24665b017972d8f7c266214d30655ea5e105826ef212048f9460632dd61e3df)
> 
>     * [ ]  [Opcodes / Statuscodes](https://github.com/discord/discord-api-docs/pull/2855/files/4f22153fb8650ef1467a42274ac3d6f2f0a11a29#diff-2adb841744dbfb715ce95d82e0c7bad2a498da041ee52c1282e2336286b8361a)
> 
>     * [ ]  [Guild Structure](https://github.com/discord/discord-api-docs/pull/2855/files/4f22153fb8650ef1467a42274ac3d6f2f0a11a29#diff-6a43fc10e10de61f31b90ab22421ef0612d0ea75e3cd53891c6393a6fb84872d)
> 
>     * [ ]  [Channels / Messages](https://github.com/discord/discord-api-docs/pull/2855/files/4f22153fb8650ef1467a42274ac3d6f2f0a11a29#diff-160acb4654c611c67c4ee46b2ce5dda2be82212af8d1d00cd0256ef6edda1e95)
> 
>     * [x]  [Permissions](https://github.com/discord/discord-api-docs/pull/2855/files/4f22153fb8650ef1467a42274ac3d6f2f0a11a29#diff-83c324034ba0b1753dde3487f095f5307f7036c3e53a25bacba1879733a6ce23)

Taking over this too

> 
> 
> Stage Channel
> 
>     * [ ]  [Stage Instance](https://discord.com/developers/docs/resources/stage-instance)

And this too

**Comment by Lulalaby** [comment]
`Guild member mute and deafen` seems to be already in master

**Comment by Lulalaby** [comment]
- [ ]  Webhooks source guild and channel
- [ ]  Invite expiration
- [ ]  Message application id
- [ ]  Webhook url
- [ ]  Guild create and modify fields
- [ ]  Team name

**Comment by DWaffles** [comment]
> `Guild member mute and deafen` seems to be already in master

I looked into this as well and it seemed to be the case. I'll see later if guild member voice states worked as planned.

**Comment by Lulalaby** [comment]
Low priority is done in #889

**Comment by Lulalaby** [comment]
High priority: 1 (6) | Incomplete
Normal priority: 11 (15) | Incomplete
Low priority: 8 (8) | Done
Threads: 1 (6) | Incomplete
Stage Instance: 0 (1) | Incomplete

**Comment by Lulalaby** [comment]
` Team name` is as well in master, please check

**Comment by Lulalaby** [comment]
Fucked up #889, switched to #890

**Comment by Lulalaby** [comment]
Anyone want to do `Remove user dms endpoint and Remove private channels`

**Comment by Lulalaby** [comment]
And `Files on patch`

**Comment by Lulalaby** [comment]
The rest is covered by me & @DWaffles in #890

**Comment by Lulalaby** [comment]
### Overall status [List: Done (Total) | State]
- [ ] High priority: 4 (6) | Incomplete
- [ ] Normal priority: 12 (15) | Incomplete
- [x] Low priority: 8 (8) | Done
- [ ] Threads: 2 (6) | Incomplete

**Comment by Lulalaby** [comment]
Open: 
[Get webhook message/interaction response](https://github.com/discord/discord-api-docs/commit/94d57ea3ed3b2c42cbbb488c9f93d2bc81706cff) Will do in #890 
[Video quality mode](https://github.com/discord/discord-api-docs/commit/3ae41f2a5b6ba1c9356919e16a41e91db04713ca) Covered in #888 
[Remove user dms endpoint](https://github.com/discord/discord-api-docs/commit/ca5064c46dc18e13cd2d65dea735eb44a52998de) [Remove private channels](https://github.com/discord/discord-api-docs/commit/f36156dbb641f5c4d4f4593f345bfd6e27fdee08) Won't do, please ping and I add you to the PR to cover it up
[Threads - Gateway Events](https://discord.com/developers/docs/topics/gateway#list-of-intents) covered in #890

**Comment by Lulalaby** [comment]
If https://github.com/discord/discord-api-docs/pull/2982 get's approved, we need to remove the `region` field in Guilds.

**Comment by Lulalaby** [comment]
Attention by the gateway methods: https://github.com/discord/discord-api-docs/issues/2978#issuecomment-846039051

**Comment by Lulalaby** [comment]
Open: 
[Get webhook message/interaction response](https://github.com/discord/discord-api-docs/commit/94d57ea3ed3b2c42cbbb488c9f93d2bc81706cff) Will do in #890 
[Threads - Gateway Events](https://discord.com/developers/docs/topics/gateway#list-of-intents) covered in #890 
Activity Buttons - Needs a rework

**Comment by Lulalaby** [comment]
Normal priority is done in #890

**Comment by Lulalaby** [comment]
@DWaffles takes a look on `Files on patch`

**Comment by Lulalaby** [comment]
Threads implemented 99.99% only one thing missing. Will do later.
Still need to redo RPC Activity Button tho and `Files on patch` needs to be done.
Then we're ready to go.

**Comment by Lulalaby** [comment]
Threads is implemented

**Comment by Lulalaby** [comment]
Only `Files on patch`  left :3

**Comment by IDoEverything** [comment]
I've added a few more features to add; this issue can serve as an ever-updating todo list of sorts.

**Comment by airbreather** [comment]
discord/discord-api-docs#6025
![image](https://user-images.githubusercontent.com/3792815/231176565-5779dcf6-5cb8-4328-b84c-ec0198b554e8.png)
![image](https://user-images.githubusercontent.com/3792815/231176642-f1649483-7bd6-4c46-99bc-2e5f6dcf9489.png)
