### ISSUE TITLE
GuildMemberAdd event

### ISSUE THREAD

**Issue by GabiRP** [DSharpPlus/DSharpPlus#830]
Make sure you familiarize yourself with our contributing guidelines.

# Summary
GuildMemberAdd event doesn't work

# Details
Event GuildMemberAdd doesn't run, I've tried running the exact same code on other events, and it works, but on the GuildMemberAdd, doesn't work

# Steps to reproduce
1. Make the event GuildMemberAdd
2. Register the event
3. Run the bot
4. Ask someone or use an alt account to join a server where the bot is
5. The event doesn't run

# Notes
Here is the code (the code works, what doesn't work is the event). I have the event registered, i've tried to run the exact same code in other events and it works.

![image](https://user-images.githubusercontent.com/57387907/114076263-c27e9200-98a6-11eb-8d31-632d602b063c.png)

**Comment by Kiritsu** [comment]
Did you enable required intents?

**Comment by GabiRP** [comment]
Yes, I have enabled Presence and Server members intent

**Comment by Neuheit** [comment]
You're also blocking the gateway thread, make sure to wrap any `await`s in a `Task.Run`

**Comment by Kiritsu** [comment]
Even in your DiscordClientConfiguration?

**Comment by GabiRP** [comment]
I can't check anything rn, I'll check it tomorrow and I will tell you.

**Comment by GabiRP** [comment]
So, the Server members and presence intents are enabled in the DiscordClientConfiguration and in the developers page

**Comment by GabiRP** [comment]
wait, now it works

**Comment by GabiRP** [comment]
Well, now it works, idk what I have changed but it works, thanks
