### ISSUE TITLE
Command context's client Shard ID does not match guild's Shard ID

### ISSUE THREAD

**Issue by alexhorner** [DSharpPlus/DSharpPlus#831]
# Summary
When you compare the Shard ID of the client from a command context to the Shard ID of the client retrieved using the context's Guild ID, they do not match.

# Details
Running on `4.0.0-nightly-00833` packages across the board, .NET Core 3.1 on Windows 10 using Jetbrains Rider

# Steps to reproduce
1. Ensure your bot is in multiple guilds so that the bot can be accessed from multiple shards. I used 2 guilds.
2. Inject the `DiscordShardedClient` into `CommandsNext`'s DI ServiceCollection so you may access it in the constructor of a command module
3. Ensure the `DiscordShardedClient` is using more than one shard. For my test, I configured it to use 3 shards.
4. Create a command module extending `BaseCommandModule` and insert the following command
    ```csharp
    [Command("testshardmatch")]
    public async Task TestShardMatch(CommandContext ctx)
    {
        //Assuming the DiscordShardedClient has been DI'd into the module as _shardedClient
        await ctx.RespondAsync($"Context shard ID is {ctx.Client.ShardId} and by guild ID shard ID is {_shardedClient.GetShard(ctx.Guild.Id).ShardId}");
    }
    ```
5. Execute this command for multiple guilds. You can find my examples in the notes. You should see that the IDs do not match

# Notes
Guild A:
![image](https://user-images.githubusercontent.com/33007665/114223555-e5bd4600-9967-11eb-82f7-60852151386d.png)

Guild B:
![image](https://user-images.githubusercontent.com/33007665/114223595-ed7cea80-9967-11eb-9566-67e1b2acd853.png)

**Comment by Neuheit** [comment]
Can you share the code on how you have your client injected?

**Comment by alexhorner** [comment]
@Neuheit The sharded client is injected like so:

```csharp
private static DiscordShardedClient _discord;
private static IReadOnlyDictionary<int, CommandsNextExtension> _commands;
private static readonly ServiceCollection ServiceCollection = new ServiceCollection();

_discord = new DiscordShardedClient(new DiscordConfiguration
{
    Token = Configuration.Token,
    TokenType = TokenType.Bot,
    MinimumLogLevel = LogLevel.Debug,
    ShardCount = 3
});

ServiceCollection.AddSingleton(_discord);

_commands = await _discord.UseCommandsNextAsync(new CommandsNextConfiguration
{
    StringPrefixes = new List<string>
    {
        "!"
    },
    EnableMentionPrefix = true,
    Services = ServiceCollection.BuildServiceProvider(),
    IgnoreExtraArguments = true,
    EnableDefaultHelp = false
});

await _discord.StartAsync();
```

**Comment by alexhorner** [comment]
Attached is a complete solution that you just need to add a token into. Tested with this solution and the issue is reproducable
[TestBot.zip](https://github.com/DSharpPlus/DSharpPlus/files/6291490/TestBot.zip)

**Comment by Neuheit** [comment]
This is caused due to manual sharding. The client's shard id is manually set by the number of shards, which in this case is specified by the user, while the `GetShard()` method will always use the [formula by Discord](https://discord.com/developers/docs/topics/gateway#sharding-sharding-formula) to calculate it, which is determined by the gateway. 

We should be able to fix this by having an internal check from within the `GetShard()` method for manual sharding.

**Comment by alexhorner** [comment]
Ah, I see. As I am not at 1k yet, I decided to manually shard so I may test sharding is working with my code prior to it happening automatically. Thanks for taking a look at this!
