### ISSUE TITLE
NullReferenceException when trying to give Thumbnail.Url of an embed message a url

### ISSUE THREAD

**Issue by Quicksoapy** [DSharpPlus/DSharpPlus#832]
`    [Command("Pokedex")]
    public async Task pokefunction(CommandContext ctx, string pokemon)
    {
        //https://pokeapi.co/api/v2/
        DiscordEmbedBuilder Embed = new DiscordEmbedBuilder();
        string json = new WebClient().DownloadString("https://pokeapi.co/api/v2/pokemon/" + pokemon);
        dynamic response = JsonConvert.DeserializeObject(json);
        string name = response.forms[0].name;
        int height = response.height;
        string photo = response.sprites.front_default;
        int weight = response.weight;
        Console.WriteLine(photo);
        Embed.Title = char.ToUpper(name[0]) + name.Substring(1);
        Embed.Thumbnail.Url = photo;
        Embed.Description = "Type: ";
        try
        {
            string type1 = response.types[0].type.name;
            string type2 = response.types[1].type.name;
            Embed.Description += char.ToUpper(type1[0]) + type1.Substring(1) + "/" + char.ToUpper(type2[0]) +
                                 type2.Substring(1) + ".";
        }
        catch
        {
            string type1 = response.types[0].type.name;
            Embed.Description += char.ToUpper(type1[0]) + type1.Substring(1) + ".";
        }
        
        Embed.Description += Environment.NewLine +"Height: " + height * 10 + "cm." + Environment.NewLine + "Weight: " + weight / 10 + "kg.";
        ctx.Channel.SendMessageAsync(Embed);
    }`
For reference, here is my code. I use Dsharpplus version 4.0.0-rc2, ive done some debugging and after debugging, it appears that the variable 'photo' i gave to Embed.Thumbnail.Url contains a valid url to a png, but when continuing the Embed.Thumbnail.Url remains Null.

My system has Windows 10, my IDE is Jetbrains Rider.

**Comment by Emzi0767** [comment]
This code is so horrible I don't even know where to begin unpacking this. Aside from this, support questions belong in the Discord server.
