### ISSUE TITLE
Editing a reply message which didn't mention makes it mention

### ISSUE THREAD

**Issue by Emzi0767** [DSharpPlus/DSharpPlus#833]
# Summary
If you send a reply message that does not mention, then edit it, it will make it mention. This is not normal behaviour.

# Details
No idea why that is, I reckon @VelvetThePanda and @ProfDoof will have some input as they are the ones who originally implemented the feature in D#+

# Steps to reproduce
```cs
[Command]
public async Task TestReplyBork(CommandContext ctx)
{
    var msg = await ctx.RespondAsync("nope"); // sends a non-mentioning reply by default
    await msg.ModifyAsync(x => x.Content = "yep"); // now it mentions
}
```

# Notes
This has to be resolved before 4.0 release.

**Comment by VelvetThePanda** [comment]
If I'm not mistaken this is undefined behavior in the API? This same behavior is expressed in the desktop and mobile client. It's likely to do with mentions being overrided or the likes. Using the MessageBuilder does not have this problem last I checked.

**Comment by Emzi0767** [comment]
I tried editing as a user and that did not happen.

**Comment by MerlijnVanherck** [comment]
This seems to be a case of Discord lying in their documentation. They say [replied_user](https://discord.com/developers/docs/resources/channel#allowed-mentions-object-allowed-mentions-structure) defaults to false, but that doesn't seem to be the case.

I changed the code in [EditMessageAsync](https://github.com/DSharpPlus/DSharpPlus/blob/c6950f4c0dc20209c7503e168373e42f80c53c5c/DSharpPlus/Net/Rest/DiscordApiClient.cs#L949) to include this else:
```cs
if (mentions != null)
    pld.Mentions = new DiscordMentions(mentions);
else
    pld.Mentions = new DiscordMentions(Mentions.None);
```

And that fixes it in the sense that the message no longer mentions after an edit, if you want to allow users to change whether an existing reply can mention you'd have to add an additional parameter probably.

**Comment by VelvetThePanda** [comment]
This could be changed to a null coalescing operator.

**Comment by VelvetThePanda** [comment]
Furthermore, @Emzi0767, it does seem to have inconsistent behavior across clients. Mobile for example still has this issue ![image](https://user-images.githubusercontent.com/42438262/114270765-2787d400-99dc-11eb-9ba4-e4663044802a.jpeg)

**Comment by Neuheit** [comment]
> This seems to be a case of Discord lying in their documentation. They say [replied_user](https://discord.com/developers/docs/resources/channel#allowed-mentions-object-allowed-mentions-structure) defaults to false, but that doesn't seem to be the case.

This appears to be correct, this example sends a null mentions object when sending, but Discord still makes it mention.
