### ISSUE TITLE
Pagination Page Count 

### ISSUE THREAD

**Issue by BIGDummyHead** [DSharpPlus/DSharpPlus#848]
Make sure you familiarize yourself with our contributing guidelines.

# Summary
Pagination doesn't count pages correctly, for example if my Pagination has 2 pages it says 1/1 no matter what...

# Details
I am on .Net Core 3.1, using 4.0.0.1 Nightly DSharpPlus.Interactivity

```csharp
  
 pages.AddRange(inter.GeneratePagesInEmbed(adder.Value, SplitType.Line, mainB));

 await inter.SendPaginatedMessageAsync(ctx.Channel, ctx.User, pages, behaviour: PaginationBehaviour.Ignore, deletion: PaginationDeletion.DeleteEmojis);

```

# Steps to reproduce
^ See above code...

# Notes
This picture should display 1/2 in it's footer.
![2Img](https://user-images.githubusercontent.com/47464673/115490682-29dffe80-a224-11eb-90b2-232ce1e5919c.png)

**Comment by Neuheit** [comment]
Can you send the full string you are using for the `input` parameter?

**Comment by BIGDummyHead** [comment]
Pg.1
 
Access a page of LiveLeak!
Page Number (The Page To Jump To), Keywords (Words To Search)

Pg.2

Access the first page of LiveLeak!
Keywords (Words to search for on LL)

To note: These are designed as two separate pages
![_genBug](https://user-images.githubusercontent.com/47464673/115567751-36467480-a281-11eb-9e35-685cbf0f57a6.png)

**Comment by Neuheit** [comment]
Awesome thank you. I know why it's doing this but I needed your example to see if it fixed it.

**Comment by BIGDummyHead** [comment]
Alright awesome, thank you!

**Comment by Neuheit** [comment]
Ok I know what's causing this actually. From your snippet you are generating 2 separate sets of pages, which in your case will only contain one page each. When sending the embed, it will use the embed from the first page (which will only be 1/1). So ideally, you should only use that method once, or construct the pages manually yourself.

**Comment by Neuheit** [comment]
Going to close this for now, if you still feel like this is a bug feel free to reopen.
