### ISSUE TITLE
[Question] How to send multiple embed 

### ISSUE THREAD

**Issue by garsia0** [DSharpPlus/DSharpPlus#858]
how i can send multiple embed over CommandContext.RespondAsync() or send raw json message ?

**Comment by VelvetThePanda** [comment]
1. Webhook
2. Questions are better suited for the [Official DSharpPlus Server](https://discord.gg/dsharpplus) or the [Discord API Server](https://discord.gg/discord-api)

**Comment by uwx** [comment]
What the panda said.
