### ISSUE TITLE
InvalidCastException when converting DiscordUser to DiscordMember

### ISSUE THREAD

**Issue by ISmellYu** [DSharpPlus/DSharpPlus#861]
# Summary
System.InvalidCastException when trying to cast `DiscordUser` to `DiscordMember`

# Details
.NET 5.0
Windows 10
DSharpPlus 4.0.0

```
[Error] Exception occured
System.InvalidCastException: Unable to cast object of type 'DSharpPlus.Entities.DiscordUser' to type 'DSharpPlus.Entities.DiscordMember'.
   at dcBot.Run.Bot.OnVoiceState(DiscordClient sender, VoiceStateUpdateEventArgs e) in C:\Users\lukas\RiderProjects\discord\bot\Run\Main.cs:line 219
   at Emzi0767.Utilities.AsyncEvent`2.InvokeAsync(TSender sender, TArgs e, AsyncEventExceptionMode exceptionMode)
```

# Steps to reproduce
Add event to `Client.VoiceStateUpdated`, convert `DiscordUser` to `DiscordMember` using `VoiceStateUpdateEventArgs` property `After` and finally property `User`.
```
private Task OnVoiceState(DiscordClient sender, VoiceStateUpdateEventArgs e)
        {
            var member = (DiscordMember) e.After.User;
            Console.WriteLine(member.Nickname);
            return Task.CompletedTask;
}
```

# Notes
It's working like 50% of the time when i join or leave a channel it throws an error but when my friend joins it works. Funny thing that yesterday it didnt work with both of us.

**Comment by Soyvolon** [comment]
`DiscordMember` is a child of `DiscordUser` and as such you should not be trying to convert a `DiscordUser` to a `DiscordMember` because the member class has more information and accessible methods than the user object.

**Comment by ISmellYu** [comment]
So why in your docs it says 
![image](https://user-images.githubusercontent.com/38290598/115998481-c0773b80-a5e7-11eb-9b98-996e457143a7.png)

**Comment by Soyvolon** [comment]
No clue. Afaik you should not be casting a `DiscordUser` to `DiscordMember` unless you know for sure the user object is an instance of the member object.

If you want to talk more about your code and getting it to work with the current behavior, please head over to the [Discord](https://discord.gg/dsharpplus)

**Comment by Neuheit** [comment]
Do you have the proper intents enabled on your dashboard and `DiscordConfiguration`? When I had my guild member and presence intents enabled I had no issues, however the moment I turned them off I started to receive this exception.

**Comment by ISmellYu** [comment]
Okay so i added this to my discord configuration `Intents = DiscordIntents.All,` and enabled these 2 checks  
![image](https://user-images.githubusercontent.com/38290598/116002569-aa26ab00-a5fa-11eb-8dc5-2f4cc8e465e2.png)
AND IT WORKED, thanks for help
