### ISSUE TITLE
In a [GroupCommand] Task even with the [RequireGuild] attribute the command is still fired in a DM channel

### ISSUE THREAD

**Issue by Lexa013** [DSharpPlus/DSharpPlus#865]
![image](https://user-images.githubusercontent.com/48451588/116087225-f298a400-a6a0-11eb-9ea7-31bb327d4067.png)
![image](https://user-images.githubusercontent.com/48451588/116087237-f4626780-a6a0-11eb-93d3-66c543a2130e.png)

**Comment by DWaffles** [comment]
I use 4.0.0-nightly-00786, so I'm a few months behind, but I can replicate the above. Putting `[RequireGuild()]` directly onto a method marked with `[GroupCommand]` bypasses the guild check. 


![ylGcBPCEzW](https://user-images.githubusercontent.com/42708798/116110326-35478580-a67b-11eb-8c46-2ee8d91077c2.png)
![Discord_cf7Grss3iN](https://user-images.githubusercontent.com/42708798/116110358-3d072a00-a67b-11eb-9a46-62478092e1d9.png)

I've found that putting `[RequireGuild()]` onto the actual command module [like so](https://i.imgur.com/7AjH7dt.png) causes the execution of the command to [fail](https://i.imgur.com/a6CCoZK.png) like it should.

**Comment by Kiritsu** [comment]
Have you tried putting it on the group itself, and not the group command?

**Comment by DWaffles** [comment]
> 
> 
> Have you tried putting it on the group itself, and not the group command?

Yes, if you place `RequireGuild()` onto the group itself, it executes the checks properly for the `GroupCommand`. The issue arises when the group does not have `RequireGroup()` but `GroupCommand` does. 

There's a few cases where the default command of a group should be done in a guild only, yet other commands in that group do not require it. You can do the guild check programmatically, so it's not a major breaking issue.

**Comment by VelvetThePanda** [comment]
I'm 2h late on this but this is a non-issue as this is how CNext is intended to work; execution checks propagate to the same command (i.e. overloads), but not to the whole group. If you want the group to share common execution checks, put them on the group, not the command.

**Comment by DWaffles** [comment]
> execution checks propagate to the same command (i.e. overloads), but not to the whole group.

The issue is that placing placing `[GroupCommand]` onto a command causes it to **skip and bypass** the `[RequireGuild]` check and fire the command within a **DM** for that command. This does not seem like planned behavior but rather an oversight or logic error. 


![QvzbCHp6ux](https://user-images.githubusercontent.com/42708798/116202795-99605d00-a700-11eb-8dd0-cac1e0b13f0a.png)
![9qU6rcrPm7](https://user-images.githubusercontent.com/42708798/116202806-9bc2b700-a700-11eb-8914-86dcdb355d11.png)

The code workaround around this would be to manually code in a guild check at the start of the command, something like so. But this isn't doesn't seem like intended behavior for a method marked with `[RequireGuild]`.
```
if(ctx.Guild is null)
{
  List<CheckBaseAttribute> failedChecks = new();
  failedChecks.Add(new RequireGuildAttribute());
  throw new ChecksFailedException(ctx.Command, ctx, failedChecks);
}

**Comment by Lexa013** [comment]
I don't want to put the RequireGuild on the group beacause i would be able to execute some specific command in DM

**Comment by Emzi0767** [comment]
I don't think you quite understand. A group command is not part of the group, it is the group. A group, on its own, is a command, which can house other commands, and has no overloads. The attribute adds an overload to that collection. Overloads have no properties of their own other than reference to the invoked method, and information about argument types. Therefore to apply checks to the group command, you have to apply them to the group.
