### ISSUE TITLE
Unhandled exceptions in async event handlers are swallowed silently

### ISSUE THREAD

**Issue by decaprime** [DSharpPlus/DSharpPlus#875]
# Summary
Unhandled exceptions that are thrown inside of async event handlers are swallowed silently. My [expectation, re: discord,](https://discord.com/channels/81384788765712384/381890239171395595/838617720844976138) is that they would be surfaced in the ClientErrored event. If the event handler is not async then exceptions do go to ClientErrored as expected.

# Details
I forked [https://github.com/DSharpPlus/Example-Bots/tree/master/DSPlus.Examples.CSharp.Ex01](DSPlus.Examples.CSharp.Ex01) to create a sample project that reproduces the issue. I updated the sample to 4.0.1 and .NET 5.0, added add/remove reaction handler that throw to repro:

https://github.com/decaprime/dsharpplus-async-event-handling-repro

# How to use this repro:
## Remarks
- ClientErrored logs Critical (this is the expectation)
- All exceptions are logged via [FirstChanceException](https://github.com/decaprime/dsharpplus-async-event-handling-repro/blob/main/Program.cs#L81) as validation they fired and were NOT handled
## Steps
1. Setup some bot credential in config.json as in the example
2. Run the bot
3. You need a message with the bot for you to react to (DM/new message, doesn't matter)
4. Add reaction -> (async handler) -> exception ->No Critical Log **[REPRO]** 
5. Remove reaction -> (handler) -> exception -> Critical Log

**Comment by VelvetThePanda** [comment]
Can repro.

**Comment by uwx** [comment]
Exception handling in Emzi's AsyncEvent class doesn't seem to account for the fact that Task.WhenAny doesn't propagate async exceptions, but rather leaves it up to the user to check the Faulted or Canceled state. See the following lines:

https://github.com/Emzi0767/Common/blob/master/src/Emzi0767.Common/Utilities/AsyncEvent/AsyncEvent.cs#L140-L154

This means it does not correctly fall through to the catch handler when an exception is thrown asynchronously. When it's thrown synchronously, the Task hasn't been returned yet, therefore the exception is propagated.

How this went unnoticed for so many months is beyond me.

**Comment by VelvetThePanda** [comment]
Sounds about right. Would explain why exceptions only get thrown into the void when they're actually asynchronous. For the time being (this could be patched tomorrow if emzi can be bothered). I'd recommend subbing to TaskScheduler.UnobservedTaskException (I think that's what it's called) as well, and checking for event errors there as well. Cumbersome, but, it works.

**Comment by Neuheit** [comment]
CC @Emzi0767

**Comment by Emzi0767** [comment]
Emzi0767.Common v2.6.2 is currently undergoing NuGet validation. Fix will be pushed as soon as that's done.
