### ISSUE TITLE
ERROR:  Object reference when trying to GetRole with DiscordRestClient

### ISSUE THREAD

**Issue by Bishbash777** [DSharpPlus/DSharpPlus#881]
When trying to use DsharpPlus.Rest.GetGuildMemberAsync() I am a recieving a object reference error stemming from DiscordGuild.GetRole(Uint64 id) I have correctly initialized the cache for it and CAN recieve guild data from the rest client however, i cannot recieve role data - see implementation below...

(IK i can get role data from DiscordClient but for large servers, it uses cached data and not live data - which is not helpful in my use case, i need to see the role as soon as the user has it (When i want to access it))

**Stack:**
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at DSharpPlus.Entities.DiscordGuild.GetRole(UInt64 id)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at SEDiscordBridge.SEDiscordBridgePlugin.GetRoles(UInt64 userID, UInt64 steamID) in F:\plugins\GIT\SEDB-RELOADED\SEDiscordBridge\SEDiscordBridgePlugin.cs:line 237
   at SEDiscordBridge.SEDiscordBridgePlugin.InjectDiscordID(IPlayer player) in F:\plugins\GIT\SEDB-RELOADED\SEDiscordBridge\SEDiscordBridgePlugin.cs:line 211
```
**Code block in question**
```
public Dictionary<ulong, string> GetRoles(ulong userID, ulong steamID) {
            IEnumerable<DiscordRole> discordRoles = new List<DiscordRole>();
            Dictionary<ulong, string> roleData = new Dictionary<ulong, string>();
            var guilds = DiscordBridge.DiscordRestClient.Guilds;
            foreach (var guildID in guilds) {
                discordRoles = DiscordBridge.DiscordRestClient.GetGuildMemberAsync(guildID.Value.Id, userID).Result.Roles;
                if (discordRoles != null) {
                    foreach (var role in discordRoles) {
                        roleData.Add(role.Id, role.Name);
                    }
                }
            }

            return roleData;
        }
```

**Comment by Neuheit** [comment]
You're using `.Result`, which will lead to unpredictable behavior in the library. I recommend you read more about TAP and how to properly implement it or else you will encounter more of these issues.

**Comment by Bishbash777** [comment]
Could you give me a pointer for proper usage? Spent hours trying to figure it out
