### ISSUE TITLE
CommandsNext, RawArguments does not correlate correctly to RawArgumentsString

### ISSUE THREAD

**Issue by OoLunar** [DSharpPlus/DSharpPlus#886]
# Summary
`CommandContext.RawArguments` does not correlate correctly to `CommandContext.RawArgumentsString`. Sometimes `null` is returned (uninitialized variable, according to Omnisharp's Debugger), sometimes a list with missing values are returned. Regardless, `RawArguments` is never correct.

Command: `>>mute @User Testing`
![image](https://user-images.githubusercontent.com/46751150/118691477-bd2e3480-b7ce-11eb-8d45-b52588273d35.png)

From @VelvetThePanda:
Command: `>>doas userId pog something else`
![image](https://user-images.githubusercontent.com/46751150/118691744-fcf51c00-b7ce-11eb-84a4-a2e4534e0f9f.png)

Command: `>>tag pog 1 2 3`
![image](https://i.velvetthepanda.dev/u/WHDec.png)

When creating `CommandContext`:
![image](https://user-images.githubusercontent.com/46751150/118693082-5a3d9d00-b7d0-11eb-9737-3291e7722818.png)

# Details
DSharpPlus version: 4.0.1
Dotnet version: 5.0.202
OS: Windows 10, x64

# Steps to reproduce
1. Execute command with multiple arguments.
2. `Console.WriteLine(string.Join(' ', CommandContext.RawArguments))`, either get a `NullReferenceException` or mismatching arguments.

# Notes
Discord context that makes up most of the issue: https://discord.com/channels/379378609942560770/379378610412191753/844235877828001802

**Comment by VelvetThePanda** [comment]
Do you have a repo for this by chance?

**Comment by OoLunar** [comment]
I'm assuming you meant repro. This should be enough: https://dsharpplus.github.io/articles/commands/command_handler.html#handle-commands

**Comment by VelvetThePanda** [comment]
> I'm assuming you meant repro. This should be enough: https://dsharpplus.github.io/articles/commands/command_handler.html#finished-product

Have you tried on the latest nightly yet

**Comment by OoLunar** [comment]
Just tested on `4.1.0-nightly-00862`. Same results as 4.0.1 release.

**Comment by Neuheit** [comment]
Tested this and it appears to be a converter issue, CC @Emzi0767.

**Comment by OoLunar** [comment]
Closing due to being unable to reproduce on latest nightlies:
```cs
using System.Threading.Tasks;
using DSharpPlus.CommandsNext;
using DSharpPlus.CommandsNext.Attributes;

namespace Tomoe.Commands
{
    [Group("dsp_fix")]
    public class CommandTest : BaseCommandModule
    {
        // Test if the Raw Arguments are set correctly.
        [Command("raw_argument_converter")]
        public async Task RawArgumentConverter(CommandContext context, [RemainingText] string args) => await context.RespondAsync(string.Join(' ', context.RawArguments) + " == " + context.RawArgumentString + ": " + (string.Join(' ', context.RawArguments) == context.RawArgumentString));
    }
}

```
![image](https://user-images.githubusercontent.com/46751150/147865145-0c8bd322-5bae-4273-82bd-a685fd8ad232.png)
