### ISSUE TITLE
Deprecate field `regions` in GuildEdit and the view of the value

### ISSUE THREAD

**Issue by Lulalaby** [DSharpPlus/DSharpPlus#895]
If https://github.com/discord/discord-api-docs/pull/2982 get's approved, we need to remove the `region` field in Guilds.
Or it will be in a new version bumb, we'll see

Thing is:
The field is not used anymore. It's still there, but unnecessary.
![Voice-Region setting is removed](https://user-images.githubusercontent.com/14029133/119249296-ae150100-bb97-11eb-9daa-c5661a564400.png)
I would like to hide it.

**Comment by Neuheit** [comment]
We won't be removing it, rather adding the depreciated attribute telling them to use the newer property.

**Comment by Lulalaby** [comment]
> 
> 
> We won't be removing it, rather adding the depreciated attribute telling them to use the newer property.

got it, done

**Comment by Emzi0767** [comment]
The PR linked got rejected. I second Neu's idea.

**Comment by Lulalaby** [comment]
> The PR linked got rejected. I second Neu's idea.

Yes I know
1: I closed the pr and switched to https://github.com/discord/discord-api-docs/pull/3001
2: Is included in #890

**Comment by Neuheit** [comment]
This is something we will get around to with the V9 implementation, as of now you can still access the guild's region.
