### ISSUE TITLE
RespondAsync doesn't mention anyone

### ISSUE THREAD

**Issue by VelvetThePanda** [DSharpPlus/DSharpPlus#897]
# Summary
Calling `CommandContext#RespondAsync`, `DiscordMessage#RespondAsync`, or even using a MessageBuilder and supplying `true` as the second parameter seems to completely ignore passed mentions, and will not mention any role/user.
# Details
This seems to be in part due to some change in the ApiClient, where mentions aren't being passed to the REST Payload. `DiscordChannel#SendMessageAsync` doesn't have this issue as it uses a different overload that *does* seem to pass mentions. 

Though at the same time this could be a DAPI change? I'm not too sure.

# Steps to reproduce
- Get a channel.
- Get a message object (or message builder).
- Create a message that mentions someone.
- Send that message.
- Observe.

# Notes
This could be intentional design, but I feel like we should allow *all* mentions by default.

**Comment by Neuheit** [comment]
Do you have a code example to reproduce with?

**Comment by VelvetThePanda** [comment]
```cs
public class MentionTest : BaseCommandModule 
{
    public async Task Mention(CommandContext ctx)
    {
        await ctx.RespondAsync($"Hey {ctx.User.Mention}, Listen!"); // No Mention :(
    }
}
```

**Comment by VelvetThePanda** [comment]
This can be mitigated by specifying mentions on the builder, or using `DiscordChannel#SendMessageAsync()`, but by default SendMessage uses Mentions.None, which leads to this payload
```json
{
  "tts": false,
  "message_reference": {
    "message_id": 846972963844653000,
    "fail_if_not_exists": false
  },
  "content": "Hey <@209279906280898562>, Listen!",
  "allowed_mentions": {
    "parse": [],
    "replied_user": false
  }
}```

**Comment by Neuheit** [comment]
Looks like this design is intentional, whether we should change it I'm not sure.

**Comment by VelvetThePanda** [comment]
Mmh. I feel at the very least we should add an `AllowMention` argument to the respond method

**Comment by Emzi0767** [comment]
Ah, this might be a result of passing a new mentions array for silent reply. It's indeed a bug.

**Comment by VelvetThePanda** [comment]
Yeah I noticed that even with the message builder, it ignores the mentions unless you specify `.WithAllowedMentions()`
