### ISSUE TITLE
Support for buttons

### ISSUE THREAD

**Issue by Redblueflame** [DSharpPlus/DSharpPlus#898]
# Summary
Today, discord added support for buttons in bot messages & responses, allowing for richer interaction with bots.

# Details
The documentation about buttons and components, in general, are available here: https://discord.com/developers/docs/interactions/message-components

The main issue with this system is that it is dependant on the Interaction part of the slash commands API for button interaction, so this issue is blocked by #712 for the buttons to be clickable.

**Comment by uwx** [comment]
Will be fixed by #894.

**Comment by VelvetThePanda** [comment]
@uwx minor detail but did you forget to mark this as core?
