### ISSUE TITLE
DiscordMember arguments don't support mentioning the current user

### ISSUE THREAD

**Issue by VelvetThePanda** [DSharpPlus/DSharpPlus#899]
# Summary
Taking a DiscordMember/DiscordUser doesn't support mentioning "the bot". 

# Details
Passing an Id as the argument seems to work fine, or mentioning anyone else.
4.1.0 nightly seems to be broken. As far as I'm aware 4.0.1 works, though.

# Steps to reproduce
Invoke command that takes a DiscordUser/Member
Mention someone in that invocation
Observe.

Invoke again, but mentioning the bot (that serves the command).
Observe no command being executed.

# Notes
Emzi bad x2

**Comment by Emzi0767** [comment]
> Emzi bad x2

No u

**Comment by Neuheit** [comment]
Do you have a sample to reproduce this? Mentioning the bot from an argument seems to work perfectly fine for me.

**Comment by DWaffles** [comment]
> Do you have a sample to reproduce this? Mentioning the bot from an argument seems to work perfectly fine for me.

Same here.

**Comment by CloudTheWolf** [comment]
Also can not replicate on 4.1.0-nightly-00876

**Comment by VelvetThePanda** [comment]
> Do you have a sample to reproduce this? Mentioning the bot from an argument seems to work perfectly fine for me.

Completely forgot I was the one that opened this issue. Oops.

**Comment by Neuheit** [comment]
> 
> 
> > Do you have a sample to reproduce this? Mentioning the bot from an argument seems to work perfectly fine for me.
> 
> Completely forgot I was the one that opened this issue. Oops.

So do you have a sample? If not I'll just close this issue for now.
