### ISSUE TITLE
MessageReactionAdd Interactivity Not Working - Event Took Too Long

### ISSUE THREAD

**Issue by nlogozzo** [DSharpPlus/DSharpPlus#918]
# Summary
I'm having an issue with the MessageReactionAdd event. I'm trying to create a system where a user clicks on a reaction on a message in a channel and then the bot will DM the user and ask them for more information. However, the system works up until the interactivity point. Here is my code for the handler below:

```csharp
        public static async Task MessageReactionAdded(DiscordClient client, MessageReactionAddEventArgs args)
        {
            var guildSettings = Bot.GuildDatabase.GetGuildSettingsByID(Convert.ToInt64(args.Guild.Id));
            if (args.Message.Id == Convert.ToUInt64(guildSettings.PlanMessageID))
            {
                var embed = new DiscordEmbedBuilder();
                var member = await args.Guild.GetMemberAsync(args.User.Id);
                var toTheMoonRole = args.Guild.GetRoleByName("to the moon");
                var verificationChannel = await args.Guild.GetChannelByNameAsync("🚨-accept-first-disclaimer");
                DiscordChannel channel;
                try
                {

                    channel = await member.CreateDmChannelAsync();
                }
                catch
                {
                    channel = args.Channel;
                }
                if (member.ContainsRole(toTheMoonRole))
                {
                    embed.Title = "Error";
                    embed.Description = $"{member.Mention} is already subscribed";
                    embed.Color = DiscordColor.Red;
                    await channel.SendMessageAsync(embed: embed);
                }
                else
                {
                    //==Get Member Info==//
                    var memberInfo = Bot.MemberDatabase.GetMemberInfoByID(Convert.ToInt64(member.Id));
                    memberInfo.DiscordName = member.Username;
                    memberInfo.PlanName = "To The Moon";
                    //==First Name==//
                    var getFirstNameMsg = await channel.SendMessageAsync("===Personal Information===\n\nEnter your first name:");
                    var getFirstNameResult = await getFirstNameMsg.GetNextMessageAsync();
                    if (getFirstNameResult.TimedOut)
                    {
                       //time out message
                    }
                    memberInfo.FirstName = getFirstNameResult.Result.Content;
                    //==Last Name==//
                    var getLastNameMsg = await channel.SendMessageAsync("Enter your last name: ");
                    var getLastNameResult = await getLastNameMsg.GetNextMessageAsync();
                    if (getLastNameResult.TimedOut)
                    {
                        ...
                    }
                    memberInfo.LastName = getLastNameResult.Result.Content;
                    ...
```
The code throws a warning in the console saying the event took too long to execute. However, after 30 seconds, which the interactivity is set too, the time out message is sent in the channel. However, if the user types something, the bot doesn't get the message and will eventually time out again. I don't understand why its not getting the user input.

**Comment by jeffreyladd** [comment]
You are blocking the gateway thread, wrap what your doimg in a task.run

**Comment by nlogozzo** [comment]
@jeffreyladd Let me try...

**Comment by nlogozzo** [comment]
So I basically change it into 
```csharp
public static async Task MessageReactionAdded(DiscordClient client, MessageReactionAddEventArgs args)
{
    await Task.Run(async () => 
    {
        ...
    });
}
```
@jeffreyladd I still get the warning and it still doesn't work

**Comment by jeffreyladd** [comment]
Remove the await causw you are still blocking it

**Comment by nlogozzo** [comment]
@jeffreyladd changed it too
```csharp
public static Task MessageReactionAdded(DiscordClient client, MessageReactionAddEventArgs args)
{
    Task.Run(async () => 
    {
        ...
    });
    return Task.CompletedTask;
}
```
I'm not getting the warning now, but it's not recognizing the input still

**Comment by jeffreyladd** [comment]
So set a breakpoint at the start, IF your breakpoint never gets hit either A) double check ur intents and/or B) check to verify ur hooking the event correctlt

**Comment by nlogozzo** [comment]
It hits the breakpoint on the line
`var getFirstNameResult = await getFirstNameMsg.GetNextMessageAsync();` 
the code after is 
```csharp
if (getFirstNameResult.TimedOut)
{
    embed.ClearFields();
    embed.Title = "Order Canceled";
    embed.Description = $"Select a plan again in {verificationChannel.Mention} to start over.";
    embed.Color = DiscordColor.Red;
    await channel.SendMessageAsync(embed: embed);
    return;
}
```
And like I said it times out and reaches that message. Which means the event is hooked up correctly because then none of this would happen.
And this is my client config:
```csharp
Client = new DiscordClient(new DiscordConfiguration()
            {
                Token = config.Token,
                TokenType = TokenType.Bot,
                Intents = DiscordIntents.All,
                MinimumLogLevel = LogLevel.Warning
            });
```

**Comment by nlogozzo** [comment]
@jeffreyladd I'm so lost on why it's not working lol
Is there a why I can run a command from the event and put it in a command handler instead. Maybe it will redirect it out of the event?

**Comment by ProfDoof** [comment]
Couple of things, 
1. Do you have your interactivity configured correctly so that it will time out after the appropriate amount of time? 
2. Is it sending the message that says `Order cancelled`?
3. Is the person sending the message the same person as the one who created the message `getFirstNameMsg` (short answer, no it's not. Reread what GetNextMessageAsync does [in the docs](https://dsharpplus.github.io/api/DSharpPlus.Interactivity.Extensions.MessageExtensions.html?q=GetNextMess#DSharpPlus_Interactivity_Extensions_MessageExtensions_GetNextMessageAsync_DiscordMessage_System_Nullable_TimeSpan__))

**Comment by ProfDoof** [comment]
Also, in the future, if you have a question that is just "I'm doing something wrong but what????!!!!" head on over to the Discord server. :smile: 

https://discord.gg/dsharpplus

**Comment by nlogozzo** [comment]
1. Yes
```csharp
Client.UseInteractivity(new InteractivityConfiguration()
            {
                Timeout = TimeSpan.FromSeconds(30),
                PollBehaviour = PollBehaviour.KeepEmojis
            });
```
2. Yes, like i've said the message times out and sends that order canceled that's how I know the event works
3. And yeah your right, it's not the same author cause the bot sends the message. let me try something and let you know @ProfDoof 
P.S. should we continue this convo in the discord?

**Comment by nlogozzo** [comment]
Fixed!! Changed the line to:
```csharp
var getFirstNameResult = await client.GetInteractivity().WaitForMessageAsync(msg =>
                        {
                            return msg.Channel == channel && msg.Author == args.User;
                        });
```
Thanks for the help!
