### ISSUE TITLE
[Enhancement] Format message mentions into human-readable version

### ISSUE THREAD

**Issue by Evengard** [DSharpPlus/DSharpPlus#935]
I have a bot which retransmits and shows some messages on my website. The problem is that the mentions are not really human-readable - it's just a bunch of cryptic tags with snowflake identifiers, which are useless for a simple user.
For now I just transform it simply and dirty with Formatter.Strip(), but it would be nice to have a method which would output the message into something similar to what is shown in the Discord client itself.
Aka `Some message with mention <@!1111111111111>` would be transformed into `Some message with mention @GuildUsername`.
I probably could do it myself, but I think other people could find this useful too.

**Comment by VelvetThePanda** [comment]
They seem cryptic because that’s how snowflakes (and by extension mentions) work. Seeing a username is simply client side rendering. You could always replace mentions with the user’s username, but since the use-case of such a feature is rather niche, I wouldn’t have high hopes for it being implemented into the library.

**Comment by Evengard** [comment]
I know, and I actually pointed out that with some effort I could implement it myself, it's not that hard. Still, it could be nice to have such a feature directly in the library (maybe even I'd submit a pull request - if it's ever needed).

**Comment by VelvetThePanda** [comment]
Yes, but given that this seems to be a hyper-specific issue, and the fact that the library is made to interface with *Discord*, which already handles rendering mentions, I stand by my previous comment.

**Comment by Evengard** [comment]
Why then Formatter.Purge() even exists? Its usecase is somewhat close to this one.

**Comment by VelvetThePanda** [comment]
> Why then Formatter.Purge() even exists? Its usecase is somewhat close to this one.

Because [it doesn't?](https://github.com/DSharpPlus/DSharpPlus/blob/3e480fafbc7741b3550064a9b10cda0077f9234e/DSharpPlus/Formatter.cs)

**Comment by Evengard** [comment]
My bad, I meant this one: https://dsharpplus.github.io/api/DSharpPlus.Formatter.html#DSharpPlus_Formatter_Strip_System_String_

**Comment by IDoEverything** [comment]
that's completely different

**Comment by Evengard** [comment]
It is, but its use case are kinda close.

**Comment by IDoEverything** [comment]
I can see the use in this though, maybe a method that converts user, role and channel mentions to a human-readable form, though still a very niche use case. Feel free to pr it.

**Comment by Evengard** [comment]
I'm a little confused, should I PR against master or release/4.0?

**Comment by VelvetThePanda** [comment]
> I'm a little confused, should I PR against master or release/4.0?

Master.

**Comment by Evengard** [comment]
Thanks!
After investigating the source, seems like I will need to make some additional work on emojis part too...

**Comment by Emzi0767** [comment]
Formatter.Strip, as the name implies, strips formatting, mentions aren't exactly formatting.

**Comment by Evengard** [comment]
...Yet for some reason they are stripped by Formatter.Strip =)

**Comment by Neuheit** [comment]
See referenced pull requests.
