### ISSUE TITLE
Newly joined guilds are not available to commands in their context

### ISSUE THREAD

**Issue by alexhorner** [DSharpPlus/DSharpPlus#979]
# Summary
`System.NullReferenceException` occurs when accessing `ctx.Guild` properties when a command is executed, but only when the bot has joined the guild in which the command was run after startup.

# Details
When a bot is started, and a command is run, `ctx.Guild` can be accessed as expected, but only when the command is called from a guild which the bot was already in prior to starting up.

If the same command is called from a guild which the bot was joined to after it had started up, `ctx.Guild` will be null.

# Steps to reproduce
1. Create a bot
2. Join it to a guild
3. Start it up
4. Run the provided Guild command in the guild. It succeeds.
5. Join it to another guild whilst it is running
6. Run the provided Guild command in the new guild. It throws.
7. Restart the bot
8. Run the provided Guild command in the new guild again. It succeeds.

# Notes
This issue affects DiscordClient, DiscordShardedClient with 1 shard and DiscordShardedClient with 3 shards.

Here is the provided Guild command:
```csharp
[Command("guild")]
public async Task Guild(CommandContext ctx)
{
    await ctx.RespondAsync($"You are calling from guild {ctx.Guild.Name} ({ctx.Guild.Id})");
}
```

I am using DSharpPlus 4.1.0-nightly-00915

**Comment by Emzi0767** [comment]
Is 915 latest?

**Comment by Lulalaby** [comment]
> 
> 
> Is 915 latest?

Yes it is Emzi
![image](https://user-images.githubusercontent.com/14029133/124467738-8b7e2680-dd98-11eb-9f47-198b16315ede.png)

**Comment by Emzi0767** [comment]
There was recently a fix for null guilds, who was responsible? Is it a possible regression?

**Comment by Lulalaby** [comment]
I'll take a look

**Comment by Lulalaby** [comment]
Could be this https://github.com/DSharpPlus/DSharpPlus/pull/970

**Comment by Lulalaby** [comment]
Or https://github.com/DSharpPlus/DSharpPlus/commit/ae72488c268103bcf3e6400e7860d647771995ba

**Comment by Lulalaby** [comment]
This 3 relates to Guild

https://github.com/DSharpPlus/DSharpPlus/pull/970
https://github.com/DSharpPlus/DSharpPlus/commit/ae72488c268103bcf3e6400e7860d647771995ba
https://github.com/DSharpPlus/DSharpPlus/commit/566fd6cdfe8055023a48788f26c9ca319f7be88b

**Comment by Emzi0767** [comment]
None of these seem to affect caching, which I suspect is at the root of the issue. Perhaps something changed in guild create handling?

**Comment by Lulalaby** [comment]
I'll take a closer look

**Comment by alexhorner** [comment]
- In 00904 everything works as it should do, the issue is not present
- In 00905 the issue occurs for any guild, whether the bot was previously in it or not
- In 00906 everything works as it should do, the issue is not present
- In 00907 everything works as it should do, the issue is not present
- In 00908 the issue occurs as described
- In 00909 the issue occurs as described
- In 00910 the issue occurs as described

**Comment by Lulalaby** [comment]
ok thanks that helps

**Comment by Emzi0767** [comment]
That indicates fbee5ff33743a3e88dd5822fc7ec7cd67735df7c is to blame.

cc @Neuheit

**Comment by Lulalaby** [comment]
Can reproduce 
![image](https://user-images.githubusercontent.com/14029133/124478131-28df5780-dda5-11eb-9835-f33d88266d63.png)

**Comment by Lulalaby** [comment]
Workaround:

```csharp
        // client.GuildCreated += Client_GuildCreated;

        private static Task Client_GuildCreated(DiscordClient sender, GuildCreateEventArgs e)
        {
            Console.ForegroundColor = ConsoleColor.Cyan;
            Console.WriteLine("Joined Guild: " + e.Guild.Name);
            Console.WriteLine("Reloading");
            sender.ReconnectAsync(true);
            return Task.CompletedTask;
        }
```

**Comment by VelvetThePanda** [comment]
> Workaround:
> 
> ```cs
>         // client.GuildCreated += Client_GuildCreated;
> 
>         private static Task Client_GuildCreated(DiscordClient sender, GuildCreateEventArgs e)
>         {
>             Console.ForegroundColor = ConsoleColor.Cyan;
>             Console.WriteLine("Joined Guild: " + e.Guild.Name);
>             Console.WriteLine("Reloading");
>             sender.ReconnectAsync(true);
>             return Task.CompletedTask;
>         }
> ```

Mmmmm. Gotta love temporarily killing your bot/a shard every time you join a server

**Comment by Lulalaby** [comment]
It's not the best, but till a fix is out, this works

**Comment by Emzi0767** [comment]
We've recommended worse temporary solutions in the past

**Comment by VelvetThePanda** [comment]
![rp_blank](https://user-images.githubusercontent.com/42438262/124479093-e6e9ed80-dd73-11eb-86b1-4da7c995d120.png)

**Comment by Emzi0767** [comment]
No image spam

**Comment by VelvetThePanda** [comment]
@Lulalaby Are you sure `DiscordClient#GetGuildAsync` wouldn't work. P sure we at least partially cache those entities.

**Comment by Lulalaby** [comment]
Lemme try

**Comment by Lulalaby** [comment]
Nope, doesn't work.

**Comment by Lulalaby** [comment]
I don't see why it didn't cache.
I'll do a bit debugging later and try to get a fix asap.

**Comment by Neuheit** [comment]
> 
> 
> That indicates [fbee5ff](https://github.com/DSharpPlus/DSharpPlus/commit/fbee5ff33743a3e88dd5822fc7ec7cd67735df7c) is to blame.
> 
> cc @Neuheit

Yep I think I know why this is failing, I'll revert my changes to `DiscordGuild` in that commit when I can.

**Comment by Lulalaby** [comment]
> 
> 
> > That indicates [fbee5ff](https://github.com/DSharpPlus/DSharpPlus/commit/fbee5ff33743a3e88dd5822fc7ec7cd67735df7c) is to blame.
> > cc @Neuheit
> 
> Yep I think I know why this is failing, I'll revert my changes to `DiscordGuild` in that commit when I can.

Well can we keep and fix it?
What was the directly goal anyway

**Comment by Neuheit** [comment]
> Well can we keep and fix it?
> What was the directly goal anyway

I was trying to find an alternative use to our ReadOnlyConcurrentDictionary class, but turned out it was actually needed. To fix this, just undo the recent changes I did to `DiscordGuild` and `DiscordGuildPreview`.

**Comment by Lulalaby** [comment]
Okay

**Comment by Lulalaby** [comment]
Can validate. This revert/fix works.
