### ISSUE TITLE
SendPaginatedMessageAsync throws NullReferenceException when Page does not contain an Embed

### ISSUE THREAD

**Issue by aPinat** [DSharpPlus/DSharpPlus#986]
# Summary
A `NullReferenceException` occurs when trying to send a paginated message (using Interactivity) and the page to send does not contain an embed.

# Details
D#+ 4.1.0-nightly-00917, .NET 5

# Steps to reproduce
1. Try to send Page without Embed

```c#
await ctx.Client.GetInteractivity().SendPaginatedMessageAsync(ctx.Channel, ctx.User, new[] {new Page("TEST")});
```

2. Observe exception with stacktrace below

```c#
System.NullReferenceException: Object reference not set to an instance of an object.
   at DSharpPlus.Net.DiscordApiClient.CreateMessageAsync(UInt64 channel_id, DiscordMessageBuilder builder)
   at DSharpPlus.Interactivity.InteractivityExtension.SendPaginatedMessageAsync(DiscordChannel c, DiscordUser u, IEnumerable`1 pages, PaginationEmojis emojis, Nullable`1 behaviour, Nullable`1 deletion, Nullable`1 timeoutoverride)
```

3. Trying to send Page with Embed works fine

```c#
await ctx.Client.GetInteractivity().SendPaginatedMessageAsync(ctx.Channel, ctx.User, new[] {new Page(embed: new DiscordEmbedBuilder().WithDescription("TEST"))});
```

**Comment by VelvetThePanda** [comment]
I am partly at fault for this. The message builder doesn't validate null values, which become a problem when trying to send a message

**Comment by VelvetThePanda** [comment]
[This PR](https://github.com/DSharpPlus/DSharpPlus/pull/983) fixes that issue.
