### ISSUE TITLE
change TypeInfo.GetCustomAttributes<BaseCommandModule>(false) != null, to (...).Length > 0

### ISSUE THREAD

**Issue by Eliemer** [DSharpPlus/DSharpPlus#995]
# Summary
During CommandsNextEntension.RegisterCommands(), theres a check for IsModuleCandidateType(). In that check theres an "if" statement that checks for compiler generated attributes in the form of a null check. For the sake of interoperability with F# i suggest adding a check for Array.Length > 0, since F# types (classes) will never return a null value and thus always be flagged as Compiler generated classes. 

With this issue, I can't use the CommandsNext package at all, as it will always cause an error on startup

# Details
relevant piece of code is in:
- https://github.com/DSharpPlus/DSharpPlus/blob/7f690198ecb8d0f7ecd66c1432539bbe309efcdb/DSharpPlus.CommandsNext/CommandsNextUtilities.cs#L296

relevant stacktrace:
```
ArgumentNullException: Type must be a class, which cannot be abstract or static. (Parameter 't')
   at DSharpPlus.CommandsNext.CommandsNextExtension.RegisterCommands(Type t)
   at DSharpPlus.CommandsNext.CommandsNextExtension.RegisterCommands[T]()
   at <StartupCode$DiscordBotFSharp>.$Core..cctor() in C:\Users\EliRodriguez\source\repos\DiscordBotFSharp\DiscordBotFSharp\Core.fs:line 79
```

my command class:
```fs
namespace Bot.Commands

open System.Threading.Tasks
open DSharpPlus.CommandsNext
open DSharpPlus.CommandsNext.Attributes
open DSharpPlus.Entities

type Commands = 
    inherit BaseCommandModule

    member private self.Ping(ctx : CommandContext) : Async<unit> = 
        async { 
            do! ctx.TriggerTypingAsync() 
                |> Async.AwaitTask

            let emoji = DiscordEmoji.FromName(ctx.Client, ":ping_pong:")

            do! ctx.RespondAsync(sprintf "%s Pong! Socket Latency: %ims" (emoji.ToString()) ctx.Client.Ping) 
                |> Async.AwaitTask 
                |> Async.Ignore
        }

    [<Command("ping"); Description("Responds with socket latency")>]
    member public self.PingAsync(ctx : CommandContext) : Task<unit> =
        self.Ping ctx |> Async.StartAsTask
```

my command register code:
```fs
// reads a json, custom type
let config = ConfigLoader.loadConfig()

// DiscordConfiguration object
let discordConfig = ConfigLoader.loadDiscordConfig(config)

// CommandsNextConfiguration object
let commandConfig = ConfigLoader.loadCommandConfig(config)
   
let discordClient = new DiscordClient(discordConfig)
let commands = discordClient.UseCommandsNext(commandConfig) 
commands.RegisterCommands<Commands>()
```

# Suggested edit:
```cs
var compilerAttrs = ti.GetCustomAttribute<CompilerGeneratedAttribute>(false);
if (compilerAttrs != null && compilerAttrs.Length > 0)
```

**Comment by Eliemer** [comment]
I came back to this and replicated all the checks related to `isModuleCandidate`. Turns out its because it couldnt find a method that returned `Task`. My commands returned `Task<unit>`. Closing as non-issue

**Comment by Eliemer** [comment]
For anyone looking to use this library in F#. My two cents: 
- return type for commands MUST be `Task`, not `Task<unit>`
- your parameters MUST be explicitly type, not infered by the compiler.

**Comment by baronfel** [comment]
I'd like to request reopening this and using it to enhance the error message generated for this case. I've helped a handful of F# devs around this exact case, and even something as simple as "and there must be at least one member defined that returns a Task" would have solved their problem early on.

**Comment by johanalkstal** [comment]
I've spent quite some time trying to understand what I had done wrong because of the error message

```
ArgumentNullException: Type must be a class, which cannot be abstract or static. (Parameter 't')
   at DSharpPlus.CommandsNext.CommandsNextExtension.RegisterCommands(Type t)
   at DSharpPlus.CommandsNext.CommandsNextExtension.RegisterCommands[T]()
```

I could not understand why it would not work until I got a helpful hint that I just need to make sure I explicitly type the return of a command to `Task` instead of letting it be inferred as `Task<unit>`.

Since the error message does not hint at any way on what the actual problem and solution is, it would probably help many developers if this was updated.
